Repository element-hq/element-x-ios, pull requests merged in 2024-11, with the labels that each got.

#3479 Update SDK 1.0.63
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Sources/Mocks/Generated/SDKGeneratedMocks.swift
  ElementX/Sources/Services/RoomDirectorySearch/RoomDirectorySearchProxy.swift
  project.yml
Labels: pr-misc

#3480 Update the README.
  README.md
Labels: pr-doc

#3471 Encryption Flow Coordinators.
  ElementX.xcodeproj/project.pbxproj
  ElementX/Sources/FlowCoordinators/EncryptionResetFlowCoordinator.swift
  ElementX/Sources/FlowCoordinators/EncryptionSettingsFlowCoordinator.swift
  ElementX/Sources/FlowCoordinators/OnboardingFlowCoordinator.swift
  ElementX/Sources/FlowCoordinators/SettingsFlowCoordinator.swift
  ElementX/Sources/Mocks/ClientProxyMock.swift
  ElementX/Sources/Mocks/SDK/IdentityResetHandleSDKMock.swift
  ElementX/Sources/Mocks/SecureBackupControllerMock.swift
  ElementX/Sources/Other/AccessibilityIdentifiers.swift
  ElementX/Sources/Screens/EncryptionReset/EncryptionResetPasswordScreen/EncryptionResetPasswordScreenCoordinator.swift
  ElementX/Sources/Screens/EncryptionReset/EncryptionResetPasswordScreen/EncryptionResetPasswordScreenModels.swift
  ElementX/Sources/Screens/EncryptionReset/EncryptionResetPasswordScreen/EncryptionResetPasswordScreenViewModel.swift
  ElementX/Sources/Screens/EncryptionReset/EncryptionResetPasswordScreen/View/EncryptionResetPasswordScreen.swift
  ElementX/Sources/Screens/EncryptionReset/EncryptionResetScreen/EncryptionResetScreenCoordinator.swift
  ElementX/Sources/Screens/EncryptionReset/EncryptionResetScreen/EncryptionResetScreenModels.swift
  ElementX/Sources/Screens/EncryptionReset/EncryptionResetScreen/EncryptionResetScreenViewModel.swift
  ElementX/Sources/Screens/EncryptionReset/EncryptionResetScreen/EncryptionResetScreenViewModelProtocol.swift
  ElementX/Sources/Screens/EncryptionReset/EncryptionResetScreen/View/EncryptionResetScreen.swift
  ElementX/Sources/Screens/SecureBackup/SecureBackupKeyBackupScreen/View/SecureBackupKeyBackupScreen.swift
  ElementX/Sources/Screens/SecureBackup/SecureBackupRecoveryKeyScreen/SecureBackupRecoveryKeyScreenCoordinator.swift
  ElementX/Sources/Screens/SecureBackup/SecureBackupRecoveryKeyScreen/SecureBackupRecoveryKeyScreenModels.swift
  ElementX/Sources/Screens/SecureBackup/SecureBackupRecoveryKeyScreen/SecureBackupRecoveryKeyScreenViewModel.swift
  ElementX/Sources/Screens/SecureBackup/SecureBackupRecoveryKeyScreen/View/SecureBackupRecoveryKeyScreen.swift
  ElementX/Sources/Screens/SecureBackup/SecureBackupScreen/SecureBackupScreenCoordinator.swift
  ElementX/Sources/Screens/SecureBackup/SecureBackupScreen/SecureBackupScreenModels.swift
  ElementX/Sources/Screens/SecureBackup/SecureBackupScreen/SecureBackupScreenViewModel.swift
  ElementX/Sources/Screens/SecureBackup/SecureBackupScreen/View/SecureBackupScreen.swift
  ElementX/Sources/UITests/UITestsAppCoordinator.swift
  ElementX/Sources/UITests/UITestsScreenIdentifier.swift
  UITests/Sources/EncryptionResetUITests.swift
  UITests/Sources/EncryptionSettingsUITests.swift
  UITests/Sources/__Snapshots__/Application/encryptionReset-0-iPad-10th-generation-en-GB.UI.png
  UITests/Sources/__Snapshots__/Application/encryptionReset-0-iPhone-16-en-GB.UI.png
  UITests/Sources/__Snapshots__/Application/encryptionReset-1-iPad-10th-generation-en-GB.UI.png
  UITests/Sources/__Snapshots__/Application/encryptionReset-1-iPhone-16-en-GB.UI.png
  UITests/Sources/__Snapshots__/Application/encryptionReset-2-iPad-10th-generation-en-GB.UI.png
  UITests/Sources/__Snapshots__/Application/encryptionReset-2-iPhone-16-en-GB.UI.png
  UITests/Sources/__Snapshots__/Application/encryptionSettings-0-iPad-10th-generation-en-GB.UI.png
  UITests/Sources/__Snapshots__/Application/encryptionSettings-0-iPhone-16-en-GB.UI.png
  UITests/Sources/__Snapshots__/Application/encryptionSettings-1-iPad-10th-generation-en-GB.UI.png
  UITests/Sources/__Snapshots__/Application/encryptionSettings-1-iPhone-16-en-GB.UI.png
  UITests/Sources/__Snapshots__/Application/encryptionSettings-2-iPad-10th-generation-en-GB.UI.png
  UITests/Sources/__Snapshots__/Application/encryptionSettings-2-iPhone-16-en-GB.UI.png
  UITests/Sources/__Snapshots__/Application/encryptionSettings-3-iPad-10th-generation-en-GB.UI.png
  UITests/Sources/__Snapshots__/Application/encryptionSettings-3-iPhone-16-en-GB.UI.png
  UITests/Sources/__Snapshots__/Application/encryptionSettings-4-iPad-10th-generation-en-GB.UI.png
  UITests/Sources/__Snapshots__/Application/encryptionSettings-4-iPhone-16-en-GB.UI.png
  UITests/Sources/__Snapshots__/Application/encryptionSettings-5-iPad-10th-generation-en-GB.UI.png
  UITests/Sources/__Snapshots__/Application/encryptionSettings-5-iPhone-16-en-GB.UI.png
  UITests/Sources/__Snapshots__/Application/encryptionSettings-6-iPad-10th-generation-en-GB.UI.png
  UITests/Sources/__Snapshots__/Application/encryptionSettings-6-iPhone-16-en-GB.UI.png
Labels: pr-misc

#3482 Directly show Recovery Key and Encryption Reset screens from the home screen banner.
  ElementX/Sources/FlowCoordinators/UserSessionFlowCoordinator.swift
  ElementX/Sources/FlowCoordinators/UserSessionFlowCoordinatorStateMachine.swift
  ElementX/Sources/Screens/HomeScreen/HomeScreenCoordinator.swift
  ElementX/Sources/Screens/HomeScreen/HomeScreenModels.swift
  ElementX/Sources/Screens/HomeScreen/HomeScreenViewModel.swift
  ElementX/Sources/Screens/HomeScreen/View/HomeScreenRecoveryKeyConfirmationBanner.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_homeScreenRecoveryKeyConfirmationBanner-iPad-en-GB.Out-of-sync.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_homeScreenRecoveryKeyConfirmationBanner-iPad-pseudo.Out-of-sync.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_homeScreenRecoveryKeyConfirmationBanner-iPhone-16-en-GB.Out-of-sync.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_homeScreenRecoveryKeyConfirmationBanner-iPhone-16-pseudo.Out-of-sync.png
Labels: pr-change

#3481 Stop the sync loop after each background app refresh.
  ElementX/Sources/Application/AppCoordinator.swift
  ElementX/Sources/Services/Client/ClientProxy.swift
Labels: pr-bugfix

#3483 Fix the Setup Recovery flow from the home screen banner.
  ElementX/Sources/FlowCoordinators/UserSessionFlowCoordinator.swift
  ElementX/Sources/Screens/HomeScreen/HomeScreenCoordinator.swift
  ElementX/Sources/Screens/HomeScreen/HomeScreenModels.swift
  ElementX/Sources/Screens/HomeScreen/HomeScreenViewModel.swift
  ElementX/Sources/Screens/HomeScreen/View/HomeScreenRecoveryKeyConfirmationBanner.swift
Labels: pr-bugfix

#3486 Fix race condition when setting up session verification controller subscriptions
  ElementX/Sources/Services/Client/ClientProxy.swift
Labels: pr-bugfix

#3488 Syncing fixes
  ElementX/Sources/Application/AppCoordinator.swift
  ElementX/Sources/Services/ElementCall/ElementCallService.swift
  ElementX/Sources/Services/ElementCall/ElementCallServiceProtocol.swift
Labels: pr-bugfix

#3490 Update SDK 1.0.64
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Sources/Services/Client/ClientProxy.swift
  ElementX/Sources/Services/Client/ClientProxyProtocol.swift
  project.yml
Labels: pr-misc

#3491 Start syncing when receiving a background VoIP call for the cases in which the app was suspended but not terminated
  ElementX/Sources/Application/AppCoordinator.swift
Labels: pr-bugfix

#3494 Update SDK 1.0.65
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Sources/Mocks/Generated/SDKGeneratedMocks.swift
  ElementX/Sources/Services/Timeline/TimelineProxy.swift
  project.yml
Labels: pr-bugfix

#3497 Fix incorrect analytics mapping for UTDs.
  .github/workflows/danger.yml
  .github/workflows/pr-build.yml
  .github/workflows/translations-pr.yml
  .github/workflows/unit_tests.yml
  .github/workflows/unit_tests_enterprise.yml
  ElementX/Sources/FlowCoordinators/UserSessionFlowCoordinator.swift
Labels: pr-misc

#3499 Fix for creating a knocking room
  ElementX/Resources/Localizations/en.lproj/Localizable.strings
  ElementX/Sources/Generated/Strings.swift
  ElementX/Sources/Services/Client/ClientProxy.swift
Labels: pr-bugfix

#3495 Tweak the session verification icons and copy.
  ElementX/Sources/Screens/Onboarding/SessionVerificationScreen/SessionVerificationScreenModels.swift
  ElementX/Sources/Screens/Onboarding/SessionVerificationScreen/View/SessionVerificationScreen.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_sessionVerification-iPad-en-GB.Accepting-Challenge.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_sessionVerification-iPad-en-GB.Accepting-Verification-Request.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_sessionVerification-iPad-en-GB.Cancelled.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_sessionVerification-iPad-en-GB.Declining-Challenge.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_sessionVerification-iPad-en-GB.Initial-Initiator.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_sessionVerification-iPad-en-GB.Initial-Responder.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_sessionVerification-iPad-en-GB.Request-Accepted.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_sessionVerification-iPad-en-GB.Requesting-Verification.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_sessionVerification-iPad-en-GB.SAS-Verification-started.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_sessionVerification-iPad-en-GB.Showing-Challenge.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_sessionVerification-iPad-en-GB.Starting-SAS-Verification.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_sessionVerification-iPad-en-GB.Verified.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_sessionVerification-iPad-pseudo.Accepting-Challenge.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_sessionVerification-iPad-pseudo.Accepting-Verification-Request.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_sessionVerification-iPad-pseudo.Cancelled.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_sessionVerification-iPad-pseudo.Declining-Challenge.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_sessionVerification-iPad-pseudo.Initial-Initiator.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_sessionVerification-iPad-pseudo.Initial-Responder.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_sessionVerification-iPad-pseudo.Request-Accepted.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_sessionVerification-iPad-pseudo.Requesting-Verification.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_sessionVerification-iPad-pseudo.SAS-Verification-started.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_sessionVerification-iPad-pseudo.Showing-Challenge.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_sessionVerification-iPad-pseudo.Starting-SAS-Verification.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_sessionVerification-iPad-pseudo.Verified.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_sessionVerification-iPhone-16-en-GB.Accepting-Challenge.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_sessionVerification-iPhone-16-en-GB.Accepting-Verification-Request.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_sessionVerification-iPhone-16-en-GB.Cancelled.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_sessionVerification-iPhone-16-en-GB.Declining-Challenge.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_sessionVerification-iPhone-16-en-GB.Initial-Initiator.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_sessionVerification-iPhone-16-en-GB.Initial-Responder.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_sessionVerification-iPhone-16-en-GB.Request-Accepted.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_sessionVerification-iPhone-16-en-GB.Requesting-Verification.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_sessionVerification-iPhone-16-en-GB.SAS-Verification-started.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_sessionVerification-iPhone-16-en-GB.Showing-Challenge.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_sessionVerification-iPhone-16-en-GB.Starting-SAS-Verification.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_sessionVerification-iPhone-16-en-GB.Verified.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_sessionVerification-iPhone-16-pseudo.Accepting-Challenge.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_sessionVerification-iPhone-16-pseudo.Accepting-Verification-Request.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_sessionVerification-iPhone-16-pseudo.Cancelled.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_sessionVerification-iPhone-16-pseudo.Declining-Challenge.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_sessionVerification-iPhone-16-pseudo.Initial-Initiator.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_sessionVerification-iPhone-16-pseudo.Initial-Responder.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_sessionVerification-iPhone-16-pseudo.Request-Accepted.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_sessionVerification-iPhone-16-pseudo.Requesting-Verification.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_sessionVerification-iPhone-16-pseudo.SAS-Verification-started.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_sessionVerification-iPhone-16-pseudo.Showing-Challenge.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_sessionVerification-iPhone-16-pseudo.Starting-SAS-Verification.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_sessionVerification-iPhone-16-pseudo.Verified.png
Labels: pr-misc

#3501 Make stopSync more aware of background usage.
  ElementX/Sources/Application/AppCoordinator.swift
Labels: pr-bugfix

#3503 Regenerate thumbnails to see if it helps with phantom avatar switching.
  ElementX/Sources/Other/Extensions/UNNotificationContent.swift
Labels: pr-bugfix

#3502 Update the strings for unsupported calls.
  ElementX/Resources/Localizations/en.lproj/Localizable.strings
  ElementX/Sources/Generated/Strings.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/CallInviteRoomTimelineView.swift
  ElementX/Sources/Services/Room/RoomSummary/RoomEventStringBuilder.swift
  NSE/Sources/NotificationContentBuilder.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_callInviteRoomTimelineView-iPad-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_callInviteRoomTimelineView-iPad-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_callInviteRoomTimelineView-iPhone-16-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_callInviteRoomTimelineView-iPhone-16-pseudo.1.png
Labels: pr-misc

#3507 Fix #1947 - Check expected files are still present before restoring a session.
  ElementX/Sources/Services/UserSession/SessionDirectories.swift
  ElementX/Sources/Services/UserSession/UserSessionStore.swift
Labels: pr-bugfix

#3510 Knock requests banner
  ElementX.xcodeproj/project.pbxproj
  ElementX/Resources/Localizations/en.lproj/Localizable.strings
  ElementX/Resources/Localizations/en.lproj/Localizable.stringsdict
  ElementX/Sources/Generated/Strings.swift
  ElementX/Sources/Other/Avatars.swift
  ElementX/Sources/Other/SwiftUI/Views/StackedAvatarsView.swift
  ElementX/Sources/Screens/RoomScreen/View/KnockRequestsBannerView.swift
  PreviewTests/Sources/GeneratedPreviewTests.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_callInviteRoomTimelineView-iPad-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_callInviteRoomTimelineView-iPad-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_callInviteRoomTimelineView-iPhone-16-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_callInviteRoomTimelineView-iPhone-16-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_knockRequestsBannerView-iPad-en-GB.Multiple-Requests.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_knockRequestsBannerView-iPad-en-GB.Single-Request-No-Display-Name.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_knockRequestsBannerView-iPad-en-GB.Single-Request-with-reason.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_knockRequestsBannerView-iPad-en-GB.Single-Request.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_knockRequestsBannerView-iPad-pseudo.Multiple-Requests.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_knockRequestsBannerView-iPad-pseudo.Single-Request-No-Display-Name.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_knockRequestsBannerView-iPad-pseudo.Single-Request-with-reason.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_knockRequestsBannerView-iPad-pseudo.Single-Request.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_knockRequestsBannerView-iPhone-16-en-GB.Multiple-Requests.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_knockRequestsBannerView-iPhone-16-en-GB.Single-Request-No-Display-Name.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_knockRequestsBannerView-iPhone-16-en-GB.Single-Request-with-reason.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_knockRequestsBannerView-iPhone-16-en-GB.Single-Request.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_knockRequestsBannerView-iPhone-16-pseudo.Multiple-Requests.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_knockRequestsBannerView-iPhone-16-pseudo.Single-Request-No-Display-Name.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_knockRequestsBannerView-iPhone-16-pseudo.Single-Request-with-reason.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_knockRequestsBannerView-iPhone-16-pseudo.Single-Request.png
Labels: pr-wip

#3512 Bump the RustSDK to v1.0.67
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Sources/FlowCoordinators/RoomFlowCoordinator.swift
  ElementX/Sources/Mocks/Generated/GeneratedMocks.swift
  ElementX/Sources/Mocks/Generated/SDKGeneratedMocks.swift
  ElementX/Sources/Mocks/JoinedRoomProxyMock.swift
  ElementX/Sources/Other/Extensions/ClientBuilder.swift
  ElementX/Sources/Screens/ResolveVerifiedUserSendFailureScreen/ResolveVerifiedUserSendFailureScreenCoordinator.swift
  ElementX/Sources/Screens/ResolveVerifiedUserSendFailureScreen/ResolveVerifiedUserSendFailureScreenViewModel.swift
  ElementX/Sources/Screens/ResolveVerifiedUserSendFailureScreen/View/ResolveVerifiedUserSendFailureScreen.swift
  ElementX/Sources/Screens/RoomScreen/RoomScreenCoordinator.swift
  ElementX/Sources/Screens/Timeline/TimelineModels.swift
  ElementX/Sources/Screens/Timeline/TimelineViewModel.swift
  ElementX/Sources/Services/Client/ClientProxy.swift
  ElementX/Sources/Services/Room/JoinedRoomProxy.swift
  ElementX/Sources/Services/Room/RoomProxyProtocol.swift
  ElementX/Sources/Services/Room/RoomSummary/RoomEventStringBuilder.swift
  ElementX/Sources/Services/Room/RoomSummary/RoomMessageEventStringBuilder.swift
  ElementX/Sources/Services/Timeline/TimelineController/MockRoomTimelineController.swift
  ElementX/Sources/Services/Timeline/TimelineController/RoomTimelineController.swift
  ElementX/Sources/Services/Timeline/TimelineController/RoomTimelineControllerProtocol.swift
  ElementX/Sources/Services/Timeline/TimelineItemProxy.swift
  ElementX/Sources/Services/Timeline/TimelineItems/RoomTimelineItemFactory.swift
  NSE/Sources/NotificationServiceExtension.swift
  UnitTests/Sources/LoggingTests.swift
  UnitTests/Sources/ResolveVerifiedUserSendFailureScreenViewModelTests.swift
  project.yml
Labels: pr-misc

#3514 Enable local echoes for media uploads on development builds.
  ElementX/Sources/Screens/MediaUploadPreviewScreen/MediaUploadPreviewScreenViewModel.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/ImageRoomTimelineView.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/StickerRoomTimelineView.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/VideoRoomTimelineView.swift
  ElementX/Sources/Services/Timeline/Fixtures/RoomTimelineItemFixtures.swift
  ElementX/Sources/Services/Timeline/TimelineItems/Items/Messages/ImageRoomTimelineItemContent.swift
  ElementX/Sources/Services/Timeline/TimelineItems/Items/Messages/VideoRoomTimelineItemContent.swift
  ElementX/Sources/Services/Timeline/TimelineItems/Items/Other/StickerRoomTimelineItem.swift
  ElementX/Sources/Services/Timeline/TimelineItems/RoomTimelineItemFactory.swift
  ElementX/Sources/Services/Timeline/TimelineProxy.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_imageRoomTimelineView-iPad-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_imageRoomTimelineView-iPad-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_imageRoomTimelineView-iPhone-16-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_imageRoomTimelineView-iPhone-16-pseudo.1.png
Labels: pr-feature

#3520 Fix share extension app group so it works for nightlies too
  ShareExtension/SupportingFiles/ShareExtension.entitlements
Labels: pr-bugfix

#3518 Group image and video metadata in specialised structs
  ElementX/Sources/Other/SwiftUI/Layout/TimelineMediaFrame.swift
  ElementX/Sources/Screens/RoomScreen/ComposerToolbar/View/MessageComposer.swift
  ElementX/Sources/Screens/Timeline/TimelineInteractionHandler.swift
  ElementX/Sources/Screens/Timeline/View/Replies/TimelineReplyView.swift
  ElementX/Sources/Screens/Timeline/View/Style/TimelineItemBubbledStylerView.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/ImageRoomTimelineView.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/StickerRoomTimelineView.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/VideoRoomTimelineView.swift
  ElementX/Sources/Services/Timeline/Fixtures/RoomTimelineItemFixtures.swift
  ElementX/Sources/Services/Timeline/TimelineItemProxy.swift
  ElementX/Sources/Services/Timeline/TimelineItems/Items/Messages/ImageRoomTimelineItemContent.swift
  ElementX/Sources/Services/Timeline/TimelineItems/Items/Messages/VideoRoomTimelineItemContent.swift
  ElementX/Sources/Services/Timeline/TimelineItems/Items/Other/StickerRoomTimelineItem.swift
  ElementX/Sources/Services/Timeline/TimelineItems/RoomTimelineItemFactory.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_imageRoomTimelineView-iPad-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_imageRoomTimelineView-iPad-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_imageRoomTimelineView-iPhone-16-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_imageRoomTimelineView-iPhone-16-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_stickerRoomTimelineView-iPad-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_stickerRoomTimelineView-iPad-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_stickerRoomTimelineView-iPhone-16-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_stickerRoomTimelineView-iPhone-16-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_videoRoomTimelineView-iPad-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_videoRoomTimelineView-iPad-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_videoRoomTimelineView-iPhone-16-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_videoRoomTimelineView-iPhone-16-pseudo.1.png
  UnitTests/Sources/LoggingTests.swift
Labels: pr-misc

#3521 Fix toolbar icons disappearing on the iPad after backgrounding the app
  ElementX/Sources/Application/Navigation/NavigationCoordinators.swift
Labels: pr-bugfix

#3524 Update the SDK.
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Sources/Mocks/Generated/SDKGeneratedMocks.swift
  ElementX/Sources/Services/Timeline/TimelineProxy.swift
  project.yml
Labels: pr-misc

#3511 Fix a bug where the security banner has the wrong state when out of sync.
  ElementX/Sources/Screens/HomeScreen/HomeScreenModels.swift
  ElementX/Sources/Screens/HomeScreen/HomeScreenViewModel.swift
  ElementX/Sources/Screens/HomeScreen/View/HomeScreenContent.swift
  ElementX/Sources/Screens/HomeScreen/View/HomeScreenRecoveryKeyConfirmationBanner.swift
  UnitTests/Sources/HomeScreenViewModelTests.swift
Labels: pr-bugfix

#3525 Fix image animations / remove fading when switching between local and remote echoes.
  ElementX/Sources/Other/SwiftUI/Views/LoadableImage.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/ImageRoomTimelineView.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/StickerRoomTimelineView.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/VideoRoomTimelineView.swift
Labels: pr-bugfix

#3532 Update compound iOS
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Sources/Other/SwiftUI/Layout/ScaledFrameModifier.swift
  ElementX/Sources/Other/SwiftUI/Layout/ScaledOffsetModifier.swift
  ElementX/Sources/Other/SwiftUI/Layout/ScaledPaddingModifier.swift
  project.yml
Labels: pr-misc

#3528 Expose the public search feature flag in the developer settings and disable it by default.
  ElementX/Sources/Application/AppSettings.swift
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/DeveloperOptionsScreenModels.swift
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/View/DeveloperOptionsScreen.swift
Labels: pr-misc

#3531 Support adding a caption to media uploads.
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Sources/Mocks/Generated/GeneratedMocks.swift
  ElementX/Sources/Mocks/JoinedRoomProxyMock.swift
  ElementX/Sources/Mocks/TimelineProxyMock.swift
  ElementX/Sources/Other/SwiftUI/Views/BigIcon.swift
  ElementX/Sources/Screens/MediaUploadPreviewScreen/MediaUploadPreviewScreenModels.swift
  ElementX/Sources/Screens/MediaUploadPreviewScreen/MediaUploadPreviewScreenViewModel.swift
  ElementX/Sources/Screens/MediaUploadPreviewScreen/View/MediaUploadPreviewScreen.swift
  ElementX/Sources/Screens/RoomScreen/ComposerToolbar/View/ComposerToolbar.swift
  ElementX/Sources/Screens/RoomScreen/ComposerToolbar/View/MessageComposer.swift
  ElementX/Sources/Screens/RoomScreen/ComposerToolbar/View/RoomAttachmentPicker.swift
  ElementX/Sources/Screens/RoomScreen/ComposerToolbar/View/VoiceMessageRecordingButton.swift
  ElementX/Sources/Services/Timeline/TimelineProxy.swift
  ElementX/Sources/Services/Timeline/TimelineProxyProtocol.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_composerToolbar-iPad-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_composerToolbar-iPad-en-GB.Reply.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_composerToolbar-iPad-en-GB.Voice-Message.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_composerToolbar-iPad-en-GB.With-Suggestions.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_composerToolbar-iPad-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_composerToolbar-iPad-pseudo.Reply.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_composerToolbar-iPad-pseudo.Voice-Message.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_composerToolbar-iPad-pseudo.With-Suggestions.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_composerToolbar-iPhone-16-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_composerToolbar-iPhone-16-en-GB.Reply.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_composerToolbar-iPhone-16-en-GB.Voice-Message.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_composerToolbar-iPhone-16-en-GB.With-Suggestions.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_composerToolbar-iPhone-16-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_composerToolbar-iPhone-16-pseudo.Reply.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_composerToolbar-iPhone-16-pseudo.Voice-Message.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_composerToolbar-iPhone-16-pseudo.With-Suggestions.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_mediaUploadPreviewScreen-iPad-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_mediaUploadPreviewScreen-iPad-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_mediaUploadPreviewScreen-iPhone-16-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_mediaUploadPreviewScreen-iPhone-16-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_messageComposer-iPad-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_messageComposer-iPad-en-GB.Replying-in-thread.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_messageComposer-iPad-en-GB.Replying.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_messageComposer-iPad-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_messageComposer-iPad-pseudo.Replying-in-thread.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_messageComposer-iPad-pseudo.Replying.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_messageComposer-iPhone-16-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_messageComposer-iPhone-16-en-GB.Replying-in-thread.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_messageComposer-iPhone-16-en-GB.Replying.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_messageComposer-iPhone-16-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_messageComposer-iPhone-16-pseudo.Replying-in-thread.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_messageComposer-iPhone-16-pseudo.Replying.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomScreen-iPad-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomScreen-iPad-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomScreen-iPhone-16-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomScreen-iPhone-16-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineView-iPad-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineView-iPad-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineView-iPhone-16-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineView-iPhone-16-pseudo.1.png
  UnitTests/Sources/MediaUploadPreviewScreenViewModelTests.swift
Labels: pr-feature

#3534 Show both defaults and frequent emojis in the timeline item menu, make the list scrollable
  ElementX/Sources/Application/AppSettings.swift
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/DeveloperOptionsScreenModels.swift
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/View/DeveloperOptionsScreen.swift
  ElementX/Sources/Screens/Timeline/View/ItemMenu/TimelineItemMenu.swift
  ElementX/Sources/Screens/Timeline/View/ItemMenu/TimelineItemMenuAction.swift
  ElementX/Sources/Services/Emojis/EmojiProvider.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPad-en-GB.Authenticity.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPad-en-GB.Button-shapes.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPad-en-GB.Identity-Changed.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPad-en-GB.Normal.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPad-en-GB.Own-Unsigned-Devices.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPad-en-GB.Unencrypted.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPad-en-GB.Unknown-failure.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPad-en-GB.Unsigned-Devices.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPad-en-GB.Unsigned.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPad-pseudo.Authenticity.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPad-pseudo.Button-shapes.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPad-pseudo.Identity-Changed.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPad-pseudo.Normal.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPad-pseudo.Own-Unsigned-Devices.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPad-pseudo.Unencrypted.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPad-pseudo.Unknown-failure.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPad-pseudo.Unsigned-Devices.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPad-pseudo.Unsigned.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPhone-16-en-GB.Authenticity.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPhone-16-en-GB.Button-shapes.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPhone-16-en-GB.Identity-Changed.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPhone-16-en-GB.Normal.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPhone-16-en-GB.Own-Unsigned-Devices.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPhone-16-en-GB.Unencrypted.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPhone-16-en-GB.Unknown-failure.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPhone-16-en-GB.Unsigned-Devices.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPhone-16-en-GB.Unsigned.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPhone-16-pseudo.Authenticity.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPhone-16-pseudo.Button-shapes.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPhone-16-pseudo.Identity-Changed.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPhone-16-pseudo.Normal.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPhone-16-pseudo.Own-Unsigned-Devices.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPhone-16-pseudo.Unencrypted.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPhone-16-pseudo.Unknown-failure.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPhone-16-pseudo.Unsigned-Devices.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPhone-16-pseudo.Unsigned.png
Labels: pr-feature

#3540 Fix UI tests, update compound to roll back snapshot testing and avoid the requirement for Swift Testing.
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  project.yml
Labels: pr-misc

#3539 Link the MatrixRustSDK dynamically and only embed it in the main target
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/SupportingFiles/target.yml
  PreviewTests/SupportingFiles/target.yml
  UnitTests/SupportingFiles/target.yml
  project.yml
Labels: pr-build

#3541 Handle NSItemProvider public.image data types.
  ElementX/Sources/Other/Extensions/NSItemProvider.swift
  ElementX/Sources/Screens/MediaPickerScreen/PhotoLibraryPicker.swift
  ElementX/Sources/Screens/Timeline/TimelineInteractionHandler.swift
  ShareExtension/Sources/ShareExtensionViewController.swift
Labels: pr-bugfix

#3542 Enable inline replies for push notifications.
  ElementX/Sources/Services/Notification/Manager/NotificationManager.swift
  UnitTests/Sources/NotificationManager/NotificationManagerTests.swift
Labels: pr-feature

#3543 Fix the media upload preview screen on macOS.
  ElementX/Sources/Screens/MediaUploadPreviewScreen/View/MediaUploadPreviewScreen.swift
Labels: pr-bugfix

#3545 Update the SDK.
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  project.yml
Labels: pr-misc

#3546 Add support for sharing URLs and text.
  ElementX/Sources/FlowCoordinators/RoomFlowCoordinator.swift
  ElementX/Sources/FlowCoordinators/UserSessionFlowCoordinator.swift
  ElementX/Sources/Mocks/JoinedRoomProxyMock.swift
  ElementX/Sources/Other/Extensions/NSItemProvider.swift
  ElementX/Sources/Screens/RoomScreen/ComposerToolbar/ComposerToolbarViewModel.swift
  ElementX/Sources/Screens/RoomScreen/ComposerToolbar/ComposerToolbarViewModelProtocol.swift
  ElementX/Sources/Screens/RoomScreen/RoomScreenCoordinator.swift
  ElementX/Sources/Screens/Timeline/TimelineModels.swift
  ElementX/Sources/ShareExtension/ShareExtensionModels.swift
  ShareExtension/Sources/ShareExtensionViewController.swift
  ShareExtension/SupportingFiles/Info.plist
  UnitTests/Sources/ComposerToolbarViewModelTests.swift
  UnitTests/Sources/RoomFlowCoordinatorTests.swift
  UnitTests/Sources/UserSessionFlowCoordinatorTests.swift
Labels: pr-change

#3547 Add support for adding/editing/removing media captions.
  ElementX/Resources/Localizations/en.lproj/Localizable.strings
  ElementX/Sources/Generated/Strings.swift
  ElementX/Sources/Mocks/Generated/GeneratedMocks.swift
  ElementX/Sources/Screens/RoomScreen/ComposerToolbar/ComposerToolbarModels.swift
  ElementX/Sources/Screens/RoomScreen/ComposerToolbar/ComposerToolbarViewModel.swift
  ElementX/Sources/Screens/RoomScreen/ComposerToolbar/View/MessageComposer.swift
  ElementX/Sources/Screens/Timeline/TimelineInteractionHandler.swift
  ElementX/Sources/Screens/Timeline/TimelineViewModel.swift
  ElementX/Sources/Screens/Timeline/View/ItemMenu/TimelineItemMenuAction.swift
  ElementX/Sources/Screens/Timeline/View/ItemMenu/TimelineItemMenuActionProvider.swift
  ElementX/Sources/Services/Timeline/TimelineController/MockRoomTimelineController.swift
  ElementX/Sources/Services/Timeline/TimelineController/RoomTimelineController.swift
  ElementX/Sources/Services/Timeline/TimelineController/RoomTimelineControllerProtocol.swift
  ElementX/Sources/Services/Timeline/TimelineItems/EventBasedMessageTimelineItemProtocol.swift
  ElementX/Sources/Services/Timeline/TimelineProxy.swift
  ElementX/Sources/Services/Timeline/TimelineProxyProtocol.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_messageComposer-iPad-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_messageComposer-iPad-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_messageComposer-iPhone-16-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_messageComposer-iPhone-16-pseudo.1.png
  UnitTests/Sources/ComposerToolbarViewModelTests.swift
Labels: pr-change

#3544 Delay handling inline notification replies until the user session is established
  ElementX/Sources/Application/AppCoordinator.swift
Labels: pr-bugfix

#3549 Also put the share extension Info.plist updates in the xcodegen yaml 🤦‍♂️
  ElementX.xcodeproj/project.pbxproj
  ShareExtension/SupportingFiles/target.yml
Labels: pr-bugfix

#3550 Knock Requests banner display logic
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Sources/Mocks/InvitedRoomProxyMock.swift
  ElementX/Sources/Mocks/JoinedRoomProxyMock.swift
  ElementX/Sources/Mocks/KnockedRoomProxyMock.swift
  ElementX/Sources/Screens/KnockRequestsListScreen/KnockRequestsListScreenModels.swift
  ElementX/Sources/Screens/KnockRequestsListScreen/KnockRequestsListScreenViewModel.swift
  ElementX/Sources/Screens/KnockRequestsListScreen/View/KnockRequestsListScreen.swift
  ElementX/Sources/Screens/RoomDetailsScreen/RoomDetailsScreenModels.swift
  ElementX/Sources/Screens/RoomDetailsScreen/RoomDetailsScreenViewModel.swift
  ElementX/Sources/Screens/RoomDetailsScreen/View/RoomDetailsScreen.swift
  ElementX/Sources/Screens/RoomScreen/RoomScreenModels.swift
  ElementX/Sources/Screens/RoomScreen/RoomScreenViewModel.swift
  ElementX/Sources/Screens/RoomScreen/View/RoomScreen.swift
  ElementX/Sources/Services/Room/RoomInfoProxy.swift
  project.yml
Labels: pr-wip

#3554 Update how file captions are rendered
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Sources/Screens/RoomScreen/ComposerToolbar/View/MessageComposer.swift
  ElementX/Sources/Screens/Timeline/View/Replies/TimelineReplyView.swift
  ElementX/Sources/Screens/Timeline/View/Style/TimelineItemBubbledStylerView.swift
  ElementX/Sources/Screens/Timeline/View/Style/TimelineItemSendInfoLabel.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/AudioRoomTimelineView.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/FileRoomTimelineView.swift
  ElementX/Sources/Services/Timeline/TimelineItems/Items/Messages/AudioRoomTimelineItemContent.swift
  ElementX/Sources/Services/Timeline/TimelineItems/Items/Messages/FileRoomTimelineItemContent.swift
  ElementX/Sources/Services/Timeline/TimelineItems/Items/Messages/VoiceMessages/VoiceMessageRoomTimelineView.swift
  ElementX/Sources/Services/Timeline/TimelineItems/RoomTimelineItemFactory.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_audioRoomTimelineView-iPad-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_audioRoomTimelineView-iPad-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_audioRoomTimelineView-iPhone-16-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_audioRoomTimelineView-iPhone-16-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_fileRoomTimelineView-iPad-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_fileRoomTimelineView-iPad-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_fileRoomTimelineView-iPhone-16-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_fileRoomTimelineView-iPhone-16-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemBubbledStylerView-iPad-en-GB.Pinned-messages.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemBubbledStylerView-iPad-en-GB.Thread-decorator.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemBubbledStylerView-iPad-pseudo.Pinned-messages.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemBubbledStylerView-iPad-pseudo.Thread-decorator.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemBubbledStylerView-iPhone-16-en-GB.Pinned-messages.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemBubbledStylerView-iPhone-16-en-GB.Thread-decorator.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemBubbledStylerView-iPhone-16-pseudo.Pinned-messages.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemBubbledStylerView-iPhone-16-pseudo.Thread-decorator.png
  UnitTests/Sources/LoggingTests.swift
  project.yml
Labels: pr-change

#3555 Knock Requests navigation flows
  ElementX/Resources/Localizations/en.lproj/Localizable.strings
  ElementX/Sources/FlowCoordinators/RoomFlowCoordinator.swift
  ElementX/Sources/Generated/Strings.swift
  ElementX/Sources/Screens/KnockRequestsListScreen/KnockRequestsListScreenCoordinator.swift
  ElementX/Sources/Screens/KnockRequestsListScreen/KnockRequestsListScreenModels.swift
  ElementX/Sources/Screens/KnockRequestsListScreen/KnockRequestsListScreenViewModel.swift
  ElementX/Sources/Screens/KnockRequestsListScreen/View/KnockRequestCell.swift
  ElementX/Sources/Screens/KnockRequestsListScreen/View/KnockRequestsListScreen.swift
  ElementX/Sources/Screens/RoomScreen/RoomScreenCoordinator.swift
  ElementX/Sources/Screens/RoomScreen/RoomScreenModels.swift
  ElementX/Sources/Screens/RoomScreen/RoomScreenViewModel.swift
  ElementX/Sources/Screens/RoomScreen/View/RoomScreen.swift
Labels: pr-wip

#3556 Fix the presentation of QuickLook when viewing logs on macOS.
  ElementX/Sources/FlowCoordinators/BugReportFlowCoordinator.swift
  ElementX/Sources/Screens/LogViewerScreen/View/LogViewerScreen.swift
Labels: pr-bugfix

#3553 Move timeline item tap gestures to the items themselves instead of the bubbled styler
  ElementX/Sources/Other/SwiftUI/Views/LoadableImage.swift
  ElementX/Sources/Screens/Timeline/TimelineModels.swift
  ElementX/Sources/Screens/Timeline/TimelineViewModel.swift
  ElementX/Sources/Screens/Timeline/View/Style/TimelineItemBubbledStylerView.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/AudioRoomTimelineView.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/CallNotificationRoomTimelineView.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/FileRoomTimelineView.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/ImageRoomTimelineView.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/LocationRoomTimelineView.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/StickerRoomTimelineView.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/VideoRoomTimelineView.swift
  ElementX/Sources/Screens/Timeline/View/TimelineSenderAvatarView.swift
  ElementX/Sources/Services/Timeline/TimelineItems/Items/Messages/VoiceMessages/VoiceMessageRoomTimelineView.swift
Labels: pr-misc

#3557 Bump the RustSDK to v1.0.75
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Sources/Mocks/Generated/SDKGeneratedMocks.swift
  project.yml
Labels: pr-misc

#3560 Move the media caption composer (and Add Caption action) behind a feature flag for now.
  ElementX/Sources/Application/AppSettings.swift
  ElementX/Sources/FlowCoordinators/RoomFlowCoordinator.swift
  ElementX/Sources/Screens/MediaUploadPreviewScreen/MediaUploadPreviewScreenCoordinator.swift
  ElementX/Sources/Screens/MediaUploadPreviewScreen/MediaUploadPreviewScreenModels.swift
  ElementX/Sources/Screens/MediaUploadPreviewScreen/MediaUploadPreviewScreenViewModel.swift
  ElementX/Sources/Screens/MediaUploadPreviewScreen/View/MediaUploadPreviewScreen.swift
  ElementX/Sources/Screens/PinnedEventsTimelineScreen/View/PinnedEventsTimelineScreen.swift
  ElementX/Sources/Screens/RoomScreen/View/RoomScreen.swift
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/DeveloperOptionsScreenModels.swift
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/View/DeveloperOptionsScreen.swift
  ElementX/Sources/Screens/Timeline/TimelineModels.swift
  ElementX/Sources/Screens/Timeline/TimelineViewModel.swift
  ElementX/Sources/Screens/Timeline/View/ItemMenu/TimelineItemMenuActionProvider.swift
  ElementX/Sources/Screens/Timeline/View/Style/TimelineItemBubbledStylerView.swift
  UnitTests/Sources/MediaUploadPreviewScreenViewModelTests.swift
Labels: pr-misc

#3559 Stop delaying ElementCall until the next sync loop and only notify other participants when presumed to already be up to date.
  ElementX/Sources/FlowCoordinators/UserSessionFlowCoordinator.swift
  ElementX/Sources/Screens/CallScreen/CallScreenViewModel.swift
  ElementX/Sources/Screens/CallScreen/View/CallScreen.swift
  ElementX/Sources/Services/ElementCall/ElementCallConfiguration.swift
Labels: pr-bugfix

#3561 Add back missing send button when media captions are disabled.
  ElementX/Sources/Screens/MediaUploadPreviewScreen/View/MediaUploadPreviewScreen.swift
Labels: pr-bugfix

#3567 Fix a bug on iOS 17 where you couldn't long press on a message.
  ElementX/Sources/Screens/Timeline/View/Style/TimelineItemBubbledStylerView.swift
Labels: pr-bugfix

#3568 Small Knock adjustments
  ElementX/Sources/Screens/CreateRoom/CreateRoomViewModel.swift
  ElementX/Sources/Screens/CreateRoom/View/CreateRoomScreen.swift
  ElementX/Sources/Screens/JoinRoomScreen/View/JoinRoomScreen.swift
Labels: pr-bugfix

#3564 Wait until the sync has stopped before marking a background task as complete.
  ElementX/Sources/Application/AppCoordinator.swift
  ElementX/Sources/Mocks/Generated/GeneratedMocks.swift
  ElementX/Sources/Services/Client/ClientProxy.swift
  ElementX/Sources/Services/Client/ClientProxyProtocol.swift
Labels: pr-bugfix

#3569 Make the Unit Test media files into development assets.
  .gitattributes
  DevelopmentAssets/Media/landscape_test_image.jpg
  DevelopmentAssets/Media/landscape_test_video.mov
  DevelopmentAssets/Media/portrait_test_image.jpg
  DevelopmentAssets/Media/portrait_test_video.mp4
  DevelopmentAssets/Media/test_animated_image.gif
  DevelopmentAssets/Media/test_apple_image.heic
  DevelopmentAssets/Media/test_audio.mp3
  DevelopmentAssets/Media/test_image.png
  DevelopmentAssets/Media/test_pdf.pdf
  DevelopmentAssets/Media/test_rotated_image.jpg
  DevelopmentAssets/Media/test_voice_message.m4a
  ElementX.xcodeproj/project.pbxproj
  ElementX/SupportingFiles/target.yml
  UnitTests/SupportingFiles/target.yml
Labels: pr-misc

#3563 Add support for copying a caption.
  ElementX/Resources/Localizations/en.lproj/Localizable.strings
  ElementX/Sources/Generated/Strings.swift
  ElementX/Sources/Other/SwiftUI/Layout/MenuSheetLabelStyle.swift
  ElementX/Sources/Screens/RoomScreen/ComposerToolbar/View/RoomAttachmentPicker.swift
  ElementX/Sources/Screens/Timeline/TimelineInteractionHandler.swift
  ElementX/Sources/Screens/Timeline/View/ItemMenu/TimelineItemMacContextMenu.swift
  ElementX/Sources/Screens/Timeline/View/ItemMenu/TimelineItemMenu.swift
  ElementX/Sources/Screens/Timeline/View/ItemMenu/TimelineItemMenuAction.swift
  ElementX/Sources/Screens/Timeline/View/ItemMenu/TimelineItemMenuActionProvider.swift
  ElementX/Sources/Services/Timeline/Fixtures/RoomTimelineItemFixtures.swift
  ElementX/Sources/Services/Timeline/TimelineItems/EventBasedMessageTimelineItemProtocol.swift
  ElementX/Sources/Services/Timeline/TimelineItems/EventBasedTimelineItemProtocol.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPad-en-GB.Authenticity.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPad-en-GB.Button-shapes.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPad-en-GB.Identity-Changed.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPad-en-GB.Media-with-Caption.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPad-en-GB.Media.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPad-en-GB.Normal.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPad-en-GB.Own-Unsigned-Devices.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPad-en-GB.Unencrypted.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPad-en-GB.Unknown-failure.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPad-en-GB.Unsigned-Devices.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPad-en-GB.Unsigned.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPad-pseudo.Authenticity.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPad-pseudo.Button-shapes.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPad-pseudo.Identity-Changed.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPad-pseudo.Media-with-Caption.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPad-pseudo.Media.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPad-pseudo.Normal.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPad-pseudo.Own-Unsigned-Devices.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPad-pseudo.Unencrypted.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPad-pseudo.Unknown-failure.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPad-pseudo.Unsigned-Devices.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPad-pseudo.Unsigned.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPhone-16-en-GB.Authenticity.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPhone-16-en-GB.Button-shapes.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPhone-16-en-GB.Identity-Changed.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPhone-16-en-GB.Media-with-Caption.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPhone-16-en-GB.Media.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPhone-16-en-GB.Normal.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPhone-16-en-GB.Own-Unsigned-Devices.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPhone-16-en-GB.Unencrypted.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPhone-16-en-GB.Unknown-failure.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPhone-16-en-GB.Unsigned-Devices.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPhone-16-en-GB.Unsigned.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPhone-16-pseudo.Authenticity.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPhone-16-pseudo.Button-shapes.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPhone-16-pseudo.Identity-Changed.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPhone-16-pseudo.Media-with-Caption.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPhone-16-pseudo.Media.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPhone-16-pseudo.Normal.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPhone-16-pseudo.Own-Unsigned-Devices.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPhone-16-pseudo.Unencrypted.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPhone-16-pseudo.Unknown-failure.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPhone-16-pseudo.Unsigned-Devices.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPhone-16-pseudo.Unsigned.png
Labels: pr-change

#3571 Handle media source validation more gracefully.
  ElementX/Sources/Other/SwiftUI/Views/LoadableImage.swift
  ElementX/Sources/Screens/RoomDetailsScreen/RoomDetailsScreenViewModel.swift
  ElementX/Sources/Screens/RoomMemberDetailsScreen/RoomMemberDetailsScreenViewModel.swift
  ElementX/Sources/Screens/UserProfileScreen/UserProfileScreenViewModel.swift
  ElementX/Sources/Services/Media/Provider/MediaSourceProxy.swift
  ElementX/Sources/Services/Notification/Proxy/NotificationItemProxy.swift
  ElementX/Sources/Services/Timeline/TimelineController/RoomTimelineController.swift
  ElementX/Sources/Services/Timeline/TimelineItemProxy.swift
  ElementX/Sources/Services/Timeline/TimelineItems/RoomTimelineItemFactory.swift
  UnitTests/Sources/MediaProvider/MediaLoaderTests.swift
  UnitTests/Sources/MediaProvider/MediaProviderTests.swift
  UnitTests/Sources/VoiceMessageCacheTests.swift
  UnitTests/Sources/VoiceMessageMediaManagerTests.swift
Labels: pr-bugfix

#3575 Move pinned messages button in details
  ElementX/Sources/Screens/RoomDetailsScreen/View/RoomDetailsScreen.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomDetailsScreen-iPad-en-GB.DM-Room.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomDetailsScreen-iPad-en-GB.Generic-Room.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomDetailsScreen-iPad-en-GB.Simple-Room.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomDetailsScreen-iPad-pseudo.DM-Room.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomDetailsScreen-iPad-pseudo.Generic-Room.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomDetailsScreen-iPad-pseudo.Simple-Room.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomDetailsScreen-iPhone-16-en-GB.DM-Room.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomDetailsScreen-iPhone-16-en-GB.Generic-Room.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomDetailsScreen-iPhone-16-en-GB.Simple-Room.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomDetailsScreen-iPhone-16-pseudo.DM-Room.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomDetailsScreen-iPhone-16-pseudo.Generic-Room.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomDetailsScreen-iPhone-16-pseudo.Simple-Room.png
Labels: pr-change

#3574 Add a warning to the media caption composer.
  ElementX/Resources/Localizations/en.lproj/Localizable.strings
  ElementX/Sources/Application/AppSettings.swift
  ElementX/Sources/FlowCoordinators/RoomFlowCoordinator.swift
  ElementX/Sources/Generated/Strings.swift
  ElementX/Sources/Screens/MediaUploadPreviewScreen/MediaUploadPreviewScreenCoordinator.swift
  ElementX/Sources/Screens/MediaUploadPreviewScreen/MediaUploadPreviewScreenModels.swift
  ElementX/Sources/Screens/MediaUploadPreviewScreen/MediaUploadPreviewScreenViewModel.swift
  ElementX/Sources/Screens/MediaUploadPreviewScreen/View/MediaUploadPreviewScreen.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_mediaUploadPreviewScreen-iPad-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_mediaUploadPreviewScreen-iPad-en-GB.Caption-warning.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_mediaUploadPreviewScreen-iPad-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_mediaUploadPreviewScreen-iPad-pseudo.Caption-warning.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_mediaUploadPreviewScreen-iPhone-16-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_mediaUploadPreviewScreen-iPhone-16-en-GB.Caption-warning.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_mediaUploadPreviewScreen-iPhone-16-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_mediaUploadPreviewScreen-iPhone-16-pseudo.Caption-warning.png
  UnitTests/Sources/MediaUploadPreviewScreenViewModelTests.swift
Labels: pr-change
