Repository element-hq/element-x-ios, pull requests merged in 2024-08, with the labels that each got.

#3107 Crypto identity reset
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Resources/Localizations/en.lproj/Localizable.strings
  ElementX/Sources/FlowCoordinators/OnboardingFlowCoordinator.swift
  ElementX/Sources/FlowCoordinators/SettingsFlowCoordinator.swift
  ElementX/Sources/FlowCoordinators/UserSessionFlowCoordinator.swift
  ElementX/Sources/Generated/Strings.swift
  ElementX/Sources/Mocks/Generated/GeneratedMocks.swift
  ElementX/Sources/Mocks/Generated/SDKGeneratedMocks.swift
  ElementX/Sources/Other/SwiftUI/Views/RoundedLabelItem.swift
  ElementX/Sources/Screens/EncryptionReset/EncryptionResetPasswordScreen/EncryptionResetPasswordScreenCoordinator.swift
  ElementX/Sources/Screens/EncryptionReset/EncryptionResetPasswordScreen/EncryptionResetPasswordScreenModels.swift
  ElementX/Sources/Screens/EncryptionReset/EncryptionResetPasswordScreen/EncryptionResetPasswordScreenViewModel.swift
  ElementX/Sources/Screens/EncryptionReset/EncryptionResetPasswordScreen/EncryptionResetPasswordScreenViewModelProtocol.swift
  ElementX/Sources/Screens/EncryptionReset/EncryptionResetPasswordScreen/View/EncryptionResetPasswordScreen.swift
  ElementX/Sources/Screens/EncryptionReset/EncryptionResetScreen/EncryptionResetScreenCoordinator.swift
  ElementX/Sources/Screens/EncryptionReset/EncryptionResetScreen/EncryptionResetScreenModels.swift
  ElementX/Sources/Screens/EncryptionReset/EncryptionResetScreen/EncryptionResetScreenViewModel.swift
  ElementX/Sources/Screens/EncryptionReset/EncryptionResetScreen/EncryptionResetScreenViewModelProtocol.swift
  ElementX/Sources/Screens/EncryptionReset/EncryptionResetScreen/View/EncryptionResetScreen.swift
  ElementX/Sources/Screens/Onboarding/AnalyticsPromptScreen/View/AnalyticsPromptScreen.swift
  ElementX/Sources/Screens/Onboarding/IdentityConfirmationScreen/View/IdentityConfirmationScreen.swift
  ElementX/Sources/Screens/SecureBackup/ResetKeyScreen/ResetRecoveryKeyScreenCoordinator.swift
  ElementX/Sources/Screens/SecureBackup/ResetKeyScreen/ResetRecoveryKeyScreenViewModel.swift
  ElementX/Sources/Screens/SecureBackup/ResetKeyScreen/View/ResetRecoveryKeyScreen.swift
  ElementX/Sources/Screens/SecureBackup/SecureBackupRecoveryKeyScreen/SecureBackupRecoveryKeyScreenCoordinator.swift
  ElementX/Sources/Screens/SecureBackup/SecureBackupRecoveryKeyScreen/SecureBackupRecoveryKeyScreenModels.swift
  ElementX/Sources/Screens/SecureBackup/SecureBackupRecoveryKeyScreen/SecureBackupRecoveryKeyScreenViewModel.swift
  ElementX/Sources/Screens/SecureBackup/SecureBackupRecoveryKeyScreen/View/SecureBackupRecoveryKeyScreen.swift
  ElementX/Sources/Screens/SecureBackup/SecureBackupScreen/SecureBackupScreenCoordinator.swift
  ElementX/Sources/Screens/Settings/SettingsScreen/SettingsScreenCoordinator.swift
  ElementX/Sources/Services/Client/ClientProxy.swift
  ElementX/Sources/Services/Client/ClientProxyProtocol.swift
  PreviewTests/__Snapshots__/PreviewTests/test_analyticsPromptScreen-iPad-en-GB.1.png
  PreviewTests/__Snapshots__/PreviewTests/test_analyticsPromptScreen-iPad-pseudo.1.png
  PreviewTests/__Snapshots__/PreviewTests/test_analyticsPromptScreen-iPhone-15-en-GB.1.png
  PreviewTests/__Snapshots__/PreviewTests/test_analyticsPromptScreen-iPhone-15-pseudo.1.png
  PreviewTests/__Snapshots__/PreviewTests/test_analyticsPromptScreenCheckmarkItem-iPad-en-GB.1.png
  PreviewTests/__Snapshots__/PreviewTests/test_analyticsPromptScreenCheckmarkItem-iPad-pseudo.1.png
  PreviewTests/__Snapshots__/PreviewTests/test_analyticsPromptScreenCheckmarkItem-iPhone-15-en-GB.1.png
  PreviewTests/__Snapshots__/PreviewTests/test_analyticsPromptScreenCheckmarkItem-iPhone-15-pseudo.1.png
  PreviewTests/__Snapshots__/PreviewTests/test_encryptionResetPasswordScreen-iPad-en-GB.1.png
  PreviewTests/__Snapshots__/PreviewTests/test_encryptionResetPasswordScreen-iPad-pseudo.1.png
  PreviewTests/__Snapshots__/PreviewTests/test_encryptionResetPasswordScreen-iPhone-15-en-GB.1.png
  PreviewTests/__Snapshots__/PreviewTests/test_encryptionResetPasswordScreen-iPhone-15-pseudo.1.png
  PreviewTests/__Snapshots__/PreviewTests/test_encryptionResetScreen-iPad-en-GB.1.png
  PreviewTests/__Snapshots__/PreviewTests/test_encryptionResetScreen-iPad-pseudo.1.png
  PreviewTests/__Snapshots__/PreviewTests/test_encryptionResetScreen-iPhone-15-en-GB.1.png
  PreviewTests/__Snapshots__/PreviewTests/test_encryptionResetScreen-iPhone-15-pseudo.1.png
  PreviewTests/__Snapshots__/PreviewTests/test_identityConfirmationScreen-iPad-en-GB.1.png
  PreviewTests/__Snapshots__/PreviewTests/test_identityConfirmationScreen-iPad-pseudo.1.png
  PreviewTests/__Snapshots__/PreviewTests/test_identityConfirmationScreen-iPhone-15-en-GB.1.png
  PreviewTests/__Snapshots__/PreviewTests/test_identityConfirmationScreen-iPhone-15-pseudo.1.png
  PreviewTests/__Snapshots__/PreviewTests/test_resetRecoveryKeyScreen-iPad-en-GB.1.png
  PreviewTests/__Snapshots__/PreviewTests/test_resetRecoveryKeyScreen-iPad-pseudo.1.png
  PreviewTests/__Snapshots__/PreviewTests/test_resetRecoveryKeyScreen-iPhone-15-en-GB.1.png
  PreviewTests/__Snapshots__/PreviewTests/test_resetRecoveryKeyScreen-iPhone-15-pseudo.1.png
  project.yml
Labels: pr-feature

#3112 Update sonarcloud project key
  CONTRIBUTING.md
  README.md
  renovate.json
Labels: pr-build

#3051 Show Encryption Authenticity warnings on messages in the timeline.
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Resources/Localizations/en.lproj/Localizable.strings
  ElementX/Resources/Localizations/en.lproj/Untranslated.strings
  ElementX/Sources/Application/AppSettings.swift
  ElementX/Sources/FlowCoordinators/RoomFlowCoordinator.swift
  ElementX/Sources/Generated/Strings+Untranslated.swift
  ElementX/Sources/Generated/Strings.swift
  ElementX/Sources/Screens/RoomScreen/View/Style/TimelineItemBubbledStylerView.swift
  ElementX/Sources/Screens/RoomScreen/View/Style/TimelineItemSendInfoLabel.swift
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/DeveloperOptionsScreenModels.swift
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/View/DeveloperOptionsScreen.swift
  ElementX/Sources/Services/Timeline/TimelineItemContent/EncryptionAuthenticity.swift
  ElementX/Sources/Services/Timeline/TimelineItemContent/RoomTimelineItemProperties.swift
  ElementX/Sources/Services/Timeline/TimelineItemProxy.swift
  ElementX/Sources/Services/Timeline/TimelineItems/EventBasedTimelineItemProtocol.swift
  ElementX/Sources/Services/Timeline/TimelineItems/RoomTimelineItemFactory.swift
  ElementX/Sources/UITests/UITestsAppCoordinator.swift
  Package.resolved
  PreviewTests/__Snapshots__/PreviewTests/test_timelineItemBubbledStylerView-iPad-en-GB.Encryption-Indicators.png
  PreviewTests/__Snapshots__/PreviewTests/test_timelineItemBubbledStylerView-iPad-pseudo.Encryption-Indicators.png
  PreviewTests/__Snapshots__/PreviewTests/test_timelineItemBubbledStylerView-iPhone-15-en-GB.Encryption-Indicators.png
  PreviewTests/__Snapshots__/PreviewTests/test_timelineItemBubbledStylerView-iPhone-15-pseudo.Encryption-Indicators.png
  PreviewTests/__Snapshots__/PreviewTests/test_timelineItemSendInfoLabel-iPad-en-GB.1.png
  PreviewTests/__Snapshots__/PreviewTests/test_timelineItemSendInfoLabel-iPad-pseudo.1.png
  PreviewTests/__Snapshots__/PreviewTests/test_timelineItemSendInfoLabel-iPhone-15-en-GB.1.png
  PreviewTests/__Snapshots__/PreviewTests/test_timelineItemSendInfoLabel-iPhone-15-pseudo.1.png
  UnitTests/Sources/TimelineItemFactoryTests.swift
  project.yml
Labels: pr-wip

#3099 Pinned items timeline implementation for the banner
  ElementX/Sources/Mocks/Generated/GeneratedMocks.swift
  ElementX/Sources/Mocks/Generated/SDKGeneratedMocks.swift
  ElementX/Sources/Mocks/RoomProxyMock.swift
  ElementX/Sources/Other/Extensions/AttributedString.swift
  ElementX/Sources/Screens/RoomScreen/RoomScreenModels.swift
  ElementX/Sources/Screens/RoomScreen/RoomScreenViewModel.swift
  ElementX/Sources/Screens/RoomScreen/View/PinnedItemsBanner/PinnedItemsBannerView.swift
  ElementX/Sources/Screens/RoomScreen/View/RoomScreen.swift
  ElementX/Sources/Screens/RoomScreen/View/Style/TimelineItemBubbledStylerView.swift
  ElementX/Sources/Services/Client/ClientProxy.swift
  ElementX/Sources/Services/Room/RoomProxy.swift
  ElementX/Sources/Services/Room/RoomProxyProtocol.swift
  ElementX/Sources/Services/Room/RoomSummary/RoomEventStringBuilder.swift
  ElementX/Sources/Services/Room/RoomSummary/RoomMessageEventStringBuilder.swift
  ElementX/Sources/Services/Timeline/TimelineController/RoomTimelineController.swift
  ElementX/Sources/Services/Timeline/TimelineController/RoomTimelineControllerFactory.swift
  ElementX/Sources/UITests/UITestsAppCoordinator.swift
  NSE/Sources/NotificationContentBuilder.swift
  NSE/Sources/NotificationServiceExtension.swift
  PreviewTests/__Snapshots__/PreviewTests/test_pinnedItemsBannerView-iPad-en-GB.1.png
  PreviewTests/__Snapshots__/PreviewTests/test_pinnedItemsBannerView-iPad-pseudo.1.png
  PreviewTests/__Snapshots__/PreviewTests/test_pinnedItemsBannerView-iPhone-15-en-GB.1.png
  PreviewTests/__Snapshots__/PreviewTests/test_pinnedItemsBannerView-iPhone-15-pseudo.1.png
Labels: pr-wip

#3114 Fix a bug where moving a new line in the composer could move the caret.
  ElementX/Sources/Screens/RoomScreen/ComposerToolbar/View/MessageComposerTextField.swift
Labels: pr-bugfix

#3116 Add Encryption Authenticity explanations.
  ElementX/Sources/Other/SwiftUI/Views/RoomInviterLabel.swift
  ElementX/Sources/Screens/HomeScreen/View/HomeScreenInviteCell.swift
  ElementX/Sources/Screens/RoomScreen/RoomScreenModels.swift
  ElementX/Sources/Screens/RoomScreen/RoomScreenViewModel.swift
  ElementX/Sources/Screens/RoomScreen/View/ItemMenu/TimelineItemMenu.swift
  ElementX/Sources/Screens/RoomScreen/View/Style/TimelineItemBubbledStylerView.swift
  ElementX/Sources/Screens/RoomScreen/View/Style/TimelineItemSendInfoLabel.swift
  ElementX/Sources/Services/Timeline/TimelineItemContent/EncryptionAuthenticity.swift
  PreviewTests/__Snapshots__/PreviewTests/test_timelineItemBubbledStylerView-iPad-en-GB.Encryption-Indicators.png
  PreviewTests/__Snapshots__/PreviewTests/test_timelineItemBubbledStylerView-iPad-pseudo.Encryption-Indicators.png
  PreviewTests/__Snapshots__/PreviewTests/test_timelineItemBubbledStylerView-iPhone-15-en-GB.Encryption-Indicators.png
  PreviewTests/__Snapshots__/PreviewTests/test_timelineItemBubbledStylerView-iPhone-15-pseudo.Encryption-Indicators.png
  PreviewTests/__Snapshots__/PreviewTests/test_timelineItemMenu-iPad-en-GB.Authenticity-not-guaranteed.png
  PreviewTests/__Snapshots__/PreviewTests/test_timelineItemMenu-iPad-en-GB.Unencrypted.png
  PreviewTests/__Snapshots__/PreviewTests/test_timelineItemMenu-iPad-pseudo.Authenticity-not-guaranteed.png
  PreviewTests/__Snapshots__/PreviewTests/test_timelineItemMenu-iPad-pseudo.Unencrypted.png
  PreviewTests/__Snapshots__/PreviewTests/test_timelineItemMenu-iPhone-15-en-GB.Authenticity-not-guaranteed.png
  PreviewTests/__Snapshots__/PreviewTests/test_timelineItemMenu-iPhone-15-en-GB.Unencrypted.png
  PreviewTests/__Snapshots__/PreviewTests/test_timelineItemMenu-iPhone-15-pseudo.Authenticity-not-guaranteed.png
  PreviewTests/__Snapshots__/PreviewTests/test_timelineItemMenu-iPhone-15-pseudo.Unencrypted.png
  PreviewTests/__Snapshots__/PreviewTests/test_timelineItemSendInfoLabel-iPad-en-GB.1.png
  PreviewTests/__Snapshots__/PreviewTests/test_timelineItemSendInfoLabel-iPad-pseudo.1.png
  PreviewTests/__Snapshots__/PreviewTests/test_timelineItemSendInfoLabel-iPhone-15-en-GB.1.png
  PreviewTests/__Snapshots__/PreviewTests/test_timelineItemSendInfoLabel-iPhone-15-pseudo.1.png
Labels: pr-wip

#3120 Fixes #3050 - Sync mute state between ElementCall and CallKit
  ElementX/Sources/Application/AppCoordinator.swift
  ElementX/Sources/Mocks/Generated/GeneratedMocks.swift
  ElementX/Sources/Screens/CallScreen/CallScreenViewModel.swift
  ElementX/Sources/Services/ElementCall/ElementCallService.swift
  ElementX/Sources/Services/ElementCall/ElementCallServiceProtocol.swift
  ElementX/Sources/Services/ElementCall/ElementCallWidgetDriver.swift
  ElementX/Sources/Services/ElementCall/ElementCallWidgetDriverProtocol.swift
Labels: pr-feature

#3118 Pinned events banner loading state
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Resources/Localizations/en.lproj/Localizable.strings
  ElementX/Sources/Generated/Strings.swift
  ElementX/Sources/Mocks/NetworkMonitorMock.swift
  ElementX/Sources/Screens/RoomScreen/RoomScreenCoordinator.swift
  ElementX/Sources/Screens/RoomScreen/RoomScreenModels.swift
  ElementX/Sources/Screens/RoomScreen/RoomScreenViewModel.swift
  ElementX/Sources/Screens/RoomScreen/View/PinnedItemsBanner/PinnedItemsBannerView.swift
  ElementX/Sources/Screens/RoomScreen/View/ReadReceipts/ReadReceiptsSummaryView.swift
  ElementX/Sources/Screens/RoomScreen/View/RoomScreen.swift
  ElementX/Sources/Screens/RoomScreen/View/Supplementary/TimelineReadReceiptsView.swift
  ElementX/Sources/Screens/RoomScreen/View/Timeline/HighlightedTimelineItemModifier.swift
  ElementX/Sources/Screens/RoomScreen/View/Timeline/TimelineView.swift
  ElementX/Sources/Services/Room/RoomSummary/RoomEventStringBuilder.swift
  ElementX/Sources/Services/Room/RoomSummary/RoomMessageEventStringBuilder.swift
  ElementX/Sources/UITests/UITestsAppCoordinator.swift
  ElementX/Sources/UnitTests/UnitTestsAppCoordinator.swift
  PreviewTests/__Snapshots__/PreviewTests/test_pinnedItemsBannerView-iPad-en-GB.1.png
  PreviewTests/__Snapshots__/PreviewTests/test_pinnedItemsBannerView-iPad-pseudo.1.png
  PreviewTests/__Snapshots__/PreviewTests/test_pinnedItemsBannerView-iPhone-15-en-GB.1.png
  PreviewTests/__Snapshots__/PreviewTests/test_pinnedItemsBannerView-iPhone-15-pseudo.1.png
  UnitTests/Sources/PillContextTests.swift
  UnitTests/Sources/PinnedEventsBannerStateTests.swift
  UnitTests/Sources/RoomScreenViewModelTests.swift
  project.yml
Labels: pr-wip

#3121 Finalise strings/icons for EncryptionAuthenticity.
  ElementX/Resources/Localizations/en.lproj/Localizable.strings
  ElementX/Sources/Generated/Strings.swift
  ElementX/Sources/Screens/RoomScreen/View/ItemMenu/TimelineItemMenu.swift
  ElementX/Sources/Services/Timeline/TimelineItemContent/EncryptionAuthenticity.swift
  PreviewTests/__Snapshots__/PreviewTests/test_timelineItemBubbledStylerView-iPad-en-GB.Encryption-Indicators.png
  PreviewTests/__Snapshots__/PreviewTests/test_timelineItemBubbledStylerView-iPad-pseudo.Encryption-Indicators.png
  PreviewTests/__Snapshots__/PreviewTests/test_timelineItemBubbledStylerView-iPhone-15-en-GB.Encryption-Indicators.png
  PreviewTests/__Snapshots__/PreviewTests/test_timelineItemBubbledStylerView-iPhone-15-pseudo.Encryption-Indicators.png
  PreviewTests/__Snapshots__/PreviewTests/test_timelineItemMenu-iPad-en-GB.Unencrypted.png
  PreviewTests/__Snapshots__/PreviewTests/test_timelineItemMenu-iPad-en-GB.Unsigned.png
  PreviewTests/__Snapshots__/PreviewTests/test_timelineItemMenu-iPad-pseudo.Unencrypted.png
  PreviewTests/__Snapshots__/PreviewTests/test_timelineItemMenu-iPad-pseudo.Unsigned.png
  PreviewTests/__Snapshots__/PreviewTests/test_timelineItemMenu-iPhone-15-en-GB.Unencrypted.png
  PreviewTests/__Snapshots__/PreviewTests/test_timelineItemMenu-iPhone-15-en-GB.Unsigned.png
  PreviewTests/__Snapshots__/PreviewTests/test_timelineItemMenu-iPhone-15-pseudo.Unencrypted.png
  PreviewTests/__Snapshots__/PreviewTests/test_timelineItemMenu-iPhone-15-pseudo.Unsigned.png
  PreviewTests/__Snapshots__/PreviewTests/test_timelineItemSendInfoLabel-iPad-en-GB.1.png
  PreviewTests/__Snapshots__/PreviewTests/test_timelineItemSendInfoLabel-iPad-pseudo.1.png
  PreviewTests/__Snapshots__/PreviewTests/test_timelineItemSendInfoLabel-iPhone-15-en-GB.1.png
  PreviewTests/__Snapshots__/PreviewTests/test_timelineItemSendInfoLabel-iPhone-15-pseudo.1.png
Labels: pr-wip

#3123 state events for pinning and unpinning
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/View/DeveloperOptionsScreen.swift
  ElementX/Sources/Services/Client/ClientProxy.swift
  ElementX/Sources/Services/Timeline/TimelineItems/RoomStateEventStringBuilder.swift
  project.yml
Labels: pr-wip

#3124 Put a space between the version and build numbers on the Nightly icon
  fastlane/Fastfile
Labels: pr-misc

#3125 Make sure the whole room header is tappable.
  ElementX/Sources/Screens/RoomScreen/View/RoomScreen.swift
Labels: pr-bugfix

#3128 Pinned events banner goes backwards
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Sources/Screens/RoomScreen/RoomScreenModels.swift
  ElementX/Sources/Screens/RoomScreen/RoomScreenViewModel.swift
  UnitTests/Sources/PinnedEventsBannerStateTests.swift
  project.yml
Labels: pr-wip

#3129 Delete more unnecessary logs
  ElementX/Sources/Screens/HomeScreen/HomeScreenViewModel.swift
  ElementX/Sources/Screens/MessageForwardingScreen/MessageForwardingScreenViewModel.swift
  ElementX/Sources/Screens/RoomScreen/View/Timeline/TimelineTableViewController.swift
  ElementX/Sources/Services/Room/RoomSummary/RoomSummaryProvider.swift
  ElementX/Sources/Services/Timeline/RoomTimelineProvider.swift
  ElementX/Sources/Services/Timeline/TimelineProxy.swift
Labels: pr-misc

#3127 Force the room list search text field to always be displayed
  ElementX/Sources/Screens/HomeScreen/View/HomeScreenContent.swift
  PreviewTests/__Snapshots__/PreviewTests/test_homeScreen-iPad-en-GB.Loaded.png
  PreviewTests/__Snapshots__/PreviewTests/test_homeScreen-iPad-pseudo.Loaded.png
  PreviewTests/__Snapshots__/PreviewTests/test_homeScreen-iPhone-15-en-GB.Loaded.png
  PreviewTests/__Snapshots__/PreviewTests/test_homeScreen-iPhone-15-pseudo.Loaded.png
Labels: pr-bugfix

#3138 Fix search in the Change Roles screen.
  ElementX/Sources/Screens/RoomChangeRolesScreen/View/RoomChangeRolesScreen.swift
Labels: pr-bugfix

#3143 Fix for a memory leak
  ElementX/Sources/Screens/RoomScreen/RoomScreenViewModel.swift
Labels: pr-wip

#3141 Fixes #3126 - Prevent identity confirmation from blocking the user's progress after registering through OIDC
  ElementX/Sources/FlowCoordinators/OnboardingFlowCoordinator.swift
Labels: pr-bugfix

#3153 Remove links from pinned events banner
  ElementX/Sources/Screens/RoomScreen/RoomScreenModels.swift
Labels: pr-wip

#3156 Stop showing filters when the room list is not in the `rooms` display mode
  ElementX/Sources/Screens/HomeScreen/HomeScreenModels.swift
  PreviewTests/__Snapshots__/PreviewTests/test_homeScreen-iPad-en-GB.Empty.png
  PreviewTests/__Snapshots__/PreviewTests/test_homeScreen-iPad-pseudo.Empty.png
Labels: pr-bugfix

#3158 Bump the SDK to v1.0.37
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  project.yml
Labels: pr-misc

#3163 PinnedBanner is now managed by the RoomScreenViewModel
  ElementX.xcodeproj/project.pbxproj
  ElementX/Sources/Mocks/EventTimelineItemSDKMock.swift
  ElementX/Sources/Screens/FilePreviewScreen/InteractiveQuickLook.swift
  ElementX/Sources/Screens/PinnedEventsTimelineScreen/PinnedEventsTimelineScreenModels.swift
  ElementX/Sources/Screens/PinnedEventsTimelineScreen/View/PinnedEventsTimelineScreen.swift
  ElementX/Sources/Screens/RoomScreen/RoomScreenCoordinator.swift
  ElementX/Sources/Screens/RoomScreen/RoomScreenModels.swift
  ElementX/Sources/Screens/RoomScreen/RoomScreenViewModel.swift
  ElementX/Sources/Screens/RoomScreen/RoomScreenViewModelProtocol.swift
  ElementX/Sources/Screens/RoomScreen/View/RoomScreen.swift
  ElementX/Sources/Screens/Timeline/TimelineModels.swift
  ElementX/Sources/Screens/Timeline/TimelineViewModel.swift
  UnitTests/Sources/RoomScreenViewModelTests.swift
  UnitTests/Sources/TimelineViewModelTests.swift
Labels: pr-wip

#3167 Update package acknowledgements (after resetting the packages).
  ElementX/SupportingFiles/Settings.bundle/Acknowledgements.plist
  ElementX/SupportingFiles/Settings.bundle/Packages/compound-design-tokens.plist
  ElementX/SupportingFiles/Settings.bundle/Packages/emojibase-bindings.plist
  ElementX/SupportingFiles/Settings.bundle/Packages/maplibre-gl-native-distribution.plist
  ElementX/SupportingFiles/Settings.bundle/Packages/matrix-analytics-events.plist
  ElementX/SupportingFiles/Settings.bundle/Packages/matrix-rust-components-swift.plist
  ElementX/SupportingFiles/Settings.bundle/Packages/ogg-swift.plist
  ElementX/SupportingFiles/Settings.bundle/Packages/opus-swift.plist
  ElementX/SupportingFiles/Settings.bundle/Packages/posthog-ios.plist
  ElementX/SupportingFiles/Settings.bundle/Packages/sentry-cocoa.plist
  ElementX/SupportingFiles/Settings.bundle/Packages/swift-ogg.plist
Labels: pr-misc

#3169 RoomScreenViewModel refactor part 2
  ElementX/Sources/Screens/RoomScreen/RoomScreenCoordinator.swift
  ElementX/Sources/Screens/RoomScreen/RoomScreenModels.swift
  ElementX/Sources/Screens/RoomScreen/RoomScreenViewModel.swift
  ElementX/Sources/Screens/RoomScreen/View/RoomScreen.swift
  ElementX/Sources/Screens/Timeline/TimelineInteractionHandler.swift
  ElementX/Sources/Screens/Timeline/TimelineModels.swift
  ElementX/Sources/Screens/Timeline/TimelineViewModel.swift
  ElementX/Sources/Screens/Timeline/View/Style/TimelineItemBubbledStylerView.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/HighlightedTimelineItemModifier.swift
  ElementX/Sources/Screens/Timeline/View/TimelineView.swift
  UnitTests/Sources/RoomScreenViewModelTests.swift
Labels: pr-bugfix

#3171 Bump the SDK to v1.0.39
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Sources/Services/Room/RoomSummary/RoomSummaryProvider.swift
  project.yml
Labels: pr-misc

#3174 Navigation support for upcoming Element Call Picture in Picture mode.
  ElementX/Sources/Application/AppSettings.swift
  ElementX/Sources/Application/Navigation/NavigationCoordinators.swift
  ElementX/Sources/FlowCoordinators/UserSessionFlowCoordinator.swift
  ElementX/Sources/Mocks/Generated/GeneratedMocks.swift
  ElementX/Sources/Screens/CallScreen/CallScreenCoordinator.swift
  ElementX/Sources/Screens/CallScreen/CallScreenModels.swift
  ElementX/Sources/Screens/CallScreen/CallScreenViewModel.swift
  ElementX/Sources/Screens/CallScreen/View/CallScreen.swift
  ElementX/Sources/Screens/RoomScreen/RoomScreenCoordinator.swift
  ElementX/Sources/Screens/RoomScreen/RoomScreenModels.swift
  ElementX/Sources/Screens/RoomScreen/RoomScreenViewModel.swift
  ElementX/Sources/Services/ElementCall/ElementCallService.swift
  ElementX/Sources/Services/ElementCall/ElementCallServiceProtocol.swift
  UnitTests/Sources/NavigationSplitCoordinatorTests.swift
Labels: pr-wip

#3180 Show message encryption authenticity warnings in the timeline.
  ElementX/Sources/Application/AppSettings.swift
  ElementX/Sources/FlowCoordinators/RoomFlowCoordinator.swift
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/DeveloperOptionsScreenModels.swift
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/View/DeveloperOptionsScreen.swift
  ElementX/Sources/Services/Timeline/TimelineItems/RoomTimelineItemFactory.swift
  ElementX/Sources/UITests/UITestsAppCoordinator.swift
  UnitTests/Sources/TimelineItemFactoryTests.swift
Labels: pr-feature

#3181 Remove GenericCallLinkCoordinator, merging it into CallScreen.
  ElementX.xcodeproj/project.pbxproj
  ElementX/Sources/Application/AppCoordinator.swift
  ElementX/Sources/Application/Navigation/NavigationCoordinators.swift
  ElementX/Sources/Application/Navigation/NavigationRootCoordinator.swift
  ElementX/Sources/FlowCoordinators/UserSessionFlowCoordinator.swift
  ElementX/Sources/Mocks/Generated/GeneratedMocks.swift
  ElementX/Sources/Mocks/RoomProxyMock.swift
  ElementX/Sources/Screens/CallScreen/CallScreenCoordinator.swift
  ElementX/Sources/Screens/CallScreen/CallScreenViewModel.swift
  ElementX/Sources/Screens/CallScreen/View/CallScreen.swift
  ElementX/Sources/Screens/Other/GenericCallLinkCoordinator.swift
  ElementX/Sources/Services/ElementCall/ElementCallConfiguration.swift
  ElementX/Sources/Services/ElementCall/ElementCallWidgetDriver.swift
  ElementX/Sources/Services/ElementCall/ElementCallWidgetDriverProtocol.swift
  ElementX/Sources/Services/ElementCall/GenericCallLinkWidgetDriver.swift
  ElementX/Sources/Services/Room/RoomProxy.swift
  ElementX/Sources/Services/Room/RoomProxyProtocol.swift
  UnitTests/Sources/NavigationRootCoordinatorTests.swift
Labels: pr-misc

#3142 Clarify the copy for Mentions in notifications.
  NSE/Sources/NotificationContentBuilder.swift
Labels: pr-change

#3191 Remove a notification if its event has been redacted.
  ElementX/Sources/Other/Extensions/UNNotificationContent.swift
  NSE/Sources/NotificationContentBuilder.swift
  NSE/Sources/NotificationServiceExtension.swift
  NSE/Sources/Other/UNNotificationRequest.swift
Labels: pr-change

#3182 Pinned Events Timeline actions and differentiation
  ElementX.xcodeproj/project.pbxproj
  ElementX/Resources/Localizations/en.lproj/Localizable.strings
  ElementX/Sources/FlowCoordinators/PinnedEventsTimelineFlowCoordinator.swift
  ElementX/Sources/FlowCoordinators/RoomFlowCoordinator.swift
  ElementX/Sources/Generated/Strings.swift
  ElementX/Sources/Screens/PinnedEventsTimelineScreen/PinnedEventsTimelineScreenCoordinator.swift
  ElementX/Sources/Screens/PinnedEventsTimelineScreen/View/PinnedEventsTimelineScreen.swift
  ElementX/Sources/Screens/RoomPollsHistoryScreen/View/RoomPollsHistoryScreen.swift
  ElementX/Sources/Screens/RoomScreen/RoomScreenCoordinator.swift
  ElementX/Sources/Screens/RoomScreen/RoomScreenModels.swift
  ElementX/Sources/Screens/RoomScreen/RoomScreenViewModel.swift
  ElementX/Sources/Screens/RoomScreen/RoomScreenViewModelProtocol.swift
  ElementX/Sources/Screens/RoomScreen/View/PinnedItemsBanner/PinnedItemsBannerView.swift
  ElementX/Sources/Screens/RoomScreen/View/RoomScreen.swift
  ElementX/Sources/Screens/Timeline/TimelineInteractionHandler.swift
  ElementX/Sources/Screens/Timeline/TimelineModels.swift
  ElementX/Sources/Screens/Timeline/TimelineViewModel.swift
  ElementX/Sources/Screens/Timeline/View/ItemMenu/TimelineItemMenuAction.swift
  ElementX/Sources/Screens/Timeline/View/ItemMenu/TimelineItemMenuActionProvider.swift
  ElementX/Sources/Screens/Timeline/View/Polls/PollView.swift
  ElementX/Sources/Screens/Timeline/View/ReadReceipts/ReadReceiptsSummaryView.swift
  ElementX/Sources/Screens/Timeline/View/Style/TimelineItemBubbledStylerView.swift
  ElementX/Sources/Screens/Timeline/View/Supplementary/TimelineItemStatusView.swift
  ElementX/Sources/Screens/Timeline/View/Supplementary/TimelineReadReceiptsView.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/HighlightedTimelineItemModifier.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/PollRoomTimelineView.swift
  ElementX/Sources/Screens/Timeline/View/TimelineView.swift
  ElementX/Sources/Services/Room/JoinedRoomProxy.swift
  ElementX/Sources/Services/Timeline/GeoURI.swift
  ElementX/Sources/Services/Timeline/TimelineController/RoomTimelineController.swift
  ElementX/Sources/Services/Timeline/TimelineController/RoomTimelineControllerFactory.swift
  ElementX/Sources/UITests/UITestsAppCoordinator.swift
  PreviewTests/__Snapshots__/PreviewTests/test_pollRoomTimelineView-iPad-en-GB.Preview.png
  PreviewTests/__Snapshots__/PreviewTests/test_pollRoomTimelineView-iPad-pseudo.Preview.png
  PreviewTests/__Snapshots__/PreviewTests/test_pollRoomTimelineView-iPhone-15-en-GB.Preview.png
  PreviewTests/__Snapshots__/PreviewTests/test_pollRoomTimelineView-iPhone-15-pseudo.Preview.png
  PreviewTests/__Snapshots__/PreviewTests/test_pollView-iPad-en-GB.Preview.png
  PreviewTests/__Snapshots__/PreviewTests/test_pollView-iPad-pseudo.Preview.png
  PreviewTests/__Snapshots__/PreviewTests/test_pollView-iPhone-15-en-GB.Preview.png
  PreviewTests/__Snapshots__/PreviewTests/test_pollView-iPhone-15-pseudo.Preview.png
  UnitTests/Sources/PillContextTests.swift
  UnitTests/Sources/PinnedEventsBannerStateTests.swift
  UnitTests/Sources/RoomScreenViewModelTests.swift
  UnitTests/Sources/TimelineViewModelTests.swift
Labels: pr-wip

#3192 Fix the call URL input field in Developer Options
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/View/DeveloperOptionsScreen.swift
Labels: pr-misc

#3193 `TimelineKind` refactor
  ElementX/Sources/Mocks/Generated/GeneratedMocks.swift
  ElementX/Sources/Mocks/RoomTimelineProviderMock.swift
  ElementX/Sources/Screens/PinnedEventsTimelineScreen/PinnedEventsTimelineScreenCoordinator.swift
  ElementX/Sources/Screens/PinnedEventsTimelineScreen/View/PinnedEventsTimelineScreen.swift
  ElementX/Sources/Screens/RoomScreen/RoomScreenCoordinator.swift
  ElementX/Sources/Screens/RoomScreen/View/PinnedItemsBanner/PinnedItemsBannerView.swift
  ElementX/Sources/Screens/RoomScreen/View/RoomScreen.swift
  ElementX/Sources/Screens/Timeline/TimelineViewModel.swift
  ElementX/Sources/Screens/Timeline/View/ReadReceipts/ReadReceiptsSummaryView.swift
  ElementX/Sources/Screens/Timeline/View/Supplementary/TimelineReadReceiptsView.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/HighlightedTimelineItemModifier.swift
  ElementX/Sources/Screens/Timeline/View/TimelineView.swift
  ElementX/Sources/Services/Room/JoinedRoomProxy.swift
  ElementX/Sources/Services/Timeline/RoomTimelineProvider.swift
  ElementX/Sources/Services/Timeline/RoomTimelineProviderProtocol.swift
  ElementX/Sources/Services/Timeline/TimelineController/MockRoomTimelineController.swift
  ElementX/Sources/Services/Timeline/TimelineController/RoomTimelineController.swift
  ElementX/Sources/Services/Timeline/TimelineController/RoomTimelineControllerFactory.swift
  ElementX/Sources/Services/Timeline/TimelineController/RoomTimelineControllerProtocol.swift
  ElementX/Sources/Services/Timeline/TimelineProxy.swift
  ElementX/Sources/Services/Timeline/TimelineProxyProtocol.swift
  ElementX/Sources/UITests/UITestsAppCoordinator.swift
  PreviewTests/__Snapshots__/PreviewTests/test_pinnedItemsBannerView-iPhone-15-pseudo.1.png
  UnitTests/Sources/PillContextTests.swift
  UnitTests/Sources/TimelineViewModelTests.swift
Labels: pr-wip

#3196 Update the SDK
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Resources/Localizations/en.lproj/Localizable.strings
  ElementX/Sources/Generated/Strings.swift
  ElementX/Sources/Mocks/Generated/SDKGeneratedMocks.swift
  ElementX/Sources/Other/Extensions/URL.swift
  ElementX/Sources/Screens/Timeline/TimelineViewModel.swift
  ElementX/Sources/Screens/Timeline/View/Style/TimelineItemSendInfoLabel.swift
  ElementX/Sources/Screens/Timeline/View/Style/TimelineStyler.swift
  ElementX/Sources/Services/Authentication/AuthenticationService.swift
  ElementX/Sources/Services/Keychain/KeychainController.swift
  ElementX/Sources/Services/QRCode/QRCodeLoginService.swift
  ElementX/Sources/Services/Timeline/TimelineItemContent/EncryptionAuthenticity.swift
  ElementX/Sources/Services/Timeline/TimelineItemProxy.swift
  ElementX/Sources/Services/Timeline/TimelineItems/EventBasedTimelineItemProtocol.swift
  ElementX/Sources/Services/UserSession/RestorationToken.swift
  ElementX/Sources/Services/UserSession/SessionDirectories.swift
  ElementX/Sources/Services/UserSession/UserSessionStore.swift
  ElementX/Sources/Services/UserSession/UserSessionStoreProtocol.swift
  NSE/Sources/Other/NSEUserSession.swift
  NSE/SupportingFiles/target.yml
  UnitTests/Sources/KeychainControllerTests.swift
  UnitTests/Sources/RestorationTokenTests.swift
  UnitTests/Sources/SessionDirectoriesTests.swift
  UnitTests/Sources/TextBasedRoomTimelineTests.swift
  project.yml
Labels: pr-misc

#3204 Picture in Picture support for Calls (requires a supported widget deployment).
  ElementX/Sources/Application/AppCoordinator.swift
  ElementX/Sources/Application/AppSettings.swift
  ElementX/Sources/FlowCoordinators/UserSessionFlowCoordinator.swift
  ElementX/Sources/Screens/CallScreen/CallScreenCoordinator.swift
  ElementX/Sources/Screens/CallScreen/CallScreenViewModel.swift
  ElementX/Sources/Screens/CallScreen/View/CallScreen.swift
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/DeveloperOptionsScreenModels.swift
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/View/DeveloperOptionsScreen.swift
Labels: pr-feature

#3209 Make sure reactions always go through the timeline controller.
  ElementX/Sources/Screens/Timeline/TimelineInteractionHandler.swift
Labels: pr-bugfix
