Repository element-hq/element-x-ios, pull requests merged in 2024-10, with the labels that each got.

#3356 Bump the RustSDK to v1.0.53: adopt latest record based timeline item APIs
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Sources/Application/AppMediatorProtocol.swift
  ElementX/Sources/Mocks/EventTimelineItem.swift
  ElementX/Sources/Mocks/Generated/SDKGeneratedMocks.swift
  ElementX/Sources/Mocks/PollMock.swift
  ElementX/Sources/Mocks/RoomTimelineProviderMock.swift
  ElementX/Sources/Mocks/SDK/EventTimelineItemSDKMock.swift
  ElementX/Sources/Mocks/TimelineItemMock.swift
  ElementX/Sources/Other/Extensions/Array.swift
  ElementX/Sources/Other/Extensions/ProposedViewSize.swift
  ElementX/Sources/Other/Extensions/URL.swift
  ElementX/Sources/Screens/MessageForwardingScreen/View/MessageForwardingScreen.swift
  ElementX/Sources/Screens/RoomScreen/ComposerToolbar/ComposerToolbarViewModel.swift
  ElementX/Sources/Screens/RoomScreen/ComposerToolbar/View/ComposerToolbar.swift
  ElementX/Sources/Screens/Timeline/TimelineModels.swift
  ElementX/Sources/Screens/Timeline/TimelineTableViewController.swift
  ElementX/Sources/Screens/Timeline/TimelineViewModel.swift
  ElementX/Sources/Screens/Timeline/View/Style/SwipeToReplyView.swift
  ElementX/Sources/Screens/Timeline/View/Style/TimelineItemBubbledStylerView.swift
  ElementX/Sources/Screens/Timeline/View/Style/TimelineStyler.swift
  ElementX/Sources/Screens/Timeline/View/Supplementary/TimelineItemStatusView.swift
  ElementX/Sources/Screens/Timeline/View/Supplementary/TimelineReactionsView.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/CollapsibleRoomTimelineView.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/ReadMarkerRoomTimelineView.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/SeparatorRoomTimelineView.swift
  ElementX/Sources/Services/Authentication/AuthenticationServiceProtocol.swift
  ElementX/Sources/Services/Room/RoomSummary/RoomEventStringBuilder.swift
  ElementX/Sources/Services/Room/RoomSummary/RoomSummaryProvider.swift
  ElementX/Sources/Services/SecureBackup/SecureBackupController.swift
  ElementX/Sources/Services/Timeline/Fixtures/RoomTimelineItemFixtures.swift
  ElementX/Sources/Services/Timeline/RoomTimelineProvider.swift
  ElementX/Sources/Services/Timeline/TimelineController/RoomTimelineController.swift
  ElementX/Sources/Services/Timeline/TimelineItemContent/CustomStringConvertible.swift
  ElementX/Sources/Services/Timeline/TimelineItemProxy.swift
  ElementX/Sources/Services/Timeline/TimelineItems/Items/Virtual/PaginationIndicatorRoomTimelineItem.swift
  ElementX/Sources/Services/Timeline/TimelineItems/Items/Virtual/TimelineStartRoomTimelineItem.swift
  ElementX/Sources/Services/Timeline/TimelineItems/RoomTimelineItemFactory.swift
  ElementX/Sources/Services/Timeline/TimelineItems/RoomTimelineItemViewState.swift
  ElementX/Sources/Services/Timeline/TimelineProxy.swift
  UITests/Sources/PollFormScreenUITests.swift
  UITests/Sources/UserSessionScreenTests.swift
  UnitTests/Sources/ComposerToolbarViewModelTests.swift
  UnitTests/Sources/LoggingTests.swift
  UnitTests/Sources/MessageForwardingScreenViewModelTests.swift
  UnitTests/Sources/RoomScreenViewModelTests.swift
  UnitTests/Sources/TimelineItemFactoryTests.swift
  UnitTests/Sources/TimelineViewModelTests.swift
  project.yml
Labels: pr-misc

#3360 use element-hq RTE version
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/SupportingFiles/Settings.bundle/Packages/matrix-rich-text-editor-swift.plist
  project.yml
Labels: pr-misc

#3366 Initial implementation of hiding media in the timeline.
  ElementX/Resources/Localizations/en.lproj/Localizable.strings
  ElementX/Sources/Application/AppSettings.swift
  ElementX/Sources/Generated/Strings.swift
  ElementX/Sources/Other/SwiftUI/Views/LoadableAvatarImage.swift
  ElementX/Sources/Other/SwiftUI/Views/LoadableImage.swift
  ElementX/Sources/Screens/RoomPollsHistoryScreen/View/RoomPollsHistoryScreen.swift
  ElementX/Sources/Screens/RoomScreen/View/RoomScreen.swift
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/DeveloperOptionsScreenModels.swift
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/View/DeveloperOptionsScreen.swift
  ElementX/Sources/Screens/Timeline/TimelineModels.swift
  ElementX/Sources/Screens/Timeline/TimelineTableViewController.swift
  ElementX/Sources/Screens/Timeline/TimelineViewModel.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/ImageRoomTimelineView.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/StickerRoomTimelineView.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/VideoRoomTimelineView.swift
  ElementX/Sources/Screens/Timeline/View/TimelineView.swift
  ElementX/Sources/Services/Timeline/Fixtures/RoomTimelineItemFixtures.swift
  NSE/Sources/NotificationContentBuilder.swift
  NSE/Sources/NotificationServiceExtension.swift
  PreviewTests/Sources/GeneratedPreviewTests.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_loadableImage-iPad-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_loadableImage-iPad-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_loadableImage-iPhone-16-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_loadableImage-iPhone-16-pseudo.1.png
Labels: pr-wip

#3374 Record a missing snapshot.
  UITests/Sources/__Snapshots__/Application/authenticationFlow-1-iPhone-16-en-GB.UI.png
Labels: pr-misc

#3375 Update the SDK and use media `filename` and `caption` internally.
  ElementX.xcodeproj/project.pbxproj
  ElementX/Sources/Mocks/ClientProxyMock.swift
  ElementX/Sources/Mocks/Generated/GeneratedMocks.swift
  ElementX/Sources/Mocks/Generated/SDKGeneratedMocks.swift
  ElementX/Sources/Mocks/MediaProviderMock.swift
  ElementX/Sources/Other/SwiftUI/Views/LoadableImage.swift
  ElementX/Sources/Screens/RoomScreen/ComposerToolbar/View/MessageComposer.swift
  ElementX/Sources/Screens/Timeline/TimelineInteractionHandler.swift
  ElementX/Sources/Screens/Timeline/View/Replies/TimelineReplyView.swift
  ElementX/Sources/Screens/Timeline/View/Style/TimelineItemBubbledStylerView.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/AudioRoomTimelineView.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/FileRoomTimelineView.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/ImageRoomTimelineView.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/VideoRoomTimelineView.swift
  ElementX/Sources/Services/Client/ClientProxy.swift
  ElementX/Sources/Services/Media/Provider/MediaLoader.swift
  ElementX/Sources/Services/Media/Provider/MediaLoaderProtocol.swift
  ElementX/Sources/Services/Media/Provider/MediaProvider.swift
  ElementX/Sources/Services/Media/Provider/MediaProviderProtocol.swift
  ElementX/Sources/Services/Timeline/Fixtures/RoomTimelineItemFixtures.swift
  ElementX/Sources/Services/Timeline/TimelineItems/Items/Messages/AudioRoomTimelineItem.swift
  ElementX/Sources/Services/Timeline/TimelineItems/Items/Messages/AudioRoomTimelineItemContent.swift
  ElementX/Sources/Services/Timeline/TimelineItems/Items/Messages/FileRoomTimelineItem.swift
  ElementX/Sources/Services/Timeline/TimelineItems/Items/Messages/FileRoomTimelineItemContent.swift
  ElementX/Sources/Services/Timeline/TimelineItems/Items/Messages/ImageRoomTimelineItem.swift
  ElementX/Sources/Services/Timeline/TimelineItems/Items/Messages/ImageRoomTimelineItemContent.swift
  ElementX/Sources/Services/Timeline/TimelineItems/Items/Messages/VideoRoomTimelineItem.swift
  ElementX/Sources/Services/Timeline/TimelineItems/Items/Messages/VideoRoomTimelineItemContent.swift
  ElementX/Sources/Services/Timeline/TimelineItems/Items/Messages/VoiceMessageRoomTimelineItem.swift
  ElementX/Sources/Services/Timeline/TimelineItems/Items/Messages/VoiceMessages/VoiceMessageRoomTimelineView.swift
  ElementX/Sources/Services/Timeline/TimelineItems/RoomTimelineItemFactory.swift
  ElementX/Sources/Services/VoiceMessage/VoiceMessageMediaManager.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_messageComposer-iPad-en-GB.Replying-in-thread.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_messageComposer-iPad-en-GB.Replying.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_messageComposer-iPad-pseudo.Replying-in-thread.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_messageComposer-iPad-pseudo.Replying.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_messageComposer-iPhone-16-en-GB.Replying-in-thread.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_messageComposer-iPhone-16-en-GB.Replying.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_messageComposer-iPhone-16-pseudo.Replying-in-thread.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_messageComposer-iPhone-16-pseudo.Replying.png
  UnitTests/Sources/LoggingTests.swift
  UnitTests/Sources/VoiceMessageMediaManagerTests.swift
Labels: pr-misc

#3376 Add new emoji from iOS 17.4 to the reaction picker.
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_emojiPickerScreen-iPad-en-GB.Screen.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_emojiPickerScreen-iPad-pseudo.Screen.png
  project.yml
Labels: pr-change

#3377 update sdk
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  project.yml
Labels: pr-misc

#3358 crypto: Configure decryption trustRequirement based on config flag
  ElementX/Sources/Other/Extensions/ClientBuilder.swift
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/View/DeveloperOptionsScreen.swift
Labels: pr-feature

#3386 Add a subtitle to the QR Code login instructions.
  ElementX/Resources/Localizations/en.lproj/Localizable.strings
  ElementX/Sources/Generated/Strings.swift
  ElementX/Sources/Screens/QRCodeLoginScreen/View/QRCodeLoginScreen.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_qRCodeLoginScreen-iPad-en-GB.Initial.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_qRCodeLoginScreen-iPad-pseudo.Initial.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_qRCodeLoginScreen-iPhone-16-en-GB.Initial.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_qRCodeLoginScreen-iPhone-16-pseudo.Initial.png
Labels: pr-change

#3389 Ask the iPad to reveal the keyboard in UI Tests when it's hidden.
  ElementX/Sources/Other/Extensions/XCUIElement.swift
  UITests/Sources/AppLockSetupUITests.swift
  UITests/Sources/AuthenticationFlowCoordinatorUITests.swift
  UITests/Sources/BugReportUITests.swift
  UITests/Sources/RoomMembersListScreenUITests.swift
  UITests/Sources/ServerSelectionUITests.swift
  UITests/Sources/StartChatScreenUITests.swift
Labels: pr-misc

#3391 Tweak the UI in the EncryptionReset, IdentityConfirmation and SecureBackupRecovery screens.
  ElementX/Resources/Localizations/en.lproj/Localizable.strings
  ElementX/Sources/Generated/Strings.swift
  ElementX/Sources/Screens/EncryptionReset/EncryptionResetScreen/View/EncryptionResetScreen.swift
  ElementX/Sources/Screens/Onboarding/IdentityConfirmationScreen/View/IdentityConfirmationScreen.swift
  ElementX/Sources/Screens/SecureBackup/SecureBackupRecoveryKeyScreen/View/SecureBackupRecoveryKeyScreen.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_encryptionResetScreen-iPad-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_encryptionResetScreen-iPad-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_encryptionResetScreen-iPhone-16-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_encryptionResetScreen-iPhone-16-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_identityConfirmationScreen-iPad-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_identityConfirmationScreen-iPad-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_identityConfirmationScreen-iPhone-16-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_identityConfirmationScreen-iPhone-16-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_secureBackupRecoveryKeyScreen-iPad-en-GB.Incomplete.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_secureBackupRecoveryKeyScreen-iPad-pseudo.Incomplete.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_secureBackupRecoveryKeyScreen-iPhone-16-en-GB.Incomplete.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_secureBackupRecoveryKeyScreen-iPhone-16-pseudo.Incomplete.png
Labels: pr-change

#3393 Update the secondary button stroke colour.
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/SupportingFiles/Settings.bundle/Acknowledgements.plist
  ElementX/SupportingFiles/Settings.bundle/Packages/compound-ios.plist
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_homeScreenInviteCell-iPad-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_homeScreenInviteCell-iPad-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_homeScreenInviteCell-iPhone-16-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_homeScreenInviteCell-iPhone-16-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_identityConfirmationScreen-iPad-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_identityConfirmationScreen-iPad-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_identityConfirmationScreen-iPhone-16-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_identityConfirmationScreen-iPhone-16-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_joinRoomScreen-iPad-en-GB.Invite.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_joinRoomScreen-iPad-pseudo.Invite.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_joinRoomScreen-iPhone-16-en-GB.Invite.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_joinRoomScreen-iPhone-16-pseudo.Invite.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_qRCodeLoginScreen-iPad-en-GB.Device-code.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_qRCodeLoginScreen-iPad-en-GB.Verification-code.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_qRCodeLoginScreen-iPad-pseudo.Device-code.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_qRCodeLoginScreen-iPad-pseudo.Verification-code.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_qRCodeLoginScreen-iPhone-16-en-GB.Device-code.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_qRCodeLoginScreen-iPhone-16-en-GB.Verification-code.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_qRCodeLoginScreen-iPhone-16-pseudo.Device-code.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_qRCodeLoginScreen-iPhone-16-pseudo.Verification-code.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_resolveVerifiedUserSendFailureScreen-iPad-en-GB.Identity-Changed.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_resolveVerifiedUserSendFailureScreen-iPad-en-GB.Own-Unsigned-Device.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_resolveVerifiedUserSendFailureScreen-iPad-en-GB.Unsigned-Device.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_resolveVerifiedUserSendFailureScreen-iPad-pseudo.Identity-Changed.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_resolveVerifiedUserSendFailureScreen-iPad-pseudo.Own-Unsigned-Device.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_resolveVerifiedUserSendFailureScreen-iPad-pseudo.Unsigned-Device.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_resolveVerifiedUserSendFailureScreen-iPhone-16-en-GB.Identity-Changed.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_resolveVerifiedUserSendFailureScreen-iPhone-16-en-GB.Own-Unsigned-Device.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_resolveVerifiedUserSendFailureScreen-iPhone-16-en-GB.Unsigned-Device.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_resolveVerifiedUserSendFailureScreen-iPhone-16-pseudo.Identity-Changed.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_resolveVerifiedUserSendFailureScreen-iPhone-16-pseudo.Own-Unsigned-Device.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_resolveVerifiedUserSendFailureScreen-iPhone-16-pseudo.Unsigned-Device.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomPollsHistoryScreen-iPad-en-GB.No-polls.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomPollsHistoryScreen-iPad-pseudo.No-polls.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomPollsHistoryScreen-iPhone-16-en-GB.No-polls.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomPollsHistoryScreen-iPhone-16-pseudo.No-polls.png
  UITests/Sources/__Snapshots__/Application/invites-1-iPad-10th-generation-en-GB.UI.png
  UITests/Sources/__Snapshots__/Application/invites-1-iPhone-16-en-GB.UI.png
  UITests/Sources/__Snapshots__/Application/invites-iPad-10th-generation-en-GB.UI.png
  UITests/Sources/__Snapshots__/Application/invites-iPhone-16-en-GB.UI.png
  project.yml
Labels: pr-change

#3394 Introduce a feature flag for the new identity pinning violation notifications feature
  ElementX/Sources/Application/AppSettings.swift
  ElementX/Sources/Screens/RoomScreen/RoomScreenViewModel.swift
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/DeveloperOptionsScreenModels.swift
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/View/DeveloperOptionsScreen.swift
Labels: pr-feature

#3392 Show the Login with QR Code button.
  ElementX/Sources/Screens/AuthenticationStartScreen/AuthenticationStartScreenViewModel.swift
Labels: pr-feature

#3395 Fix identity pinning link.
  ElementX/Sources/Application/AppSettings.swift
Labels: pr-bugfix

#3396 Update the version to 1.9.0.
  ElementX.xcodeproj/project.pbxproj
  project.yml
Labels: pr-build

#3397 Create Room with knock rule
  ElementX/Sources/Application/AppSettings.swift
  ElementX/Sources/Mocks/ClientProxyMock.swift
  ElementX/Sources/Mocks/Generated/GeneratedMocks.swift
  ElementX/Sources/Screens/CreateRoom/CreateRoomCoordinator.swift
  ElementX/Sources/Screens/CreateRoom/CreateRoomModels.swift
  ElementX/Sources/Screens/CreateRoom/CreateRoomViewModel.swift
  ElementX/Sources/Screens/CreateRoom/View/CreateRoomScreen.swift
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/DeveloperOptionsScreenModels.swift
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/View/DeveloperOptionsScreen.swift
  ElementX/Sources/Services/Client/ClientProxy.swift
  ElementX/Sources/Services/Client/ClientProxyProtocol.swift
  ElementX/Sources/Services/CreateRoom/CreateRoomFlowParameters.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_createRoom-iPad-en-GB.Create-Public-Room.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_createRoom-iPad-pseudo.Create-Public-Room.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_createRoom-iPhone-16-en-GB.Create-Public-Room.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_createRoom-iPhone-16-pseudo.Create-Public-Room.png
  UnitTests/Sources/CreateRoomViewModelTests.swift
Labels: pr-wip

#3407 Fix a bug opening images with a valid filename but a mimetype of `image/*` (sent by EXA).
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Sources/Mocks/EventTimelineItem.swift
  ElementX/Sources/Mocks/Generated/SDKGeneratedMocks.swift
  ElementX/Sources/Services/Client/ClientProxy.swift
  ElementX/Sources/Services/Media/Provider/MediaLoader.swift
  ElementX/Sources/Services/Timeline/TimelineItemProxy.swift
  project.yml
Labels: pr-bugfix

#3408 Allow video uploads to be optimised to reduce bandwidth.
  ElementX/Sources/Application/AppSettings.swift
  ElementX/Sources/FlowCoordinators/RoomFlowCoordinator.swift
  ElementX/Sources/FlowCoordinators/SettingsFlowCoordinator.swift
  ElementX/Sources/FlowCoordinators/UserSessionFlowCoordinator.swift
  ElementX/Sources/Screens/MediaUploadPreviewScreen/View/MediaUploadPreviewScreen.swift
  ElementX/Sources/Screens/RoomDetailsEditScreen/RoomDetailsEditScreenCoordinator.swift
  ElementX/Sources/Screens/RoomDetailsEditScreen/RoomDetailsEditScreenViewModel.swift
  ElementX/Sources/Screens/RoomDetailsEditScreen/View/RoomDetailsEditScreen.swift
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/DeveloperOptionsScreenModels.swift
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/View/DeveloperOptionsScreen.swift
  ElementX/Sources/Screens/Settings/UserDetailsEditScreen/UserDetailsEditScreenCoordinator.swift
  ElementX/Sources/Screens/Settings/UserDetailsEditScreen/UserDetailsEditScreenViewModel.swift
  ElementX/Sources/Screens/Settings/UserDetailsEditScreen/View/UserDetailsEditScreen.swift
  ElementX/Sources/Screens/StartChatScreen/StartChatScreenCoordinator.swift
  ElementX/Sources/Services/Media/MediaUploadingPreprocessor.swift
  ElementX/Sources/UITests/UITestsAppCoordinator.swift
  UnitTests/Sources/MediaUploadingPreprocessorTests.swift
  UnitTests/Sources/RoomDetailsEditScreenViewModelTests.swift
Labels: pr-wip

#3416 Fix some warnings.
  ElementX/Sources/FlowCoordinators/AuthenticationFlowCoordinator.swift
  ElementX/Sources/Other/Extensions/Dictionary.swift
  ElementX/Sources/Screens/CallScreen/CallScreenViewModel.swift
  ElementX/Sources/Screens/CreateRoom/CreateRoomViewModel.swift
  ElementX/Sources/Services/BugReport/BugReportService.swift
  ElementX/Sources/Services/Client/ClientProxy.swift
  ElementX/Sources/Services/Client/ClientProxyProtocol.swift
  ElementX/Sources/Services/ElementCall/ElementCallService.swift
  ElementX/Sources/Services/Timeline/TimelineItemProxy.swift
  ElementX/Sources/UITests/UITestsSignalling.swift
Labels: pr-misc

#3414 Only subscribe to identity updates if the room is encrypted.
  ElementX/Sources/Services/Room/JoinedRoomProxy.swift
Labels: pr-bugfix

#3418 Refactor the`TimelineItemIdentifier` handling
  ElementX.xcodeproj/project.pbxproj
  ElementX/Sources/Application/AppCoordinator.swift
  ElementX/Sources/Mocks/Generated/GeneratedMocks.swift
  ElementX/Sources/Mocks/PollMock.swift
  ElementX/Sources/Screens/MessageForwardingScreen/View/MessageForwardingScreen.swift
  ElementX/Sources/Screens/ResolveVerifiedUserSendFailureScreen/View/ResolveVerifiedUserSendFailureScreen.swift
  ElementX/Sources/Screens/RoomScreen/ComposerToolbar/ComposerToolbarModels.swift
  ElementX/Sources/Screens/RoomScreen/ComposerToolbar/ComposerToolbarViewModel.swift
  ElementX/Sources/Screens/RoomScreen/ComposerToolbar/View/ComposerToolbar.swift
  ElementX/Sources/Screens/RoomScreen/ComposerToolbar/View/MessageComposer.swift
  ElementX/Sources/Screens/Timeline/TimelineInteractionHandler.swift
  ElementX/Sources/Screens/Timeline/TimelineViewModel.swift
  ElementX/Sources/Screens/Timeline/View/Style/SwipeToReplyView.swift
  ElementX/Sources/Screens/Timeline/View/Style/TimelineItemBubbledStylerView.swift
  ElementX/Sources/Screens/Timeline/View/Style/TimelineItemSendInfoLabel.swift
  ElementX/Sources/Screens/Timeline/View/Style/TimelineStyler.swift
  ElementX/Sources/Screens/Timeline/View/Supplementary/TimelineReactionsView.swift
  ElementX/Sources/Screens/Timeline/View/Supplementary/TimelineReadReceiptsView.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/AudioRoomTimelineView.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/CallInviteRoomTimelineView.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/CallNotificationRoomTimelineView.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/CollapsibleRoomTimelineView.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/EmoteRoomTimelineView.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/EncryptedRoomTimelineView.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/FileRoomTimelineView.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/ImageRoomTimelineView.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/LocationRoomTimelineView.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/NoticeRoomTimelineView.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/ReadMarkerRoomTimelineView.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/RedactedRoomTimelineView.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/SeparatorRoomTimelineView.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/StateRoomTimelineView.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/StickerRoomTimelineView.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/TextRoomTimelineView.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/UnsupportedRoomTimelineView.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/VideoRoomTimelineView.swift
  ElementX/Sources/Services/Timeline/Fixtures/RoomTimelineItemFixtures.swift
  ElementX/Sources/Services/Timeline/TimelineController/MockRoomTimelineController.swift
  ElementX/Sources/Services/Timeline/TimelineController/RoomTimelineController.swift
  ElementX/Sources/Services/Timeline/TimelineController/RoomTimelineControllerProtocol.swift
  ElementX/Sources/Services/Timeline/TimelineItemIdentifier.swift
  ElementX/Sources/Services/Timeline/TimelineItemProxy.swift
  ElementX/Sources/Services/Timeline/TimelineItems/Items/Messages/VoiceMessages/VoiceMessageRoomPlaybackView.swift
  ElementX/Sources/Services/Timeline/TimelineItems/Items/Messages/VoiceMessages/VoiceMessageRoomTimelineView.swift
  ElementX/Sources/Services/Timeline/TimelineItems/Items/Virtual/PaginationIndicatorRoomTimelineItem.swift
  ElementX/Sources/Services/Timeline/TimelineItems/Items/Virtual/TimelineStartRoomTimelineItem.swift
  ElementX/Sources/Services/Timeline/TimelineProxy.swift
  ElementX/Sources/Services/Timeline/TimelineProxyProtocol.swift
  UnitTests/Sources/AudioPlayerStateTests.swift
  UnitTests/Sources/ComposerToolbarViewModelTests.swift
  UnitTests/Sources/LoggingTests.swift
  UnitTests/Sources/MediaPlayerProviderTests.swift
  UnitTests/Sources/MessageForwardingScreenViewModelTests.swift
  UnitTests/Sources/ResolveVerifiedUserSendFailureScreenViewModelTests.swift
  UnitTests/Sources/TextBasedRoomTimelineTests.swift
  UnitTests/Sources/TimelineViewModelTests.swift
Labels: pr-misc

#3412 Allow image uploads to be optimised to reduce bandwidth.
  ElementX.xcodeproj/project.pbxproj
  ElementX/Sources/Services/Media/MediaUploadingPreprocessor.swift
  UnitTests/Resources/Media/test_animated_image.gif
  UnitTests/Resources/Media/test_apple_image.heic
  UnitTests/Sources/MediaUploadingPreprocessorTests.swift
Labels: pr-wip

#3415 Fix the pinned identity banner to always show the user ID regardless of ambiguity.
  ElementX/Resources/Localizations/en.lproj/Localizable.strings
  ElementX/Sources/Generated/Strings.swift
  ElementX/Sources/Screens/RoomScreen/View/RoomScreenFooterView.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomScreenFooterView-iPad-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomScreenFooterView-iPad-en-GB.With-displayname.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomScreenFooterView-iPad-en-GB.Without-displayname.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomScreenFooterView-iPad-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomScreenFooterView-iPad-pseudo.With-displayname.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomScreenFooterView-iPad-pseudo.Without-displayname.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomScreenFooterView-iPhone-16-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomScreenFooterView-iPhone-16-en-GB.With-displayname.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomScreenFooterView-iPhone-16-en-GB.Without-displayname.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomScreenFooterView-iPhone-16-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomScreenFooterView-iPhone-16-pseudo.With-displayname.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomScreenFooterView-iPhone-16-pseudo.Without-displayname.png
Labels: pr-bugfix

#3423 Adopt various rust side Timeline API additions
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Sources/FlowCoordinators/RoomFlowCoordinator.swift
  ElementX/Sources/Mocks/Generated/GeneratedMocks.swift
  ElementX/Sources/Mocks/Generated/SDKGeneratedMocks.swift
  ElementX/Sources/Mocks/RoomTimelineProviderMock.swift
  ElementX/Sources/Mocks/SDK/ClientSDKMock.swift
  ElementX/Sources/Screens/Timeline/TimelineInteractionHandler.swift
  ElementX/Sources/Screens/Timeline/TimelineModels.swift
  ElementX/Sources/Screens/Timeline/TimelineTableViewController.swift
  ElementX/Sources/Screens/Timeline/TimelineViewModel.swift
  ElementX/Sources/Screens/Timeline/View/Style/TimelineItemBubbledStylerView.swift
  ElementX/Sources/Screens/Timeline/View/Style/TimelineStyler.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/CollapsibleRoomTimelineView.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/ReadMarkerRoomTimelineView.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/SeparatorRoomTimelineView.swift
  ElementX/Sources/Services/Authentication/AuthenticationService.swift
  ElementX/Sources/Services/Room/RoomSummary/RoomSummaryProvider.swift
  ElementX/Sources/Services/Timeline/Fixtures/RoomTimelineItemFixtures.swift
  ElementX/Sources/Services/Timeline/TimelineController/MockRoomTimelineController.swift
  ElementX/Sources/Services/Timeline/TimelineController/RoomTimelineController.swift
  ElementX/Sources/Services/Timeline/TimelineController/RoomTimelineControllerProtocol.swift
  ElementX/Sources/Services/Timeline/TimelineItemIdentifier.swift
  ElementX/Sources/Services/Timeline/TimelineItemProxy.swift
  ElementX/Sources/Services/Timeline/TimelineItems/Items/Virtual/PaginationIndicatorRoomTimelineItem.swift
  ElementX/Sources/Services/Timeline/TimelineItems/Items/Virtual/TimelineStartRoomTimelineItem.swift
  ElementX/Sources/Services/Timeline/TimelineItems/RoomTimelineItemViewState.swift
  ElementX/Sources/Services/Timeline/TimelineProxy.swift
  ElementX/Sources/Services/Timeline/TimelineProxyProtocol.swift
  UnitTests/Sources/LoggingTests.swift
  UnitTests/Sources/MessageForwardingScreenViewModelTests.swift
  UnitTests/Sources/RoomScreenViewModelTests.swift
  UnitTests/Sources/TimelineItemFactoryTests.swift
  UnitTests/Sources/TimelineViewModelTests.swift
  project.yml
Labels: pr-api

#3424 Knock and knocked state for the join room screen
  ElementX.xcodeproj/project.pbxproj
  ElementX/Resources/Localizations/en.lproj/Localizable.strings
  ElementX/Sources/FlowCoordinators/RoomFlowCoordinator.swift
  ElementX/Sources/Generated/Strings.swift
  ElementX/Sources/Mocks/Generated/GeneratedMocks.swift
  ElementX/Sources/Mocks/KnockedRoomProxyMock.swift
  ElementX/Sources/Other/Extensions/String.swift
  ElementX/Sources/Screens/JoinRoomScreen/JoinRoomScreenCoordinator.swift
  ElementX/Sources/Screens/JoinRoomScreen/JoinRoomScreenModels.swift
  ElementX/Sources/Screens/JoinRoomScreen/JoinRoomScreenViewModel.swift
  ElementX/Sources/Screens/JoinRoomScreen/View/JoinRoomScreen.swift
  ElementX/Sources/Services/Client/ClientProxy.swift
  ElementX/Sources/Services/Client/ClientProxyProtocol.swift
  ElementX/Sources/Services/Room/KnockedRoomProxy.swift
  ElementX/Sources/Services/Room/RoomProxyProtocol.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_joinRoomScreen-iPad-en-GB.Knock.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_joinRoomScreen-iPad-en-GB.Knocked.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_joinRoomScreen-iPad-pseudo.Knock.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_joinRoomScreen-iPad-pseudo.Knocked.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_joinRoomScreen-iPhone-16-en-GB.Knock.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_joinRoomScreen-iPhone-16-en-GB.Knocked.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_joinRoomScreen-iPhone-16-pseudo.Knock.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_joinRoomScreen-iPhone-16-pseudo.Knocked.png
  UnitTests/Sources/JoinRoomScreenViewModelTests.swift
Labels: pr-wip

#3435 Fix a bug where uploaded images could have the wrong aspect ratio in the timeline.
  ElementX.xcodeproj/project.pbxproj
  ElementX/Sources/Services/Media/MediaUploadingPreprocessor.swift
  UnitTests/Resources/Media/test_rotated_image.jpg
  UnitTests/Sources/MediaUploadingPreprocessorTests.swift
Labels: pr-bugfix

#3429 Add support for rendering media captions in the timeline.
  ElementX/Sources/Screens/Timeline/View/Style/TimelineItemBubbledStylerView.swift
  ElementX/Sources/Screens/Timeline/View/Style/TimelineItemSendInfoLabel.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/ImageRoomTimelineView.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/VideoRoomTimelineView.swift
  ElementX/Sources/Services/Timeline/TimelineItems/EventBasedMessageTimelineItemProtocol.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_imageRoomTimelineView-iPad-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_imageRoomTimelineView-iPad-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_imageRoomTimelineView-iPhone-16-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_imageRoomTimelineView-iPhone-16-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_videoRoomTimelineView-iPad-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_videoRoomTimelineView-iPad-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_videoRoomTimelineView-iPhone-16-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_videoRoomTimelineView-iPhone-16-pseudo.1.png
Labels: pr-change

#3427 Show a verification badge on the Room Member/User Profile screens.
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Sources/Mocks/ClientProxyMock.swift
  ElementX/Sources/Mocks/Generated/GeneratedMocks.swift
  ElementX/Sources/Mocks/Generated/SDKGeneratedMocks.swift
  ElementX/Sources/Mocks/SDK/UserIdentitySDKMock.swift
  ElementX/Sources/Other/SwiftUI/Views/AvatarHeaderView.swift
  ElementX/Sources/Screens/RoomMemberDetailsScreen/RoomMemberDetailsScreenModels.swift
  ElementX/Sources/Screens/RoomMemberDetailsScreen/RoomMemberDetailsScreenViewModel.swift
  ElementX/Sources/Screens/RoomMemberDetailsScreen/View/RoomMemberDetailsScreen.swift
  ElementX/Sources/Screens/RoomScreen/ComposerToolbar/ComposerToolbarModels.swift
  ElementX/Sources/Screens/RoomScreen/ComposerToolbar/ComposerToolbarViewModel.swift
  ElementX/Sources/Screens/RoomScreen/ComposerToolbar/View/MessageComposer.swift
  ElementX/Sources/Screens/Timeline/TimelineInteractionHandler.swift
  ElementX/Sources/Screens/Timeline/TimelineViewModel.swift
  ElementX/Sources/Screens/UserProfileScreen/UserProfileScreenModels.swift
  ElementX/Sources/Screens/UserProfileScreen/UserProfileScreenViewModel.swift
  ElementX/Sources/Screens/UserProfileScreen/View/UserProfileScreen.swift
  ElementX/Sources/Services/Client/ClientProxy.swift
  ElementX/Sources/Services/Client/ClientProxyProtocol.swift
  ElementX/Sources/Services/Timeline/TimelineController/MockRoomTimelineController.swift
  ElementX/Sources/Services/Timeline/TimelineController/RoomTimelineController.swift
  ElementX/Sources/Services/Timeline/TimelineController/RoomTimelineControllerProtocol.swift
  ElementX/Sources/Services/Timeline/TimelineProxy.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_avatarHeaderView-iPad-en-GB.Members.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_avatarHeaderView-iPad-pseudo.Members.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_avatarHeaderView-iPhone-16-en-GB.Members.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_avatarHeaderView-iPhone-16-pseudo.Members.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomMemberDetailsScreen-iPad-en-GB.Ignored-User.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomMemberDetailsScreen-iPad-en-GB.Other-User.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomMemberDetailsScreen-iPad-en-GB.Verified-User.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomMemberDetailsScreen-iPad-pseudo.Ignored-User.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomMemberDetailsScreen-iPad-pseudo.Other-User.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomMemberDetailsScreen-iPad-pseudo.Verified-User.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomMemberDetailsScreen-iPhone-16-en-GB.Ignored-User.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomMemberDetailsScreen-iPhone-16-en-GB.Other-User.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomMemberDetailsScreen-iPhone-16-en-GB.Verified-User.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomMemberDetailsScreen-iPhone-16-pseudo.Ignored-User.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomMemberDetailsScreen-iPhone-16-pseudo.Other-User.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomMemberDetailsScreen-iPhone-16-pseudo.Verified-User.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_userProfileScreen-iPad-en-GB.Other-User.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_userProfileScreen-iPad-en-GB.Verified-User.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_userProfileScreen-iPad-pseudo.Other-User.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_userProfileScreen-iPad-pseudo.Verified-User.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_userProfileScreen-iPhone-16-en-GB.Other-User.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_userProfileScreen-iPhone-16-en-GB.Verified-User.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_userProfileScreen-iPhone-16-pseudo.Other-User.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_userProfileScreen-iPhone-16-pseudo.Verified-User.png
  UnitTests/Sources/ComposerToolbarViewModelTests.swift
  project.yml
Labels: pr-change

#3437 Adopt various Rust side API changes
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Sources/Mocks/Generated/SDKGeneratedMocks.swift
  ElementX/Sources/Services/Client/ClientProxy.swift
  ElementX/Sources/Services/Client/ClientProxyProtocol.swift
  ElementX/Sources/Services/Room/JoinedRoomProxy.swift
  ElementX/Sources/Services/Room/RoomSummary/RoomSummaryProvider.swift
  ElementX/Sources/Services/Timeline/TimelineProxy.swift
  project.yml
Labels: pr-misc

#3440 Update compound to change checkmark color
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_createRoom-iPad-en-GB.Create-Public-Room.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_createRoom-iPad-en-GB.Create-Room-without-users.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_createRoom-iPad-en-GB.Create-Room.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_createRoom-iPad-pseudo.Create-Public-Room.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_createRoom-iPad-pseudo.Create-Room-without-users.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_createRoom-iPad-pseudo.Create-Room.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_createRoom-iPhone-16-en-GB.Create-Public-Room.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_createRoom-iPhone-16-en-GB.Create-Room-without-users.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_createRoom-iPhone-16-en-GB.Create-Room.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_createRoom-iPhone-16-pseudo.Create-Public-Room.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_createRoom-iPhone-16-pseudo.Create-Room-without-users.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_createRoom-iPhone-16-pseudo.Create-Room.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomChangePermissionsScreen-iPad-en-GB.Member-moderation.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomChangePermissionsScreen-iPad-en-GB.Messages-and-Content.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomChangePermissionsScreen-iPad-en-GB.Room-details.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomChangePermissionsScreen-iPad-pseudo.Member-moderation.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomChangePermissionsScreen-iPad-pseudo.Messages-and-Content.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomChangePermissionsScreen-iPad-pseudo.Room-details.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomChangePermissionsScreen-iPhone-16-en-GB.Member-moderation.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomChangePermissionsScreen-iPhone-16-en-GB.Messages-and-Content.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomChangePermissionsScreen-iPhone-16-en-GB.Room-details.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomChangePermissionsScreen-iPhone-16-pseudo.Member-moderation.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomChangePermissionsScreen-iPhone-16-pseudo.Messages-and-Content.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomChangePermissionsScreen-iPhone-16-pseudo.Room-details.png
  project.yml
Labels: pr-change

#3441 Fix a bug where the pinned items banner could overlay the composer.
  ElementX/Sources/Screens/RoomScreen/View/RoomScreen.swift
Labels: pr-bugfix

#3444 Fix composer mention pills showing up as file icons on first use on iOS 18
  ElementX/Sources/Screens/RoomScreen/ComposerToolbar/View/MessageComposerTextField.swift
Labels: pr-bugfix

#3442 Fix a bug where the room state wouldn't indicate when a call was in progress.
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Resources/Localizations/en.lproj/Localizable.strings
  ElementX/Sources/FlowCoordinators/UserSessionFlowCoordinator.swift
  ElementX/Sources/Generated/Strings.swift
  ElementX/Sources/Mocks/Generated/GeneratedMocks.swift
  ElementX/Sources/Mocks/Generated/SDKGeneratedMocks.swift
  ElementX/Sources/Screens/JoinRoomScreen/JoinRoomScreenViewModel.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/EncryptedRoomTimelineView.swift
  ElementX/Sources/Services/Client/ClientProxy.swift
  ElementX/Sources/Services/Client/ClientProxyProtocol.swift
  ElementX/Sources/Services/Room/RoomSummary/RoomEventStringBuilder.swift
  ElementX/Sources/Services/Timeline/TimelineItemProxy.swift
  ElementX/Sources/Services/Timeline/TimelineItems/Items/Other/EncryptedRoomTimelineItem.swift
  ElementX/Sources/Services/Timeline/TimelineItems/RoomTimelineItemFactory.swift
  project.yml
Labels: pr-bugfix

#3443 remove iOS 16 support
  ElementX.xcodeproj/project.pbxproj
  ElementX/Sources/Application/AppCoordinator.swift
  ElementX/Sources/Application/Navigation/NavigationCoordinators.swift
  ElementX/Sources/Other/Pills/PillView.swift
  ElementX/Sources/Other/SwiftUI/Search.swift
  ElementX/Sources/Screens/AppLock/AppLockScreen/View/AppLockScreen.swift
  ElementX/Sources/Screens/AppLock/AppLockSetupPINScreen/View/PINTextField.swift
  ElementX/Sources/Screens/AppLock/AppLockSetupSettingsScreen/View/AppLockSetupSettingsScreen.swift
  ElementX/Sources/Screens/Authentication/LoginScreen/View/LoginScreen.swift
  ElementX/Sources/Screens/Authentication/ServerSelectionScreen/View/ServerSelectionScreen.swift
  ElementX/Sources/Screens/BugReportScreen/View/BugReportScreen.swift
  ElementX/Sources/Screens/CreatePollScreen/View/PollFormScreen.swift
  ElementX/Sources/Screens/EmojiPickerScreen/View/EmojiPickerScreen.swift
  ElementX/Sources/Screens/GlobalSearchScreen/View/GlobalSearchScreen.swift
  ElementX/Sources/Screens/HomeScreen/View/HomeScreenContent.swift
  ElementX/Sources/Screens/InviteUsersScreen/View/InviteUsersScreen.swift
  ElementX/Sources/Screens/JoinRoomScreen/View/JoinRoomScreen.swift
  ElementX/Sources/Screens/Onboarding/IdentityConfirmationScreen/View/IdentityConfirmationScreen.swift
  ElementX/Sources/Screens/RoomChangeRolesScreen/View/RoomChangeRolesScreen.swift
  ElementX/Sources/Screens/RoomDetailsScreen/View/RoomDetailsScreen.swift
  ElementX/Sources/Screens/RoomNotificationSettingsScreen/View/RoomNotificationSettingsScreen.swift
  ElementX/Sources/Screens/RoomPollsHistoryScreen/View/RoomPollsHistoryScreen.swift
  ElementX/Sources/Screens/RoomScreen/ComposerToolbar/View/ComposerToolbar.swift
  ElementX/Sources/Screens/RoomScreen/ComposerToolbar/View/VoiceMessagePreviewComposer.swift
  ElementX/Sources/Screens/RoomScreen/View/SwipeRightAction.swift
  ElementX/Sources/Screens/SecureBackup/SecureBackupRecoveryKeyScreen/View/SecureBackupRecoveryKeyScreen.swift
  ElementX/Sources/Screens/Settings/AnalyticsSettingsScreen/View/AnalyticsSettingsScreen.swift
  ElementX/Sources/Screens/Settings/NotificationSettingsScreen/View/NotificationSettingsScreen.swift
  ElementX/Sources/Screens/Timeline/View/Style/TimelineItemBubbledStylerView.swift
  ElementX/Sources/Screens/Timeline/View/Style/TimelineStyler.swift
  ElementX/Sources/Screens/Timeline/View/Supplementary/ReactionsSummaryView.swift
  ElementX/Sources/Screens/Timeline/View/TypingIndicatorView.swift
  ElementX/Sources/Services/Timeline/TimelineItems/Items/Messages/VoiceMessages/VoiceMessageRoomPlaybackView.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemBubbledStylerView-iPad-en-GB.Encryption-Indicators.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemBubbledStylerView-iPad-en-GB.Mock-Timeline-RTL.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemBubbledStylerView-iPad-en-GB.Mock-Timeline.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemBubbledStylerView-iPad-en-GB.Replies.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemBubbledStylerView-iPad-pseudo.Encryption-Indicators.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemBubbledStylerView-iPad-pseudo.Mock-Timeline-RTL.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemBubbledStylerView-iPad-pseudo.Mock-Timeline.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemBubbledStylerView-iPad-pseudo.Replies.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemBubbledStylerView-iPhone-16-en-GB.Encryption-Indicators.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemBubbledStylerView-iPhone-16-en-GB.Mock-Timeline-RTL.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemBubbledStylerView-iPhone-16-en-GB.Mock-Timeline.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemBubbledStylerView-iPhone-16-en-GB.Replies.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemBubbledStylerView-iPhone-16-pseudo.Encryption-Indicators.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemBubbledStylerView-iPhone-16-pseudo.Mock-Timeline-RTL.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemBubbledStylerView-iPhone-16-pseudo.Mock-Timeline.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemBubbledStylerView-iPhone-16-pseudo.Replies.png
  Tools/Scripts/Templates/SimpleScreenExample/ElementX/View/TemplateScreen.swift
  project.yml
Labels: pr-misc

#3451 min macos support
  ElementX.xcodeproj/project.pbxproj
  project.yml
Labels: pr-build

#3453 Hook reaction pickers into the system's recently used keyboard emojis
  ElementX.xcodeproj/project.pbxproj
  ElementX/Resources/Localizations/en.lproj/Localizable.strings
  ElementX/Sources/Application/AppSettings.swift
  ElementX/Sources/FlowCoordinators/PinnedEventsTimelineFlowCoordinator.swift
  ElementX/Sources/FlowCoordinators/RoomFlowCoordinator.swift
  ElementX/Sources/FlowCoordinators/UserSessionFlowCoordinator.swift
  ElementX/Sources/Generated/Strings.swift
  ElementX/Sources/Screens/EmojiPickerScreen/EmojiPickerScreenModels.swift
  ElementX/Sources/Screens/EmojiPickerScreen/EmojiPickerScreenViewModel.swift
  ElementX/Sources/Screens/EmojiPickerScreen/View/EmojiPickerScreen.swift
  ElementX/Sources/Screens/PinnedEventsTimelineScreen/PinnedEventsTimelineScreenCoordinator.swift
  ElementX/Sources/Screens/PinnedEventsTimelineScreen/View/PinnedEventsTimelineScreen.swift
  ElementX/Sources/Screens/RoomScreen/RoomScreenCoordinator.swift
  ElementX/Sources/Screens/RoomScreen/View/RoomScreen.swift
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/DeveloperOptionsScreenModels.swift
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/View/DeveloperOptionsScreen.swift
  ElementX/Sources/Screens/Timeline/TimelineModels.swift
  ElementX/Sources/Screens/Timeline/TimelineViewModel.swift
  ElementX/Sources/Screens/Timeline/View/ItemMenu/TimelineItemMenu.swift
  ElementX/Sources/Screens/Timeline/View/ItemMenu/TimelineItemMenuAction.swift
  ElementX/Sources/Screens/Timeline/View/ItemMenu/TimelineItemMenuActionProvider.swift
  ElementX/Sources/Screens/Timeline/View/ReadReceipts/ReadReceiptsSummaryView.swift
  ElementX/Sources/Screens/Timeline/View/Style/TimelineItemBubbledStylerView.swift
  ElementX/Sources/Screens/Timeline/View/Supplementary/TimelineReadReceiptsView.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/HighlightedTimelineItemModifier.swift
  ElementX/Sources/Screens/Timeline/View/TimelineView.swift
  ElementX/Sources/Services/Emojis/EmojiCategory.swift
  ElementX/Sources/Services/Emojis/EmojiItem.swift
  ElementX/Sources/Services/Emojis/EmojiProvider.swift
  ElementX/Sources/Services/Emojis/EmojiProviderProtocol.swift
  ElementX/Sources/UITests/UITestsAppCoordinator.swift
  UnitTests/Sources/EmojiProviderTests.swift
  UnitTests/Sources/PillContextTests.swift
  UnitTests/Sources/RoomFlowCoordinatorTests.swift
  UnitTests/Sources/TimelineViewModelTests.swift
Labels: pr-feature

#3455 Fix the order of the frequently used emojis when showing them in the full reaction picker
  ElementX/Sources/Services/Emojis/EmojiProvider.swift
Labels: pr-bugfix

#3458 Revert "min macos support"
  ElementX.xcodeproj/project.pbxproj
  project.yml
Labels: pr-build

#3457 Enable identity pinning violation notifications unconditionally
  ElementX/Sources/Application/AppSettings.swift
  ElementX/Sources/Screens/RoomScreen/RoomScreenViewModel.swift
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/DeveloperOptionsScreenModels.swift
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/View/DeveloperOptionsScreen.swift
Labels: pr-change

#3462 Switch optimised video uploads to use 720p
  ElementX/Sources/Services/Media/MediaUploadingPreprocessor.swift
  UnitTests/Sources/MediaUploadingPreprocessorTests.swift
Labels: pr-wip

#3464 Tweak the flow for disabling key storage.
  ElementX.xcodeproj/project.pbxproj
  ElementX/Sources/Other/SwiftUI/Views/VisualListItem.swift
  ElementX/Sources/Screens/EncryptionReset/EncryptionResetScreen/View/EncryptionResetScreen.swift
  ElementX/Sources/Screens/Onboarding/AnalyticsPromptScreen/View/AnalyticsPromptScreen.swift
  ElementX/Sources/Screens/SecureBackup/SecureBackupKeyBackupScreen/View/SecureBackupKeyBackupScreen.swift
  ElementX/Sources/Screens/SecureBackup/SecureBackupScreen/SecureBackupScreenModels.swift
  ElementX/Sources/Screens/SecureBackup/SecureBackupScreen/SecureBackupScreenViewModel.swift
  ElementX/Sources/Screens/SecureBackup/SecureBackupScreen/View/SecureBackupScreen.swift
  PreviewTests/Sources/GeneratedPreviewTests.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_analyticsPromptScreen-iPad-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_analyticsPromptScreen-iPad-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_analyticsPromptScreen-iPhone-16-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_analyticsPromptScreen-iPhone-16-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_analyticsPromptScreenCheckmarkItem-iPad-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_analyticsPromptScreenCheckmarkItem-iPad-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_analyticsPromptScreenCheckmarkItem-iPhone-16-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_analyticsPromptScreenCheckmarkItem-iPhone-16-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_encryptionResetScreen-iPad-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_encryptionResetScreen-iPad-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_encryptionResetScreen-iPhone-16-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_encryptionResetScreen-iPhone-16-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_secureBackupKeyBackupScreen-iPad-en-GB.Set-up.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_secureBackupKeyBackupScreen-iPad-pseudo.Set-up.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_secureBackupKeyBackupScreen-iPhone-16-en-GB.Set-up.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_secureBackupKeyBackupScreen-iPhone-16-pseudo.Set-up.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_secureBackupScreen-iPad-en-GB.Key-backup-disabled.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_secureBackupScreen-iPad-pseudo.Key-backup-disabled.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_secureBackupScreen-iPhone-16-en-GB.Key-backup-disabled.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_secureBackupScreen-iPhone-16-pseudo.Key-backup-disabled.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_visualListItem-iPad-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_visualListItem-iPad-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_visualListItem-iPhone-16-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_visualListItem-iPhone-16-pseudo.1.png
Labels: pr-change

#3466 Update verify identity button title.
  ElementX/Resources/Localizations/en.lproj/Localizable.strings
  ElementX/Sources/Generated/Strings.swift
  ElementX/Sources/Screens/RoomMemberDetailsScreen/RoomMemberDetailsScreenModels.swift
  ElementX/Sources/Screens/RoomMemberDetailsScreen/View/RoomMemberDetailsScreen.swift
  ElementX/Sources/Screens/UserProfileScreen/UserProfileScreenModels.swift
  ElementX/Sources/Screens/UserProfileScreen/View/UserProfileScreen.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomMemberDetailsScreen-iPad-en-GB.Ignored-User.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomMemberDetailsScreen-iPad-en-GB.Other-User.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomMemberDetailsScreen-iPad-pseudo.Ignored-User.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomMemberDetailsScreen-iPad-pseudo.Other-User.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomMemberDetailsScreen-iPhone-16-en-GB.Ignored-User.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomMemberDetailsScreen-iPhone-16-en-GB.Other-User.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomMemberDetailsScreen-iPhone-16-pseudo.Ignored-User.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomMemberDetailsScreen-iPhone-16-pseudo.Other-User.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_userProfileScreen-iPad-en-GB.Other-User.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_userProfileScreen-iPad-pseudo.Other-User.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_userProfileScreen-iPhone-16-en-GB.Other-User.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_userProfileScreen-iPhone-16-pseudo.Other-User.png
Labels: pr-misc

#3468 Update the strings for out of sync Key Storage.
  ElementX/Resources/Localizations/en.lproj/Localizable.strings
  ElementX/Sources/Generated/Strings.swift
  ElementX/Sources/Screens/HomeScreen/View/HomeScreenRecoveryKeyConfirmationBanner.swift
  ElementX/Sources/Screens/SecureBackup/SecureBackupRecoveryKeyScreen/SecureBackupRecoveryKeyScreenViewModel.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_homeScreenRecoveryKeyConfirmationBanner-iPad-en-GB.Out-of-sync.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_homeScreenRecoveryKeyConfirmationBanner-iPad-en-GB.Set-up-recovery.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_homeScreenRecoveryKeyConfirmationBanner-iPad-pseudo.Out-of-sync.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_homeScreenRecoveryKeyConfirmationBanner-iPad-pseudo.Set-up-recovery.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_homeScreenRecoveryKeyConfirmationBanner-iPhone-16-en-GB.Out-of-sync.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_homeScreenRecoveryKeyConfirmationBanner-iPhone-16-en-GB.Set-up-recovery.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_homeScreenRecoveryKeyConfirmationBanner-iPhone-16-pseudo.Out-of-sync.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_homeScreenRecoveryKeyConfirmationBanner-iPhone-16-pseudo.Set-up-recovery.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_secureBackupScreen-iPad-en-GB.Recovery-incomplete.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_secureBackupScreen-iPad-pseudo.Recovery-incomplete.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_secureBackupScreen-iPhone-16-en-GB.Recovery-incomplete.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_secureBackupScreen-iPhone-16-pseudo.Recovery-incomplete.png
Labels: pr-misc

#3467 Enable the Optimised Media Uploads feature.
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Resources/Localizations/en.lproj/Localizable.strings
  ElementX/Sources/Application/AppSettings.swift
  ElementX/Sources/FlowCoordinators/SettingsFlowCoordinator.swift
  ElementX/Sources/FlowCoordinators/UserSessionFlowCoordinator.swift
  ElementX/Sources/Generated/Strings.swift
  ElementX/Sources/Screens/Settings/AvancedOptionsScreen/AdvancedSettingsScreenCoordinator.swift
  ElementX/Sources/Screens/Settings/AvancedOptionsScreen/AdvancedSettingsScreenModels.swift
  ElementX/Sources/Screens/Settings/AvancedOptionsScreen/AdvancedSettingsScreenViewModel.swift
  ElementX/Sources/Screens/Settings/AvancedOptionsScreen/View/AdvancedSettingsScreen.swift
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/DeveloperOptionsScreenModels.swift
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/View/DeveloperOptionsScreen.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_advancedSettingsScreen-iPad-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_advancedSettingsScreen-iPad-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_advancedSettingsScreen-iPhone-16-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_advancedSettingsScreen-iPhone-16-pseudo.1.png
  UnitTests/Sources/MediaUploadingPreprocessorTests.swift
  project.yml
Labels: pr-feature
