Repository element-hq/element-x-ios, pull requests merged in 2024-09, with the labels that each got.

#3219 Accept current autocorrection/suggestion before sending a message
  ElementX/Sources/Screens/RoomScreen/ComposerToolbar/ComposerToolbarModels.swift
  ElementX/Sources/Screens/RoomScreen/ComposerToolbar/View/ComposerToolbar.swift
  ElementX/Sources/Screens/RoomScreen/ComposerToolbar/View/MessageComposer.swift
  ElementX/Sources/Screens/RoomScreen/ComposerToolbar/View/MessageComposerTextField.swift
Labels: pr-bugfix

#3220 Update subscriptions if visible range rooms change without the range itself changing
  ElementX/Sources/Screens/HomeScreen/HomeScreenModels.swift
  ElementX/Sources/Screens/HomeScreen/HomeScreenViewModel.swift
  ElementX/Sources/Screens/HomeScreen/View/HomeScreenContent.swift
  ElementX/Sources/Services/Room/RoomSummary/RoomSummaryProvider.swift
Labels: pr-bugfix

#3224 Prevent verification state changes other than `verified` from blocking the user on the session verification screen
  ElementX/Sources/FlowCoordinators/OnboardingFlowCoordinator.swift
Labels: pr-bugfix

#3225 Make pinned events required state in SlidingSync
  ElementX/Sources/Services/Client/ClientProxyProtocol.swift
Labels: pr-bugfix

#3229 Force room title headers to layout on one single line
  ElementX/Sources/Screens/RoomScreen/View/RoomHeaderView.swift
Labels: pr-bugfix

#3230 Bump the RustSDK to v1.0.44
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Sources/Services/Timeline/TimelineItemProxy.swift
  project.yml
Labels: pr-misc

#3233 Delay setting up subscriptions until the RoomListService is running in order to avoid cancelling in flight initial sync requests
  ElementX/Sources/Services/Client/ClientProxy.swift
  ElementX/Sources/Services/Room/RoomSummary/RoomSummaryProvider.swift
Labels: pr-change

#3234 Rewrite how out of band verification changes are handled within the onboarding flows
  ElementX/Sources/FlowCoordinators/OnboardingFlowCoordinator.swift
Labels: pr-bugfix

#3242 Pin Tweaks
  ElementX/Sources/Screens/RoomScreen/View/PinnedItemsBanner/PinnedItemsBannerView.swift
  ElementX/Sources/Screens/Timeline/TimelineTableViewController.swift
  ElementX/Sources/Screens/Timeline/View/ItemMenu/TimelineItemMenuAction.swift
  ElementX/Sources/Screens/Timeline/View/ItemMenu/TimelineItemMenuActionProvider.swift
  ElementX/Sources/Screens/Timeline/View/Style/TimelineItemBubbledStylerView.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_pinnedItemsBannerView-iPad-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_pinnedItemsBannerView-iPad-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_pinnedItemsBannerView-iPhone-15-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_pinnedItemsBannerView-iPhone-15-pseudo.1.png
Labels: pr-wip

#3245 Fix wrong durations for uploaded media
  ElementX/Sources/Services/Media/MediaUploadingPreprocessor.swift
  UnitTests/Sources/MediaUploadingPreprocessorTests.swift
Labels: pr-bugfix

#3246 Switch codecov-action back to v3 as 4 significantly decreases coverage
  .github/workflows/integration-tests.yml
  .github/workflows/ui_tests.yml
  .github/workflows/unit_tests.yml
Labels: pr-build

#3248 Make sure introspections are used on iOS 18.
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Sources/Other/Extensions/PlatformViewVersionPredicate.swift
  project.yml
Labels: pr-bugfix

#3254 Bring back default controls for QuickLook based media viewers
  ElementX/Sources/Screens/FilePreviewScreen/InteractiveQuickLook.swift
  ElementX/Sources/Screens/RoomDetailsScreen/View/RoomDetailsScreen.swift
  ElementX/Sources/Screens/RoomMemberDetailsScreen/View/RoomMemberDetailsScreen.swift
  ElementX/Sources/Screens/UserProfileScreen/View/UserProfileScreen.swift
Labels: pr-bugfix

#3257 Added a pin icon
  ElementX/Sources/Screens/Timeline/TimelineViewModel.swift
  ElementX/Sources/Screens/Timeline/View/Style/TimelineItemBubbledStylerView.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemBubbledStylerView-iPad-en-GB.Pinned-messages.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemBubbledStylerView-iPad-pseudo.Pinned-messages.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemBubbledStylerView-iPhone-15-en-GB.Pinned-messages.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemBubbledStylerView-iPhone-15-pseudo.Pinned-messages.png
  UnitTests/Sources/TimelineViewModelTests.swift
Labels: pr-wip

#3255 Reduce the maximum height used by the plain text composer
  ElementX/Sources/Screens/RoomScreen/ComposerToolbar/View/MessageComposer.swift
Labels: pr-bugfix

#3260 version bump to 1.8.0
  ElementX.xcodeproj/project.pbxproj
  project.yml
Labels: pr-build

#3261 Make the SessionDirectories type responsible for cleaning up data.
  ElementX/Sources/Other/Extensions/FileManager.swift
  ElementX/Sources/Services/Authentication/AuthenticationService.swift
  ElementX/Sources/Services/Keychain/KeychainController.swift
  ElementX/Sources/Services/QRCode/QRCodeLoginService.swift
  ElementX/Sources/Services/UserSession/RestorationToken.swift
  ElementX/Sources/Services/UserSession/SessionDirectories.swift
  ElementX/Sources/Services/UserSession/UserSessionStore.swift
  NSE/Sources/Other/NSEUserSession.swift
  UnitTests/Sources/KeychainControllerTests.swift
  UnitTests/Sources/RestorationTokenTests.swift
  UnitTests/Sources/SessionDirectoriesTests.swift
Labels: pr-change

#3265 Sdk v1.0.47
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Sources/Mocks/Generated/SDKGeneratedMocks.swift
  ElementX/Sources/Services/Timeline/TimelineProxy.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemBubbledStylerView-iPad-en-GB.Pinned-messages.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemBubbledStylerView-iPad-pseudo.Pinned-messages.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemBubbledStylerView-iPhone-15-en-GB.Pinned-messages.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemBubbledStylerView-iPhone-15-pseudo.Pinned-messages.png
  project.yml
Labels: pr-build

#3266 Try uploading test results to Codecov.
  .github/workflows/integration-tests.yml
  .github/workflows/ui_tests.yml
  .github/workflows/unit_tests.yml
Labels: pr-build

#3273 Make sure we don't reuse an old NSEUserSession after logging out and back in.
  NSE/Sources/NotificationServiceExtension.swift
  NSE/Sources/Other/NSEUserSession.swift
Labels: pr-bugfix

#3272 Make sure we reset the feature flag when upgrading to SSS.
  ElementX/Sources/Screens/HomeScreen/HomeScreenViewModel.swift
Labels: pr-bugfix

#3274 Fix interactive dismissal of our QLPreviewController iOS 18 (when built with Xcode 16).
  ElementX/Sources/Screens/FilePreviewScreen/InteractiveQuickLook.swift
Labels: pr-bugfix

#3282 Allow registration on matrix.org using a custom helper URL.
  ElementX/Sources/Application/AppSettings.swift
  ElementX/Sources/FlowCoordinators/AuthenticationFlowCoordinator.swift
  ElementX/Sources/Screens/Authentication/LoginScreen/LoginHomeserver.swift
  ElementX/Sources/Screens/Authentication/ServerConfirmationScreen/ServerConfirmationScreenModels.swift
  ElementX/Sources/Screens/Authentication/ServerConfirmationScreen/ServerConfirmationScreenViewModel.swift
  ElementX/Sources/Screens/Authentication/ServerConfirmationScreen/View/ServerConfirmationScreen.swift
  ElementX/Sources/Screens/AuthenticationStartScreen/AuthenticationStartScreenCoordinator.swift
  ElementX/Sources/Screens/AuthenticationStartScreen/AuthenticationStartScreenModels.swift
  ElementX/Sources/Screens/AuthenticationStartScreen/AuthenticationStartScreenViewModel.swift
  ElementX/Sources/Screens/AuthenticationStartScreen/View/AuthenticationStartScreen.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_authenticationStartScreen-iPad-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_authenticationStartScreen-iPad-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_authenticationStartScreen-iPhone-15-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_authenticationStartScreen-iPhone-15-pseudo.1.png
  UnitTests/Sources/ServerConfigurationScreenViewStateTests.swift
Labels: Trigger-PR-Build, pr-wip

#3295 Allow account deactivation when not using OIDC.
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Resources/Localizations/en.lproj/Localizable.strings
  ElementX/Sources/FlowCoordinators/SettingsFlowCoordinator.swift
  ElementX/Sources/Generated/Strings.swift
  ElementX/Sources/Mocks/ClientProxyMock.swift
  ElementX/Sources/Mocks/Generated/GeneratedMocks.swift
  ElementX/Sources/Mocks/Generated/SDKGeneratedMocks.swift
  ElementX/Sources/Screens/DeactivateAccountScreen/DeactivateAccountScreenCoordinator.swift
  ElementX/Sources/Screens/DeactivateAccountScreen/DeactivateAccountScreenModels.swift
  ElementX/Sources/Screens/DeactivateAccountScreen/DeactivateAccountScreenViewModel.swift
  ElementX/Sources/Screens/DeactivateAccountScreen/DeactivateAccountScreenViewModelProtocol.swift
  ElementX/Sources/Screens/DeactivateAccountScreen/View/DeactivateAccountScreen.swift
  ElementX/Sources/Screens/EncryptionReset/EncryptionResetPasswordScreen/View/EncryptionResetPasswordScreen.swift
  ElementX/Sources/Screens/SecureBackup/SecureBackupRecoveryKeyScreen/View/SecureBackupRecoveryKeyScreen.swift
  ElementX/Sources/Screens/Settings/SettingsScreen/SettingsScreenCoordinator.swift
  ElementX/Sources/Screens/Settings/SettingsScreen/SettingsScreenModels.swift
  ElementX/Sources/Screens/Settings/SettingsScreen/SettingsScreenViewModel.swift
  ElementX/Sources/Screens/Settings/SettingsScreen/View/SettingsScreen.swift
  ElementX/Sources/Services/Client/ClientProxy.swift
  ElementX/Sources/Services/Client/ClientProxyProtocol.swift
  PreviewTests/Sources/PreviewTests.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_deactivateAccountScreen-iPad-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_deactivateAccountScreen-iPad-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_deactivateAccountScreen-iPhone-15-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_deactivateAccountScreen-iPhone-15-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_resolveVerifiedUserSendFailureScreen-iPad-en-GB.Unsigned-Device.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_resolveVerifiedUserSendFailureScreen-iPad-pseudo.Unsigned-Device.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_resolveVerifiedUserSendFailureScreen-iPhone-15-en-GB.Unsigned-Device.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_resolveVerifiedUserSendFailureScreen-iPhone-15-pseudo.Unsigned-Device.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_settingsScreen-iPad-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_settingsScreen-iPad-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_settingsScreen-iPhone-15-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_settingsScreen-iPhone-15-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPad-en-GB.Unsigned-Devices.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPad-pseudo.Unsigned-Devices.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPhone-15-en-GB.Unsigned-Devices.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemMenu-iPhone-15-pseudo.Unsigned-Devices.png
  Tools/Scripts/Templates/SimpleScreenExample/ElementX/TemplateScreenCoordinator.swift
  UnitTests/Sources/DeactivateAccountScreenViewModelTests.swift
  project.yml
Labels: pr-change

#3297 Push the deactivate account screen.
  ElementX/Sources/FlowCoordinators/SettingsFlowCoordinator.swift
  ElementX/Sources/Screens/DeactivateAccountScreen/DeactivateAccountScreenCoordinator.swift
  ElementX/Sources/Screens/DeactivateAccountScreen/DeactivateAccountScreenModels.swift
  ElementX/Sources/Screens/DeactivateAccountScreen/DeactivateAccountScreenViewModel.swift
  ElementX/Sources/Screens/DeactivateAccountScreen/View/DeactivateAccountScreen.swift
  ElementX/Sources/Screens/Settings/SettingsScreen/View/SettingsScreen.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_deactivateAccountScreen-iPad-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_deactivateAccountScreen-iPad-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_deactivateAccountScreen-iPhone-15-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_deactivateAccountScreen-iPhone-15-pseudo.1.png
  UnitTests/Sources/DeactivateAccountScreenViewModelTests.swift
Labels: pr-misc

#3298 Bump SDK to 1.0.51
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  project.yml
Labels: pr-build

#3294 Stop delaying subscriptions until after startup
  ElementX/Sources/Services/Client/ClientProxy.swift
  ElementX/Sources/Services/Room/RoomSummary/RoomSummaryProvider.swift
Labels: pr-misc

#3301 Try to stop random codecov test result action failures from failing the whole test run.
  .github/workflows/integration-tests.yml
  .github/workflows/ui_tests.yml
  .github/workflows/unit_tests.yml
Labels: pr-build

#3247 crypto: Add configuration flag to enable invisible crypto
  ElementX.xcodeproj/project.pbxproj
  ElementX/Sources/Application/AppSettings.swift
  ElementX/Sources/Other/Extensions/ClientBuilder.swift
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/DeveloperOptionsScreenModels.swift
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/View/DeveloperOptionsScreen.swift
  ElementX/Sources/Services/Authentication/AuthenticationClientBuilder.swift
  ElementX/Sources/Services/UserSession/UserSessionStore.swift
  NSE/Sources/NotificationServiceExtension.swift
  NSE/Sources/Other/NSESettingsProtocol.swift
  NSE/Sources/Other/NSEUserSession.swift
Labels: pr-feature

#3304 Various Danger fixes
  Dangerfile.swift
Labels: pr-misc

#3307 Await for room sync only for push notification invites
  ElementX/Sources/Application/AppCoordinator.swift
  ElementX/Sources/Mocks/Generated/GeneratedMocks.swift
  ElementX/Sources/Services/Client/ClientProxy.swift
  ElementX/Sources/Services/Client/ClientProxyProtocol.swift
Labels: pr-bugfix

#3288 quick and dirty /join command
  ElementX/Sources/Screens/Timeline/TimelineModels.swift
  ElementX/Sources/Screens/Timeline/TimelineViewModel.swift
  ElementX/Sources/Screens/Timeline/View/TimelineView.swift
Labels: pr-feature

#3308 Enable message pinning
  ElementX/Sources/Application/AppSettings.swift
Labels: pr-feature

#3317 A bunch of random tweaks.
  ElementX/Sources/FlowCoordinators/RoomFlowCoordinator.swift
  ElementX/Sources/Other/Logging/TracingConfiguration.swift
  ElementX/Sources/Screens/CallScreen/CallScreenModels.swift
  ElementX/Sources/Screens/CallScreen/CallScreenViewModel.swift
  ElementX/Sources/Screens/CallScreen/View/CallScreen.swift
  ElementX/Sources/Screens/GlobalSearchScreen/View/GlobalSearchScreen.swift
  ElementX/Sources/Screens/ResolveVerifiedUserSendFailureScreen/ResolveVerifiedUserSendFailureScreenCoordinator.swift
  ElementX/Sources/Screens/ResolveVerifiedUserSendFailureScreen/ResolveVerifiedUserSendFailureScreenViewModel.swift
  ElementX/Sources/Screens/ResolveVerifiedUserSendFailureScreen/View/ResolveVerifiedUserSendFailureScreen.swift
  ElementX/Sources/Screens/Timeline/TimelineViewModel.swift
  ElementX/Sources/Services/Timeline/TimelineProxy.swift
  UnitTests/Sources/ResolveVerifiedUserSendFailureScreenViewModelTests.swift
  UnitTests/Sources/RoomScreenViewModelTests.swift
Labels: pr-misc

#3319 Fix: confusion of lab flags for invisible crypto
  ElementX/Sources/Services/UserSession/UserSessionStore.swift
Labels: pr-bugfix

#3323 Fix a bug where the Join Room screen was sometimes shown instead of the Room.
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  project.yml
Labels: pr-bugfix

#3324 Fix a bug on iOS 18 where the timeline background would use the wrong colour scheme when using the app switcher.
  .swiftlint.yml
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Sources/Other/HTMLParsing/AttributedStringBuilder.swift
  ElementX/Sources/Screens/RoomScreen/ComposerToolbar/View/MessageComposerTextField.swift
  ElementX/Sources/Screens/RoomScreen/RoomScreenCoordinator.swift
  ElementX/Sources/Screens/Timeline/TimelineTableViewController.swift
  project.yml
Labels: pr-bugfix

#3325 Don't use the new iPad modal presentation mode for the timeline item menu
  ElementX/Sources/Screens/Timeline/View/ItemMenu/TimelineItemMenu.swift
Labels: pr-bugfix

#3327 Add detection for latest devices.
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  fastlane/Fastfile
  project.yml
Labels: pr-change

#3328 Use a plain view for reactions instead of a TabView.
  ElementX/Sources/Screens/Timeline/View/Supplementary/ReactionsSummaryView.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_reactionsSummaryView-iPad-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_reactionsSummaryView-iPad-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_reactionsSummaryView-iPhone-16-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_reactionsSummaryView-iPhone-16-pseudo.1.png
Labels: pr-bugfix

#3326 Upgrade Kingfisher to fix a bug that prevented GIFs from being tapped.
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Sources/Services/Media/Provider/MediaProvider.swift
  UnitTests/Sources/MediaProvider/MockImageCache.swift
  project.yml
Labels: pr-bugfix

#3316 Configure the AuthenticationService later now that we have 2 flows on the start screen.
  ElementX.xcodeproj/project.pbxproj
  ElementX/Sources/Application/AppCoordinator.swift
  ElementX/Sources/FlowCoordinators/AuthenticationFlowCoordinator.swift
  ElementX/Sources/Mocks/AuthenticationClientBuilderFactoryMock.swift
  ElementX/Sources/Mocks/AuthenticationClientBuilderMock.swift
  ElementX/Sources/Mocks/Generated/GeneratedMocks.swift
  ElementX/Sources/Mocks/SDK/ClientSDKMock.swift
  ElementX/Sources/Mocks/SDK/EventTimelineItemSDKMock.swift
  ElementX/Sources/Mocks/UserSessionStoreMock.swift
  ElementX/Sources/Screens/Authentication/LoginScreen/LoginHomeserver.swift
  ElementX/Sources/Screens/Authentication/LoginScreen/LoginScreenCoordinator.swift
  ElementX/Sources/Screens/Authentication/ServerConfirmationScreen/ServerConfirmationScreenCoordinator.swift
  ElementX/Sources/Screens/Authentication/ServerConfirmationScreen/ServerConfirmationScreenModels.swift
  ElementX/Sources/Screens/Authentication/ServerConfirmationScreen/ServerConfirmationScreenViewModel.swift
  ElementX/Sources/Screens/Authentication/ServerConfirmationScreen/View/ServerConfirmationScreen.swift
  ElementX/Sources/Screens/Authentication/ServerSelectionScreen/MockServerSelectionScreenState.swift
  ElementX/Sources/Screens/Authentication/ServerSelectionScreen/ServerSelectionScreenCoordinator.swift
  ElementX/Sources/Screens/Authentication/ServerSelectionScreen/ServerSelectionScreenModels.swift
  ElementX/Sources/Screens/Authentication/ServerSelectionScreen/ServerSelectionScreenViewModel.swift
  ElementX/Sources/Screens/Authentication/ServerSelectionScreen/View/ServerSelectionScreen.swift
  ElementX/Sources/Services/Authentication/AuthenticationClientBuilder.swift
  ElementX/Sources/Services/Authentication/AuthenticationClientBuilderFactory.swift
  ElementX/Sources/Services/Authentication/AuthenticationService.swift
  ElementX/Sources/Services/Authentication/AuthenticationServiceProtocol.swift
  ElementX/Sources/Services/Authentication/MockAuthenticationService.swift
  ElementX/Sources/Services/QRCode/QRCodeLoginService.swift
  ElementX/Sources/Services/UserSession/UserSessionStore.swift
  ElementX/Sources/Services/UserSession/UserSessionStoreProtocol.swift
  ElementX/Sources/UITests/UITestsAppCoordinator.swift
  ElementX/Sources/UITests/UITestsScreenIdentifier.swift
  UITests/Sources/AuthenticationFlowCoordinatorUITests.swift
  UITests/Sources/LoginScreenUITests.swift
  UITests/Sources/__Snapshots__/Application/authenticationFlow-1-iPad-10th-generation-en-GB.UI.png
  UITests/Sources/__Snapshots__/Application/authenticationFlow-1-iPhone-15-en-GB.UI.png
  UITests/Sources/__Snapshots__/Application/login-0-iPad-10th-generation-en-GB.UI.png
  UITests/Sources/__Snapshots__/Application/login-0-iPhone-16-en-GB.UI.png
  UITests/Sources/__Snapshots__/Application/login-1-iPad-10th-generation-en-GB.UI.png
  UITests/Sources/__Snapshots__/Application/login-1-iPhone-16-en-GB.UI.png
  UITests/Sources/__Snapshots__/Application/login-iPad-10th-generation-en-GB.UI.png
  UITests/Sources/__Snapshots__/Application/login-iPhone-16-en-GB.UI.png
  UnitTests/Sources/AuthenticationServiceTests.swift
  UnitTests/Sources/ServerConfigurationScreenViewStateTests.swift
  UnitTests/Sources/ServerConfirmationScreenViewModelTests.swift
  UnitTests/Sources/ServerSelectionViewModelTests.swift
Labels: pr-change

#3330 Integration test improvements
  .github/workflows/integration-tests.yml
  ElementX.xcodeproj/project.pbxproj
  ElementX/Sources/Other/AccessibilityIdentifiers.swift
  ElementX/Sources/Other/Extensions/ProcessInfo.swift
  ElementX/Sources/Other/Logging/RustTracing.swift
  ElementX/Sources/Screens/RoomScreen/ComposerToolbar/View/ComposerToolbar.swift
  IntegrationTests/Sources/UserFlowTests.swift
  NSE/SupportingFiles/target.yml
Labels: pr-misc

#3331 crypto: rename invisible crypto flag to deviceIsolationMode
  ElementX/Sources/Application/AppSettings.swift
  ElementX/Sources/Other/Extensions/ClientBuilder.swift
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/DeveloperOptionsScreenModels.swift
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/View/DeveloperOptionsScreen.swift
  ElementX/Sources/Services/Authentication/AuthenticationClientBuilder.swift
  ElementX/Sources/Services/UserSession/UserSessionStore.swift
  NSE/Sources/Other/NSEUserSession.swift
Labels: T-Task, pr-misc

#3329 Start fixing flakey tests ❄️
  .github/workflows/integration-tests.yml
  .github/workflows/unit_tests.yml
  .github/workflows/unit_tests_enterprise.yml
  ElementX/Sources/Other/Extensions/Snapshotting.swift
  PreviewTests/Sources/PreviewTests.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_emojiPickerScreen-iPhone-16-en-GB.Screen.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_emojiPickerScreen-iPhone-16-pseudo.Screen.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_globalSearchScreen-iPhone-16-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_globalSearchScreen-iPhone-16-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_homeScreen-iPhone-16-en-GB.Empty.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_homeScreen-iPhone-16-en-GB.Loaded.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_homeScreen-iPhone-16-pseudo.Empty.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_homeScreen-iPhone-16-pseudo.Loaded.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_placeholderScreen-iPhone-16-en-GB.Split-View.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_placeholderScreen-iPhone-16-pseudo.Split-View.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomDetailsScreen-iPhone-16-en-GB.Simple-Room.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomDetailsScreen-iPhone-16-pseudo.Simple-Room.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomDirectorySearchScreen-iPad-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomDirectorySearchScreen-iPad-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomDirectorySearchScreen-iPhone-16-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomDirectorySearchScreen-iPhone-16-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomMembersListScreen-iPhone-16-en-GB.Admin-Banned.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomMembersListScreen-iPhone-16-en-GB.Admin-Empty-Banned.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomMembersListScreen-iPhone-16-en-GB.Admin-Members.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomMembersListScreen-iPhone-16-en-GB.Invites.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomMembersListScreen-iPhone-16-en-GB.Member.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomMembersListScreen-iPhone-16-pseudo.Admin-Banned.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomMembersListScreen-iPhone-16-pseudo.Admin-Empty-Banned.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomMembersListScreen-iPhone-16-pseudo.Admin-Members.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomMembersListScreen-iPhone-16-pseudo.Invites.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomMembersListScreen-iPhone-16-pseudo.Member.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_settingsScreen-iPhone-16-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_settingsScreen-iPhone-16-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemBubbledStylerView-iPhone-16-en-GB.Pinned-messages.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemBubbledStylerView-iPhone-16-pseudo.Pinned-messages.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemDebugView-iPhone-16-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemDebugView-iPhone-16-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_voiceMessagePreviewComposer-iPad-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_voiceMessagePreviewComposer-iPad-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_voiceMessagePreviewComposer-iPhone-16-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_voiceMessagePreviewComposer-iPhone-16-pseudo.1.png
  UnitTests/Sources/ComposerToolbarViewModelTests.swift
  UnitTests/Sources/TimelineViewModelTests.swift
  UnitTests/Sources/UserSessionFlowCoordinatorTests.swift
Labels: pr-build

#3335 Make sure the room header takes up as much space as possible (to hide the back button).
  ElementX/Sources/Screens/RoomScreen/View/RoomHeaderView.swift
  codecov.yml
Labels: pr-bugfix

#3338 Have ElementCall always default to the speaker; prevent the lock button from ending the call
  ElementX/Sources/Services/ElementCall/ElementCallService.swift
Labels: pr-bugfix

#3339 Log any failures when creating a call widget.
  ElementX/Sources/Services/ElementCall/ElementCallWidgetDriver.swift
Labels: pr-misc

#3336 Tracing and integration test tweaks
  .github/workflows/integration-tests.yml
  .github/workflows/unit_tests.yml
  .github/workflows/unit_tests_enterprise.yml
  ElementX/Sources/Application/AppCoordinator.swift
  ElementX/Sources/Other/Extensions/XCUIElement.swift
  ElementX/Sources/Other/Logging/MXLog.swift
  ElementX/Sources/Other/Logging/RustTracing.swift
  ElementX/Sources/Other/Logging/TracingConfiguration.swift
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/View/DeveloperOptionsScreen.swift
  ElementX/Sources/UITests/UITestsAppCoordinator.swift
  IntegrationTests/Sources/Common.swift
  IntegrationTests/Sources/UserFlowTests.swift
  NSE/Sources/Other/NSELogger.swift
  UnitTests/Sources/LoggingTests.swift
  UnitTests/Sources/TracingConfigurationTests.swift
  fastlane/Fastfile
Labels: pr-misc

#3341 Allow focusing the different avatars making up a DM details cluster separately.
  ElementX/Sources/Other/SwiftUI/Views/AvatarHeaderView.swift
  ElementX/Sources/Other/SwiftUI/Views/LoadableAvatarImage.swift
  ElementX/Sources/Other/SwiftUI/Views/RoomAvatarImage.swift
  ElementX/Sources/Screens/RoomDetailsScreen/RoomDetailsScreenModels.swift
  ElementX/Sources/Screens/RoomDetailsScreen/RoomDetailsScreenViewModel.swift
  ElementX/Sources/Screens/RoomDetailsScreen/View/RoomDetailsScreen.swift
  ElementX/Sources/Screens/RoomMemberDetailsScreen/RoomMemberDetailsScreenModels.swift
  ElementX/Sources/Screens/RoomMemberDetailsScreen/RoomMemberDetailsScreenViewModel.swift
  ElementX/Sources/Screens/RoomMemberDetailsScreen/View/RoomMemberDetailsScreen.swift
  ElementX/Sources/Screens/UserProfileScreen/UserProfileScreenModels.swift
  ElementX/Sources/Screens/UserProfileScreen/UserProfileScreenViewModel.swift
  ElementX/Sources/Screens/UserProfileScreen/View/UserProfileScreen.swift
Labels: pr-bugfix

#3349 Switch UI tests back to the perf-only runner.
  .github/workflows/ui_tests.yml
  ci_scripts/free_space.sh
Labels: pr-build

#3318 Remove message pinning FF
  ElementX/Sources/Application/AppSettings.swift
  ElementX/Sources/Screens/RoomDetailsScreen/RoomDetailsScreenModels.swift
  ElementX/Sources/Screens/RoomDetailsScreen/RoomDetailsScreenViewModel.swift
  ElementX/Sources/Screens/RoomDetailsScreen/View/RoomDetailsScreen.swift
  ElementX/Sources/Screens/RoomScreen/RoomScreenModels.swift
  ElementX/Sources/Screens/RoomScreen/RoomScreenViewModel.swift
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/DeveloperOptionsScreenModels.swift
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/View/DeveloperOptionsScreen.swift
  ElementX/Sources/Screens/Timeline/TimelineViewModel.swift
  ElementX/Sources/Screens/Timeline/View/Style/TimelineItemBubbledStylerView.swift
  ElementX/Sources/Services/Client/ClientProxy.swift
  UnitTests/Sources/RoomScreenViewModelTests.swift
  UnitTests/Sources/TimelineViewModelTests.swift
Labels: pr-misc
