Repository element-hq/element-x-ios, pull requests merged in 2024-07, with the labels that each got.

#2987 Update the SDK.
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  project.yml
Labels: pr-misc

#2984 Setup unit tests for Enterprise.
  .github/workflows/unit_tests_enterprise.yml
  ElementX/Sources/Application/AppSettings.swift
  ci_scripts/ci_post_clone.sh
  fastlane/Fastfile
Labels: pr-build

#2971 Allow Element Call's widget URL to be configured by the homeserver.
  ElementX.xcodeproj/project.pbxproj
  ElementX/Sources/Application/AppSettings.swift
  ElementX/Sources/FlowCoordinators/UserSessionFlowCoordinator.swift
  ElementX/Sources/Mocks/Generated/GeneratedMocks.swift
  ElementX/Sources/Mocks/Generated/SDKGeneratedMocks.swift
  ElementX/Sources/Screens/CallScreen/CallScreenCoordinator.swift
  ElementX/Sources/Screens/CallScreen/CallScreenViewModel.swift
  ElementX/Sources/Screens/CallScreen/View/CallScreen.swift
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/DeveloperOptionsScreenCoordinator.swift
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/DeveloperOptionsScreenModels.swift
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/DeveloperOptionsScreenViewModel.swift
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/View/DeveloperOptionsScreen.swift
  ElementX/Sources/Services/Client/ClientProxy.swift
  ElementX/Sources/Services/Client/ClientProxyProtocol.swift
  ElementX/Sources/Services/Client/ElementWellKnown.swift
Labels: pr-feature

#2989 Edit by timeline item only if the event id is missing
  ElementX/Sources/Services/Timeline/TimelineProxy.swift
Labels: pr-bugfix

#2992 Use the same format for project.yml as Ruby's YAML output.
  project.yml
Labels: pr-misc

#2995 Add a missing scheme when getting the Element .well-known file.
  ElementX/Sources/Services/Client/ClientProxy.swift
Labels: pr-bugfix

#2996 Volatile draft to restore the composer after an edit.
  ElementX/Sources/Mocks/Generated/GeneratedMocks.swift
  ElementX/Sources/Screens/RoomScreen/ComposerToolbar/ComposerToolbarViewModel.swift
  ElementX/Sources/Screens/RoomScreen/RoomScreenInteractionHandler.swift
  ElementX/Sources/Screens/RoomScreen/RoomScreenModels.swift
  ElementX/Sources/Services/ComposerDraft/ComposerDraftService.swift
  ElementX/Sources/Services/ComposerDraft/ComposerDraftServiceProtocol.swift
  UnitTests/Sources/ComposerToolbarViewModelTests.swift
Labels: pr-feature

#2999 Update the SDK ready for the release.
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  project.yml
Labels: pr-misc

#2978 Use local room list sorting from Rust.
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Sources/Mocks/ClientProxyMock.swift
  ElementX/Sources/Mocks/Generated/SDKGeneratedMocks.swift
  ElementX/Sources/Mocks/RoomSummaryProviderMock.swift
  ElementX/Sources/Screens/GlobalSearchScreen/GlobalSearchScreenViewModel.swift
  ElementX/Sources/Screens/HomeScreen/HomeScreenModels.swift
  ElementX/Sources/Screens/HomeScreen/HomeScreenViewModel.swift
  ElementX/Sources/Screens/HomeScreen/View/HomeScreenInviteCell.swift
  ElementX/Sources/Screens/HomeScreen/View/HomeScreenRoomCell.swift
  ElementX/Sources/Screens/MessageForwardingScreen/MessageForwardingScreenViewModel.swift
  ElementX/Sources/Screens/Settings/NotificationSettingsEditScreen/NotificationSettingsEditScreenViewModel.swift
  ElementX/Sources/Screens/Settings/NotificationSettingsEditScreen/View/NotificationSettingsEditScreen.swift
  ElementX/Sources/Screens/Settings/NotificationSettingsEditScreen/View/NotificationSettingsEditScreenRoomCell.swift
  ElementX/Sources/Services/Client/ClientProxyProtocol.swift
  ElementX/Sources/Services/Room/RoomSummary/RoomSummary.swift
  ElementX/Sources/Services/Room/RoomSummary/RoomSummaryProvider.swift
  ElementX/Sources/Services/Room/RoomSummary/RoomSummaryProviderProtocol.swift
  PreviewTests/__Snapshots__/PreviewTests/test_homeScreen-iPad-en-GB.Loaded.png
  PreviewTests/__Snapshots__/PreviewTests/test_homeScreen-iPad-pseudo.Loaded.png
  PreviewTests/__Snapshots__/PreviewTests/test_homeScreen-iPhone-15-en-GB.Loaded.png
  PreviewTests/__Snapshots__/PreviewTests/test_homeScreen-iPhone-15-pseudo.Loaded.png
  UnitTests/Sources/HomeScreenRoomTests.swift
  UnitTests/Sources/LoggingTests.swift
  UnitTests/Sources/RoomSummaryTests.swift
  project.yml
Labels: pr-change

#3000 Fix for the left room event using member instead of the sender
  ElementX/Sources/Services/Timeline/TimelineItems/RoomStateEventStringBuilder.swift
Labels: pr-bugfix

#3001 Fix a crash when 2 present room events are sent in quick succession.
  ElementX/Sources/FlowCoordinators/RoomFlowCoordinator.swift
Labels: pr-bugfix

#3014 Replace old visible rooms range with subscriptions in the room list.
  ElementX/Sources/FlowCoordinators/RoomFlowCoordinator.swift
  ElementX/Sources/Mocks/Generated/GeneratedMocks.swift
  ElementX/Sources/Services/Client/ClientProxyProtocol.swift
  ElementX/Sources/Services/Room/RoomProxy.swift
  ElementX/Sources/Services/Room/RoomProxyProtocol.swift
  ElementX/Sources/Services/Room/RoomSummary/RoomSummaryProvider.swift
Labels: pr-change

#3012 Make sure the BugReportScreen allows the user to retry if sending fails.
  ElementX.xcodeproj/project.pbxproj
  ElementX/Sources/Screens/BugReportScreen/BugReportScreenViewModel.swift
  UnitTests/Sources/BugReportScreenViewModelTests.swift
Labels: pr-bugfix

#3003 FIX: saving draft did not save the pill markdown content
  ElementX/Sources/Screens/RoomScreen/ComposerToolbar/ComposerToolbarViewModel.swift
Labels: pr-bugfix

#3015 Update RTE to 2.37.5
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  project.yml
Labels: pr-change

#3016 Update the SDK (fixes unnecessary encryption state requests in the room list).
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  project.yml
Labels: pr-bugfix

#3018 Restore Mentions in plain text mode
  ElementX/Sources/Screens/RoomScreen/ComposerToolbar/ComposerToolbarViewModel.swift
  UnitTests/Sources/ComposerToolbarViewModelTests.swift
Labels: pr-bugfix

#3017 Make sure Element Call uses the correct theme and language.
  ElementX/Sources/FlowCoordinators/UserSessionFlowCoordinator.swift
  ElementX/Sources/Mocks/Generated/GeneratedMocks.swift
  ElementX/Sources/Mocks/RoomProxyMock.swift
  ElementX/Sources/Screens/CallScreen/CallScreenCoordinator.swift
  ElementX/Sources/Screens/CallScreen/CallScreenViewModel.swift
  ElementX/Sources/Screens/CallScreen/View/CallScreen.swift
  ElementX/Sources/Services/ElementCall/ElementCallWidgetDriver.swift
  ElementX/Sources/Services/ElementCall/ElementCallWidgetDriverProtocol.swift
Labels: pr-bugfix

#3023 Fix stuck unread indicators.
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Sources/Mocks/Generated/SDKGeneratedMocks.swift
  ElementX/Sources/Other/Extensions/ClientBuilder.swift
  project.yml
Labels: pr-bugfix

#3024 Handle renamed PIN alert string.
  ElementX/Resources/Localizations/be.lproj/Localizable.strings
  ElementX/Resources/Localizations/bg.lproj/Localizable.strings
  ElementX/Resources/Localizations/cs.lproj/Localizable.strings
  ElementX/Resources/Localizations/de.lproj/Localizable.strings
  ElementX/Resources/Localizations/el.lproj/Localizable.strings
  ElementX/Resources/Localizations/en.lproj/Localizable.strings
  ElementX/Resources/Localizations/es.lproj/Localizable.strings
  ElementX/Resources/Localizations/et.lproj/Localizable.strings
  ElementX/Resources/Localizations/fr.lproj/Localizable.strings
  ElementX/Resources/Localizations/hu.lproj/Localizable.strings
  ElementX/Resources/Localizations/id.lproj/Localizable.strings
  ElementX/Resources/Localizations/it.lproj/Localizable.strings
  ElementX/Resources/Localizations/ka.lproj/Localizable.strings
  ElementX/Resources/Localizations/pt.lproj/Localizable.strings
  ElementX/Resources/Localizations/ro.lproj/Localizable.strings
  ElementX/Resources/Localizations/ru.lproj/Localizable.strings
  ElementX/Resources/Localizations/sk.lproj/Localizable.strings
  ElementX/Resources/Localizations/sv.lproj/Localizable.strings
  ElementX/Resources/Localizations/uk.lproj/Localizable.strings
  ElementX/Resources/Localizations/zh-Hans.lproj/Localizable.strings
  ElementX/Resources/Localizations/zh-Hant-TW.lproj/Localizable.strings
  ElementX/Sources/Generated/Strings.swift
  ElementX/Sources/Screens/AppLock/AppLockSetupPINScreen/AppLockSetupPINScreenViewModel.swift
Labels: pr-i18n

#3029 Fix an App Store upload error due to an RTE version mismatch.
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/SupportingFiles/target.yml
Labels: pr-build

#3040 Fix RTE framework signature error when building DEBUG builds for a device.
  ElementX.xcodeproj/project.pbxproj
  ElementX/SupportingFiles/target.yml
Labels: pr-build

#3043 Update RTE with inline prediction working
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  project.yml
Labels: pr-misc

#3030 Fix the string used for encrypted events in the room list.
  ElementX/Sources/Services/Room/RoomSummary/RoomEventStringBuilder.swift
Labels: pr-bugfix

#3039 Upgrade Compound.
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  PreviewTests/__Snapshots__/PreviewTests/test_pollFormScreen-iPad-en-GB.Edit.png
  PreviewTests/__Snapshots__/PreviewTests/test_pollFormScreen-iPad-pseudo.Edit.png
  PreviewTests/__Snapshots__/PreviewTests/test_pollFormScreen-iPhone-15-en-GB.Edit.png
  PreviewTests/__Snapshots__/PreviewTests/test_pollFormScreen-iPhone-15-pseudo.Edit.png
  PreviewTests/__Snapshots__/PreviewTests/test_roomDetailsEditScreen-iPad-en-GB.Editable.png
  PreviewTests/__Snapshots__/PreviewTests/test_roomDetailsEditScreen-iPad-pseudo.Editable.png
  PreviewTests/__Snapshots__/PreviewTests/test_roomDetailsEditScreen-iPhone-15-en-GB.Editable.png
  PreviewTests/__Snapshots__/PreviewTests/test_roomDetailsEditScreen-iPhone-15-pseudo.Editable.png
  PreviewTests/__Snapshots__/PreviewTests/test_templateScreen-iPad-en-GB.1.png
  PreviewTests/__Snapshots__/PreviewTests/test_templateScreen-iPad-pseudo.1.png
  PreviewTests/__Snapshots__/PreviewTests/test_templateScreen-iPhone-15-en-GB.1.png
  PreviewTests/__Snapshots__/PreviewTests/test_templateScreen-iPhone-15-pseudo.1.png
  project.yml
Labels: pr-build

#3052 Run the integration tests on GitHub again.
  .github/workflows/integration-tests.yml
Labels: pr-build

#3054 Update the SDK fixing a few room list bugs.
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Sources/Mocks/Generated/GeneratedMocks.swift
  ElementX/Sources/Mocks/Generated/SDKGeneratedMocks.swift
  ElementX/Sources/Mocks/RoomProxyMock.swift
  ElementX/Sources/Screens/CallScreen/CallScreenViewModel.swift
  ElementX/Sources/Screens/CallScreen/View/CallScreen.swift
  ElementX/Sources/Services/ElementCall/ElementCallWidgetDriver.swift
  ElementX/Sources/Services/Room/RoomProxy.swift
  ElementX/Sources/Services/Room/RoomProxyProtocol.swift
  ElementX/Sources/Services/Timeline/TimelineProxy.swift
  project.yml
Labels: pr-bugfix

#3056 Add a ClientBuilder hook.
  ElementX.xcodeproj/project.pbxproj
  ElementX/Sources/Application/AppCoordinator.swift
  ElementX/Sources/Hooks/AppHooks.swift
  ElementX/Sources/Other/Extensions/ClientBuilder.swift
  ElementX/Sources/Services/Authentication/AuthenticationService.swift
  ElementX/Sources/Services/QRCode/QRCodeLoginService.swift
  ElementX/Sources/Services/UserSession/UserSessionStore.swift
  NSE/Sources/NotificationServiceExtension.swift
  NSE/Sources/Other/NSEUserSession.swift
  NSE/SupportingFiles/target.yml
Labels: pr-misc

#3057 Add a feature flag for Simplified Sliding Sync.
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Sources/Application/AppCoordinator.swift
  ElementX/Sources/Application/AppSettings.swift
  ElementX/Sources/Mocks/Generated/SDKGeneratedMocks.swift
  ElementX/Sources/Other/Extensions/ClientBuilder.swift
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/DeveloperOptionsScreenModels.swift
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/View/DeveloperOptionsScreen.swift
  ElementX/Sources/Services/Authentication/AuthenticationService.swift
  ElementX/Sources/Services/QRCode/QRCodeLoginService.swift
  ElementX/Sources/Services/UserSession/UserSessionStore.swift
  NSE/Sources/NotificationServiceExtension.swift
  NSE/Sources/Other/NSESettingsProtocol.swift
  NSE/Sources/Other/NSEUserSession.swift
  project.yml
Labels: pr-wip

#3061 Fix a potential race condition when redacting a message.
  ElementX.xcodeproj/project.pbxproj
  ElementX/Sources/Screens/RoomScreen/RoomScreenInteractionHandler.swift
  ElementX/Sources/Screens/RoomScreen/RoomScreenModels.swift
  ElementX/Sources/Screens/RoomScreen/RoomScreenViewModel.swift
  ElementX/Sources/Screens/RoomScreen/View/ItemMenu/TimelineItemMacContextMenu.swift
  ElementX/Sources/Screens/RoomScreen/View/ItemMenu/TimelineItemMenu.swift
  ElementX/Sources/Screens/RoomScreen/View/ItemMenu/TimelineItemMenuAction.swift
  ElementX/Sources/Screens/RoomScreen/View/ItemMenu/TimelineItemMenuActionProvider.swift
  ElementX/Sources/Screens/RoomScreen/View/RoomScreen.swift
  ElementX/Sources/Screens/RoomScreen/View/Style/TimelineItemBubbledStylerView.swift
  ElementX/Sources/Services/Timeline/TimelineItems/RoomTimelineItemProtocol.swift
  ElementX/Sources/Services/Timeline/TimelineProxy.swift
Labels: pr-bugfix

#3044 Use the same UI as Android when tapping a link to a private room.
  ElementX/Sources/Screens/JoinRoomScreen/JoinRoomScreenModels.swift
  ElementX/Sources/Screens/JoinRoomScreen/JoinRoomScreenViewModel.swift
  ElementX/Sources/Screens/JoinRoomScreen/View/JoinRoomScreen.swift
  ElementX/Sources/Services/Client/ClientProxy.swift
  ElementX/Sources/Services/Client/ClientProxyProtocol.swift
  PreviewTests/__Snapshots__/PreviewTests/test_joinRoomScreen-iPad-en-GB.Invite.png
  PreviewTests/__Snapshots__/PreviewTests/test_joinRoomScreen-iPad-en-GB.Join.png
  PreviewTests/__Snapshots__/PreviewTests/test_joinRoomScreen-iPad-en-GB.Knock.png
  PreviewTests/__Snapshots__/PreviewTests/test_joinRoomScreen-iPad-en-GB.Unknown.png
  PreviewTests/__Snapshots__/PreviewTests/test_joinRoomScreen-iPad-pseudo.Invite.png
  PreviewTests/__Snapshots__/PreviewTests/test_joinRoomScreen-iPad-pseudo.Join.png
  PreviewTests/__Snapshots__/PreviewTests/test_joinRoomScreen-iPad-pseudo.Knock.png
  PreviewTests/__Snapshots__/PreviewTests/test_joinRoomScreen-iPad-pseudo.Unknown.png
  PreviewTests/__Snapshots__/PreviewTests/test_joinRoomScreen-iPhone-15-en-GB.Invite.png
  PreviewTests/__Snapshots__/PreviewTests/test_joinRoomScreen-iPhone-15-en-GB.Join.png
  PreviewTests/__Snapshots__/PreviewTests/test_joinRoomScreen-iPhone-15-en-GB.Knock.png
  PreviewTests/__Snapshots__/PreviewTests/test_joinRoomScreen-iPhone-15-pseudo.Invite.png
  PreviewTests/__Snapshots__/PreviewTests/test_joinRoomScreen-iPhone-15-pseudo.Join.png
  PreviewTests/__Snapshots__/PreviewTests/test_joinRoomScreen-iPhone-15-pseudo.Knock.png
Labels: pr-bugfix

#3063 Pinning items Feature Flag
  .swiftlint.yml
  ElementX/Resources/Localizations/en.lproj/Localizable.strings
  ElementX/Sources/Application/AppSettings.swift
  ElementX/Sources/FlowCoordinators/RoomFlowCoordinator.swift
  ElementX/Sources/Generated/Strings.swift
  ElementX/Sources/Screens/RoomScreen/RoomScreenInteractionHandler.swift
  ElementX/Sources/Screens/RoomScreen/RoomScreenModels.swift
  ElementX/Sources/Screens/RoomScreen/RoomScreenViewModel.swift
  ElementX/Sources/Screens/RoomScreen/View/ItemMenu/TimelineItemMenu.swift
  ElementX/Sources/Screens/RoomScreen/View/ItemMenu/TimelineItemMenuAction.swift
  ElementX/Sources/Screens/RoomScreen/View/ItemMenu/TimelineItemMenuActionProvider.swift
  ElementX/Sources/Screens/RoomScreen/View/RoomScreen.swift
  ElementX/Sources/Screens/RoomScreen/View/Style/TimelineItemBubbledStylerView.swift
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/DeveloperOptionsScreenModels.swift
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/View/DeveloperOptionsScreen.swift
  ElementX/Sources/Services/Client/ClientProxy.swift
  PreviewTests/__Snapshots__/PreviewTests/test_timelineItemMenu-iPad-en-GB.With-button-shapes-off.png
  PreviewTests/__Snapshots__/PreviewTests/test_timelineItemMenu-iPad-en-GB.With-button-shapes-on.png
  PreviewTests/__Snapshots__/PreviewTests/test_timelineItemMenu-iPad-pseudo.With-button-shapes-off.png
  PreviewTests/__Snapshots__/PreviewTests/test_timelineItemMenu-iPad-pseudo.With-button-shapes-on.png
  PreviewTests/__Snapshots__/PreviewTests/test_timelineItemMenu-iPhone-15-en-GB.With-button-shapes-off.png
  PreviewTests/__Snapshots__/PreviewTests/test_timelineItemMenu-iPhone-15-en-GB.With-button-shapes-on.png
  PreviewTests/__Snapshots__/PreviewTests/test_timelineItemMenu-iPhone-15-pseudo.With-button-shapes-off.png
  PreviewTests/__Snapshots__/PreviewTests/test_timelineItemMenu-iPhone-15-pseudo.With-button-shapes-on.png
Labels: pr-wip

#3062 Fixes #2840 - Use both the room list room and the room preview details to populate the join room screen
  ElementX/Sources/Screens/JoinRoomScreen/JoinRoomScreenModels.swift
  ElementX/Sources/Screens/JoinRoomScreen/JoinRoomScreenViewModel.swift
  PreviewTests/__Snapshots__/PreviewTests/test_joinRoomScreen-iPad-en-GB.Unknown.png
  PreviewTests/__Snapshots__/PreviewTests/test_joinRoomScreen-iPad-pseudo.Unknown.png
Labels: pr-bugfix

#3067 Removed RTE script
  ElementX.xcodeproj/project.pbxproj
  ElementX/SupportingFiles/target.yml
Labels: pr-build

#3075 Fix editing items not in the timeline failing
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Sources/Mocks/Generated/GeneratedMocks.swift
  ElementX/Sources/Mocks/Generated/SDKGeneratedMocks.swift
  ElementX/Sources/Services/Room/RoomProxy.swift
  ElementX/Sources/Services/Room/RoomProxyProtocol.swift
  ElementX/Sources/Services/Timeline/TimelineController/RoomTimelineController.swift
  ElementX/Sources/Services/Timeline/TimelineProxy.swift
  ElementX/Sources/Services/Timeline/TimelineProxyProtocol.swift
  project.yml
Labels: pr-bugfix

#3072 Pinned Items Banner UI
  ElementX.xcodeproj/project.pbxproj
  ElementX/Sources/Screens/RoomScreen/RoomScreenModels.swift
  ElementX/Sources/Screens/RoomScreen/RoomScreenViewModel.swift
  ElementX/Sources/Screens/RoomScreen/View/PinnedItemsBanner/PinnedItemsBannerView.swift
  ElementX/Sources/Screens/RoomScreen/View/PinnedItemsBanner/PinnedItemsIndicatorView.swift
  ElementX/Sources/Screens/RoomScreen/View/RoomScreen.swift
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/View/DeveloperOptionsScreen.swift
  PreviewTests/__Snapshots__/PreviewTests/test_pinnedItemsBannerView-iPad-en-GB.1.png
  PreviewTests/__Snapshots__/PreviewTests/test_pinnedItemsBannerView-iPad-pseudo.1.png
  PreviewTests/__Snapshots__/PreviewTests/test_pinnedItemsBannerView-iPhone-15-en-GB.1.png
  PreviewTests/__Snapshots__/PreviewTests/test_pinnedItemsBannerView-iPhone-15-pseudo.1.png
  PreviewTests/__Snapshots__/PreviewTests/test_pinnedItemsIndicatorView-iPad-en-GB.1.png
  PreviewTests/__Snapshots__/PreviewTests/test_pinnedItemsIndicatorView-iPad-pseudo.1.png
  PreviewTests/__Snapshots__/PreviewTests/test_pinnedItemsIndicatorView-iPhone-15-en-GB.1.png
  PreviewTests/__Snapshots__/PreviewTests/test_pinnedItemsIndicatorView-iPhone-15-pseudo.1.png
Labels: pr-wip

#3077 ElementCall unable to access media on ongoing CallKit session.
  ElementX/Sources/Screens/CallScreen/View/CallScreen.swift
  ElementX/Sources/Services/ElementCall/ElementCallService.swift
Labels: pr-bugfix

#3076 Set version to 1.7.0
  ElementX.xcodeproj/project.pbxproj
  project.yml
Labels: pr-misc

#3071 Automatically sign out when toggling the Simplified Sliding Sync feature flag.
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Sources/Application/AppSettings.swift
  ElementX/Sources/FlowCoordinators/SettingsFlowCoordinator.swift
  ElementX/Sources/Other/Extensions/ClientBuilder.swift
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/DeveloperOptionsScreenCoordinator.swift
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/DeveloperOptionsScreenModels.swift
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/DeveloperOptionsScreenViewModel.swift
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/View/DeveloperOptionsScreen.swift
  ElementX/Sources/Services/Authentication/AuthenticationService.swift
  ElementX/Sources/Services/QRCode/QRCodeLoginService.swift
  ElementX/Sources/Services/UserSession/UserSessionStore.swift
  NSE/Sources/Other/NSEUserSession.swift
  project.yml
Labels: pr-wip

#3081 Fix the restoration of a Simplified Sliding Sync session.
  ElementX/Sources/Services/UserSession/RestorationToken.swift
  UnitTests/Sources/KeychainControllerTests.swift
Labels: pr-wip

#3080 Hide/Show pin banner based on scroll direction
  ElementX/Sources/Screens/RoomScreen/RoomScreenModels.swift
  ElementX/Sources/Screens/RoomScreen/RoomScreenViewModel.swift
  ElementX/Sources/Screens/RoomScreen/View/PinnedItemsBanner/PinnedItemsIndicatorView.swift
  ElementX/Sources/Screens/RoomScreen/View/RoomScreen.swift
  ElementX/Sources/Screens/RoomScreen/View/Timeline/TimelineTableViewController.swift
  PreviewTests/__Snapshots__/PreviewTests/test_pinnedItemsIndicatorView-iPad-en-GB.1.png
  PreviewTests/__Snapshots__/PreviewTests/test_pinnedItemsIndicatorView-iPad-pseudo.1.png
  PreviewTests/__Snapshots__/PreviewTests/test_pinnedItemsIndicatorView-iPhone-15-en-GB.1.png
  PreviewTests/__Snapshots__/PreviewTests/test_pinnedItemsIndicatorView-iPhone-15-pseudo.1.png
Labels: pr-wip

#3082 Trim number of resolved alias vias and always default to a join button in the room preview screen
  ElementX/Sources/Screens/JoinRoomScreen/JoinRoomScreenViewModel.swift
  ElementX/Sources/Services/Client/ClientProxy.swift
  PreviewTests/__Snapshots__/PreviewTests/test_joinRoomScreen-iPad-en-GB.Unknown.png
  PreviewTests/__Snapshots__/PreviewTests/test_joinRoomScreen-iPad-pseudo.Unknown.png
  PreviewTests/__Snapshots__/PreviewTests/test_joinRoomScreen-iPhone-15-en-GB.Unknown.png
  PreviewTests/__Snapshots__/PreviewTests/test_joinRoomScreen-iPhone-15-pseudo.Unknown.png
Labels: pr-bugfix

#3083 Update Compound and handle API breaks in Introspect.
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Sources/Other/SwiftUI/Layout/FullscreenDialog.swift
  ElementX/Sources/Screens/Authentication/AuthenticationTextFieldStyle.swift
  project.yml
Labels: pr-misc

#3086 Fix a crash experienced when trying to report a crash.
  ElementX/Sources/Application/AppCoordinator.swift
  ElementX/Sources/Services/Analytics/Signposter.swift
Labels: pr-bugfix

#3090 Fix a potential crash when logging out.
  ElementX/Sources/Services/Client/ClientProxy.swift
Labels: pr-bugfix

#3084 Pin/Unpin Logic
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Resources/Localizations/en.lproj/Localizable.strings
  ElementX/Sources/Generated/Strings.swift
  ElementX/Sources/Mocks/Generated/GeneratedMocks.swift
  ElementX/Sources/Mocks/Generated/SDKGeneratedMocks.swift
  ElementX/Sources/Mocks/RoomProxyMock.swift
  ElementX/Sources/Other/Extensions/Task.swift
  ElementX/Sources/Screens/RoomScreen/RoomScreenInteractionHandler.swift
  ElementX/Sources/Screens/RoomScreen/RoomScreenModels.swift
  ElementX/Sources/Screens/RoomScreen/RoomScreenViewModel.swift
  ElementX/Sources/Screens/RoomScreen/View/ItemMenu/TimelineItemMenuAction.swift
  ElementX/Sources/Screens/RoomScreen/View/ItemMenu/TimelineItemMenuActionProvider.swift
  ElementX/Sources/Screens/RoomScreen/View/PinnedItemsBanner/PinnedItemsBannerView.swift
  ElementX/Sources/Screens/RoomScreen/View/RoomScreen.swift
  ElementX/Sources/Screens/RoomScreen/View/Style/TimelineItemBubbledStylerView.swift
  ElementX/Sources/Services/Room/RoomProxy.swift
  ElementX/Sources/Services/Room/RoomProxyProtocol.swift
  ElementX/Sources/Services/Timeline/TimelineController/MockRoomTimelineController.swift
  ElementX/Sources/Services/Timeline/TimelineController/RoomTimelineController.swift
  ElementX/Sources/Services/Timeline/TimelineController/RoomTimelineControllerProtocol.swift
  ElementX/Sources/Services/Timeline/TimelineProxy.swift
  ElementX/Sources/Services/Timeline/TimelineProxyProtocol.swift
  project.yml
Labels: pr-wip

#3093 Add the inviter to `JoinRoomScreen` when it's an invite.
  ElementX.xcodeproj/project.pbxproj
  ElementX/Sources/Mocks/Generated/GeneratedMocks.swift
  ElementX/Sources/Mocks/RoomMemberProxyMock.swift
  ElementX/Sources/Mocks/RoomProxyMock.swift
  ElementX/Sources/Other/SwiftUI/Views/RoomInviterLabel.swift
  ElementX/Sources/Screens/HomeScreen/HomeScreenModels.swift
  ElementX/Sources/Screens/HomeScreen/View/HomeScreenInviteCell.swift
  ElementX/Sources/Screens/JoinRoomScreen/JoinRoomScreenModels.swift
  ElementX/Sources/Screens/JoinRoomScreen/JoinRoomScreenViewModel.swift
  ElementX/Sources/Screens/JoinRoomScreen/View/JoinRoomScreen.swift
  ElementX/Sources/Services/Room/RoomProxy.swift
  ElementX/Sources/Services/Room/RoomProxyProtocol.swift
  PreviewTests/__Snapshots__/PreviewTests/test_roomInviterLabel-iPad-en-GB.1.png
  PreviewTests/__Snapshots__/PreviewTests/test_roomInviterLabel-iPad-pseudo.1.png
  PreviewTests/__Snapshots__/PreviewTests/test_roomInviterLabel-iPhone-15-en-GB.1.png
  PreviewTests/__Snapshots__/PreviewTests/test_roomInviterLabel-iPhone-15-pseudo.1.png
Labels: pr-change

#3100 Refactor TimelineItemSendInfo out of the styler.
  ElementX.xcodeproj/project.pbxproj
  ElementX/Resources/Localizations/en.lproj/Untranslated.strings
  ElementX/Sources/Generated/Strings+Untranslated.swift
  ElementX/Sources/Screens/RoomScreen/View/Style/TimelineItemBubbledStylerView.swift
  ElementX/Sources/Screens/RoomScreen/View/Style/TimelineItemSendInfoLabel.swift
  ElementX/Sources/Services/Timeline/TimelineItems/EventBasedTimelineItemProtocol.swift
  PreviewTests/__Snapshots__/PreviewTests/test_timelineItemSendInfoLabel-iPad-en-GB.1.png
  PreviewTests/__Snapshots__/PreviewTests/test_timelineItemSendInfoLabel-iPad-pseudo.1.png
  PreviewTests/__Snapshots__/PreviewTests/test_timelineItemSendInfoLabel-iPhone-15-en-GB.1.png
  PreviewTests/__Snapshots__/PreviewTests/test_timelineItemSendInfoLabel-iPhone-15-pseudo.1.png
Labels: pr-misc
