Repository element-hq/element-x-ios, pull requests merged in 2024-06, with the labels that each got.

#2966 Replace Towncrier with GitHub releases + labels.
  .github/PULL_REQUEST_TEMPLATE.md
  .github/release.yml
  CONTRIBUTING.md
  Dangerfile.swift
  changelog.d/_template.md.jinja
  ci_scripts/ci_common.sh
  ci_scripts/ci_post_xcodebuild.sh
  fastlane/Fastfile
  fastlane/changelog.rb
  towncrier.toml
Labels: pr-build

#2968 Hide timeline style selection
  ElementX/Sources/Application/AppSettings.swift
  ElementX/Sources/Screens/RoomScreen/RoomScreenModels.swift
  ElementX/Sources/Screens/RoomScreen/RoomScreenViewModel.swift
  ElementX/Sources/Screens/Settings/AvancedOptionsScreen/AdvancedSettingsScreenModels.swift
  ElementX/Sources/Screens/Settings/AvancedOptionsScreen/View/AdvancedSettingsScreen.swift
  PreviewTests/__Snapshots__/PreviewTests/test_advancedSettingsScreen-iPad-en-GB.1.png
  PreviewTests/__Snapshots__/PreviewTests/test_advancedSettingsScreen-iPad-pseudo.1.png
  PreviewTests/__Snapshots__/PreviewTests/test_advancedSettingsScreen-iPhone-15-en-GB.1.png
  PreviewTests/__Snapshots__/PreviewTests/test_advancedSettingsScreen-iPhone-15-pseudo.1.png
Labels: pr-change

#2972 Trigger a Danger CI run when labelling a PR too.
  .github/workflows/danger.yml
Labels: pr-build

#2969 Stop the timeline from requesting back pagination whilst loading existing items.
  ElementX/Sources/Screens/RoomScreen/RoomScreenModels.swift
  ElementX/Sources/Screens/RoomScreen/View/Timeline/TimelineTableViewController.swift
  ElementX/Sources/Services/Timeline/RoomTimelineProvider.swift
  ElementX/Sources/Services/Timeline/RoomTimelineProviderProtocol.swift
  ElementX/Sources/Services/Timeline/TimelineProxy.swift
Labels: pr-bugfix

#2981 Add changelog labels to PRs from Localazy and Renovate.
  .github/workflows/translations-pr.yml
  renovate.json
Labels: pr-build

#2982 Remove layout styling abstraction
  ElementX/Sources/Screens/RoomScreen/RoomScreenModels.swift
  ElementX/Sources/Screens/RoomScreen/View/RoomScreen.swift
  ElementX/Sources/Screens/RoomScreen/View/Style/TimelineItemBubbledStylerView.swift
  ElementX/Sources/Screens/RoomScreen/View/Style/TimelineStyle.swift
  ElementX/Sources/Screens/RoomScreen/View/Style/TimelineStyler.swift
  ElementX/Sources/Screens/RoomScreen/View/Supplementary/TimelineItemStatusView.swift
  ElementX/Sources/Screens/RoomScreen/View/Timeline/EmoteRoomTimelineView.swift
  ElementX/Sources/Screens/RoomScreen/View/Timeline/EncryptedRoomTimelineView.swift
  ElementX/Sources/Screens/RoomScreen/View/Timeline/FormattedBodyText.swift
  ElementX/Sources/Screens/RoomScreen/View/Timeline/LocationRoomTimelineView.swift
  ElementX/Sources/Screens/RoomScreen/View/Timeline/NoticeRoomTimelineView.swift
  ElementX/Sources/Screens/RoomScreen/View/Timeline/PollRoomTimelineView.swift
  ElementX/Sources/Screens/RoomScreen/View/Timeline/TextBasedRoomTimelineViewProtocol.swift
  ElementX/Sources/Screens/RoomScreen/View/Timeline/TextRoomTimelineView.swift
  ElementX/Sources/Screens/RoomScreen/View/Timeline/TimelineTableViewController.swift
  ElementX/Sources/Screens/RoomScreen/View/Timeline/TimelineView.swift
  ElementX/Sources/Screens/Settings/SettingsScreen/SettingsScreenCoordinator.swift
  ElementX/Sources/Screens/Settings/SettingsScreen/SettingsScreenViewModel.swift
  ElementX/Sources/Screens/Settings/SettingsScreen/View/SettingsScreen.swift
  ElementX/Sources/Services/Timeline/TimelineItems/EventBasedTimelineItemProtocol.swift
  UnitTests/Sources/SettingsViewModelTests.swift
  UnitTests/Sources/TextBasedRoomTimelineTests.swift
Labels: pr-misc

#2985 Setup Sentry instrumentation on top of the existing Signposter
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Sources/Application/AppCoordinator.swift
  ElementX/Sources/Mocks/Generated/GeneratedMocks.swift
  ElementX/Sources/Screens/HomeScreen/View/HomeScreen.swift
  ElementX/Sources/Screens/HomeScreen/View/HomeScreenContent.swift
  ElementX/Sources/Screens/RoomScreen/View/RoomScreen.swift
  ElementX/Sources/Services/Analytics/AnalyticsService.swift
  ElementX/Sources/Services/Analytics/Signposter.swift
  ElementX/Sources/Services/BugReport/BugReportService.swift
  ElementX/Sources/Services/BugReport/BugReportServiceProtocol.swift
  ElementX/SupportingFiles/target.yml
  UnitTests/Sources/BugReportServiceTests.swift
  project.yml
Labels: pr-misc
