Repository element-hq/element-x-ios, pull requests merged in 2025-10, with the labels that each got.

#4563 Joining a space from the room flow.
  ElementX.xcodeproj/project.pbxproj
  ElementX/Sources/Application/Navigation/NavigationTabCoordinator.swift
  ElementX/Sources/Application/Settings/AppSettings.swift
  ElementX/Sources/FlowCoordinators/ChatsFlowCoordinator.swift
  ElementX/Sources/FlowCoordinators/RoomFlowCoordinator.swift
  ElementX/Sources/FlowCoordinators/RoomFlowCoordinatorStateMachine.swift
  ElementX/Sources/FlowCoordinators/SpaceFlowCoordinator.swift
  ElementX/Sources/Other/SwiftUI/Backports.swift
  ElementX/Sources/Screens/Spaces/SpaceScreen/SpaceScreenCoordinator.swift
  ElementX/Sources/Screens/Spaces/SpaceScreen/SpaceScreenModels.swift
  ElementX/Sources/Screens/Spaces/SpaceScreen/SpaceScreenViewModel.swift
  ElementX/Sources/Screens/Spaces/SpaceScreen/View/SpaceScreen.swift
  UnitTests/Sources/RoomSummaryProviderTests.swift
Labels: pr-wip

#4569 A couple of small tweaks.
  .github/workflows/compound-ios.yml
  ElementX.xcodeproj/project.pbxproj
  ElementX/Sources/FlowCoordinators/ChatsFlowCoordinator.swift
  ElementX/Sources/Other/SwiftUI/Animation/ZoomTransition.swift
  ElementX/Sources/Other/SwiftUI/Backports.swift
  ElementX/Sources/Other/SwiftUI/Styles/ElementTextFieldStyle.swift
  ElementX/Sources/Other/SwiftUI/Views/RoomHeaderView.swift
  ElementX/Sources/Screens/HomeScreen/View/HomeScreen.swift
  ElementX/Sources/Screens/MediaEventsTimelineScreen/View/MediaEventsTimelineScreen.swift
  ElementX/Sources/Screens/RoomScreen/ComposerToolbar/View/CompletionSuggestionView.swift
  ElementX/Sources/Screens/Spaces/SpaceListScreen/View/SpaceListScreen.swift
  ElementX/Sources/Screens/Timeline/View/ItemMenu/TimelineItemMenu.swift
  ElementX/Sources/Screens/Timeline/View/Polls/PollView.swift
  ElementX/Sources/Services/Room/RoomSummary/RoomEventStringBuilder.swift
  ElementX/Sources/Services/Timeline/TimelineItems/RoomTimelineItemFactory.swift
  ElementX/Sources/Services/Timeline/TimelineProxy.swift
  ElementX/Sources/Services/UserSession/RestorationToken.swift
  ElementX/Sources/UITests/UITestsSignalling.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/completionSuggestion.iPad-en-GB-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/completionSuggestion.iPad-en-GB-1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/completionSuggestion.iPad-pseudo-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/completionSuggestion.iPad-pseudo-1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/completionSuggestion.iPhone-16-en-GB-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/completionSuggestion.iPhone-16-en-GB-1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/completionSuggestion.iPhone-16-pseudo-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/completionSuggestion.iPhone-16-pseudo-1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/composerToolbar.With-Suggestions-iPad-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/composerToolbar.With-Suggestions-iPad-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/composerToolbar.With-Suggestions-iPhone-16-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/composerToolbar.With-Suggestions-iPhone-16-pseudo.png
  compound-ios/Sources/Compound/Icons/CompoundIcon.swift
Labels: pr-bugfix

#4573 Labs screen
  AccessibilityTests/Sources/GeneratedAccessibilityTests.swift
  ElementX.xcodeproj/project.pbxproj
  ElementX/Sources/FlowCoordinators/SettingsFlowCoordinator.swift
  ElementX/Sources/Other/TestablePreview/TestablePreviewsDictionary.swift
  ElementX/Sources/Screens/LabsScreen/LabsScreenCoordinator.swift
  ElementX/Sources/Screens/LabsScreen/LabsScreenModels.swift
  ElementX/Sources/Screens/LabsScreen/LabsScreenViewModel.swift
  ElementX/Sources/Screens/LabsScreen/LabsScreenViewModelProtocol.swift
  ElementX/Sources/Screens/LabsScreen/View/LabsScreen.swift
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/DeveloperOptionsScreenModels.swift
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/View/DeveloperOptionsScreen.swift
  ElementX/Sources/Screens/Settings/SettingsScreen/SettingsScreenCoordinator.swift
  ElementX/Sources/Screens/Settings/SettingsScreen/SettingsScreenModels.swift
  ElementX/Sources/Screens/Settings/SettingsScreen/SettingsScreenViewModel.swift
  ElementX/Sources/Screens/Settings/SettingsScreen/View/SettingsScreen.swift
  PreviewTests/Sources/GeneratedPreviewTests.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/labsScreen.iPad-en-GB-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/labsScreen.iPad-pseudo-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/labsScreen.iPhone-16-en-GB-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/labsScreen.iPhone-16-pseudo-0.png
Labels: pr-feature

#4581 Clear cache on changing the threads FF
  ElementX/Resources/Localizations/en.lproj/Localizable.strings
  ElementX/Sources/FlowCoordinators/SettingsFlowCoordinator.swift
  ElementX/Sources/Generated/Strings.swift
  ElementX/Sources/Screens/LabsScreen/LabsScreenCoordinator.swift
  ElementX/Sources/Screens/LabsScreen/LabsScreenModels.swift
  ElementX/Sources/Screens/LabsScreen/LabsScreenViewModel.swift
  ElementX/Sources/Screens/LabsScreen/View/LabsScreen.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/labsScreen.iPad-en-GB-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/labsScreen.iPad-pseudo-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/labsScreen.iPhone-16-en-GB-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/labsScreen.iPhone-16-pseudo-0.png
Labels: pr-change

#4579 Implemented message forwarding for media previews and media timelines
  ElementX/Sources/FlowCoordinators/MediaEventsTimelineFlowCoordinator.swift
  ElementX/Sources/FlowCoordinators/RoomFlowCoordinator.swift
  ElementX/Sources/FlowCoordinators/RoomFlowCoordinatorStateMachine.swift
  ElementX/Sources/Screens/FilePreviewScreen/TimelineMediaPreviewModels.swift
  ElementX/Sources/Screens/FilePreviewScreen/TimelineMediaPreviewViewModel.swift
  ElementX/Sources/Screens/MediaEventsTimelineScreen/MediaEventsTimelineScreenCoordinator.swift
  ElementX/Sources/Screens/MediaEventsTimelineScreen/MediaEventsTimelineScreenModels.swift
  ElementX/Sources/Screens/MediaEventsTimelineScreen/MediaEventsTimelineScreenViewModel.swift
  ElementX/Sources/Screens/PinnedEventsTimelineScreen/PinnedEventsTimelineScreenCoordinator.swift
  ElementX/Sources/Screens/PinnedEventsTimelineScreen/PinnedEventsTimelineScreenModels.swift
  ElementX/Sources/Screens/PinnedEventsTimelineScreen/PinnedEventsTimelineScreenViewModel.swift
  ElementX/Sources/Screens/RoomScreen/RoomScreenCoordinator.swift
  ElementX/Sources/Screens/RoomScreen/RoomScreenModels.swift
  ElementX/Sources/Screens/RoomScreen/RoomScreenViewModel.swift
  ElementX/Sources/Screens/ThreadTimelineScreen/ThreadTimelineScreenCoordinator.swift
  ElementX/Sources/Screens/ThreadTimelineScreen/ThreadTimelineScreenModels.swift
  ElementX/Sources/Screens/ThreadTimelineScreen/ThreadTimelineScreenViewModel.swift
  ElementX/Sources/Screens/Timeline/TimelineViewModel.swift
  ElementX/Sources/Screens/Timeline/TimelineViewModelProtocol.swift
  ElementX/Sources/Screens/Timeline/View/ItemMenu/TimelineItemMenuAction.swift
  ElementX/Sources/Screens/Timeline/View/Style/TimelineItemBubbledStylerView.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/joinedMembersBadgeView.iPad-en-GB-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/joinedMembersBadgeView.iPad-pseudo-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/joinedMembersBadgeView.iPhone-16-en-GB-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/joinedMembersBadgeView.iPhone-16-pseudo-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/timelineMediaPreviewDetailsView.Image-iPad-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/timelineMediaPreviewDetailsView.Image-iPad-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/timelineMediaPreviewDetailsView.Image-iPhone-16-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/timelineMediaPreviewDetailsView.Image-iPhone-16-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/timelineMediaPreviewDetailsView.Incoming-on-Room-iPad-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/timelineMediaPreviewDetailsView.Incoming-on-Room-iPad-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/timelineMediaPreviewDetailsView.Incoming-on-Room-iPhone-16-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/timelineMediaPreviewDetailsView.Incoming-on-Room-iPhone-16-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/timelineMediaPreviewDetailsView.Loading-iPad-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/timelineMediaPreviewDetailsView.Loading-iPad-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/timelineMediaPreviewDetailsView.Loading-iPhone-16-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/timelineMediaPreviewDetailsView.Loading-iPhone-16-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/timelineMediaPreviewDetailsView.Unknown-type-iPad-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/timelineMediaPreviewDetailsView.Unknown-type-iPad-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/timelineMediaPreviewDetailsView.Unknown-type-iPhone-16-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/timelineMediaPreviewDetailsView.Unknown-type-iPhone-16-pseudo.png
  UnitTests/Sources/AnalyticsSettingsScreenViewModelTests.swift
Labels: pr-feature

#4586 Update sdk to 25.10.07-2
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Sources/Mocks/Generated/SDKGeneratedMocks.swift
  ElementX/Sources/Mocks/SDK/LeaveSpaceHandleSDKMock.swift
  ElementX/Sources/Services/Spaces/SpaceRoomProxy.swift
  project.yml
Labels: pr-misc

#4589 Use the space room name computed by the SDK.
  ElementX/Sources/Mocks/Generated/GeneratedMocks.swift
  ElementX/Sources/Mocks/SDK/LeaveSpaceHandleSDKMock.swift
  ElementX/Sources/Mocks/SpaceRoomProxyMock.swift
  ElementX/Sources/Screens/JoinRoomScreen/JoinRoomScreenViewModel.swift
  ElementX/Sources/Screens/Spaces/Common/SpaceHeaderView.swift
  ElementX/Sources/Screens/Spaces/Common/SpaceRoomCell.swift
  ElementX/Sources/Screens/Spaces/SpaceScreen/View/LeaveSpaceRoomDetailsCell.swift
  ElementX/Sources/Services/Spaces/SpaceRoomProxy.swift
  ElementX/Sources/Services/Spaces/SpaceRoomProxyProtocol.swift
Labels: pr-misc

#4587 Handle in-timeline permalinks to spaces
  ElementX/Sources/FlowCoordinators/RoomFlowCoordinator.swift
  ElementX/Sources/FlowCoordinators/RoomFlowCoordinatorStateMachine.swift
Labels: pr-wip
