Repository element-hq/element-x-ios, pull requests merged in 2025-03, with the labels that each got.

#3864 Prevent PRs with the X-Blocked label from being merged
  .github/workflows/blocked.yml
Labels: pr-misc

#3863 Use a static room summary provider to resolve room summaries through id and aliases
  ElementX/Sources/Mocks/ClientProxyMock.swift
  ElementX/Sources/Mocks/Generated/GeneratedMocks.swift
  ElementX/Sources/Screens/GlobalSearchScreen/GlobalSearchScreenCoordinator.swift
  ElementX/Sources/Screens/GlobalSearchScreen/GlobalSearchScreenViewModel.swift
  ElementX/Sources/Screens/GlobalSearchScreen/GlobalSearchScreenViewModelProtocol.swift
  ElementX/Sources/Screens/JoinRoomScreen/JoinRoomScreenViewModel.swift
  ElementX/Sources/Screens/MessageForwardingScreen/MessageForwardingScreenCoordinator.swift
  ElementX/Sources/Screens/MessageForwardingScreen/MessageForwardingScreenViewModel.swift
  ElementX/Sources/Screens/MessageForwardingScreen/MessageForwardingScreenViewModelProtocol.swift
  ElementX/Sources/Screens/RoomSelectionScreen/RoomSelectionScreenCoordinator.swift
  ElementX/Sources/Screens/RoomSelectionScreen/RoomSelectionScreenViewModel.swift
  ElementX/Sources/Screens/RoomSelectionScreen/RoomSelectionScreenViewModelProtocol.swift
  ElementX/Sources/Services/Client/ClientProxy.swift
  ElementX/Sources/Services/Client/ClientProxyProtocol.swift
  ElementX/Sources/Services/Room/RoomSummary/RoomSummaryProvider.swift
  ElementX/Sources/Services/Room/RoomSummary/RoomSummaryProviderProtocol.swift
Labels: pr-bugfix

#3870 Bump the RustSDK to v25.03.05
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Sources/Application/AppCoordinator.swift
  ElementX/Sources/Mocks/Generated/GeneratedMocks.swift
  ElementX/Sources/Mocks/Generated/SDKGeneratedMocks.swift
  ElementX/Sources/Services/Client/ClientProxy.swift
  ElementX/Sources/Services/Client/ClientProxyProtocol.swift
  ElementX/Sources/Services/Room/JoinedRoomProxy.swift
  ElementX/Sources/Services/Room/RoomPreview/RoomPreviewProxyProtocol.swift
  ElementX/Sources/Services/UserSession/UserSessionStore.swift
  ElementX/Sources/Services/UserSession/UserSessionStoreProtocol.swift
  project.yml
Labels: pr-misc

#3873 Prevent various room subscription task from blocking opening rooms
  ElementX/Sources/Services/Room/JoinedRoomProxy.swift
Labels: pr-bugfix

#3868 Room mentioning in the composer
  ElementX/Sources/FlowCoordinators/RoomFlowCoordinator.swift
  ElementX/Sources/Mocks/RoomSummaryProviderMock.swift
  ElementX/Sources/Other/Avatars.swift
  ElementX/Sources/Other/HTMLParsing/AttributedStringBuilder.swift
  ElementX/Sources/Other/HTMLParsing/ElementXAttributeScope.swift
  ElementX/Sources/Other/Pills/MentionBuilder.swift
  ElementX/Sources/Other/Pills/PlainMentionBuilder.swift
  ElementX/Sources/Screens/RoomScreen/ComposerToolbar/CompletionSuggestionService.swift
  ElementX/Sources/Screens/RoomScreen/ComposerToolbar/CompletionSuggestionServiceProtocol.swift
  ElementX/Sources/Screens/RoomScreen/ComposerToolbar/ComposerToolbarViewModel.swift
  ElementX/Sources/Screens/RoomScreen/ComposerToolbar/View/CompletionSuggestionView.swift
  ElementX/Sources/Screens/RoomScreen/ComposerToolbar/View/ComposerToolbar.swift
  ElementX/Sources/Screens/RoomScreen/ComposerToolbar/View/MentionSuggestionItemView.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/globalSearchScreen.iPad-en-GB-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/globalSearchScreen.iPad-pseudo-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/globalSearchScreen.iPhone-16-en-GB-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/globalSearchScreen.iPhone-16-pseudo-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/mentionSuggestionItemView.All-users-iPad-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/mentionSuggestionItemView.All-users-iPad-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/mentionSuggestionItemView.All-users-iPhone-16-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/mentionSuggestionItemView.All-users-iPhone-16-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/mentionSuggestionItemView.Room-iPad-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/mentionSuggestionItemView.Room-iPad-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/mentionSuggestionItemView.Room-iPhone-16-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/mentionSuggestionItemView.Room-iPhone-16-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/mentionSuggestionItemView.User-iPad-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/mentionSuggestionItemView.User-iPad-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/mentionSuggestionItemView.User-iPhone-16-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/mentionSuggestionItemView.User-iPhone-16-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/mentionSuggestionItemView.User-no-display-name-iPad-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/mentionSuggestionItemView.User-no-display-name-iPad-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/mentionSuggestionItemView.User-no-display-name-iPhone-16-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/mentionSuggestionItemView.User-no-display-name-iPhone-16-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/messageForwardingScreen.iPad-en-GB-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/messageForwardingScreen.iPad-pseudo-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/messageForwardingScreen.iPhone-16-en-GB-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/messageForwardingScreen.iPhone-16-pseudo-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/roomSelectionScreen.iPad-en-GB-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/roomSelectionScreen.iPad-pseudo-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/roomSelectionScreen.iPhone-16-en-GB-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/roomSelectionScreen.iPhone-16-pseudo-0.png
  UnitTests/Sources/CompletionSuggestionServiceTests.swift
  UnitTests/Sources/ComposerToolbarViewModelTests.swift
Labels: pr-feature

#3874 FF event cache true by default and updated the SDK
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Sources/Application/AppSettings.swift
  project.yml
Labels: pr-misc

#3875 ClientProxy refactor
  ElementX/Sources/FlowCoordinators/PinnedEventsTimelineFlowCoordinator.swift
  ElementX/Sources/FlowCoordinators/RoomFlowCoordinator.swift
  ElementX/Sources/FlowCoordinators/UserSessionFlowCoordinator.swift
  ElementX/Sources/Mocks/ClientProxyMock.swift
  ElementX/Sources/Mocks/Generated/GeneratedMocks.swift
  ElementX/Sources/Screens/JoinRoomScreen/JoinRoomScreenViewModel.swift
  ElementX/Sources/Services/Client/ClientProxy.swift
  ElementX/Sources/Services/Client/ClientProxyProtocol.swift
  ElementX/Sources/Services/UserSession/UserSessionStore.swift
  ElementX/Sources/Services/UserSession/UserSessionStoreProtocol.swift
Labels: pr-misc

#3876 Improve next release flow to rebase main
  ci_scripts/ci_common.sh
  fastlane/Fastfile
Labels: pr-build

#3879 Check if the git is shallow before fetching
  ci_scripts/ci_common.sh
Labels: pr-build

#3882 Change bage label colors to blue when not highlighted
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX.xcodeproj/xcshareddata/xcschemes/PreviewTests.xcscheme
  ElementX/Sources/Other/SwiftUI/Views/BadgeLabel.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/avatarHeaderView.Room-iPad-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/avatarHeaderView.Room-iPad-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/avatarHeaderView.Room-iPhone-16-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/avatarHeaderView.Room-iPhone-16-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/badgeLabel.iPad-en-GB-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/badgeLabel.iPad-pseudo-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/badgeLabel.iPhone-16-en-GB-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/badgeLabel.iPhone-16-pseudo-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/joinRoomScreen.Banned-iPad-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/joinRoomScreen.Banned-iPad-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/joinRoomScreen.Banned-iPhone-16-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/joinRoomScreen.Banned-iPhone-16-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/joinRoomScreen.Forbidden-iPad-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/joinRoomScreen.Forbidden-iPad-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/joinRoomScreen.Forbidden-iPhone-16-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/joinRoomScreen.Forbidden-iPhone-16-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/joinRoomScreen.InviteRequired-iPad-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/joinRoomScreen.InviteRequired-iPad-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/joinRoomScreen.InviteRequired-iPhone-16-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/joinRoomScreen.InviteRequired-iPhone-16-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/joinRoomScreen.Invited-iPad-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/joinRoomScreen.Invited-iPad-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/joinRoomScreen.Invited-iPhone-16-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/joinRoomScreen.Invited-iPhone-16-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/joinRoomScreen.Joinable-iPad-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/joinRoomScreen.Joinable-iPad-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/joinRoomScreen.Joinable-iPhone-16-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/joinRoomScreen.Joinable-iPhone-16-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/joinRoomScreen.Knockable-iPad-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/joinRoomScreen.Knockable-iPad-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/joinRoomScreen.Knockable-iPhone-16-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/joinRoomScreen.Knockable-iPhone-16-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/joinRoomScreen.Restricted-iPad-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/joinRoomScreen.Restricted-iPad-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/joinRoomScreen.Restricted-iPhone-16-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/joinRoomScreen.Restricted-iPhone-16-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/roomDetailsScreen.Simple-Room-iPad-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/roomDetailsScreen.Simple-Room-iPad-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/roomDetailsScreen.Simple-Room-iPhone-16-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/roomDetailsScreen.Simple-Room-iPhone-16-pseudo.png
  project.yml
Labels: pr-misc

#3888 Update sentry to 8.35
  ElementX.xcodeproj/project.pbxproj
  project.yml
Labels: pr-misc

#3894 Prefix our release tags with `release/`
  fastlane/Fastfile
Labels: pr-build

#3896 Added @room to suggestion view for room mentions
  ElementX/Sources/Screens/RoomScreen/ComposerToolbar/CompletionSuggestionServiceProtocol.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/mentionSuggestionItemView.All-users-iPad-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/mentionSuggestionItemView.All-users-iPad-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/mentionSuggestionItemView.All-users-iPhone-16-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/mentionSuggestionItemView.All-users-iPhone-16-pseudo.png
Labels: pr-change

#3891 SDK update
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Sources/Application/AppCoordinator.swift
  ElementX/Sources/Application/TargetConfiguration.swift
  ElementX/Sources/Mocks/BannedRoomProxyMock.swift
  ElementX/Sources/Mocks/Generated/GeneratedMocks.swift
  ElementX/Sources/Mocks/Generated/SDKGeneratedMocks.swift
  ElementX/Sources/Mocks/InvitedRoomProxyMock.swift
  ElementX/Sources/Mocks/JoinedRoomProxyMock.swift
  ElementX/Sources/Mocks/KnockedRoomProxyMock.swift
  ElementX/Sources/Other/Logging/ExtensionLogger.swift
  ElementX/Sources/Other/Logging/MXLog.swift
  ElementX/Sources/Other/Logging/Tracing.swift
  ElementX/Sources/Screens/MediaUploadPreviewScreen/MediaUploadPreviewScreenViewModel.swift
  ElementX/Sources/Screens/RoomDetailsScreen/RoomDetailsScreenModels.swift
  ElementX/Sources/Screens/RoomDetailsScreen/RoomDetailsScreenViewModel.swift
  ElementX/Sources/Screens/RoomMemberListScreen/RoomMembersListScreenViewModel.swift
  ElementX/Sources/Screens/RoomNotificationSettingsScreen/RoomNotificationSettingsScreenViewModel.swift
  ElementX/Sources/Screens/RoomScreen/ComposerToolbar/ComposerToolbarModels.swift
  ElementX/Sources/Screens/RoomScreen/ComposerToolbar/ComposerToolbarViewModel.swift
  ElementX/Sources/Screens/SecurityAndPrivacyScreen/SecurityAndPrivacyScreenViewModel.swift
  ElementX/Sources/Services/Authentication/AuthenticationService.swift
  ElementX/Sources/Services/Client/ClientProxy.swift
  ElementX/Sources/Services/ElementCall/ElementCallWidgetDriver.swift
  ElementX/Sources/Services/Room/JoinedRoomProxy.swift
  ElementX/Sources/Services/Room/RoomInfoProxy.swift
  ElementX/Sources/Services/Room/RoomProxyProtocol.swift
  ElementX/Sources/UITests/UITestsAppCoordinator.swift
  NSE/Sources/NotificationServiceExtension.swift
  NSE/SupportingFiles/target.yml
  ShareExtension/Sources/ShareExtensionViewController.swift
  ShareExtension/SupportingFiles/target.yml
  UnitTests/Sources/LoggingTests.swift
  project.yml
Labels: pr-misc

#3902 Fix sharing from in-app QuickLook to itself
  ElementX/Sources/FlowCoordinators/UserSessionFlowCoordinator.swift
Labels: pr-bugfix

#3907 Added a test to check if URLs with RTL are not marked as phishing
  UnitTests/Sources/AttributedStringBuilderTests.swift
Labels: pr-misc

#3913 Fix an issue rendering pills in some forks.
  ElementX/Sources/Other/InfoPlistReader.swift
Labels: pr-bugfix

#3908 Pin all 3rd party github actions to their full length commit SHA
  .github/workflows/integration-tests.yml
  .github/workflows/pr-build.yml
  .github/workflows/translations-pr.yml
  .github/workflows/ui_tests.yml
  .github/workflows/unit_tests.yml
  .github/workflows/unit_tests_enterprise.yml
Labels: pr-misc

#3918 Remove the unused TestMeasurementParser and lint integration tests again
  .swiftlint.yml
  ElementX.xcodeproj/project.pbxproj
  IntegrationTests/Sources/TestMeasurementParser.swift
Labels: pr-build

#3924 Attempt to fix the wrong timeline start display by defaulting the backwards publisher to .idle
  ElementX/Sources/Services/Timeline/TimelineProxy.swift
Labels: pr-bugfix

#3917 Stop CI from uploading Codecov results when a PR comes from a fork.
  .github/workflows/unit_tests.yml
  .github/workflows/unit_tests_enterprise.yml
Labels: pr-build

#3927 Discard any changes before rebasing main.
  fastlane/Fastfile
Labels: pr-build

#3929 Add developer options for Rust's Log Packs.
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Sources/Application/AppCoordinator.swift
  ElementX/Sources/Application/AppSettings.swift
  ElementX/Sources/Application/TargetConfiguration.swift
  ElementX/Sources/Other/Logging/TraceLogPack.swift
  ElementX/Sources/Other/Logging/Tracing.swift
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/DeveloperOptionsScreenModels.swift
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/View/DeveloperOptionsScreen.swift
  ElementX/Sources/Services/ElementCall/ElementCallWidgetDriver.swift
  NSE/Sources/NotificationServiceExtension.swift
  ShareExtension/Sources/ShareExtensionViewController.swift
  UnitTests/Sources/LoggingTests.swift
  project.yml
Labels: pr-misc

#3931 FIX: DM invites now render avatars correctly
  ElementX/Sources/Screens/HomeScreen/View/HomeScreenInviteCell.swift
  ElementX/Sources/Screens/JoinRoomScreen/JoinRoomScreenModels.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/homeScreenInviteCell.iPad-en-GB-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/homeScreenInviteCell.iPad-pseudo-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/homeScreenInviteCell.iPhone-16-en-GB-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/homeScreenInviteCell.iPhone-16-pseudo-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/joinRoomScreen.InvitedDM-iPad-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/joinRoomScreen.InvitedDM-iPad-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/joinRoomScreen.InvitedDM-iPhone-16-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/joinRoomScreen.InvitedDM-iPhone-16-pseudo.png
Labels: pr-bugfix

#3916 Updated the SDK to 25.03.24
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Sources/Application/AppSettings.swift
  ElementX/Sources/Mocks/Generated/GeneratedMocks.swift
  ElementX/Sources/Mocks/Generated/SDKGeneratedMocks.swift
  ElementX/Sources/Mocks/JoinedRoomProxyMock.swift
  ElementX/Sources/Screens/Authentication/OIDCAuthenticationPresenter.swift
  ElementX/Sources/Screens/CallScreen/CallScreenCoordinator.swift
  ElementX/Sources/Screens/CallScreen/CallScreenViewModel.swift
  ElementX/Sources/Screens/CallScreen/View/CallScreen.swift
  ElementX/Sources/Services/Authentication/AuthenticationService.swift
  ElementX/Sources/Services/Authentication/AuthenticationServiceProtocol.swift
  ElementX/Sources/Services/ElementCall/ElementCallWidgetDriver.swift
  ElementX/Sources/Services/ElementCall/ElementCallWidgetDriverProtocol.swift
  ElementX/Sources/Services/ElementCall/GenericCallLinkWidgetDriver.swift
  Tools/Sources/BuildSDK.swift
  project.yml
Labels: pr-api

#3935 Add NSPrivacyTracking and NSPrivacyCollectedDataTypes to PrivacyInfo.xcprivacy
  ElementX/SupportingFiles/PrivacyInfo.xcprivacy
Labels: pr-misc

#3938 FIX: Reply view will now render pills as plain text
  ElementX/Sources/Screens/Timeline/TimelineModels.swift
  ElementX/Sources/Screens/Timeline/TimelineViewModel.swift
  ElementX/Sources/Screens/Timeline/View/Replies/TimelineReplyView.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/timelineReplyView.iPad-en-GB-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/timelineReplyView.iPad-pseudo-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/timelineReplyView.iPhone-16-en-GB-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/timelineReplyView.iPhone-16-pseudo-0.png
Labels: pr-bugfix

#3939 Embed element call
  .githooks/pre-commit
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Sources/Application/AppSettings.swift
  ElementX/Sources/Screens/CallScreen/CallScreenViewModel.swift
  ElementX/Sources/Screens/CallScreen/View/CallScreen.swift
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/View/DeveloperOptionsScreen.swift
  ElementX/Sources/Services/Client/ElementWellKnown.swift
  ElementX/SupportingFiles/target.yml
  project.yml
Labels: pr-misc

#3943 EC Embedding improvements
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Sources/Mocks/Generated/GeneratedMocks.swift
  ElementX/Sources/Mocks/JoinedRoomProxyMock.swift
  ElementX/Sources/Screens/CallScreen/CallScreenViewModel.swift
  ElementX/Sources/Screens/CallScreen/View/CallScreen.swift
  ElementX/Sources/Services/ElementCall/ElementCallWidgetDriver.swift
  ElementX/Sources/Services/ElementCall/ElementCallWidgetDriverProtocol.swift
  ElementX/Sources/Services/ElementCall/GenericCallLinkWidgetDriver.swift
  project.yml
Labels: pr-bugfix

#3942 Attempt to prevent crashes after expiring background refreshes.
  ElementX/Sources/Application/AppCoordinator.swift
Labels: pr-bugfix

#3946 Revert "Attempt to prevent crashes after expiring background refreshes."
  ElementX/Sources/Application/AppCoordinator.swift
Labels: pr-bugfix

#3947 fix: update compound to fix accessibility in pickers and toggles
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  project.yml
Labels: pr-bugfix

#3948 a11y: add profile picture accessibility label
  ElementX/Resources/Localizations/en-US.lproj/Localizable.strings
  ElementX/Resources/Localizations/en.lproj/Localizable.strings
  ElementX/Sources/Generated/Strings.swift
  ElementX/Sources/Other/SwiftUI/Views/AvatarHeaderView.swift
Labels: pr-a11y

#3950 a11y: better voice over for voice messages
  ElementX/Resources/Localizations/en-US.lproj/Localizable.strings
  ElementX/Resources/Localizations/en.lproj/Localizable.strings
  ElementX/Sources/Generated/Strings.swift
  ElementX/Sources/Screens/Timeline/View/Style/TimelineItemAccessibilityModifier.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/VoiceMessageRoomTimelineView.swift
  ElementX/Sources/Screens/Timeline/View/VoiceMessageRoomPlaybackView.swift
Labels: pr-a11y
