Repository element-hq/element-x-ios, pull requests merged in 2025-09, with the labels that each got.

#4455 Use the SDK's SpaceService, SpaceRoom and SpaceRoomList.
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Sources/FlowCoordinators/SpaceExplorerFlowCoordinator.swift
  ElementX/Sources/FlowCoordinators/SpaceFlowCoordinator.swift
  ElementX/Sources/Mocks/Generated/GeneratedMocks.swift
  ElementX/Sources/Mocks/Generated/SDKGeneratedMocks.swift
  ElementX/Sources/Mocks/SpaceRoomListProxyMock.swift
  ElementX/Sources/Other/SDKListener.swift
  ElementX/Sources/Screens/Spaces/SpaceScreen/SpaceScreenCoordinator.swift
  ElementX/Sources/Screens/Spaces/SpaceScreen/SpaceScreenViewModel.swift
  ElementX/Sources/Screens/Spaces/SpaceScreen/View/SpaceScreen.swift
  ElementX/Sources/Services/Client/ClientProxy.swift
  ElementX/Sources/Services/Spaces/SpaceRoomListProxy.swift
  ElementX/Sources/Services/Spaces/SpaceRoomListProxyProtocol.swift
  ElementX/Sources/Services/Spaces/SpaceRoomProxy.swift
  ElementX/Sources/Services/Spaces/SpaceServiceProxy.swift
  ElementX/Sources/Services/Spaces/SpaceServiceProxyProtocol.swift
  UnitTests/Sources/SpaceListScreenViewModelTests.swift
  UnitTests/Sources/SpaceScreenViewModelTests.swift
  project.yml
Labels: pr-wip

#4457 A11y audit improvements and fixes
  AccessibilityTests/Sources/AccessibilityTests.swift
  ElementX/Sources/Other/MatrixEntityRegex.swift
  ElementX/Sources/Screens/FilePreviewScreen/View/TimelineMediaPreviewDetailsView.swift
  ElementX/Sources/Screens/FilePreviewScreen/View/TimelineMediaPreviewRedactConfirmationView.swift
  ElementX/Sources/Screens/MediaEventsTimelineScreen/View/MediaEventsTimelineScreen.swift
  ElementX/Sources/Screens/Spaces/Common/SpaceHeaderView.swift
Labels: pr-a11y

#4456 Tweaks discovered when using Compound overrides.
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Sources/Other/SwiftUI/Animation/ShimmerModifier.swift
  ElementX/Sources/Screens/HomeScreen/View/BloomModifier.swift
  ElementX/Sources/Screens/HomeScreen/View/HomeScreenContent.swift
  ElementX/Sources/Screens/HomeScreen/View/HomeScreenRoomCell.swift
  ElementX/Sources/Screens/HomeScreen/View/HomeScreenRoomList.swift
  project.yml
Labels: pr-misc

#4461 Fix a bug where invites would be hidden when the Low Priority feature is enabled.
  ElementX/Sources/Services/Room/RoomSummary/RoomSummaryProvider.swift
  UnitTests/Sources/RoomSummaryProviderTests.swift
Labels: pr-wip

#4474 MediaTimelinePreviewDetails can now be opened by long pressing in the media timeline
  ElementX.xcodeproj/project.pbxproj
  ElementX/Sources/Screens/FilePreviewScreen/View/TimelineMediaPreviewDetailsView.swift
  ElementX/Sources/Screens/FilePreviewScreen/View/TimelineMediaPreviewRedactConfirmationView.swift
  ElementX/Sources/Screens/MediaEventsTimelineScreen/MediaEventsTimelineScreenModels.swift
  ElementX/Sources/Screens/MediaEventsTimelineScreen/MediaEventsTimelineScreenViewModel.swift
  ElementX/Sources/Screens/MediaEventsTimelineScreen/View/MediaEventsTimelineScreen.swift
  ElementX/Sources/Screens/PinnedEventsTimelineScreen/PinnedEventsTimelineScreenCoordinator.swift
  ElementX/Sources/Screens/RoomScreen/RoomScreenCoordinator.swift
  ElementX/Sources/Screens/ThreadTimelineScreen/ThreadTimelineScreenCoordinator.swift
  ElementX/Sources/Screens/Timeline/TimelineModels.swift
  ElementX/Sources/Screens/Timeline/TimelineViewModel.swift
  ElementX/Sources/Screens/Timeline/View/Style/AccessibleLongPress.swift
Labels: pr-feature

#4472 Use the SDK's offline detection everywhere (except for restarting the sync loop).
  ElementX/Resources/Localizations/en.lproj/Localizable.strings
  ElementX/Sources/Application/AppCoordinator.swift
  ElementX/Sources/FlowCoordinators/RoomFlowCoordinator.swift
  ElementX/Sources/FlowCoordinators/UserSessionFlowCoordinator.swift
  ElementX/Sources/Generated/Strings.swift
  ElementX/Sources/Mocks/ClientProxyMock.swift
  ElementX/Sources/Mocks/Generated/GeneratedMocks.swift
  ElementX/Sources/Other/NetworkMonitor/NetworkMonitor.swift
  ElementX/Sources/Screens/RoomDetailsScreen/RoomDetailsScreenCoordinator.swift
  ElementX/Sources/Screens/RoomDetailsScreen/RoomDetailsScreenViewModel.swift
  ElementX/Sources/Screens/RoomDetailsScreen/View/RoomDetailsScreen.swift
  ElementX/Sources/Screens/RoomScreen/RoomScreenCoordinator.swift
  ElementX/Sources/Screens/RoomScreen/RoomScreenViewModel.swift
  ElementX/Sources/Screens/SecureBackup/SecureBackupLogoutConfirmationScreen/SecureBackupLogoutConfirmationScreenCoordinator.swift
  ElementX/Sources/Screens/SecureBackup/SecureBackupLogoutConfirmationScreen/SecureBackupLogoutConfirmationScreenViewModel.swift
  ElementX/Sources/Screens/SecureBackup/SecureBackupLogoutConfirmationScreen/View/SecureBackupLogoutConfirmationScreen.swift
  ElementX/Sources/Services/Client/ClientProxy.swift
  ElementX/Sources/Services/Client/ClientProxyProtocol.swift
  ElementX/Sources/Services/Media/Provider/MediaProvider.swift
  ElementX/Sources/Services/UserSession/UserSessionStore.swift
  NSE/Sources/NSEUserSession.swift
  UnitTests/Sources/MediaProvider/MediaProviderTests.swift
  UnitTests/Sources/RoomDetailsScreenViewModelTests.swift
  UnitTests/Sources/RoomScreenViewModelTests.swift
  UnitTests/Sources/SecureBackupLogoutConfirmationScreenViewModelTests.swift
  UnitTests/Sources/UserSessionFlowCoordinatorTests.swift
Labels: pr-bugfix

#4483 Revert weak media provider
  ElementX/Sources/Mocks/ClientProxyMock.swift
  ElementX/Sources/Mocks/Generated/GeneratedMocks.swift
  ElementX/Sources/Mocks/MediaProviderMock.swift
  ElementX/Sources/Mocks/UserSessionMock.swift
  ElementX/Sources/Other/Pills/PillView.swift
  ElementX/Sources/Other/SwiftUI/Animation/ShimmerModifier.swift
  ElementX/Sources/Other/SwiftUI/ViewModel/StateStoreViewModel.swift
  ElementX/Sources/Other/SwiftUI/ViewModel/StateStoreViewModelV2.swift
  ElementX/Sources/Other/SwiftUI/Views/AvatarHeaderView.swift
  ElementX/Sources/Other/SwiftUI/Views/LoadableImage.swift
  ElementX/Sources/Other/SwiftUI/Views/RoomAvatarImage.swift
  ElementX/Sources/Other/SwiftUI/Views/RoomHeaderView.swift
  ElementX/Sources/Other/SwiftUI/Views/RoomInviterLabel.swift
  ElementX/Sources/Other/SwiftUI/Views/StackedAvatarsView.swift
  ElementX/Sources/Other/SwiftUI/Views/UserProfileListRow.swift
  ElementX/Sources/Screens/FilePreviewScreen/TimelineMediaPreviewModifier.swift
  ElementX/Sources/Screens/FilePreviewScreen/View/TimelineMediaPreviewDetailsView.swift
  ElementX/Sources/Screens/FilePreviewScreen/View/TimelineMediaPreviewRedactConfirmationView.swift
  ElementX/Sources/Screens/GlobalSearchScreen/View/GlobalSearchScreen.swift
  ElementX/Sources/Screens/GlobalSearchScreen/View/GlobalSearchScreenCell.swift
  ElementX/Sources/Screens/HomeScreen/View/HomeScreenRoomCell.swift
  ElementX/Sources/Screens/InviteUsersScreen/View/InviteUsersScreenSelectedItem.swift
  ElementX/Sources/Screens/KnockRequestsListScreen/View/KnockRequestsListScreen.swift
  ElementX/Sources/Screens/ManageRoomMemberSheet/View/ManageRoomMemberSheetView.swift
  ElementX/Sources/Screens/MediaEventsTimelineScreen/View/MediaEventsTimelineScreen.swift
  ElementX/Sources/Screens/Onboarding/SessionVerificationScreen/View/SessionVerificationRequestDetailsView.swift
  ElementX/Sources/Screens/Onboarding/SessionVerificationScreen/View/SessionVerificationScreen.swift
  ElementX/Sources/Screens/RoomChangeRolesScreen/View/RoomChangeRolesScreen.swift
  ElementX/Sources/Screens/RoomChangeRolesScreen/View/RoomChangeRolesScreenRow.swift
  ElementX/Sources/Screens/RoomChangeRolesScreen/View/RoomChangeRolesScreenSelectedItem.swift
  ElementX/Sources/Screens/RoomDirectorySearchScreen/View/RoomDirectoryCell.swift
  ElementX/Sources/Screens/RoomScreen/ComposerToolbar/View/CompletionSuggestionView.swift
  ElementX/Sources/Screens/RoomScreen/ComposerToolbar/View/ComposerToolbar.swift
  ElementX/Sources/Screens/RoomScreen/ComposerToolbar/View/MentionSuggestionItemView.swift
  ElementX/Sources/Screens/RoomScreen/ComposerToolbar/View/RoomAttachmentPicker.swift
  ElementX/Sources/Screens/RoomScreen/View/RoomScreenFooterView.swift
  ElementX/Sources/Screens/Spaces/Common/SpaceHeaderView.swift
  ElementX/Sources/Screens/Spaces/Common/SpaceRoomCell.swift
  ElementX/Sources/Screens/Spaces/SpaceScreen/View/SpaceScreen.swift
  ElementX/Sources/Screens/Timeline/View/ReadReceipts/ReadReceiptCell.swift
  ElementX/Sources/Screens/Timeline/View/Supplementary/ReactionsSummaryView.swift
  ElementX/Sources/Services/Client/ClientProxy.swift
  ElementX/Sources/Services/Client/ClientProxyProtocol.swift
  ElementX/Sources/Services/Media/Provider/MediaLoader.swift
  ElementX/Sources/Services/Media/Provider/MediaLoaderProtocol.swift
  ElementX/Sources/Services/Media/Provider/MediaProvider.swift
  ElementX/Sources/Services/Media/Provider/MediaProviderProtocol.swift
  ElementX/Sources/Services/UserSession/UserSessionStore.swift
  ElementX/Sources/UITests/UITestsAppCoordinator.swift
  UnitTests/Sources/ComposerToolbarViewModelTests.swift
  UnitTests/Sources/GlobalSearchScreenViewModelTests.swift
  UnitTests/Sources/KnockRequestsListScreenViewModelTests.swift
  UnitTests/Sources/ManageRoomMemberSheetViewModelTests.swift
  UnitTests/Sources/RoomChangeRolesScreenViewModelTests.swift
  UnitTests/Sources/SessionVerificationViewModelTests.swift
  UnitTests/Sources/SpaceScreenViewModelTests.swift
  UnitTests/Sources/TimelineMediaPreviewViewModelTests.swift
  UnitTests/Sources/VoiceMessageMediaManagerTests.swift
Labels: pr-misc

#4499 Element Call: Send rtc.decline event when incoming call is declined
  ElementX/Sources/Mocks/Generated/GeneratedMocks.swift
  ElementX/Sources/Services/ElementCall/ElementCallService.swift
  ElementX/Sources/Services/ElementCall/ElementCallServiceConstants.swift
  ElementX/Sources/Services/Room/JoinedRoomProxy.swift
  ElementX/Sources/Services/Room/RoomProxyProtocol.swift
  NSE/Sources/NotificationHandler.swift
Labels: pr-feature

#4517 Update the SDK.
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Sources/Mocks/Generated/SDKGeneratedMocks.swift
  ElementX/Sources/Services/Room/RoomSummary/RoomEventStringBuilder.swift
  ElementX/Sources/Services/Timeline/TimelineItems/RoomTimelineItemFactory.swift
  NSE/Sources/NotificationContentBuilder.swift
  NSE/Sources/NotificationHandler.swift
  project.yml
Labels: pr-misc

#4522 Update the SDK and Element Call.
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Sources/Screens/CallScreen/CallScreenModels.swift
  ElementX/Sources/Screens/CallScreen/CallScreenViewModel.swift
  ElementX/Sources/Screens/CallScreen/View/CallScreen.swift
  ElementX/Sources/Services/ElementCall/ElementCallWidgetDriver.swift
  project.yml
Labels: pr-misc

#4520 Implement link previews for text messages using Apple's LinkPreview framework
  ElementX.xcodeproj/project.pbxproj
  ElementX/Sources/Application/AppCoordinator.swift
  ElementX/Sources/Application/FlowCoordinatorProtocol.swift
  ElementX/Sources/Application/Settings/AppSettings.swift
  ElementX/Sources/FlowCoordinators/MediaEventsTimelineFlowCoordinator.swift
  ElementX/Sources/FlowCoordinators/PinnedEventsTimelineFlowCoordinator.swift
  ElementX/Sources/FlowCoordinators/RoomFlowCoordinator.swift
  ElementX/Sources/Other/SwiftUI/Views/LinkPreviewView.swift
  ElementX/Sources/Screens/MediaEventsTimelineScreen/MediaEventsTimelineScreenCoordinator.swift
  ElementX/Sources/Screens/MediaEventsTimelineScreen/View/MediaEventsTimelineScreen.swift
  ElementX/Sources/Screens/PinnedEventsTimelineScreen/PinnedEventsTimelineScreenCoordinator.swift
  ElementX/Sources/Screens/PinnedEventsTimelineScreen/View/PinnedEventsTimelineScreen.swift
  ElementX/Sources/Screens/RoomScreen/RoomScreenCoordinator.swift
  ElementX/Sources/Screens/RoomScreen/View/RoomScreen.swift
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/DeveloperOptionsScreenModels.swift
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/View/DeveloperOptionsScreen.swift
  ElementX/Sources/Screens/ThreadTimelineScreen/ThreadTimelineScreenCoordinator.swift
  ElementX/Sources/Screens/Timeline/TimelineInteractionHandler.swift
  ElementX/Sources/Screens/Timeline/TimelineModels.swift
  ElementX/Sources/Screens/Timeline/TimelineViewModel.swift
  ElementX/Sources/Screens/Timeline/View/ReadReceipts/ReadReceiptsSummaryView.swift
  ElementX/Sources/Screens/Timeline/View/Style/TimelineItemBubbledStylerView.swift
  ElementX/Sources/Screens/Timeline/View/Supplementary/TimelineReadReceiptsView.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/HighlightedTimelineItemModifier.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/TextRoomTimelineView.swift
  ElementX/Sources/Screens/Timeline/View/TimelineView.swift
  ElementX/Sources/Services/LinkMetadata/LinkMetadataProvider.swift
  ElementX/Sources/Services/LinkMetadata/LinkMetadataProviderProtocol.swift
  ElementX/Sources/Services/Timeline/TimelineItems/Items/Messages/TextRoomTimelineItem.swift
  ElementX/Sources/Services/Timeline/TimelineItems/RoomTimelineItemView.swift
  ElementX/Sources/UITests/UITestsAppCoordinator.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/linkPreviewView.iPad-en-GB-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/linkPreviewView.iPad-pseudo-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/linkPreviewView.iPhone-16-en-GB-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/linkPreviewView.iPhone-16-pseudo-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/textRoomTimelineView.Bubble-RTL-iPad-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/textRoomTimelineView.Bubble-RTL-iPad-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/textRoomTimelineView.Bubble-RTL-iPhone-16-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/textRoomTimelineView.Bubble-RTL-iPhone-16-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/textRoomTimelineView.Bubble-iPad-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/textRoomTimelineView.Bubble-iPad-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/textRoomTimelineView.Bubble-iPhone-16-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/textRoomTimelineView.Bubble-iPhone-16-pseudo.png
  UnitTests/Sources/ChatsFlowCoordinatorTests.swift
  UnitTests/Sources/PillContextTests.swift
  UnitTests/Sources/RoomFlowCoordinatorTests.swift
  UnitTests/Sources/TimelineViewModelTests.swift
  UnitTests/Sources/UserSessionFlowCoordinatorTests.swift
Labels: pr-wip

#4543 Prevent the gradient background from being incorrectly rendered everywhere the placeholder screen is used
  ElementX/Sources/FlowCoordinators/AppLockFlowCoordinator.swift
  ElementX/Sources/Screens/Other/PlaceholderScreenCoordinator.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/placeholderScreen.With-chrome-and-background-iPad-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/placeholderScreen.With-chrome-and-background-iPad-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/placeholderScreen.With-chrome-and-background-iPhone-16-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/placeholderScreen.With-chrome-and-background-iPhone-16-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/placeholderScreen.With-chrome-and-no-background-iPad-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/placeholderScreen.With-chrome-and-no-background-iPad-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/placeholderScreen.With-chrome-and-no-background-iPhone-16-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/placeholderScreen.With-chrome-and-no-background-iPhone-16-pseudo.png
Labels: pr-bugfix

#4544 Add some new space properties.
  ElementX/Resources/Localizations/en.lproj/Localizable.strings
  ElementX/Sources/Generated/Strings.swift
  ElementX/Sources/Mocks/Generated/GeneratedMocks.swift
  ElementX/Sources/Mocks/SpaceRoomProxyMock.swift
  ElementX/Sources/Mocks/SpaceServiceProxyMock.swift
  ElementX/Sources/Screens/JoinRoomScreen/JoinRoomScreenViewModel.swift
  ElementX/Sources/Screens/Spaces/Common/SpaceHeaderView.swift
  ElementX/Sources/Screens/Spaces/Common/SpaceRoomCell.swift
  ElementX/Sources/Screens/Spaces/SpaceListScreen/SpaceListScreenViewModel.swift
  ElementX/Sources/Screens/Spaces/SpaceScreen/SpaceScreenViewModel.swift
  ElementX/Sources/Screens/Spaces/SpaceScreen/View/SpaceScreen.swift
  ElementX/Sources/Services/Spaces/SpaceRoomListProxy.swift
  ElementX/Sources/Services/Spaces/SpaceRoomProxy.swift
  ElementX/Sources/Services/Spaces/SpaceRoomProxyProtocol.swift
  ElementX/Sources/Services/Spaces/SpaceServiceProxy.swift
  ElementX/Sources/Services/Spaces/SpaceServiceProxyProtocol.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/spaceHeaderView.iPad-en-GB-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/spaceHeaderView.iPad-pseudo-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/spaceHeaderView.iPhone-16-en-GB-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/spaceHeaderView.iPhone-16-pseudo-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/spaceRoomCell.iPad-en-GB-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/spaceRoomCell.iPad-pseudo-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/spaceRoomCell.iPhone-16-en-GB-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/spaceRoomCell.iPhone-16-pseudo-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/spaceScreen.iPad-en-GB-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/spaceScreen.iPad-pseudo-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/spaceScreen.iPhone-16-en-GB-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/spaceScreen.iPhone-16-pseudo-0.png
  UnitTests/Sources/SpaceListScreenViewModelTests.swift
  UnitTests/Sources/SpaceScreenViewModelTests.swift
Labels: pr-wip

#4547 Have the nightly label actually fit the icon
  Tools/Sources/Commands/AppIconBanner.swift
Labels: pr-build

#4552 Switch all workflow runners back to macos-15 in hope that it will require less ram and won't time out
  .github/workflows/accessibility_tests.yml
  .github/workflows/automatic-calendar-version.yml
  .github/workflows/danger.yml
  .github/workflows/integration-tests.yml
  .github/workflows/translations-pr.yml
  .github/workflows/ui_tests.yml
  .github/workflows/unit_tests.yml
  .github/workflows/unit_tests_enterprise.yml
Labels: pr-build

#4555 Update acknowledgments with resolved names.
  ElementX/SupportingFiles/Settings.bundle/Acknowledgements.plist
  ElementX/SupportingFiles/Settings.bundle/Packages/AnalyticsEvents.plist
  ElementX/SupportingFiles/Settings.bundle/Packages/Emojibase.plist
  ElementX/SupportingFiles/Settings.bundle/Packages/MapLibre GL Native.plist
  ElementX/SupportingFiles/Settings.bundle/Packages/MatrixRustSDK.plist
  ElementX/SupportingFiles/Settings.bundle/Packages/Mutex.plist
  ElementX/SupportingFiles/Settings.bundle/Packages/PostHog.plist
  ElementX/SupportingFiles/Settings.bundle/Packages/Sentry.plist
  ElementX/SupportingFiles/Settings.bundle/Packages/SwiftOGG.plist
  ElementX/SupportingFiles/Settings.bundle/Packages/YbridOgg.plist
  ElementX/SupportingFiles/Settings.bundle/Packages/YbridOpus.plist
Labels: pr-misc

#4553 Update the strings for the device verification flow
  ElementX/Sources/Screens/Onboarding/SessionVerificationScreen/SessionVerificationScreenModels.swift
  ElementX/Sources/Screens/Onboarding/SessionVerificationScreen/View/SessionVerificationScreen.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/sessionVerification.Accepting-Challenge-iPad-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/sessionVerification.Accepting-Challenge-iPad-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/sessionVerification.Accepting-Challenge-iPhone-16-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/sessionVerification.Accepting-Challenge-iPhone-16-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/sessionVerification.Accepting-Verification-Request-iPad-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/sessionVerification.Accepting-Verification-Request-iPad-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/sessionVerification.Accepting-Verification-Request-iPhone-16-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/sessionVerification.Accepting-Verification-Request-iPhone-16-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/sessionVerification.Declining-Challenge-iPad-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/sessionVerification.Declining-Challenge-iPad-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/sessionVerification.Declining-Challenge-iPhone-16-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/sessionVerification.Declining-Challenge-iPhone-16-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/sessionVerification.Initial-Device-Responder-iPad-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/sessionVerification.Initial-Device-Responder-iPad-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/sessionVerification.Initial-Device-Responder-iPhone-16-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/sessionVerification.Initial-Device-Responder-iPhone-16-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/sessionVerification.Initial-User-Responder-iPad-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/sessionVerification.Initial-User-Responder-iPad-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/sessionVerification.Initial-User-Responder-iPhone-16-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/sessionVerification.Initial-User-Responder-iPhone-16-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/sessionVerification.Requesting-Verification-iPad-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/sessionVerification.Requesting-Verification-iPad-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/sessionVerification.Requesting-Verification-iPhone-16-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/sessionVerification.Requesting-Verification-iPhone-16-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/sessionVerification.SAS-Verification-started-iPad-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/sessionVerification.SAS-Verification-started-iPad-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/sessionVerification.SAS-Verification-started-iPhone-16-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/sessionVerification.SAS-Verification-started-iPhone-16-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/sessionVerification.Showing-Challenge-iPad-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/sessionVerification.Showing-Challenge-iPad-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/sessionVerification.Showing-Challenge-iPhone-16-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/sessionVerification.Showing-Challenge-iPhone-16-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/sessionVerification.Starting-SAS-Verification-iPad-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/sessionVerification.Starting-SAS-Verification-iPad-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/sessionVerification.Starting-SAS-Verification-iPhone-16-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/sessionVerification.Starting-SAS-Verification-iPhone-16-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/sessionVerification.Verified-iPad-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/sessionVerification.Verified-iPad-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/sessionVerification.Verified-iPhone-16-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/sessionVerification.Verified-iPhone-16-pseudo.png
  UITests/Sources/__Snapshots__/Application/sessionVerification.testChallengeDoesNotMatch-iPad-26-0-en-GB-1.png
  UITests/Sources/__Snapshots__/Application/sessionVerification.testChallengeDoesNotMatch-iPad-26-0-en-GB-3.png
  UITests/Sources/__Snapshots__/Application/sessionVerification.testChallengeDoesNotMatch-iPad-26-0-en-GB-4.png
  UITests/Sources/__Snapshots__/Application/sessionVerification.testChallengeDoesNotMatch-iPhone-26-0-en-GB-1.png
  UITests/Sources/__Snapshots__/Application/sessionVerification.testChallengeDoesNotMatch-iPhone-26-0-en-GB-3.png
  UITests/Sources/__Snapshots__/Application/sessionVerification.testChallengeMatches-iPad-26-0-en-GB-1.png
  UITests/Sources/__Snapshots__/Application/sessionVerification.testChallengeMatches-iPhone-26-0-en-GB-1.png
  UITests/Sources/__Snapshots__/Application/sessionVerification.testChallengeMatches-iPhone-26-0-en-GB-3.png
  UITests/Sources/__Snapshots__/Application/sessionVerification.testChallengeMatches-iPhone-26-0-en-GB-6.png
  UITests/Sources/__Snapshots__/Application/sessionVerification.testSessionVerificationCancelation-iPhone-26-0-en-GB-1.png
  UITests/Sources/__Snapshots__/Application/sessionVerification.testSessionVerificationCancelation-iPhone-26-0-en-GB-3.png
Labels: pr-change

#4554 Accept space invites from a home screen cell.
  ElementX/Sources/FlowCoordinators/ChatsFlowCoordinator.swift
  ElementX/Sources/FlowCoordinators/ChatsFlowCoordinatorStateMachine.swift
  ElementX/Sources/Mocks/InvitedRoomProxyMock.swift
  ElementX/Sources/Mocks/RoomSummaryProviderMock.swift
  ElementX/Sources/Screens/HomeScreen/HomeScreenCoordinator.swift
  ElementX/Sources/Screens/HomeScreen/HomeScreenModels.swift
  ElementX/Sources/Screens/HomeScreen/HomeScreenViewModel.swift
  UnitTests/Sources/ChatsFlowCoordinatorTests.swift
  UnitTests/Sources/HomeScreenViewModelTests.swift
  UnitTests/Sources/UserSessionFlowCoordinatorTests.swift
Labels: pr-wip
