Repository element-hq/element-x-ios, pull requests merged in 2025-04, with the labels that each got.

#3964 Bump the RustSDK to v25.03.31
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Sources/Mocks/Generated/GeneratedMocks.swift
  ElementX/Sources/Mocks/Generated/SDKGeneratedMocks.swift
  ElementX/Sources/Screens/RoomMemberDetailsScreen/RoomMemberDetailsScreenViewModel.swift
  ElementX/Sources/Screens/RoomScreen/RoomScreenViewModel.swift
  ElementX/Sources/Screens/StartChatScreen/StartChatScreenViewModel.swift
  ElementX/Sources/Screens/UserProfileScreen/UserProfileScreenViewModel.swift
  ElementX/Sources/Services/Client/ClientProxy.swift
  ElementX/Sources/Services/Client/ClientProxyProtocol.swift
  ElementX/Sources/Services/Room/JoinedRoomProxy.swift
  ElementX/Sources/Services/Timeline/TimelineController/TimelineController.swift
  ElementX/Sources/Services/Timeline/TimelineProvider.swift
  ElementX/Sources/Services/Timeline/TimelineProxy.swift
  ElementX/Sources/Services/Timeline/TimelineProxyProtocol.swift
  project.yml
Labels: pr-misc

#3960 Bring back the background refresh stop sync crash fix
  ElementX/Sources/Application/AppCoordinator.swift
Labels: pr-bugfix

#3962 Updated EC to 0.9.0
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  project.yml
Labels: pr-misc

#3966 Make the secrets optional.
  .gitignore
  .swiftlint.yml
  ElementX/Sources/Application/AppSettings.swift
  ElementX/Sources/Screens/CallScreen/CallScreenViewModel.swift
  Secrets/Secrets.pkl
  Secrets/Secrets.swift
  ci_scripts/ci_common.sh
  fastlane/Fastfile
Labels: pr-build

#3967 Add alerts with reason for kick and ban
  ElementX/Resources/Localizations/en-US.lproj/Localizable.strings
  ElementX/Resources/Localizations/en.lproj/Localizable.strings
  ElementX/Sources/Generated/Strings.swift
  ElementX/Sources/Mocks/Generated/GeneratedMocks.swift
  ElementX/Sources/Mocks/JoinedRoomProxyMock.swift
  ElementX/Sources/Screens/RoomMemberListScreen/RoomMembersListScreenModels.swift
  ElementX/Sources/Screens/RoomMemberListScreen/RoomMembersListScreenViewModel.swift
  ElementX/Sources/Screens/RoomMemberListScreen/View/RoomMembersListManageMemberSheet.swift
  ElementX/Sources/Services/Room/JoinedRoomProxy.swift
  ElementX/Sources/Services/Room/RoomProxyProtocol.swift
  UnitTests/Sources/RoomMembersListScreenViewModelTests.swift
Labels: pr-feature

#3978 Add the build number to rageshakes.
  ElementX/Sources/Services/BugReport/BugReportService.swift
Labels: pr-misc

#3977 Update the app icon.
  ElementX/Resources/Assets.xcassets/AppIcon.appiconset/AppIcon.png
Labels: pr-change

#3985 Fix UI test toggle tapping after compound accessibility change.
  UITests/Sources/EncryptionSettingsTests.swift
Labels: pr-misc

#3971 feat: report a room
  ElementX.xcodeproj/project.pbxproj
  ElementX/Sources/Application/AppSettings.swift
  ElementX/Sources/FlowCoordinators/RoomFlowCoordinator.swift
  ElementX/Sources/FlowCoordinators/UserSessionFlowCoordinator.swift
  ElementX/Sources/FlowCoordinators/UserSessionFlowCoordinatorStateMachine.swift
  ElementX/Sources/Mocks/Generated/GeneratedMocks.swift
  ElementX/Sources/Screens/HomeScreen/HomeScreenCoordinator.swift
  ElementX/Sources/Screens/HomeScreen/HomeScreenModels.swift
  ElementX/Sources/Screens/HomeScreen/HomeScreenViewModel.swift
  ElementX/Sources/Screens/HomeScreen/View/HomeScreenRoomList.swift
  ElementX/Sources/Screens/ReportRoomScreen/ReportRoomScreenCoordinator.swift
  ElementX/Sources/Screens/ReportRoomScreen/ReportRoomScreenModels.swift
  ElementX/Sources/Screens/ReportRoomScreen/ReportRoomScreenViewModel.swift
  ElementX/Sources/Screens/ReportRoomScreen/ReportRoomScreenViewModelProtocol.swift
  ElementX/Sources/Screens/ReportRoomScreen/View/ReportRoomScreen.swift
  ElementX/Sources/Screens/RoomDetailsScreen/RoomDetailsScreenCoordinator.swift
  ElementX/Sources/Screens/RoomDetailsScreen/RoomDetailsScreenModels.swift
  ElementX/Sources/Screens/RoomDetailsScreen/RoomDetailsScreenViewModel.swift
  ElementX/Sources/Screens/RoomDetailsScreen/View/RoomDetailsScreen.swift
  ElementX/Sources/Screens/RoomMemberListScreen/RoomMembersListScreenViewModel.swift
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/DeveloperOptionsScreenModels.swift
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/View/DeveloperOptionsScreen.swift
  ElementX/Sources/Services/Room/JoinedRoomProxy.swift
  ElementX/Sources/Services/Room/RoomProxyProtocol.swift
  PreviewTests/Sources/GeneratedPreviewTests.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/reportRoomScreen.iPad-en-GB-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/reportRoomScreen.iPad-pseudo-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/reportRoomScreen.iPhone-16-en-GB-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/reportRoomScreen.iPhone-16-pseudo-0.png
  UnitTests/Sources/ReportRoomScreenViewModelTests.swift
  UnitTests/Sources/UserSessionFlowCoordinatorTests.swift
Labels: pr-wip

#3989 feat: decline and block screen
  ElementX.xcodeproj/project.pbxproj
  ElementX/Sources/Application/AppSettings.swift
  ElementX/Sources/FlowCoordinators/RoomFlowCoordinator.swift
  ElementX/Sources/FlowCoordinators/UserSessionFlowCoordinator.swift
  ElementX/Sources/FlowCoordinators/UserSessionFlowCoordinatorStateMachine.swift
  ElementX/Sources/Mocks/Generated/GeneratedMocks.swift
  ElementX/Sources/Screens/DeclineAndBlockScreen/DeclineAndBlockScreenCoordinator.swift
  ElementX/Sources/Screens/DeclineAndBlockScreen/DeclineAndBlockScreenModels.swift
  ElementX/Sources/Screens/DeclineAndBlockScreen/DeclineAndBlockScreenViewModel.swift
  ElementX/Sources/Screens/DeclineAndBlockScreen/DeclineAndBlockScreenViewModelProtocol.swift
  ElementX/Sources/Screens/DeclineAndBlockScreen/View/DeclineAndBlockScreen.swift
  ElementX/Sources/Screens/HomeScreen/HomeScreenCoordinator.swift
  ElementX/Sources/Screens/HomeScreen/HomeScreenModels.swift
  ElementX/Sources/Screens/HomeScreen/HomeScreenViewModel.swift
  ElementX/Sources/Screens/JoinRoomScreen/JoinRoomScreenCoordinator.swift
  ElementX/Sources/Screens/JoinRoomScreen/JoinRoomScreenModels.swift
  ElementX/Sources/Screens/JoinRoomScreen/JoinRoomScreenViewModel.swift
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/DeveloperOptionsScreenModels.swift
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/View/DeveloperOptionsScreen.swift
  ElementX/Sources/Services/Client/ClientProxy.swift
  ElementX/Sources/Services/Client/ClientProxyProtocol.swift
  PreviewTests/Sources/GeneratedPreviewTests.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/declineAndBlockScreen.Default-iPad-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/declineAndBlockScreen.Default-iPad-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/declineAndBlockScreen.Default-iPhone-16-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/declineAndBlockScreen.Default-iPhone-16-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/declineAndBlockScreen.Report-room-selected-iPad-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/declineAndBlockScreen.Report-room-selected-iPad-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/declineAndBlockScreen.Report-room-selected-iPhone-16-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/declineAndBlockScreen.Report-room-selected-iPhone-16-pseudo.png
  UnitTests/Sources/DeclineAndBlockScreenViewModelTests.swift
  UnitTests/Sources/HomeScreenViewModelTests.swift
Labels: pr-wip

#3994 Prepare for version 25.04.x.
  ElementX.xcodeproj/project.pbxproj
  project.yml
Labels: pr-build

#3996 Fix the post-release workflow.
  .github/workflows/post-release.yml
Labels: pr-build

#3997 Re-write integration test login for OIDC.
  IntegrationTests/Sources/Common.swift
Labels: pr-misc

#3995 refactor: manage member sheet in timeline
  ElementX.xcodeproj/project.pbxproj
  ElementX/Resources/Localizations/en-US.lproj/Localizable.strings
  ElementX/Resources/Localizations/en.lproj/Localizable.strings
  ElementX/Sources/Generated/Strings.swift
  ElementX/Sources/Screens/ManageRoomMemberSheet/ManageRoomMemberSheetModels.swift
  ElementX/Sources/Screens/ManageRoomMemberSheet/ManageRoomMemberSheetViewModel.swift
  ElementX/Sources/Screens/ManageRoomMemberSheet/ManageRoomMemberSheetViewModelProtocol.swift
  ElementX/Sources/Screens/ManageRoomMemberSheet/View/ManageRoomMemberSheetView.swift
  ElementX/Sources/Screens/MediaEventsTimelineScreen/MediaEventsTimelineScreenViewModel.swift
  ElementX/Sources/Screens/PinnedEventsTimelineScreen/PinnedEventsTimelineScreenCoordinator.swift
  ElementX/Sources/Screens/PinnedEventsTimelineScreen/View/PinnedEventsTimelineScreen.swift
  ElementX/Sources/Screens/RoomMemberListScreen/RoomMembersListScreenModels.swift
  ElementX/Sources/Screens/RoomMemberListScreen/RoomMembersListScreenViewModel.swift
  ElementX/Sources/Screens/RoomMemberListScreen/View/RoomMembersListManageMemberSheet.swift
  ElementX/Sources/Screens/RoomMemberListScreen/View/RoomMembersListScreen.swift
  ElementX/Sources/Screens/RoomScreen/RoomScreenCoordinator.swift
  ElementX/Sources/Screens/RoomScreen/View/RoomScreen.swift
  ElementX/Sources/Screens/Timeline/TimelineModels.swift
  ElementX/Sources/Screens/Timeline/TimelineViewModel.swift
  ElementX/Sources/Services/Room/RoomMember/RoomMemberDetails.swift
  PreviewTests/Sources/GeneratedPreviewTests.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/manageRoomMemberSheetView.All-Actions-iPad-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/manageRoomMemberSheetView.All-Actions-iPad-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/manageRoomMemberSheetView.All-Actions-iPhone-16-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/manageRoomMemberSheetView.All-Actions-iPhone-16-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/manageRoomMemberSheetView.Ban-Only-iPad-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/manageRoomMemberSheetView.Ban-Only-iPad-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/manageRoomMemberSheetView.Ban-Only-iPhone-16-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/manageRoomMemberSheetView.Ban-Only-iPhone-16-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/manageRoomMemberSheetView.Kick-Only-iPad-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/manageRoomMemberSheetView.Kick-Only-iPad-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/manageRoomMemberSheetView.Kick-Only-iPhone-16-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/manageRoomMemberSheetView.Kick-Only-iPhone-16-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/roomMembersListManageMemberSheet.Banned-iPad-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/roomMembersListManageMemberSheet.Banned-iPad-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/roomMembersListManageMemberSheet.Banned-iPhone-16-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/roomMembersListManageMemberSheet.Banned-iPhone-16-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/roomMembersListManageMemberSheet.Joined-iPad-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/roomMembersListManageMemberSheet.Joined-iPad-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/roomMembersListManageMemberSheet.Joined-iPhone-16-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/roomMembersListManageMemberSheet.Joined-iPhone-16-pseudo.png
  UnitTests/Sources/ManageRoomMemberSheetViewModelTests.swift
  UnitTests/Sources/RoomMembersListScreenViewModelTests.swift
  UnitTests/Sources/TimelineViewModelTests.swift
Labels: pr-change

#4001 Setup the client media retention policy
  ElementX/Sources/Services/Client/ClientProxy.swift
Labels: pr-feature

#4002 Only use the appGroupTemporaryDirectory to access a file from the share extension.
  ElementX/Sources/Application/AppCoordinator.swift
  ElementX/Sources/Other/Extensions/FileManager.swift
  ElementX/Sources/Other/Extensions/NSItemProvider.swift
  ElementX/Sources/Other/Extensions/URL.swift
  ElementX/Sources/ShareExtension/ShareExtensionModels.swift
  ShareExtension/Sources/ShareExtensionViewController.swift
Labels: pr-misc

#4005 Manually enable the event cache
  ElementX/Sources/Other/Extensions/ClientBuilder.swift
Labels: pr-bugfix

#4000 Bump the SDK and adopt the new MsgLike timeline item types
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Sources/Mocks/SDK/EventTimelineItem.swift
  ElementX/Sources/Screens/FilePreviewScreen/TimelineMediaPreviewModifier.swift
  ElementX/Sources/Screens/FilePreviewScreen/View/TimelineMediaPreviewDetailsView.swift
  ElementX/Sources/Screens/FilePreviewScreen/View/TimelineMediaPreviewRedactConfirmationView.swift
  ElementX/Sources/Screens/MediaEventsTimelineScreen/View/TimelineViews/AudioFileEventsTimelineView.swift
  ElementX/Sources/Screens/MediaEventsTimelineScreen/View/TimelineViews/FileMediaEventsTimelineView.swift
  ElementX/Sources/Screens/MediaEventsTimelineScreen/View/TimelineViews/ImageMediaEventsTimelineView.swift
  ElementX/Sources/Screens/MediaEventsTimelineScreen/View/TimelineViews/VideoMediaEventsTimelineView.swift
  ElementX/Sources/Screens/MediaEventsTimelineScreen/View/TimelineViews/VoiceMessageMediaEventsTimelineView.swift
  ElementX/Sources/Screens/Timeline/TimelineInteractionHandler.swift
  ElementX/Sources/Screens/Timeline/View/ItemMenu/TimelineItemMenuActionProvider.swift
  ElementX/Sources/Screens/Timeline/View/Style/SwipeToReplyView.swift
  ElementX/Sources/Screens/Timeline/View/Style/TimelineItemBubbledStylerView.swift
  ElementX/Sources/Screens/Timeline/View/Style/TimelineStyler.swift
  ElementX/Sources/Screens/Timeline/View/Supplementary/TimelineReadReceiptsView.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/AudioRoomTimelineView.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/EmoteRoomTimelineView.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/FileRoomTimelineView.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/ImageRoomTimelineView.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/LocationRoomTimelineView.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/NoticeRoomTimelineView.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/ReadMarkerRoomTimelineView.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/TextRoomTimelineView.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/VideoRoomTimelineView.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/VoiceMessageRoomTimelineView.swift
  ElementX/Sources/Services/Room/RoomSummary/RoomEventStringBuilder.swift
  ElementX/Sources/Services/Timeline/Fixtures/RoomTimelineItemFixtures.swift
  ElementX/Sources/Services/Timeline/TimelineController/TimelineController.swift
  ElementX/Sources/Services/Timeline/TimelineItemContent/RoomTimelineItemProperties.swift
  ElementX/Sources/Services/Timeline/TimelineItemProxy.swift
  ElementX/Sources/Services/Timeline/TimelineItems/EventBasedMessageTimelineItemProtocol.swift
  ElementX/Sources/Services/Timeline/TimelineItems/Items/Messages/AudioRoomTimelineItem.swift
  ElementX/Sources/Services/Timeline/TimelineItems/Items/Messages/EmoteRoomTimelineItem.swift
  ElementX/Sources/Services/Timeline/TimelineItems/Items/Messages/FileRoomTimelineItem.swift
  ElementX/Sources/Services/Timeline/TimelineItems/Items/Messages/ImageRoomTimelineItem.swift
  ElementX/Sources/Services/Timeline/TimelineItems/Items/Messages/LocationRoomTimelineItem.swift
  ElementX/Sources/Services/Timeline/TimelineItems/Items/Messages/NoticeRoomTimelineItem.swift
  ElementX/Sources/Services/Timeline/TimelineItems/Items/Messages/TextRoomTimelineItem.swift
  ElementX/Sources/Services/Timeline/TimelineItems/Items/Messages/VideoRoomTimelineItem.swift
  ElementX/Sources/Services/Timeline/TimelineItems/Items/Messages/VoiceMessageRoomTimelineItem.swift
  ElementX/Sources/Services/Timeline/TimelineItems/RoomTimelineItemFactory.swift
  ElementX/Sources/Services/Timeline/TimelineProxy.swift
  UnitTests/Sources/LoggingTests.swift
  UnitTests/Sources/TextBasedRoomTimelineTests.swift
  UnitTests/Sources/TimelineMediaPreviewViewModelTests.swift
  UnitTests/Sources/TimelineViewModelTests.swift
  project.yml
Labels: pr-misc

#4007 External keyboard support for PIN input
  ElementX/Sources/Screens/AppLock/AppLockScreen/View/AppLockScreenPINKeypad.swift
Labels: pr-a11y

#4020 Stop showing the canonical alias for invites in the room list.
  ElementX/Sources/Screens/HomeScreen/View/HomeScreenInviteCell.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/homeScreenInviteCell.iPad-en-GB-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/homeScreenInviteCell.iPad-pseudo-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/homeScreenInviteCell.iPhone-16-en-GB-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/homeScreenInviteCell.iPhone-16-pseudo-0.png
Labels: pr-change

#4021 Update to 25.04.14
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Sources/Mocks/Generated/SDKGeneratedMocks.swift
  ElementX/Sources/Other/Extensions/ClientBuilder.swift
  ElementX/Sources/Services/Authentication/AuthenticationService.swift
  ElementX/Sources/Services/Client/ClientProxy.swift
  ElementX/Sources/Services/Keychain/KeychainController.swift
  ElementX/Sources/Services/Notification/Proxy/NotificationItemProxy.swift
  ElementX/Sources/Services/Notification/Proxy/NotificationItemProxyProtocol.swift
  ElementX/Sources/Services/Room/RoomPreview/RoomPreviewProxy.swift
  NSE/Sources/NotificationContentBuilder.swift
  project.yml
Labels: pr-misc

#4023 Add the new emoji from iOS 18.4 to the reaction picker.
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  PreviewTests/Sources/__Snapshots__/PreviewTests/emojiPickerScreen.Screen-iPad-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/emojiPickerScreen.Screen-iPad-pseudo.png
  project.yml
Labels: pr-change

#4027 Show internet connection warning when uploading keys on log out.
  ElementX/Sources/Mocks/Generated/GeneratedMocks.swift
  ElementX/Sources/Screens/SecureBackup/SecureBackupLogoutConfirmationScreen/SecureBackupLogoutConfirmationScreenModels.swift
  ElementX/Sources/Screens/SecureBackup/SecureBackupLogoutConfirmationScreen/SecureBackupLogoutConfirmationScreenViewModel.swift
  ElementX/Sources/Screens/SecureBackup/SecureBackupLogoutConfirmationScreen/View/SecureBackupLogoutConfirmationScreen.swift
  ElementX/Sources/Services/SecureBackup/SecureBackupController.swift
  ElementX/Sources/Services/SecureBackup/SecureBackupControllerProtocol.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/secureBackupLogoutConfirmationScreen.Confirmation-iPad-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/secureBackupLogoutConfirmationScreen.Confirmation-iPad-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/secureBackupLogoutConfirmationScreen.Confirmation-iPhone-16-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/secureBackupLogoutConfirmationScreen.Confirmation-iPhone-16-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/secureBackupLogoutConfirmationScreen.Offline-iPad-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/secureBackupLogoutConfirmationScreen.Offline-iPad-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/secureBackupLogoutConfirmationScreen.Offline-iPhone-16-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/secureBackupLogoutConfirmationScreen.Offline-iPhone-16-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/secureBackupLogoutConfirmationScreen.Ongoing-iPad-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/secureBackupLogoutConfirmationScreen.Ongoing-iPad-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/secureBackupLogoutConfirmationScreen.Ongoing-iPhone-16-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/secureBackupLogoutConfirmationScreen.Ongoing-iPhone-16-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/secureBackupLogoutConfirmationScreen.Stalled-iPad-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/secureBackupLogoutConfirmationScreen.Stalled-iPad-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/secureBackupLogoutConfirmationScreen.Stalled-iPhone-16-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/secureBackupLogoutConfirmationScreen.Stalled-iPhone-16-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/secureBackupLogoutConfirmationScreen.Waiting-iPad-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/secureBackupLogoutConfirmationScreen.Waiting-iPad-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/secureBackupLogoutConfirmationScreen.Waiting-iPhone-16-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/secureBackupLogoutConfirmationScreen.Waiting-iPhone-16-pseudo.png
  UnitTests/Sources/SecureBackupLogoutConfirmationScreenViewModelTests.swift
Labels: pr-change

#4030 Refactor SecureBackupControllerListener into SDKListener and use it everywhere.
  ElementX.xcodeproj/project.pbxproj
  ElementX/Sources/Mocks/Generated/GeneratedMocks.swift
  ElementX/Sources/Other/SDKListener.swift
  ElementX/Sources/Services/Authentication/AuthenticationClientBuilder.swift
  ElementX/Sources/Services/Client/ClientProxy.swift
  ElementX/Sources/Services/QRCode/QRCodeLoginService.swift
  ElementX/Sources/Services/Room/RoomSummary/RoomSummaryProvider.swift
  ElementX/Sources/Services/RoomDirectorySearch/RoomDirectorySearchProxy.swift
  ElementX/Sources/Services/SecureBackup/SecureBackupController.swift
  ElementX/Sources/Services/Timeline/TimelineProvider.swift
  ElementX/Sources/Services/Timeline/TimelineProxy.swift
Labels: pr-api

#4032 Introduce a `TimelineItemThreadSummary` object
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Sources/Application/AppSettings.swift
  ElementX/Sources/Mocks/Generated/SDKGeneratedMocks.swift
  ElementX/Sources/Mocks/SDK/EventTimelineItem.swift
  ElementX/Sources/Other/Avatars.swift
  ElementX/Sources/Screens/RoomScreen/ComposerToolbar/View/ComposerToolbar.swift
  ElementX/Sources/Screens/RoomScreen/ComposerToolbar/View/MessageComposer.swift
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/DeveloperOptionsScreenModels.swift
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/View/DeveloperOptionsScreen.swift
  ElementX/Sources/Screens/Timeline/TimelineModels.swift
  ElementX/Sources/Screens/Timeline/TimelineViewModel.swift
  ElementX/Sources/Screens/Timeline/View/Replies/TimelineReplyView.swift
  ElementX/Sources/Screens/Timeline/View/Style/TimelineItemBubbledStylerView.swift
  ElementX/Sources/Screens/Timeline/View/Threads/TimelineThreadSummaryView.swift
  ElementX/Sources/Services/ComposerDraft/ComposerDraftService.swift
  ElementX/Sources/Services/Timeline/TimelineItemContent/RoomTimelineItemProperties.swift
  ElementX/Sources/Services/Timeline/TimelineItemContent/TimelineEventContent.swift
  ElementX/Sources/Services/Timeline/TimelineItemContent/TimelineItemReplyDetails.swift
  ElementX/Sources/Services/Timeline/TimelineItemContent/TimelineItemThreadSummary.swift
  ElementX/Sources/Services/Timeline/TimelineItems/Items/Messages/LocationRoomTimelineItem.swift
  ElementX/Sources/Services/Timeline/TimelineItems/RoomTimelineItemFactory.swift
  ElementX/Sources/Services/Timeline/TimelineItems/RoomTimelineItemFactoryProtocol.swift
  PreviewTests/Sources/GeneratedPreviewTests.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/timelineItemBubbledStylerView.Thread-summary-iPad-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/timelineItemBubbledStylerView.Thread-summary-iPad-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/timelineItemBubbledStylerView.Thread-summary-iPhone-16-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/timelineItemBubbledStylerView.Thread-summary-iPhone-16-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/timelineThreadSummaryView.iPad-en-GB-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/timelineThreadSummaryView.iPad-pseudo-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/timelineThreadSummaryView.iPhone-16-en-GB-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/timelineThreadSummaryView.iPhone-16-pseudo-0.png
  UnitTests/Sources/RoomEventStringBuilderTests.swift
  project.yml
Labels: pr-wip

#4037 Update the 3rd-party acknowledgements.
  ElementX/SupportingFiles/Settings.bundle/Acknowledgements.plist
  ElementX/SupportingFiles/Settings.bundle/Packages/Prefire.plist
  ElementX/SupportingFiles/Settings.bundle/Packages/swift-custom-dump.plist
  ElementX/SupportingFiles/Settings.bundle/Packages/xctest-dynamic-overlay.plist
Labels: pr-misc

#4038 Fix a bug where your own emotes showed as '* You emoted' in the room list.
  ElementX/Sources/Services/Room/RoomSummary/RoomEventStringBuilder.swift
  ElementX/Sources/Services/Room/RoomSummary/RoomMessageEventStringBuilder.swift
  NSE/Sources/NotificationContentBuilder.swift
  UnitTests/Sources/RoomEventStringBuilderTests.swift
Labels: pr-bugfix

#4039 Tweak the size of the new bloom to match Figma better.
  ElementX/Sources/Screens/HomeScreen/View/BloomModifier.swift
Labels: pr-wip

#4043 Fix Matrix room in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: pr-doc

#4044 Report room and decline & block screens tweaks
  ElementX/Resources/Localizations/en.lproj/Localizable.strings
  ElementX/Sources/Generated/Strings.swift
  ElementX/Sources/Screens/DeclineAndBlockScreen/DeclineAndBlockScreenModels.swift
  ElementX/Sources/Screens/DeclineAndBlockScreen/DeclineAndBlockScreenViewModel.swift
  ElementX/Sources/Screens/DeclineAndBlockScreen/View/DeclineAndBlockScreen.swift
  ElementX/Sources/Screens/HomeScreen/View/HomeScreenRoomList.swift
  ElementX/Sources/Screens/ReportRoomScreen/ReportRoomScreenModels.swift
  ElementX/Sources/Screens/ReportRoomScreen/ReportRoomScreenViewModel.swift
  ElementX/Sources/Screens/ReportRoomScreen/View/ReportRoomScreen.swift
  ElementX/Sources/Screens/RoomDetailsScreen/View/RoomDetailsScreen.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/declineAndBlockScreen.Report-room-selected-iPad-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/declineAndBlockScreen.Report-room-selected-iPad-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/declineAndBlockScreen.Report-room-selected-iPhone-16-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/declineAndBlockScreen.Report-room-selected-iPhone-16-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/reportRoomScreen.iPad-en-GB-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/reportRoomScreen.iPad-pseudo-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/reportRoomScreen.iPhone-16-en-GB-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/reportRoomScreen.iPhone-16-pseudo-0.png
  UnitTests/Sources/DeclineAndBlockScreenViewModelTests.swift
Labels: pr-change

#4065 Workflow filename name change
  .github/workflows/post-release.yml
Labels: pr-misc

#4070 Remove the Learn More URL for the sliding sync proxy.
  ElementX/Resources/Localizations/be.lproj/Localizable.strings
  ElementX/Resources/Localizations/bg.lproj/Localizable.strings
  ElementX/Resources/Localizations/cs.lproj/Localizable.strings
  ElementX/Resources/Localizations/cy.lproj/Localizable.strings
  ElementX/Resources/Localizations/de.lproj/Localizable.strings
  ElementX/Resources/Localizations/el.lproj/Localizable.strings
  ElementX/Resources/Localizations/en-US.lproj/Localizable.strings
  ElementX/Resources/Localizations/en.lproj/Localizable.strings
  ElementX/Resources/Localizations/es.lproj/Localizable.strings
  ElementX/Resources/Localizations/et.lproj/Localizable.strings
  ElementX/Resources/Localizations/eu.lproj/Localizable.strings
  ElementX/Resources/Localizations/fa.lproj/Localizable.strings
  ElementX/Resources/Localizations/fi.lproj/Localizable.strings
  ElementX/Resources/Localizations/fr.lproj/Localizable.strings
  ElementX/Resources/Localizations/hu.lproj/Localizable.strings
  ElementX/Resources/Localizations/id.lproj/Localizable.strings
  ElementX/Resources/Localizations/it.lproj/Localizable.strings
  ElementX/Resources/Localizations/ka.lproj/Localizable.strings
  ElementX/Resources/Localizations/lt.lproj/Localizable.strings
  ElementX/Resources/Localizations/nb.lproj/Localizable.strings
  ElementX/Resources/Localizations/nl.lproj/Localizable.strings
  ElementX/Resources/Localizations/pl.lproj/Localizable.strings
  ElementX/Resources/Localizations/pt-BR.lproj/Localizable.strings
  ElementX/Resources/Localizations/pt.lproj/Localizable.strings
  ElementX/Resources/Localizations/ro.lproj/Localizable.strings
  ElementX/Resources/Localizations/ru.lproj/Localizable.strings
  ElementX/Resources/Localizations/sk.lproj/Localizable.strings
  ElementX/Resources/Localizations/sv.lproj/Localizable.strings
  ElementX/Resources/Localizations/tr.lproj/Localizable.strings
  ElementX/Resources/Localizations/uk.lproj/Localizable.strings
  ElementX/Resources/Localizations/uz.lproj/Localizable.strings
  ElementX/Resources/Localizations/zh-Hans.lproj/Localizable.strings
  ElementX/Resources/Localizations/zh-Hant-TW.lproj/Localizable.strings
  ElementX/Sources/Application/AppSettings.swift
  ElementX/Sources/FlowCoordinators/AuthenticationFlowCoordinator.swift
  ElementX/Sources/Generated/Strings.swift
  ElementX/Sources/Screens/Authentication/LoginScreen/LoginScreenCoordinator.swift
  ElementX/Sources/Screens/Authentication/LoginScreen/LoginScreenViewModel.swift
  ElementX/Sources/Screens/Authentication/LoginScreen/View/LoginScreen.swift
  ElementX/Sources/Screens/Authentication/ServerConfirmationScreen/ServerConfirmationScreenCoordinator.swift
  ElementX/Sources/Screens/Authentication/ServerConfirmationScreen/ServerConfirmationScreenViewModel.swift
  ElementX/Sources/Screens/Authentication/ServerConfirmationScreen/View/ServerConfirmationScreen.swift
  ElementX/Sources/Screens/Authentication/ServerSelectionScreen/ServerSelectionScreenCoordinator.swift
  ElementX/Sources/Screens/Authentication/ServerSelectionScreen/ServerSelectionScreenModels.swift
  ElementX/Sources/Screens/Authentication/ServerSelectionScreen/ServerSelectionScreenViewModel.swift
  ElementX/Sources/Screens/Authentication/ServerSelectionScreen/View/ServerSelectionScreen.swift
  ElementX/Sources/UITests/UITestsAppCoordinator.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/serverSelection.iPad-en-GB-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/serverSelection.iPad-en-GB-1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/serverSelection.iPad-pseudo-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/serverSelection.iPad-pseudo-1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/serverSelection.iPhone-16-en-GB-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/serverSelection.iPhone-16-en-GB-1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/serverSelection.iPhone-16-pseudo-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/serverSelection.iPhone-16-pseudo-1.png
  UnitTests/Sources/LoginScreenViewModelTests.swift
  UnitTests/Sources/ServerConfirmationScreenViewModelTests.swift
  UnitTests/Sources/ServerSelectionScreenViewModelTests.swift
Labels: pr-misc

#4071 Show the kick/ban reason in the timeline.
  ElementX/Sources/Services/Room/RoomSummary/RoomEventStringBuilder.swift
  ElementX/Sources/Services/Timeline/TimelineItems/RoomStateEventStringBuilder.swift
  ElementX/Sources/Services/Timeline/TimelineItems/RoomTimelineItemFactory.swift
  UnitTests/Sources/RoomStateEventStringBuilderTests.swift
Labels: pr-change

#4072 Run UI Tests on GH CI
  .github/workflows/ui_tests.yml
Labels: pr-build

#4074 Dismiss room invite notifications when rejecting them from the home screen.
  ElementX/Sources/FlowCoordinators/UserSessionFlowCoordinator.swift
  ElementX/Sources/Other/SwiftUI/Animation/ShimmerModifier.swift
  ElementX/Sources/Screens/HomeScreen/HomeScreenCoordinator.swift
  ElementX/Sources/Screens/HomeScreen/HomeScreenViewModel.swift
  ElementX/Sources/Screens/HomeScreen/View/HomeScreen.swift
  ElementX/Sources/Screens/HomeScreen/View/HomeScreenEmptyStateView.swift
  ElementX/Sources/Screens/HomeScreen/View/HomeScreenInviteCell.swift
  ElementX/Sources/Screens/HomeScreen/View/HomeScreenKnockedCell.swift
  ElementX/Sources/Screens/HomeScreen/View/HomeScreenRecoveryKeyConfirmationBanner.swift
  ElementX/Sources/Screens/HomeScreen/View/HomeScreenRoomCell.swift
  UnitTests/Sources/HomeScreenViewModelTests.swift
Labels: pr-bugfix

#4076 Disable the composer when you don't have the power to post.
  ElementX/Sources/Mocks/Generated/GeneratedMocks.swift
  ElementX/Sources/Mocks/JoinedRoomProxyMock.swift
  ElementX/Sources/Screens/RoomScreen/RoomScreenModels.swift
  ElementX/Sources/Screens/RoomScreen/RoomScreenViewModel.swift
  ElementX/Sources/Screens/RoomScreen/View/RoomScreen.swift
  ElementX/Sources/Services/Room/JoinedRoomProxy.swift
  ElementX/Sources/Services/Room/RoomProxyProtocol.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/roomScreen.Normal-iPad-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/roomScreen.Normal-iPad-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/roomScreen.Normal-iPhone-16-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/roomScreen.Normal-iPhone-16-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/roomScreen.Read-only-iPad-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/roomScreen.Read-only-iPad-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/roomScreen.Read-only-iPhone-16-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/roomScreen.Read-only-iPhone-16-pseudo.png
Labels: pr-bugfix

#4073 Run integration tests on GH CI
  .github/workflows/integration-tests.yml
  .github/workflows/unit_tests.yml
Labels: pr-build

#4079 Updated SDK and improved report flow
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Sources/Application/AppSettings.swift
  ElementX/Sources/Mocks/ClientProxyMock.swift
  ElementX/Sources/Mocks/Generated/GeneratedMocks.swift
  ElementX/Sources/Screens/HomeScreen/HomeScreenViewModel.swift
  ElementX/Sources/Screens/JoinRoomScreen/JoinRoomScreenViewModel.swift
  ElementX/Sources/Screens/RoomDetailsScreen/RoomDetailsScreenViewModel.swift
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/DeveloperOptionsScreenModels.swift
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/View/DeveloperOptionsScreen.swift
  ElementX/Sources/Services/Authentication/OIDCConfigurationProxy.swift
  ElementX/Sources/Services/Client/ClientProxy.swift
  ElementX/Sources/Services/Client/ClientProxyProtocol.swift
  ElementX/Sources/Services/Timeline/TimelineProxy.swift
  UnitTests/Sources/HomeScreenViewModelTests.swift
  UnitTests/Sources/JoinRoomScreenViewModelTests.swift
  project.yml
Labels: pr-misc
