Repository element-hq/element-x-ios, pull requests merged in 2025-06, with the labels that each got.

#4164 Make sure UI tests are run to completion on the remaining device, even if the other one fails.
  .github/workflows/ui_tests.yml
Labels: pr-build

#4099 Support for experimental MSC4286 to not render external payment details
  ElementX/Sources/Other/HTMLParsing/DTHTMLElement+AttributedStringBuilder.swift
  UnitTests/Sources/AttributedStringBuilderTests.swift
Labels: pr-feature

#4171 Allow multiple room info updates when receiving a call before deciding the room doesn't have an active call anymore
  NSE/Sources/NotificationHandler.swift
Labels: pr-change

#4136 EC: Native switch for audio outputs/inputs and earpiece
  ElementX/Sources/Screens/CallScreen/CallScreenModels.swift
  ElementX/Sources/Screens/CallScreen/CallScreenViewModel.swift
  ElementX/Sources/Screens/CallScreen/View/CallScreen.swift
  ElementX/Sources/Services/ElementCall/ElementCallWidgetDriver.swift
Labels: pr-feature

#4176 Fix subsequent media upload dialogue presentations
  ElementX/Sources/FlowCoordinators/RoomFlowCoordinatorStateMachine.swift
Labels: pr-bugfix

#4178 Hide accesibility for decorative onboarding image
  ElementX/Sources/Screens/Onboarding/NotificationPermissionsScreen/View/NotificationPermissionsScreen.swift
Labels: pr-a11y

#4172 Add a developer option for history sharing on invite
  ElementX/Sources/Application/AppSettings.swift
  ElementX/Sources/Other/Extensions/ClientBuilder.swift
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/DeveloperOptionsScreenModels.swift
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/View/DeveloperOptionsScreen.swift
  ElementX/Sources/Services/Authentication/AuthenticationClientBuilder.swift
  ElementX/Sources/Services/UserSession/UserSessionStore.swift
  NSE/Sources/NSEUserSession.swift
Labels: pr-feature

#4194 Add state to the accessibility label of RTE formatting buttons
  ElementX/Resources/Localizations/en.lproj/Localizable.strings
  ElementX/Sources/Generated/Strings.swift
  ElementX/Sources/Screens/RoomScreen/ComposerToolbar/ComposerToolbarModels.swift
Labels: pr-a11y

#4196 Exclude protocol files from code coverage checks.
  codecov.yml
Labels: pr-misc

#4200 Improved the accessibility in PollFormScreen
  ElementX/Resources/Localizations/en.lproj/Localizable.strings
  ElementX/Resources/Localizations/en.lproj/Localizable.stringsdict
  ElementX/Sources/Generated/Strings.swift
  ElementX/Sources/Screens/CreatePollScreen/View/PollFormScreen.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/pollFormScreen.Edit-iPad-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/pollFormScreen.Edit-iPad-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/pollFormScreen.Edit-iPhone-16-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/pollFormScreen.Edit-iPhone-16-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/pollFormScreen.New-iPad-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/pollFormScreen.New-iPad-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/pollFormScreen.New-iPhone-16-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/pollFormScreen.New-iPhone-16-pseudo.png
Labels: pr-a11y

#4203 Bump Compound and prevent Introspect from breaking on newer OS versions.
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  project.yml
Labels: pr-bugfix

#4217 Fix OS 26 crashes when not running a development build
  ElementX/Sources/Other/SwiftUI/Views/RoomHeaderView.swift
Labels: pr-bugfix

#4212 Flip the timeline for voice over users
  ElementX/Sources/Screens/Timeline/TimelineTableViewController.swift
Labels: pr-a11y

#4221 Stop failing bug reports when the reportURL is omitted.
  ElementX/Sources/Screens/BugReportScreen/BugReportScreenViewModel.swift
  ElementX/Sources/Services/BugReport/BugReportService.swift
  ElementX/Sources/Services/BugReport/BugReportServiceProtocol.swift
  UnitTests/Sources/BugReportScreenViewModelTests.swift
  UnitTests/Sources/BugReportServiceTests.swift
Labels: pr-bugfix

#4227 Hide timeline item actions that the user's power level does not allow
  ElementX/Sources/Screens/FilePreviewScreen/TimelineMediaPreviewViewModel.swift
  ElementX/Sources/Screens/Timeline/TimelineModels.swift
  ElementX/Sources/Screens/Timeline/TimelineViewModel.swift
  ElementX/Sources/Screens/Timeline/View/ItemMenu/TimelineItemMenu.swift
  ElementX/Sources/Screens/Timeline/View/ItemMenu/TimelineItemMenuActionProvider.swift
  ElementX/Sources/Screens/Timeline/View/Style/TimelineItemBubbledStylerView.swift
  ElementX/Sources/Screens/Timeline/View/TimelineView.swift
Labels: pr-bugfix

#4228 Fix thread summaries being shown when the thread feature flag was disabled.
  ElementX/Sources/Screens/Timeline/View/Style/TimelineItemBubbledStylerView.swift
Labels: pr-bugfix

#4230 Move all Introspect VersionPredicates into Compound to have them all in the same place.
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Sources/Other/Extensions/PlatformViewVersionPredicate.swift
  project.yml
Labels: pr-misc

#4236 Advertise support for `matrix` as a URL scheme.
  ElementX/SupportingFiles/Info.plist
  ElementX/SupportingFiles/target.yml
Labels: pr-feature

#4237 EC Timeout if it doesn't respond after 30 seconds
  ElementX/Sources/Mocks/Generated/GeneratedMocks.swift
  ElementX/Sources/Screens/CallScreen/CallScreenModels.swift
  ElementX/Sources/Screens/CallScreen/CallScreenViewModel.swift
  ElementX/Sources/Services/ElementCall/ElementCallWidgetDriver.swift
  ElementX/Sources/Services/ElementCall/ElementCallWidgetDriverProtocol.swift
Labels: pr-wip

#4245 Adopt room info power levels
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Sources/Mocks/BannedRoomProxyMock.swift
  ElementX/Sources/Mocks/Generated/GeneratedMocks.swift
  ElementX/Sources/Mocks/InvitedRoomProxyMock.swift
  ElementX/Sources/Mocks/JoinedRoomProxyMock.swift
  ElementX/Sources/Mocks/KnockedRoomProxyMock.swift
  ElementX/Sources/Mocks/RoomPowerLevelsProxyMock.swift
  ElementX/Sources/Screens/FilePreviewScreen/TimelineMediaPreviewDataSource.swift
  ElementX/Sources/Screens/FilePreviewScreen/View/TimelineMediaPreviewDetailsView.swift
  ElementX/Sources/Screens/KnockRequestsListScreen/KnockRequestsListScreenViewModel.swift
  ElementX/Sources/Screens/RoomDetailsEditScreen/RoomDetailsEditScreenViewModel.swift
  ElementX/Sources/Screens/RoomDetailsScreen/RoomDetailsScreenViewModel.swift
  ElementX/Sources/Screens/RoomDetailsScreen/View/RoomDetailsScreen.swift
  ElementX/Sources/Screens/RoomMemberListScreen/RoomMembersListScreenViewModel.swift
  ElementX/Sources/Screens/RoomRolesAndPermissionsScreen/RoomRolesAndPermissionsScreenViewModel.swift
  ElementX/Sources/Screens/RoomScreen/ComposerToolbar/CompletionSuggestionService.swift
  ElementX/Sources/Screens/RoomScreen/RoomScreenViewModel.swift
  ElementX/Sources/Screens/ThreadTimelineScreen/ThreadTimelineScreenViewModel.swift
  ElementX/Sources/Screens/Timeline/TimelineViewModel.swift
  ElementX/Sources/Services/Room/JoinedRoomProxy.swift
  ElementX/Sources/Services/Room/RoomInfoProxy.swift
  ElementX/Sources/Services/Room/RoomInfoProxyProtocol.swift
  ElementX/Sources/Services/Room/RoomPowerLevelProxyProtocol.swift
  ElementX/Sources/Services/Room/RoomPowerLevelsProxy.swift
  ElementX/Sources/Services/Room/RoomProxyProtocol.swift
  UnitTests/Sources/RoomDetailsViewModelTests.swift
  UnitTests/Sources/RoomFlowCoordinatorTests.swift
  UnitTests/Sources/RoomScreenViewModelTests.swift
  UnitTests/Sources/TimelineViewModelTests.swift
  project.yml
Labels: pr-change

#4246 Fix media previews in private room notifications and pagination on upgraded rooms.
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Sources/Mocks/Generated/SDKGeneratedMocks.swift
  ElementX/Sources/Other/Extensions/ClientBuilder.swift
  Package.resolved
  project.yml
Labels: pr-bugfix

#4253 Add View Avatar a11y label
  ElementX/Resources/Localizations/en.lproj/Localizable.strings
  ElementX/Sources/Generated/Strings.swift
  ElementX/Sources/Other/SwiftUI/Views/AvatarHeaderView.swift
  ElementX/Sources/Other/SwiftUI/Views/RoomAvatarImage.swift
Labels: pr-a11y

#4254 Use the close formatting option a11y label
  ElementX/Sources/Screens/RoomScreen/ComposerToolbar/View/ComposerToolbar.swift
Labels: pr-a11y

#4259 a11y added a label to the remove all filters button
  ElementX/Resources/Localizations/en.lproj/Localizable.strings
  ElementX/Sources/Generated/Strings.swift
  ElementX/Sources/Screens/HomeScreen/View/Filters/RoomListFiltersView.swift
Labels: pr-a11y

#4261 Be more lenient with the power levels
  ElementX/Sources/Screens/KnockRequestsListScreen/KnockRequestsListScreenViewModel.swift
  ElementX/Sources/Screens/RoomDetailsEditScreen/RoomDetailsEditScreenViewModel.swift
  ElementX/Sources/Screens/RoomDetailsScreen/RoomDetailsScreenViewModel.swift
  ElementX/Sources/Screens/RoomMemberListScreen/RoomMembersListScreenViewModel.swift
  ElementX/Sources/Screens/RoomRolesAndPermissionsScreen/RoomRolesAndPermissionsScreenViewModel.swift
  ElementX/Sources/Screens/RoomScreen/ComposerToolbar/CompletionSuggestionService.swift
  ElementX/Sources/Screens/RoomScreen/RoomScreenViewModel.swift
  ElementX/Sources/Screens/ThreadTimelineScreen/ThreadTimelineScreenViewModel.swift
  ElementX/Sources/Screens/Timeline/TimelineViewModel.swift
  UnitTests/Sources/RoomScreenViewModelTests.swift
Labels: pr-bugfix

#4263 Fix earpiece button visibility in Element Call.
  ElementX/Sources/Screens/CallScreen/CallScreenViewModel.swift
Labels: pr-bugfix

#4264 Attempt to fix message composer layout crashes when running as an iPad app on MacOS
  ElementX/Sources/Screens/RoomScreen/ComposerToolbar/View/MessageComposerTextField.swift
Labels: pr-bugfix

#4262 Replace the Report a Problem button with the app's version on the start screen.
  ElementX/Resources/Localizations/en.lproj/Localizable.strings
  ElementX/Sources/Generated/Strings.swift
  ElementX/Sources/Other/AccessibilityIdentifiers.swift
  ElementX/Sources/Screens/Authentication/StartScreen/AuthenticationStartScreenModels.swift
  ElementX/Sources/Screens/Authentication/StartScreen/AuthenticationStartScreenViewModel.swift
  ElementX/Sources/Screens/Authentication/StartScreen/View/AuthenticationStartScreen.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/authenticationStartScreen.Bug-report-disabled-iPad-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/authenticationStartScreen.Bug-report-disabled-iPad-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/authenticationStartScreen.Bug-report-disabled-iPhone-16-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/authenticationStartScreen.Bug-report-disabled-iPhone-16-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/authenticationStartScreen.Default-iPad-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/authenticationStartScreen.Default-iPad-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/authenticationStartScreen.Default-iPhone-16-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/authenticationStartScreen.Default-iPhone-16-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/authenticationStartScreen.Provisioned-iPad-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/authenticationStartScreen.Provisioned-iPad-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/authenticationStartScreen.Provisioned-iPhone-16-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/authenticationStartScreen.Provisioned-iPhone-16-pseudo.png
  UITests/Sources/AuthenticationFlowCoordinatorTests.swift
  UITests/Sources/__Snapshots__/Application/authenticationFlowCoordinator.testMultipleProvidersLoginWithPassword-iPad-18-4-en-GB.png
  UITests/Sources/__Snapshots__/Application/authenticationFlowCoordinator.testMultipleProvidersLoginWithPassword-iPhone-18-4-en-GB.png
  UITests/Sources/__Snapshots__/Application/authenticationFlowCoordinator.testProvisionedLoginWithPassword-iPad-18-4-en-GB.png
  UITests/Sources/__Snapshots__/Application/authenticationFlowCoordinator.testProvisionedLoginWithPassword-iPhone-18-4-en-GB.png
  UITests/Sources/__Snapshots__/Application/authenticationFlowCoordinator.testSingleProviderLoginWithPassword-iPad-18-4-en-GB.png
  UITests/Sources/__Snapshots__/Application/authenticationFlowCoordinator.testSingleProviderLoginWithPassword-iPhone-18-4-en-GB.png
Labels: pr-misc
