Repository element-hq/element-x-ios, pull requests merged in 2025-05, with the labels that each got.

#4083 Adopt StateStoreViewModelV2 in the authentication screens and some settings screens.
  ElementX.xcodeproj/project.pbxproj
  ElementX/Sources/Screens/Authentication/ServerConfirmationScreen/ServerConfirmationScreenViewModel.swift
  ElementX/Sources/Screens/Authentication/ServerConfirmationScreen/View/ServerConfirmationScreen.swift
  ElementX/Sources/Screens/Authentication/ServerSelectionScreen/ServerSelectionScreenViewModel.swift
  ElementX/Sources/Screens/Authentication/ServerSelectionScreen/View/ServerSelectionScreen.swift
  ElementX/Sources/Screens/Authentication/SoftLogoutScreen/SoftLogoutScreenViewModel.swift
  ElementX/Sources/Screens/Authentication/SoftLogoutScreen/View/SoftLogoutScreen.swift
  ElementX/Sources/Screens/AuthenticationStartScreen/AuthenticationStartScreenViewModel.swift
  ElementX/Sources/Screens/AuthenticationStartScreen/View/AuthenticationStartScreen.swift
  ElementX/Sources/Screens/Settings/AvancedOptionsScreen/AdvancedSettingsScreenViewModel.swift
  ElementX/Sources/Screens/Settings/AvancedOptionsScreen/View/AdvancedSettingsScreen.swift
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/DeveloperOptionsScreenViewModel.swift
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/View/DeveloperOptionsScreen.swift
  ElementX/Sources/Screens/Settings/SettingsScreen/SettingsScreenViewModel.swift
  ElementX/Sources/Screens/Settings/SettingsScreen/View/SettingsScreen.swift
  UnitTests/Sources/DeferredFulfillmentTests.swift
  UnitTests/Sources/ServerConfirmationScreenViewModelTests.swift
  UnitTests/Sources/ServerSelectionScreenViewModelTests.swift
  UnitTests/Sources/SettingsScreenViewModelTests.swift
  UnitTests/Sources/SoftLogoutScreenViewModelTests.swift
Labels: pr-api

#4084 Fix the integration tests.
  ElementX/Sources/Other/Extensions/XCUIElement.swift
  ElementX/Sources/Screens/Authentication/OIDCAuthenticationPresenter.swift
  IntegrationTests/Sources/Application.swift
  IntegrationTests/Sources/Common.swift
  IntegrationTests/Sources/UserFlowTests.swift
Labels: pr-build

#4085 Fix the UI tests.
  .github/workflows/ui_tests.yml
  ElementX.xcodeproj/project.pbxproj
  ElementX/Sources/UITests/UITestsAppCoordinator.swift
  ElementX/Sources/UITests/UITestsScreenIdentifier.swift
  Tools/Scripts/Templates/SimpleScreenExample/Tests/UI/TemplateScreenTests.swift
  UITests/Sources/AuthenticationFlowCoordinatorTests.swift
  UITests/Sources/PollFormScreenTests.swift
  UITests/Sources/UserSessionScreenTests.swift
  UITests/Sources/__Snapshots__/Application/serverSelection.testEmptyAddress-iPad-18-4-en-GB.png
  UITests/Sources/__Snapshots__/Application/serverSelection.testEmptyAddress-iPhone-18-4-en-GB.png
  UITests/Sources/__Snapshots__/Application/serverSelection.testNormalState-iPad-18-4-en-GB.png
  UITests/Sources/__Snapshots__/Application/serverSelection.testNormalState-iPhone-18-4-en-GB.png
  UITests/Sources/__Snapshots__/Application/templateScreen.testScreen-iPad-18-4-en-GB.png
  UITests/Sources/__Snapshots__/Application/templateScreen.testScreen-iPhone-18-4-en-GB.png
  UITests/SupportingFiles/target.yml
  fastlane/Fastfile
Labels: pr-build

#4086 Run the UI & Integration tests once a day instead of twice with a 6 hour offset.
  .github/workflows/integration-tests.yml
  .github/workflows/ui_tests.yml
Labels: pr-build

#4082 Move where the developer options are shown and store them in the app settings
  ElementX/Sources/Application/AppSettings.swift
  ElementX/Sources/Screens/Settings/SettingsScreen/SettingsScreenViewModel.swift
  ElementX/Sources/Screens/Settings/SettingsScreen/View/SettingsScreen.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/settingsScreen.Bug-report-disabled-iPad-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/settingsScreen.Bug-report-disabled-iPad-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/settingsScreen.Bug-report-disabled-iPhone-16-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/settingsScreen.Bug-report-disabled-iPhone-16-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/settingsScreen.Default-iPad-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/settingsScreen.Default-iPad-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/settingsScreen.Default-iPhone-16-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/settingsScreen.Default-iPhone-16-pseudo.png
Labels: pr-change

#4096 Updated the learn more link for the identity confirmation screen
  ElementX/Sources/Application/AppSettings.swift
  ElementX/Sources/Screens/Onboarding/IdentityConfirmationScreen/IdentityConfirmationScreenViewModel.swift
Labels: pr-change

#4100 Fix a bug where fetching room history could fail.
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  project.yml
Labels: pr-bugfix

#4103 Add a state machine to the AuthenticationFlowCoordinator.
  ElementX/Sources/FlowCoordinators/AuthenticationFlowCoordinator.swift
  ElementX/Sources/FlowCoordinators/BugReportFlowCoordinator.swift
  ElementX/Sources/FlowCoordinators/EncryptionSettingsFlowCoordinator.swift
  ElementX/Sources/Screens/AuthenticationStartScreen/AuthenticationStartScreenModels.swift
  ElementX/Sources/Screens/AuthenticationStartScreen/AuthenticationStartScreenViewModel.swift
  ElementX/Sources/Services/Authentication/AuthenticationServiceProtocol.swift
Labels: pr-misc

#4105 Voice over focuses the search bar automatically on the invite users screen
  ElementX/Sources/Other/SwiftUI/Layout/ViewFrameReader.swift
  ElementX/Sources/Other/SwiftUI/Search.swift
  ElementX/Sources/Screens/InviteUsersScreen/View/InviteUsersScreen.swift
Labels: pr-a11y

#4114 Fix room list heroes label format
  ElementX/Resources/Localizations/be.lproj/Localizable.stringsdict
  ElementX/Resources/Localizations/bg.lproj/Localizable.stringsdict
  ElementX/Resources/Localizations/cs.lproj/Localizable.stringsdict
  ElementX/Resources/Localizations/cy.lproj/Localizable.stringsdict
  ElementX/Resources/Localizations/de.lproj/Localizable.stringsdict
  ElementX/Resources/Localizations/el.lproj/Localizable.stringsdict
  ElementX/Resources/Localizations/en.lproj/Localizable.stringsdict
  ElementX/Resources/Localizations/es.lproj/Localizable.stringsdict
  ElementX/Resources/Localizations/et.lproj/Localizable.stringsdict
  ElementX/Resources/Localizations/eu.lproj/Localizable.stringsdict
  ElementX/Resources/Localizations/fa.lproj/Localizable.stringsdict
  ElementX/Resources/Localizations/fi.lproj/Localizable.stringsdict
  ElementX/Resources/Localizations/fr.lproj/Localizable.stringsdict
  ElementX/Resources/Localizations/hu.lproj/Localizable.stringsdict
  ElementX/Resources/Localizations/id.lproj/Localizable.stringsdict
  ElementX/Resources/Localizations/it.lproj/Localizable.stringsdict
  ElementX/Resources/Localizations/ka.lproj/Localizable.stringsdict
  ElementX/Resources/Localizations/lt.lproj/Localizable.stringsdict
  ElementX/Resources/Localizations/nb.lproj/Localizable.stringsdict
  ElementX/Resources/Localizations/nl.lproj/Localizable.stringsdict
  ElementX/Resources/Localizations/pl.lproj/Localizable.stringsdict
  ElementX/Resources/Localizations/pt-BR.lproj/Localizable.stringsdict
  ElementX/Resources/Localizations/pt.lproj/Localizable.stringsdict
  ElementX/Resources/Localizations/ro.lproj/Localizable.stringsdict
  ElementX/Resources/Localizations/ru.lproj/Localizable.stringsdict
  ElementX/Resources/Localizations/sk.lproj/Localizable.stringsdict
  ElementX/Resources/Localizations/sv.lproj/Localizable.stringsdict
  ElementX/Resources/Localizations/tr.lproj/Localizable.stringsdict
  ElementX/Resources/Localizations/uk.lproj/Localizable.stringsdict
  ElementX/Resources/Localizations/uz.lproj/Localizable.stringsdict
  ElementX/Resources/Localizations/zh-Hans.lproj/Localizable.stringsdict
  ElementX/Resources/Localizations/zh-Hant-TW.lproj/Localizable.stringsdict
  ElementX/Sources/Generated/Strings.swift
  ElementX/Sources/Mocks/RoomSummaryProviderMock.swift
  ElementX/Sources/Screens/HomeScreen/View/HomeScreenInviteCell.swift
  ElementX/Sources/Screens/HomeScreen/View/HomeScreenKnockedCell.swift
  ElementX/Sources/Screens/Timeline/View/TypingIndicatorView.swift
  ElementX/Sources/Services/Room/RoomSummary/RoomSummary.swift
  ElementX/Sources/Services/Room/RoomSummary/RoomSummaryProvider.swift
  UnitTests/Sources/HomeScreenRoomTests.swift
  UnitTests/Sources/LoggingTests.swift
  UnitTests/Sources/RoomSummaryTests.swift
Labels: pr-change

#4109 Fix various small errors when running in the Swift 6 language mode
  ElementX/Sources/Application/TargetConfiguration.swift
  ElementX/Sources/Other/ExpiringTaskRunner.swift
  ElementX/Sources/Other/HTMLParsing/ElementXAttributeScope.swift
  ElementX/Sources/Other/Logging/MXLog.swift
  ElementX/Sources/Other/MatrixEntityRegex.swift
  ElementX/Sources/Screens/EmojiPickerScreen/EmojiPickerScreenViewModel.swift
  ElementX/Sources/Services/Media/Provider/MediaFileHandleProxy.swift
  ElementX/Sources/Services/Media/Provider/MediaLoader.swift
  ElementX/Sources/Services/Media/Provider/MediaSourceProxy.swift
  NSE/Sources/NotificationServiceExtension.swift
  UnitTests/Sources/LoggingTests.swift
Labels: pr-misc

#4123 Fix a bug where accepting a DM invite would be accepted as a regular room.
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Sources/Mocks/BannedRoomProxyMock.swift
  ElementX/Sources/Mocks/Generated/SDKGeneratedMocks.swift
  ElementX/Sources/Mocks/InvitedRoomProxyMock.swift
  ElementX/Sources/Mocks/JoinedRoomProxyMock.swift
  ElementX/Sources/Mocks/KnockedRoomProxyMock.swift
  ElementX/Sources/Other/Extensions/ClientBuilder.swift
  ElementX/Sources/Services/Room/RoomInfoProxy.swift
  Package.resolved
  project.yml
Labels: pr-bugfix

#4122 Observe room info updates and automatically dismiss the room if meanwhile left or banned
  ElementX/Sources/FlowCoordinators/RoomFlowCoordinator.swift
  ElementX/Sources/Mocks/JoinedRoomProxyMock.swift
  UnitTests/Sources/RoomFlowCoordinatorTests.swift
Labels: pr-bugfix

#4132 Using 1.18.3 snapshot testing and allow UI tests to use the module properly
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  PreviewTests/Sources/PreviewTests.swift
  UITests/Sources/Application.swift
  UITests/SupportingFiles/target.yml
  project.yml
Labels: pr-build

#4133 updated the SDK to 25.05.19
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Sources/Services/ElementCall/ElementCallWidgetDriver.swift
  project.yml
Labels: pr-build

#4106 Send full user agent header to server during OIDC authentication and when viewing Account and Device management screens
  ElementX/Sources/Screens/Authentication/OIDCAuthenticationPresenter.swift
  ElementX/Sources/Screens/Settings/AccountSettings/OIDCAccountSettingsPresenter.swift
Labels: pr-change

#4135 Integration tests: support for the bottom sheet
  ElementX/Sources/Other/AccessibilityIdentifiers.swift
  ElementX/Sources/Screens/ManageRoomMemberSheet/View/ManageRoomMemberSheetView.swift
  IntegrationTests/Sources/UserFlowTests.swift
Labels: pr-build

#4137 Show an account provider picker on the server confirmation screen when required.
  ElementX/Resources/Localizations/en.lproj/Localizable.strings
  ElementX/Sources/FlowCoordinators/AuthenticationFlowCoordinator.swift
  ElementX/Sources/Generated/Strings.swift
  ElementX/Sources/Mocks/Generated/GeneratedMocks.swift
  ElementX/Sources/Other/AccessibilityIdentifiers.swift
  ElementX/Sources/Screens/Authentication/ServerConfirmationScreen/ServerConfirmationScreenCoordinator.swift
  ElementX/Sources/Screens/Authentication/ServerConfirmationScreen/ServerConfirmationScreenModels.swift
  ElementX/Sources/Screens/Authentication/ServerConfirmationScreen/ServerConfirmationScreenViewModel.swift
  ElementX/Sources/Screens/Authentication/ServerConfirmationScreen/View/ServerConfirmationScreen.swift
  ElementX/Sources/Screens/AuthenticationStartScreen/AuthenticationStartScreenViewModel.swift
  ElementX/Sources/UITests/UITestsAppCoordinator.swift
  ElementX/Sources/UITests/UITestsScreenIdentifier.swift
  Package.resolved
  PreviewTests/Sources/GeneratedPreviewTests.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/serverConfirmationScreen.Login-iPad-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/serverConfirmationScreen.Login-iPad-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/serverConfirmationScreen.Login-iPhone-16-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/serverConfirmationScreen.Login-iPhone-16-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/serverConfirmationScreen.Picker-iPad-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/serverConfirmationScreen.Picker-iPad-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/serverConfirmationScreen.Picker-iPhone-16-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/serverConfirmationScreen.Picker-iPhone-16-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/serverConfirmationScreen.Register-iPad-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/serverConfirmationScreen.Register-iPad-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/serverConfirmationScreen.Register-iPhone-16-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/serverConfirmationScreen.Register-iPhone-16-pseudo.png
  UITests/Sources/AuthenticationFlowCoordinatorTests.swift
  UITests/Sources/__Snapshots__/Application/authenticationFlowCoordinator.testMultipleProvidersLoginWithPassword-iPad-18-4-en-GB.png
  UITests/Sources/__Snapshots__/Application/authenticationFlowCoordinator.testMultipleProvidersLoginWithPassword-iPhone-18-4-en-GB.png
  UnitTests/Sources/ServerConfigurationScreenViewStateTests.swift
  UnitTests/Sources/ServerConfirmationScreenViewModelTests.swift
Labels: pr-misc

#4138 Don't group timeline items if more than 5 minutes has passed.
  ElementX/Sources/Screens/Timeline/TimelineViewModel.swift
Labels: pr-misc

#4147 Add a developer option that hides notification alerts when a sound wouldn't be played.
  ElementX/Sources/Application/AppSettings.swift
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/DeveloperOptionsScreenModels.swift
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/View/DeveloperOptionsScreen.swift
  NSE/Sources/NotificationHandler.swift
Labels: pr-misc

#4148 Bump the SDK to v25.05.26-2 and update the breaking changes following the RoomListItem removal
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Sources/Mocks/Generated/SDKGeneratedMocks.swift
  ElementX/Sources/Mocks/RoomSummaryProviderMock.swift
  ElementX/Sources/Screens/HomeScreen/View/HomeScreenInviteCell.swift
  ElementX/Sources/Screens/HomeScreen/View/HomeScreenKnockedCell.swift
  ElementX/Sources/Screens/JoinRoomScreen/JoinRoomScreenViewModel.swift
  ElementX/Sources/Services/Room/RoomSummary/RoomSummary.swift
  ElementX/Sources/Services/Room/RoomSummary/RoomSummaryProvider.swift
  UnitTests/Sources/HomeScreenRoomTests.swift
  UnitTests/Sources/LoggingTests.swift
  UnitTests/Sources/RoomSummaryTests.swift
  project.yml
Labels: pr-misc

#4153 Fix a couple of crashes on macOS from a missing environment object.
  ElementX/Sources/Screens/Timeline/View/TimelineView.swift
Labels: pr-bugfix

#4142 Handle media previews and invite avatars through the account data
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Sources/Application/AppCoordinator.swift
  ElementX/Sources/Application/AppSettings.swift
  ElementX/Sources/FlowCoordinators/SettingsFlowCoordinator.swift
  ElementX/Sources/Mocks/ClientProxyMock.swift
  ElementX/Sources/Mocks/Generated/GeneratedMocks.swift
  ElementX/Sources/Mocks/Generated/SDKGeneratedMocks.swift
  ElementX/Sources/Other/SDKListener.swift
  ElementX/Sources/Screens/HomeScreen/HomeScreenViewModel.swift
  ElementX/Sources/Screens/JoinRoomScreen/JoinRoomScreenViewModel.swift
  ElementX/Sources/Screens/JoinRoomScreen/View/JoinRoomScreen.swift
  ElementX/Sources/Screens/SecurityAndPrivacyScreen/View/SecurityAndPrivacyScreen.swift
  ElementX/Sources/Screens/Settings/AvancedOptionsScreen/AdvancedSettingsScreenCoordinator.swift
  ElementX/Sources/Screens/Settings/AvancedOptionsScreen/AdvancedSettingsScreenModels.swift
  ElementX/Sources/Screens/Settings/AvancedOptionsScreen/AdvancedSettingsScreenViewModel.swift
  ElementX/Sources/Screens/Settings/AvancedOptionsScreen/View/AdvancedSettingsScreen.swift
  ElementX/Sources/Screens/Timeline/TimelineViewModel.swift
  ElementX/Sources/Services/Client/ClientProxy.swift
  ElementX/Sources/Services/Client/ClientProxyProtocol.swift
  NSE/Sources/NSEUserSession.swift
  NSE/Sources/NotificationContentBuilder.swift
  NSE/Sources/NotificationHandler.swift
  project.yml
Labels: pr-feature

#4158 Adopt StateStoreViewModelV2 in the remaining settings screens.
  ElementX.xcodeproj/project.pbxproj
  ElementX/Sources/Application/AppCoordinator.swift
  ElementX/Sources/Other/Extensions/XCTestCase.swift
  ElementX/Sources/Screens/Authentication/LoginScreen/LoginScreenViewModel.swift
  ElementX/Sources/Screens/Authentication/LoginScreen/View/LoginScreen.swift
  ElementX/Sources/Screens/Authentication/StartScreen/AuthenticationStartScreenCoordinator.swift
  ElementX/Sources/Screens/Authentication/StartScreen/AuthenticationStartScreenModels.swift
  ElementX/Sources/Screens/Authentication/StartScreen/AuthenticationStartScreenViewModel.swift
  ElementX/Sources/Screens/Authentication/StartScreen/AuthenticationStartScreenViewModelProtocol.swift
  ElementX/Sources/Screens/Authentication/StartScreen/View/AuthenticationStartLogo.swift
  ElementX/Sources/Screens/Authentication/StartScreen/View/AuthenticationStartScreen.swift
  ElementX/Sources/Screens/Authentication/StartScreen/View/AuthenticationStartScreenBackgroundImage.swift
  ElementX/Sources/Screens/BugReportScreen/BugReportScreenViewModel.swift
  ElementX/Sources/Screens/BugReportScreen/View/BugReportScreen.swift
  ElementX/Sources/Screens/EncryptionReset/EncryptionResetPasswordScreen/EncryptionResetPasswordScreenViewModel.swift
  ElementX/Sources/Screens/EncryptionReset/EncryptionResetPasswordScreen/View/EncryptionResetPasswordScreen.swift
  ElementX/Sources/Screens/EncryptionReset/EncryptionResetScreen/EncryptionResetScreenViewModel.swift
  ElementX/Sources/Screens/EncryptionReset/EncryptionResetScreen/View/EncryptionResetScreen.swift
  ElementX/Sources/Screens/LogViewerScreen/LogViewerScreenViewModel.swift
  ElementX/Sources/Screens/LogViewerScreen/View/LogViewerScreen.swift
  ElementX/Sources/Screens/SecureBackup/SecureBackupKeyBackupScreen/SecureBackupKeyBackupScreenViewModel.swift
  ElementX/Sources/Screens/SecureBackup/SecureBackupKeyBackupScreen/View/SecureBackupKeyBackupScreen.swift
  ElementX/Sources/Screens/SecureBackup/SecureBackupLogoutConfirmationScreen/SecureBackupLogoutConfirmationScreenViewModel.swift
  ElementX/Sources/Screens/SecureBackup/SecureBackupLogoutConfirmationScreen/View/SecureBackupLogoutConfirmationScreen.swift
  ElementX/Sources/Screens/SecureBackup/SecureBackupRecoveryKeyScreen/SecureBackupRecoveryKeyScreenViewModel.swift
  ElementX/Sources/Screens/SecureBackup/SecureBackupRecoveryKeyScreen/View/SecureBackupRecoveryKeyScreen.swift
  ElementX/Sources/Screens/SecureBackup/SecureBackupScreen/SecureBackupScreenViewModel.swift
  ElementX/Sources/Screens/SecureBackup/SecureBackupScreen/View/SecureBackupScreen.swift
  ElementX/Sources/Screens/Settings/AdvancedSettingsScreen/AdvancedSettingsScreenCoordinator.swift
  ElementX/Sources/Screens/Settings/AdvancedSettingsScreen/AdvancedSettingsScreenModels.swift
  ElementX/Sources/Screens/Settings/AdvancedSettingsScreen/AdvancedSettingsScreenViewModel.swift
  ElementX/Sources/Screens/Settings/AdvancedSettingsScreen/AdvancedSettingsScreenViewModelProtocol.swift
  ElementX/Sources/Screens/Settings/AdvancedSettingsScreen/View/AdvancedSettingsScreen.swift
  ElementX/Sources/Screens/Settings/AnalyticsSettingsScreen/AnalyticsSettingsScreenViewModel.swift
  ElementX/Sources/Screens/Settings/AnalyticsSettingsScreen/View/AnalyticsSettingsScreen.swift
  ElementX/Sources/Screens/Settings/DeactivateAccountScreen/DeactivateAccountScreenCoordinator.swift
  ElementX/Sources/Screens/Settings/DeactivateAccountScreen/DeactivateAccountScreenModels.swift
  ElementX/Sources/Screens/Settings/DeactivateAccountScreen/DeactivateAccountScreenViewModel.swift
  ElementX/Sources/Screens/Settings/DeactivateAccountScreen/DeactivateAccountScreenViewModelProtocol.swift
  ElementX/Sources/Screens/Settings/DeactivateAccountScreen/View/DeactivateAccountScreen.swift
  ElementX/Sources/Screens/Settings/LegalInformationScreen/LegalInformationScreenViewModel.swift
  ElementX/Sources/Screens/Settings/LegalInformationScreen/View/LegalInformationScreen.swift
  ElementX/Sources/Screens/Settings/NotificationSettingsEditScreen/NotificationSettingsEditScreenViewModel.swift
  ElementX/Sources/Screens/Settings/NotificationSettingsEditScreen/View/NotificationSettingsEditScreen.swift
  ElementX/Sources/Screens/Settings/NotificationSettingsScreen/NotificationSettingsScreenViewModel.swift
  ElementX/Sources/Screens/Settings/NotificationSettingsScreen/View/NotificationSettingsScreen.swift
  ElementX/Sources/Screens/Settings/UserDetailsEditScreen/UserDetailsEditScreenViewModel.swift
  ElementX/Sources/Screens/Settings/UserDetailsEditScreen/View/UserDetailsEditScreen.swift
  ElementX/SupportingFiles/Settings.bundle/Packages/sentry-cocoa.plist
  UnitTests/Sources/DeactivateAccountScreenViewModelTests.swift
  UnitTests/Sources/LoginScreenViewModelTests.swift
  UnitTests/Sources/NotificationSettingsEditScreenViewModelTests.swift
  UnitTests/Sources/NotificationSettingsScreenViewModelTests.swift
  UnitTests/Sources/SecureBackupLogoutConfirmationScreenViewModelTests.swift
Labels: pr-api

#4160 Adopt the new deduplicate room versions room list filter.
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Sources/Mocks/BannedRoomProxyMock.swift
  ElementX/Sources/Mocks/Generated/SDKGeneratedMocks.swift
  ElementX/Sources/Mocks/InvitedRoomProxyMock.swift
  ElementX/Sources/Mocks/JoinedRoomProxyMock.swift
  ElementX/Sources/Mocks/KnockedRoomProxyMock.swift
  ElementX/Sources/Services/Room/RoomInfoProxy.swift
  ElementX/Sources/Services/Room/RoomSummary/RoomSummaryProvider.swift
  Package.resolved
  project.yml
Labels: pr-feature
