Repository element-hq/element-x-ios, pull requests merged in 2025-07, with the labels that each got.

#4276 Updated SDK to 25.07.01
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  project.yml
Labels: pr-misc

#4275 Adopt StateStoreViewModelV2 in more screens.
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Sources/Other/Extensions/XCTestCase.swift
  ElementX/Sources/Screens/BlockedUsersScreen/BlockedUsersScreenViewModel.swift
  ElementX/Sources/Screens/BlockedUsersScreen/View/BlockedUsersScreen.swift
  ElementX/Sources/Screens/CreatePollScreen/PollFormScreenViewModel.swift
  ElementX/Sources/Screens/CreatePollScreen/View/PollFormScreen.swift
  ElementX/Sources/Screens/DeclineAndBlockScreen/DeclineAndBlockScreenViewModel.swift
  ElementX/Sources/Screens/DeclineAndBlockScreen/View/DeclineAndBlockScreen.swift
  ElementX/Sources/Screens/EmojiPickerScreen/EmojiPickerScreenViewModel.swift
  ElementX/Sources/Screens/EmojiPickerScreen/View/EmojiPickerScreen.swift
  ElementX/Sources/Screens/LocationSharing/StaticLocationScreenViewModel.swift
  ElementX/Sources/Screens/LocationSharing/View/StaticLocationScreen.swift
  ElementX/Sources/Screens/ManageRoomMemberSheet/ManageRoomMemberSheetViewModel.swift
  ElementX/Sources/Screens/ManageRoomMemberSheet/View/ManageRoomMemberSheetView.swift
  ElementX/Sources/Screens/MediaUploadPreviewScreen/MediaUploadPreviewScreenViewModel.swift
  ElementX/Sources/Screens/MediaUploadPreviewScreen/View/MediaUploadPreviewScreen.swift
  ElementX/Sources/Screens/Onboarding/AnalyticsPromptScreen/AnalyticsPromptScreenViewModel.swift
  ElementX/Sources/Screens/Onboarding/AnalyticsPromptScreen/View/AnalyticsPromptScreen.swift
  ElementX/Sources/Screens/ReportContentScreen/ReportContentScreenViewModel.swift
  ElementX/Sources/Screens/ReportContentScreen/View/ReportContentScreen.swift
  ElementX/Sources/Screens/ReportRoomScreen/ReportRoomScreenViewModel.swift
  ElementX/Sources/Screens/ReportRoomScreen/View/ReportRoomScreen.swift
  ElementX/Sources/Screens/ResolveVerifiedUserSendFailureScreen/ResolveVerifiedUserSendFailureScreenViewModel.swift
  ElementX/Sources/Screens/ResolveVerifiedUserSendFailureScreen/View/ResolveVerifiedUserSendFailureScreen.swift
  ElementX/Sources/Screens/RoomChangePermissionsScreen/RoomChangePermissionsScreenViewModel.swift
  ElementX/Sources/Screens/RoomChangePermissionsScreen/View/RoomChangePermissionsScreen.swift
  ElementX/Sources/Screens/RoomChangeRolesScreen/RoomChangeRolesScreenViewModel.swift
  ElementX/Sources/Screens/RoomChangeRolesScreen/View/RoomChangeRolesScreen.swift
  ElementX/Sources/Screens/RoomChangeRolesScreen/View/RoomChangeRolesScreenSection.swift
  ElementX/Sources/Screens/RoomDetailsScreen/RoomDetailsScreenViewModel.swift
  ElementX/Sources/Screens/RoomDetailsScreen/View/RoomDetailsScreen.swift
  ElementX/Sources/Screens/RoomRolesAndPermissionsScreen/RoomRolesAndPermissionsScreenViewModel.swift
  ElementX/Sources/Screens/RoomRolesAndPermissionsScreen/View/RoomRolesAndPermissionsScreen.swift
  ElementX/Sources/Screens/UserProfileScreen/UserProfileScreenViewModel.swift
  ElementX/Sources/Screens/UserProfileScreen/View/UserProfileScreen.swift
  ElementX/SupportingFiles/Settings.bundle/Acknowledgements.plist
  ElementX/SupportingFiles/Settings.bundle/Packages/swift-async-algorithms.plist
  UnitTests/Sources/BlockedUsersScreenViewModelTests.swift
  UnitTests/Sources/ManageRoomMemberSheetViewModelTests.swift
  UnitTests/Sources/ReportContentScreenViewModelTests.swift
  UnitTests/Sources/ReportRoomScreenViewModelTests.swift
  UnitTests/Sources/ResolveVerifiedUserSendFailureScreenViewModelTests.swift
  UnitTests/Sources/RoomDetailsScreenViewModelTests.swift
  UnitTests/Sources/UserProfileScreenViewModelTests.swift
  UnitTests/SupportingFiles/target.yml
  project.yml
Labels: pr-api

#4286 Update the SDK.
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Sources/Services/Timeline/TimelineItems/RoomTimelineItemFactory.swift
  project.yml
Labels: pr-misc

#4294 Change the order of timeline media visibility UI
  ElementX/Sources/Screens/Settings/AdvancedSettingsScreen/View/AdvancedSettingsScreen.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/advancedSettingsScreen.iPad-en-GB-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/advancedSettingsScreen.iPad-pseudo-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/advancedSettingsScreen.iPhone-16-en-GB-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/advancedSettingsScreen.iPhone-16-pseudo-0.png
Labels: pr-change

#4300 A11y pinned items improvement
  ElementX/Sources/Screens/RoomScreen/View/RoomScreen.swift
  ElementX/Sources/Screens/Timeline/View/Style/TimelineItemBubbledStylerView.swift
Labels: pr-a11y

#4302 Hide accessibility of empty section
  ElementX/Sources/Screens/StartChatScreen/View/StartChatScreen.swift
Labels: pr-a11y

#4304 Accessibility label for editing the avatar
  ElementX/Resources/Localizations/en.lproj/Localizable.strings
  ElementX/Sources/Generated/Strings.swift
  ElementX/Sources/Screens/RoomDetailsEditScreen/View/RoomDetailsEditScreen.swift
Labels: pr-a11y

#4306 Aadded sender name when voiceover focuses a poll title
  ElementX/Sources/Other/Extensions/Section.swift
  ElementX/Sources/Screens/RoomPollsHistoryScreen/View/RoomPollsHistoryScreen.swift
  ElementX/Sources/Screens/StartChatScreen/View/StartChatScreen.swift
  ElementX/Sources/Screens/Timeline/View/Polls/PollView.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/PollRoomTimelineView.swift
Labels: pr-a11y

#4310 Announce session verification request as time limited
  ElementX/Resources/Localizations/en.lproj/Localizable.strings
  ElementX/Sources/Generated/Strings.swift
  ElementX/Sources/Screens/Onboarding/SessionVerificationScreen/View/SessionVerificationScreen.swift
Labels: pr-a11y

#4312 FF for enabling share pos and defaults to `false`
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Sources/Application/AppSettings.swift
  ElementX/Sources/Mocks/Generated/SDKGeneratedMocks.swift
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/DeveloperOptionsScreenModels.swift
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/View/DeveloperOptionsScreen.swift
  ElementX/Sources/Services/Client/ClientProxy.swift
  ElementX/Sources/Services/Room/JoinedRoomProxy.swift
  ElementX/Sources/Services/Room/RoomSummary/RoomSummaryProvider.swift
  project.yml
Labels: pr-misc

#4324 Fix a sync performance regression.
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Sources/Mocks/Generated/SDKGeneratedMocks.swift
  ElementX/Sources/Mocks/SDK/ClientSDKMock.swift
  ElementX/Sources/Services/Authentication/AuthenticationService.swift
  UnitTests/Sources/AuthenticationStartScreenViewModelTests.swift
  UnitTests/Sources/ServerConfirmationScreenViewModelTests.swift
  project.yml
Labels: pr-bugfix

#4328 Fix the user defaults key used for the developer options.
  ElementX/Sources/Application/AppSettings.swift
Labels: pr-bugfix

#4325 Accessibiliy Tests part 2
  .github/workflows/accessibility_tests.yml
  AccessibilityTests/Sources/AccessibilityTests.swift
  AccessibilityTests/Sources/GeneratedAccessibilityTests.swift
  AccessibilityTests/Sources/Test.swift
  AccessibilityTests/SupportingFiles/target.yml
  ElementX.xcodeproj/project.pbxproj
  ElementX/Sources/AccessibilityTests/AccessibilityTestsAppCoordinator.swift
  ElementX/Sources/Other/MatrixEntityRegex.swift
  ElementX/Sources/Other/Pills/PillUtilities.swift
  ElementX/Sources/Other/SwiftUI/Views/RoomHeaderView.swift
  ElementX/Sources/Screens/RoomScreen/ComposerToolbar/CompletionSuggestionService.swift
  ElementX/Sources/Screens/RoomScreen/View/RoomScreen.swift
  ElementX/SupportingFiles/target.yml
  Tools/Sourcery/AccessibilityTests.stencil
  Tools/Sourcery/AccessibilityTests.yml
  fastlane/Fastfile
Labels: pr-build

#4337 Refactor Rageshake URL overrides and Target configuration.
  ElementX.xcodeproj/project.pbxproj
  ElementX/Sources/Application/AppCoordinator.swift
  ElementX/Sources/Application/Settings/AppSettings.swift
  ElementX/Sources/Application/Settings/ConfigurableSetting.swift
  ElementX/Sources/Application/Settings/UserPreference.swift
  ElementX/Sources/Application/TargetConfiguration.swift
  ElementX/Sources/Mocks/Generated/GeneratedMocks.swift
  ElementX/Sources/Screens/CallScreen/CallScreenViewModel.swift
  ElementX/Sources/Services/BugReport/BugReportService.swift
  ElementX/Sources/Services/BugReport/BugReportServiceProtocol.swift
  NSE/Sources/NotificationServiceExtension.swift
  NSE/SupportingFiles/target.yml
  ShareExtension/Sources/ShareExtensionViewController.swift
  ShareExtension/SupportingFiles/target.yml
  UnitTests/Sources/BugReportServiceTests.swift
  UnitTests/Sources/ConfigurableSettingTests.swift
  UnitTests/Sources/LoggingTests.swift
Labels: pr-api

#4361 Update message composer design for unencrypted rooms
  ElementX/Sources/Other/Pills/PillViewOnBubblePreviews.swift
  ElementX/Sources/Screens/MediaUploadPreviewScreen/View/MediaUploadPreviewScreen.swift
  ElementX/Sources/Screens/RoomScreen/ComposerToolbar/View/ComposerToolbar.swift
  ElementX/Sources/Screens/RoomScreen/ComposerToolbar/View/MessageComposer.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/messageComposer.Replying-iPad-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/messageComposer.Replying-iPad-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/messageComposer.Replying-iPhone-16-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/messageComposer.Replying-iPhone-16-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/messageComposer.Replying-in-thread-iPad-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/messageComposer.Replying-in-thread-iPad-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/messageComposer.Replying-in-thread-iPhone-16-en-GB.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/messageComposer.Replying-in-thread-iPhone-16-pseudo.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/messageComposer.iPad-en-GB-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/messageComposer.iPad-pseudo-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/messageComposer.iPhone-16-en-GB-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/messageComposer.iPhone-16-pseudo-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/pillViewOnBubble.iPad-en-GB-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/pillViewOnBubble.iPad-pseudo-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/pillViewOnBubble.iPhone-16-en-GB-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/pillViewOnBubble.iPhone-16-pseudo-0.png
Labels: pr-change

#4362 Add support for Space avatars.
  ElementX/Sources/Other/SwiftUI/Views/LoadableAvatarImage.swift
  ElementX/Sources/Other/SwiftUI/Views/RoomAvatarImage.swift
  ElementX/Sources/Services/Room/RoomInfoProxyProtocol.swift
  ElementX/Sources/Services/Room/RoomSummary/RoomSummary.swift
  ElementX/Sources/Services/Timeline/TimelineController/TimelineController.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/roomAvatarImage.iPad-en-GB-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/roomAvatarImage.iPad-pseudo-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/roomAvatarImage.iPhone-16-en-GB-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/roomAvatarImage.iPhone-16-pseudo-0.png
  UnitTests/Sources/RoomSummaryTests.swift
Labels: pr-wip
