Repository element-hq/element-x-ios, pull requests merged in 2025-01, with the labels that each got.

#3661 Ignore Compound and RTE from license acknowledgements.
  .githooks/pre-commit
  ElementX/SupportingFiles/Settings.bundle/Acknowledgements.plist
  ElementX/SupportingFiles/Settings.bundle/Packages/compound-design-tokens.plist
  ElementX/SupportingFiles/Settings.bundle/Packages/compound-ios.plist
  ElementX/SupportingFiles/Settings.bundle/Packages/matrix-rich-text-editor-swift.plist
Labels: pr-misc

#3662 Add the event cache to the Rust tracing configuration.
  ElementX/Sources/Other/Logging/TracingConfiguration.swift
  UnitTests/Sources/TracingConfigurationTests.swift
Labels: pr-misc

#3663 Include missing gems until Fastlane is updated for Ruby 3.4
  Gemfile.lock
  fastlane/Pluginfile
Labels: pr-build

#3667 Delay snapshotting various flakey UI tests
  UITests/Sources/AppLockSetupUITests.swift
  UITests/Sources/AppLockUITests.swift
  UITests/Sources/EncryptionResetUITests.swift
  UITests/Sources/PollFormScreenUITests.swift
  UITests/Sources/RoomMembersListScreenUITests.swift
  UITests/Sources/RoomScreenUITests.swift
  UITests/Sources/ServerSelectionUITests.swift
  UITests/Sources/StartChatScreenUITests.swift
Labels: pr-misc

#3670 Simplify how to we handle background task expirations.
  ElementX/Sources/Application/AppCoordinator.swift
Labels: pr-misc

#3688 Fix flakey `RoomMemberDetailsScreen` preview test.
  ElementX/Sources/Screens/RoomMemberDetailsScreen/View/RoomMemberDetailsScreen.swift
Labels: pr-misc

#3686 Improve how alias settings are handled, add unit tests.
  ElementX/Sources/Mocks/JoinedRoomProxyMock.swift
  ElementX/Sources/Screens/EditRoomAddressScreen/EditRoomAddressScreenModels.swift
  ElementX/Sources/Screens/EditRoomAddressScreen/EditRoomAddressScreenViewModel.swift
  ElementX/Sources/Screens/SecurityAndPrivacyScreen/SecurityAndPrivacyScreenViewModel.swift
  ElementX/Sources/Services/Room/RoomInfoProxy.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_editRoomAddressScreen-iPad-en-GB.No-alias.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_editRoomAddressScreen-iPad-pseudo.No-alias.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_editRoomAddressScreen-iPhone-16-en-GB.No-alias.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_editRoomAddressScreen-iPhone-16-pseudo.No-alias.png
  UnitTests/Sources/EditRoomAddressScreenViewModelTests.swift
Labels: pr-change

#3679 Warn and block sending on verification violation
  ElementX/Sources/Mocks/Generated/GeneratedMocks.swift
  ElementX/Sources/Screens/RoomScreen/ComposerToolbar/ComposerToolbarModels.swift
  ElementX/Sources/Screens/RoomScreen/ComposerToolbar/ComposerToolbarViewModel.swift
  ElementX/Sources/Screens/RoomScreen/ComposerToolbar/View/ComposerToolbar.swift
  ElementX/Sources/Screens/RoomScreen/ComposerToolbar/View/RoomAttachmentPicker.swift
  ElementX/Sources/Screens/RoomScreen/ComposerToolbar/View/VoiceMessageRecordingButton.swift
  ElementX/Sources/Screens/RoomScreen/RoomScreenCoordinator.swift
  ElementX/Sources/Screens/RoomScreen/RoomScreenModels.swift
  ElementX/Sources/Screens/RoomScreen/RoomScreenViewModel.swift
  ElementX/Sources/Screens/RoomScreen/View/RoomScreenFooterView.swift
  ElementX/Sources/Services/Client/ClientProxy.swift
  ElementX/Sources/Services/Client/ClientProxyProtocol.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_composerToolbar-iPad-en-GB.Disabled.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_composerToolbar-iPad-pseudo.Disabled.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_composerToolbar-iPhone-16-en-GB.Disabled.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_composerToolbar-iPhone-16-pseudo.Disabled.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomScreenFooterView-iPad-en-GB.Verification-Violation.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomScreenFooterView-iPad-pseudo.Verification-Violation.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomScreenFooterView-iPhone-16-en-GB.Verification-Violation.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomScreenFooterView-iPhone-16-pseudo.Verification-Violation.png
  UnitTests/Sources/ComposerToolbarViewModelTests.swift
Labels: pr-feature

#3692 Media browser tweaks
  ElementX/Sources/Other/SwiftUI/Layout/ViewFrameReader.swift
  ElementX/Sources/Screens/FilePreviewScreen/TimelineMediaPreviewModels.swift
  ElementX/Sources/Screens/FilePreviewScreen/TimelineMediaPreviewViewModel.swift
  ElementX/Sources/Screens/FilePreviewScreen/View/TimelineMediaPreviewDetailsView.swift
  ElementX/Sources/Screens/FilePreviewScreen/View/TimelineMediaPreviewRedactConfirmationView.swift
  ElementX/Sources/Screens/FilePreviewScreen/View/TimelineMediaPreviewScreen.swift
  ElementX/Sources/Screens/MediaEventsTimelineScreen/View/MediaEventsTimelineScreen.swift
  ElementX/Sources/Screens/Timeline/TimelineInteractionHandler.swift
  ElementX/Sources/Screens/Timeline/View/ItemMenu/TimelineItemMenuAction.swift
  ElementX/Sources/Screens/Timeline/View/ItemMenu/TimelineItemMenuActionProvider.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_mediaEventsTimelineScreen-iPad-en-GB.Empty-Files.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_mediaEventsTimelineScreen-iPad-en-GB.Empty-Media.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_mediaEventsTimelineScreen-iPad-en-GB.Files.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_mediaEventsTimelineScreen-iPad-en-GB.Media.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_mediaEventsTimelineScreen-iPad-pseudo.Empty-Files.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_mediaEventsTimelineScreen-iPad-pseudo.Empty-Media.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_mediaEventsTimelineScreen-iPad-pseudo.Files.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_mediaEventsTimelineScreen-iPad-pseudo.Media.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_mediaEventsTimelineScreen-iPhone-16-en-GB.Empty-Files.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_mediaEventsTimelineScreen-iPhone-16-en-GB.Empty-Media.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_mediaEventsTimelineScreen-iPhone-16-en-GB.Files.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_mediaEventsTimelineScreen-iPhone-16-en-GB.Media.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_mediaEventsTimelineScreen-iPhone-16-pseudo.Empty-Files.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_mediaEventsTimelineScreen-iPhone-16-pseudo.Empty-Media.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_mediaEventsTimelineScreen-iPhone-16-pseudo.Files.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_mediaEventsTimelineScreen-iPhone-16-pseudo.Media.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineMediaPreviewDetailsView-iPad-en-GB.Image.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineMediaPreviewDetailsView-iPad-en-GB.Incoming-on-Room.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineMediaPreviewDetailsView-iPad-en-GB.Loading.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineMediaPreviewDetailsView-iPad-en-GB.Unknown-type.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineMediaPreviewDetailsView-iPad-pseudo.Image.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineMediaPreviewDetailsView-iPad-pseudo.Incoming-on-Room.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineMediaPreviewDetailsView-iPad-pseudo.Loading.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineMediaPreviewDetailsView-iPad-pseudo.Unknown-type.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineMediaPreviewDetailsView-iPhone-16-en-GB.Image.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineMediaPreviewDetailsView-iPhone-16-en-GB.Incoming-on-Room.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineMediaPreviewDetailsView-iPhone-16-en-GB.Loading.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineMediaPreviewDetailsView-iPhone-16-en-GB.Unknown-type.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineMediaPreviewDetailsView-iPhone-16-pseudo.Image.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineMediaPreviewDetailsView-iPhone-16-pseudo.Incoming-on-Room.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineMediaPreviewDetailsView-iPhone-16-pseudo.Loading.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineMediaPreviewDetailsView-iPhone-16-pseudo.Unknown-type.png
  UnitTests/Sources/TimelineMediaPreviewViewModelTests.swift
Labels: pr-change

#3697 Bump the RustSDK to v25.01.22 and use the new timeline building API
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Sources/Mocks/Generated/SDKGeneratedMocks.swift
  ElementX/Sources/Services/Room/JoinedRoomProxy.swift
  project.yml
Labels: pr-misc

#3699 Make sure the Recovery Key option is shown on the IdentityConfirmationScreen when available.
  ElementX/Sources/Screens/Onboarding/IdentityConfirmationScreen/IdentityConfirmationScreenViewModel.swift
  ElementX/Sources/Screens/Onboarding/IdentityConfirmationScreen/View/IdentityConfirmationScreen.swift
Labels: pr-bugfix

#3705 Switch to CalVer (manually).
  ElementX.xcodeproj/project.pbxproj
  project.yml
Labels: pr-build

#3706 Show a blank topic as removed in the state event.
  ElementX/Sources/Services/Timeline/TimelineItems/RoomStateEventStringBuilder.swift
  UnitTests/Sources/RoomStateEventStringBuilderTests.swift
Labels: pr-bugfix

#3702 Remove unused/redundant assets.
  ElementX/Resources/Assets.xcassets/colors/brand-color.colorset/Contents.json
  ElementX/Resources/Assets.xcassets/colors/grabber.colorset/Contents.json
  ElementX/Resources/Assets.xcassets/images/home/Contents.json
  ElementX/Resources/Assets.xcassets/images/home/settings-icon-with-badge.imageset/Contents.json
  ElementX/Resources/Assets.xcassets/images/home/settings-icon-with-badge.imageset/settings-icon-with-badge-dark 1.svg
  ElementX/Resources/Assets.xcassets/images/home/settings-icon-with-badge.imageset/settings-icon-with-badge-light 1.svg
  ElementX/Resources/Assets.xcassets/images/join-room-background.imageset/Contents.json
  ElementX/Resources/Assets.xcassets/images/join-room-background.imageset/join-room-background.svg
  ElementX/Resources/Assets.xcassets/images/waiting-gradient.imageset/Contents.json
  ElementX/Resources/Assets.xcassets/images/waiting-gradient.imageset/medium-light-dark.png
  ElementX/Sources/Generated/Assets.swift
  ElementX/Sources/Other/SwiftUI/Layout/FullscreenDialog.swift
  ElementX/Sources/Screens/RoomScreen/ComposerToolbar/View/MessageComposer.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_fullscreenDialog-iPad-en-GB.Bloom.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_fullscreenDialog-iPad-pseudo.Bloom.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_fullscreenDialog-iPhone-16-en-GB.Bloom.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_fullscreenDialog-iPhone-16-pseudo.Bloom.png
Labels: pr-misc

#3708 Bump the RustSDK to 25.01.27, adopt the new emoji boosting API.
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Sources/Mocks/Generated/SDKGeneratedMocks.swift
  ElementX/Sources/Other/EmojiDetection.swift
  ElementX/Sources/Other/Extensions/ClientBuilder.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/AudioRoomTimelineView.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/FileRoomTimelineView.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/FormattedBodyText.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/ImageRoomTimelineView.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/TextRoomTimelineView.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/VideoRoomTimelineView.swift
  ElementX/Sources/Services/Timeline/TimelineItemProxy.swift
  ElementX/Sources/Services/Timeline/TimelineItems/Items/Messages/AudioRoomTimelineItem.swift
  ElementX/Sources/Services/Timeline/TimelineItems/Items/Messages/FileRoomTimelineItem.swift
  ElementX/Sources/Services/Timeline/TimelineItems/Items/Messages/ImageRoomTimelineItem.swift
  ElementX/Sources/Services/Timeline/TimelineItems/Items/Messages/TextRoomTimelineItem.swift
  ElementX/Sources/Services/Timeline/TimelineItems/Items/Messages/VideoRoomTimelineItem.swift
  ElementX/Sources/Services/Timeline/TimelineItems/RoomTimelineItemFactory.swift
  ElementX/Sources/Services/Timeline/TimelineProxy.swift
  UnitTests/Sources/EmojiDetectionTests.swift
  project.yml
Labels: pr-misc

#3714 Detect the timeline start/end when swiping through media files.
  ElementX/Resources/Localizations/en-US.lproj/Localizable.strings
  ElementX/Resources/Localizations/en.lproj/Localizable.strings
  ElementX/Sources/Generated/Strings.swift
  ElementX/Sources/Screens/FilePreviewScreen/TimelineMediaPreviewDataSource.swift
  ElementX/Sources/Screens/FilePreviewScreen/TimelineMediaPreviewModels.swift
  ElementX/Sources/Screens/FilePreviewScreen/TimelineMediaPreviewViewModel.swift
  ElementX/Sources/Screens/FilePreviewScreen/View/TimelineMediaPreviewDetailsView.swift
  ElementX/Sources/Screens/FilePreviewScreen/View/TimelineMediaPreviewRedactConfirmationView.swift
  ElementX/Sources/Screens/FilePreviewScreen/View/TimelineMediaPreviewScreen.swift
  ElementX/Sources/Services/Timeline/TimelineProxy.swift
  UnitTests/Sources/TimelineMediaPreviewDataSourceTests.swift
  UnitTests/Sources/TimelineMediaPreviewViewModelTests.swift
Labels: pr-change

#3716 Attempt to fix the every flakey app lock setup test
  UITests/Sources/AppLockSetupUITests.swift
Labels: pr-misc

#3715 Do not handle offline mode yet
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Sources/Mocks/Generated/SDKGeneratedMocks.swift
  ElementX/Sources/Services/Client/ClientProxy.swift
  project.yml
Labels: pr-api

#3721 Fastlane calendar versioning check and increase
  fastlane/Fastfile
Labels: pr-build

#3722 Ensure multiple mandatory verification flows can be ran consecutively (e.g. following encryption resets)
  ElementX/Sources/FlowCoordinators/OnboardingFlowCoordinator.swift
  ElementX/Sources/FlowCoordinators/UserSessionFlowCoordinator.swift
  ElementX/Sources/Screens/Onboarding/SessionVerificationScreen/View/SessionVerificationScreen.swift
  ElementX/Sources/Services/Session/UserSession.swift
Labels: pr-bugfix

#3723 Updated the notification string for incoming calls
  ElementX/Resources/Localizations/en-US.lproj/Localizable.strings
  ElementX/Resources/Localizations/en.lproj/Localizable.strings
  ElementX/Sources/Generated/Strings.swift
  NSE/Sources/NotificationContentBuilder.swift
Labels: pr-change

#3725 Fix missing user IDs.
  ElementX/Sources/Screens/BlockedUsersScreen/View/BlockedUsersScreen.swift
Labels: pr-bugfix
