Repository element-hq/element-x-ios, pull requests merged in 2025-02, with the labels that each got.

#3726 Fix flakey room member details screen snapshot test
  ElementX/Sources/Screens/RoomMemberDetailsScreen/View/RoomMemberDetailsScreen.swift
Labels: pr-misc

#3728 RoomTimeline… refactor (drop the `Room`).
  ElementX.xcodeproj/project.pbxproj
  ElementX/Sources/Application/AppCoordinator.swift
  ElementX/Sources/FlowCoordinators/MediaEventsTimelineFlowCoordinator.swift
  ElementX/Sources/FlowCoordinators/PinnedEventsTimelineFlowCoordinator.swift
  ElementX/Sources/FlowCoordinators/RoomFlowCoordinator.swift
  ElementX/Sources/FlowCoordinators/UserSessionFlowCoordinator.swift
  ElementX/Sources/Mocks/Generated/GeneratedMocks.swift
  ElementX/Sources/Mocks/RoomTimelineControllerFactoryMock.swift
  ElementX/Sources/Mocks/TimelineControllerFactoryMock.swift
  ElementX/Sources/Mocks/TimelineProviderMock.swift
  ElementX/Sources/Mocks/TimelineProxyMock.swift
  ElementX/Sources/Screens/FilePreviewScreen/TimelineMediaPreviewModifier.swift
  ElementX/Sources/Screens/FilePreviewScreen/View/TimelineMediaPreviewDetailsView.swift
  ElementX/Sources/Screens/FilePreviewScreen/View/TimelineMediaPreviewRedactConfirmationView.swift
  ElementX/Sources/Screens/MediaEventsTimelineScreen/MediaEventsTimelineScreenCoordinator.swift
  ElementX/Sources/Screens/MediaEventsTimelineScreen/View/MediaEventsTimelineScreen.swift
  ElementX/Sources/Screens/PinnedEventsTimelineScreen/PinnedEventsTimelineScreenCoordinator.swift
  ElementX/Sources/Screens/PinnedEventsTimelineScreen/View/PinnedEventsTimelineScreen.swift
  ElementX/Sources/Screens/RoomDetailsScreen/RoomDetailsScreenViewModel.swift
  ElementX/Sources/Screens/RoomPollsHistoryScreen/RoomPollsHistoryScreenCoordinator.swift
  ElementX/Sources/Screens/RoomPollsHistoryScreen/RoomPollsHistoryScreenViewModel.swift
  ElementX/Sources/Screens/RoomPollsHistoryScreen/View/RoomPollsHistoryScreen.swift
  ElementX/Sources/Screens/RoomScreen/RoomScreenCoordinator.swift
  ElementX/Sources/Screens/RoomScreen/RoomScreenViewModel.swift
  ElementX/Sources/Screens/RoomScreen/View/RoomScreen.swift
  ElementX/Sources/Screens/Timeline/TimelineInteractionHandler.swift
  ElementX/Sources/Screens/Timeline/TimelineViewModel.swift
  ElementX/Sources/Screens/Timeline/View/ReadReceipts/ReadReceiptsSummaryView.swift
  ElementX/Sources/Screens/Timeline/View/Style/TimelineItemBubbledStylerView.swift
  ElementX/Sources/Screens/Timeline/View/Supplementary/TimelineReadReceiptsView.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/HighlightedTimelineItemModifier.swift
  ElementX/Sources/Screens/Timeline/View/TimelineView.swift
  ElementX/Sources/Services/Room/JoinedRoomProxy.swift
  ElementX/Sources/Services/Room/RoomProxyProtocol.swift
  ElementX/Sources/Services/Timeline/TimelineController/MockTimelineController.swift
  ElementX/Sources/Services/Timeline/TimelineController/RoomTimelineControllerFactory.swift
  ElementX/Sources/Services/Timeline/TimelineController/RoomTimelineControllerFactoryProtocol.swift
  ElementX/Sources/Services/Timeline/TimelineController/TimelineController.swift
  ElementX/Sources/Services/Timeline/TimelineController/TimelineControllerFactory.swift
  ElementX/Sources/Services/Timeline/TimelineController/TimelineControllerFactoryProtocol.swift
  ElementX/Sources/Services/Timeline/TimelineController/TimelineControllerProtocol.swift
  ElementX/Sources/Services/Timeline/TimelineProvider.swift
  ElementX/Sources/Services/Timeline/TimelineProviderProtocol.swift
  ElementX/Sources/Services/Timeline/TimelineProxy.swift
  ElementX/Sources/Services/Timeline/TimelineProxyProtocol.swift
  ElementX/Sources/UITests/UITestsAppCoordinator.swift
  UnitTests/Sources/PillContextTests.swift
  UnitTests/Sources/RoomFlowCoordinatorTests.swift
  UnitTests/Sources/RoomPollsHistoryScreenViewModelTests.swift
  UnitTests/Sources/RoomScreenViewModelTests.swift
  UnitTests/Sources/TimelineMediaPreviewViewModelTests.swift
  UnitTests/Sources/TimelineViewModelTests.swift
  UnitTests/Sources/UserSessionFlowCoordinatorTests.swift
Labels: pr-misc

#3732 Knocking polishing part 1
  ElementX/Sources/Screens/JoinRoomScreen/JoinRoomScreenModels.swift
  ElementX/Sources/Screens/JoinRoomScreen/JoinRoomScreenViewModel.swift
  ElementX/Sources/Services/Room/RoomInfoProxy.swift
Labels: pr-bugfix

#3731 Refactor Rust timeline identifiers into our own.
  ElementX/Sources/Mocks/Generated/GeneratedMocks.swift
  ElementX/Sources/Other/SwiftUI/Views/LoadableImage.swift
  ElementX/Sources/Screens/FilePreviewScreen/View/TimelineMediaPreviewRedactConfirmationView.swift
  ElementX/Sources/Screens/MediaEventsTimelineScreen/MediaEventsTimelineScreenViewModel.swift
  ElementX/Sources/Screens/MediaEventsTimelineScreen/View/TimelineViews/ImageMediaEventsTimelineView.swift
  ElementX/Sources/Screens/MediaEventsTimelineScreen/View/TimelineViews/SeparatorMediaEventsTimelineView.swift
  ElementX/Sources/Screens/MediaEventsTimelineScreen/View/TimelineViews/VideoMediaEventsTimelineView.swift
  ElementX/Sources/Screens/RoomScreen/ComposerToolbar/ComposerToolbarModels.swift
  ElementX/Sources/Screens/RoomScreen/ComposerToolbar/ComposerToolbarViewModel.swift
  ElementX/Sources/Screens/RoomScreen/ComposerToolbar/View/MessageComposer.swift
  ElementX/Sources/Screens/Timeline/TimelineModels.swift
  ElementX/Sources/Screens/Timeline/TimelineTableViewController.swift
  ElementX/Sources/Screens/Timeline/TimelineViewModel.swift
  ElementX/Sources/Screens/Timeline/View/Style/TimelineItemBubbledStylerView.swift
  ElementX/Sources/Screens/Timeline/View/Style/TimelineStyler.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/CollapsibleRoomTimelineView.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/ImageRoomTimelineView.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/ReadMarkerRoomTimelineView.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/SeparatorRoomTimelineView.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/StickerRoomTimelineView.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/VideoRoomTimelineView.swift
  ElementX/Sources/Services/Room/RoomSummary/RoomSummaryProvider.swift
  ElementX/Sources/Services/Timeline/Fixtures/RoomTimelineItemFixtures.swift
  ElementX/Sources/Services/Timeline/TimelineController/MockTimelineController.swift
  ElementX/Sources/Services/Timeline/TimelineController/TimelineController.swift
  ElementX/Sources/Services/Timeline/TimelineController/TimelineControllerProtocol.swift
  ElementX/Sources/Services/Timeline/TimelineItemIdentifier.swift
  ElementX/Sources/Services/Timeline/TimelineItemProxy.swift
  ElementX/Sources/Services/Timeline/TimelineItems/Items/Virtual/PaginationIndicatorRoomTimelineItem.swift
  ElementX/Sources/Services/Timeline/TimelineItems/Items/Virtual/TimelineStartRoomTimelineItem.swift
  ElementX/Sources/Services/Timeline/TimelineItems/RoomTimelineItemViewState.swift
  ElementX/Sources/Services/Timeline/TimelineProxy.swift
  ElementX/Sources/Services/Timeline/TimelineProxyProtocol.swift
  UnitTests/Sources/ComposerToolbarViewModelTests.swift
  UnitTests/Sources/LoggingTests.swift
  UnitTests/Sources/MessageForwardingScreenViewModelTests.swift
  UnitTests/Sources/RoomScreenViewModelTests.swift
  UnitTests/Sources/TimelineItemFactoryTests.swift
  UnitTests/Sources/TimelineViewModelTests.swift
Labels: pr-misc

#3734 Add back verbose logging for the timeline provider to help debug the event cache and lazy loading
  ElementX/Sources/Services/Timeline/TimelineProvider.swift
Labels: pr-misc

#3737 updated the SDK to 25.02.04
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Sources/Screens/CreateRoom/CreateRoomViewModel.swift
  ElementX/Sources/Services/Authentication/AuthenticationService.swift
  ElementX/Sources/Services/Client/ClientError.swift
  ElementX/Sources/Services/Client/ClientProxy.swift
  ElementX/Sources/Services/Client/ClientProxyProtocol.swift
  project.yml
Labels: pr-misc

#3740 Revert unsuccessful UI test stability tweaks
  UITests/Sources/AppLockSetupUITests.swift
  UITests/Sources/AppLockUITests.swift
Labels: pr-misc

#3739 Bottom Sheet to confirm DM creation
  ElementX.xcodeproj/project.pbxproj
  ElementX/Resources/Localizations/en-US.lproj/Localizable.strings
  ElementX/Resources/Localizations/en.lproj/Localizable.strings
  ElementX/Sources/Generated/Strings.swift
  ElementX/Sources/Other/Avatars.swift
  ElementX/Sources/Screens/RoomMemberDetailsScreen/RoomMemberDetailsScreenModels.swift
  ElementX/Sources/Screens/RoomMemberDetailsScreen/RoomMemberDetailsScreenViewModel.swift
  ElementX/Sources/Screens/RoomMemberDetailsScreen/View/RoomMemberDetailsScreen.swift
  ElementX/Sources/Screens/StartChatScreen/StartChatScreenModels.swift
  ElementX/Sources/Screens/StartChatScreen/StartChatScreenViewModel.swift
  ElementX/Sources/Screens/StartChatScreen/View/SendInviteConfirmationView.swift
  ElementX/Sources/Screens/StartChatScreen/View/StartChatScreen.swift
  ElementX/Sources/Screens/UserProfileScreen/UserProfileScreenModels.swift
  ElementX/Sources/Screens/UserProfileScreen/UserProfileScreenViewModel.swift
  ElementX/Sources/Screens/UserProfileScreen/View/UserProfileScreen.swift
  ElementX/Sources/Services/Users/UserProfileProxy.swift
  PreviewTests/Sources/GeneratedPreviewTests.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_sendInviteConfirmationView-iPad-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_sendInviteConfirmationView-iPad-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_sendInviteConfirmationView-iPhone-16-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_sendInviteConfirmationView-iPhone-16-pseudo.1.png
Labels: pr-change

#3736 Use the new preview screen when tapping media on the room and pinned events screens.
  .github/workflows/danger.yml
  .swiftlint.yml
  ElementX/Sources/FlowCoordinators/MediaEventsTimelineFlowCoordinator.swift
  ElementX/Sources/Mocks/Generated/GeneratedMocks.swift
  ElementX/Sources/Screens/FilePreviewScreen/TimelineMediaPreviewDataSource.swift
  ElementX/Sources/Screens/FilePreviewScreen/TimelineMediaPreviewModels.swift
  ElementX/Sources/Screens/FilePreviewScreen/TimelineMediaPreviewViewModel.swift
  ElementX/Sources/Screens/FilePreviewScreen/View/TimelineMediaPreviewController.swift
  ElementX/Sources/Screens/FilePreviewScreen/View/TimelineMediaPreviewDetailsView.swift
  ElementX/Sources/Screens/FilePreviewScreen/View/TimelineMediaPreviewRedactConfirmationView.swift
  ElementX/Sources/Screens/MediaEventsTimelineScreen/MediaEventsTimelineScreenCoordinator.swift
  ElementX/Sources/Screens/MediaEventsTimelineScreen/MediaEventsTimelineScreenViewModel.swift
  ElementX/Sources/Screens/MediaEventsTimelineScreen/MediaEventsTimelineScreenViewModelProtocol.swift
  ElementX/Sources/Screens/PinnedEventsTimelineScreen/PinnedEventsTimelineScreenCoordinator.swift
  ElementX/Sources/Screens/PinnedEventsTimelineScreen/PinnedEventsTimelineScreenModels.swift
  ElementX/Sources/Screens/PinnedEventsTimelineScreen/PinnedEventsTimelineScreenViewModel.swift
  ElementX/Sources/Screens/PinnedEventsTimelineScreen/PinnedEventsTimelineScreenViewModelProtocol.swift
  ElementX/Sources/Screens/PinnedEventsTimelineScreen/View/PinnedEventsTimelineScreen.swift
  ElementX/Sources/Screens/RoomScreen/RoomScreenCoordinator.swift
  ElementX/Sources/Screens/RoomScreen/RoomScreenModels.swift
  ElementX/Sources/Screens/RoomScreen/RoomScreenViewModel.swift
  ElementX/Sources/Screens/RoomScreen/RoomScreenViewModelProtocol.swift
  ElementX/Sources/Screens/RoomScreen/View/RoomScreen.swift
  ElementX/Sources/Screens/Timeline/TimelineInteractionHandler.swift
  ElementX/Sources/Screens/Timeline/TimelineModels.swift
  ElementX/Sources/Screens/Timeline/TimelineViewModel.swift
  ElementX/Sources/Screens/Timeline/TimelineViewModelProtocol.swift
  ElementX/Sources/Screens/Timeline/View/ItemMenu/TimelineItemMenuActionProvider.swift
  ElementX/Sources/Services/Client/ClientProxy.swift
  ElementX/Sources/Services/Client/ClientProxyProtocol.swift
  ElementX/Sources/Services/Room/JoinedRoomProxy.swift
  ElementX/Sources/Services/Room/RoomProxyProtocol.swift
  ElementX/Sources/Services/Timeline/TimelineController/MockTimelineController.swift
  ElementX/Sources/Services/Timeline/TimelineController/TimelineController.swift
  ElementX/Sources/Services/Timeline/TimelineController/TimelineControllerFactory.swift
  ElementX/Sources/Services/Timeline/TimelineController/TimelineControllerFactoryProtocol.swift
  ElementX/Sources/Services/Timeline/TimelineController/TimelineControllerProtocol.swift
  ElementX/Sources/Services/Timeline/TimelineItems/RoomStateEventStringBuilder.swift
  ElementX/Sources/Services/Timeline/TimelineItems/RoomTimelineItemFactory.swift
  ElementX/Sources/Services/Timeline/TimelineProxy.swift
  ElementX/Sources/Services/Timeline/TimelineProxyProtocol.swift
  UnitTests/Sources/HomeScreenRoomTests.swift
  UnitTests/Sources/TimelineMediaPreviewDataSourceTests.swift
  UnitTests/Sources/TimelineMediaPreviewViewModelTests.swift
  ci_scripts/ci_common.sh
Labels: pr-change

#3738 Knocking feature polishing part 2
  ElementX.xcodeproj/project.pbxproj
  ElementX/Sources/Mocks/Generated/GeneratedMocks.swift
  ElementX/Sources/Mocks/Generated/SDKGeneratedMocks.swift
  ElementX/Sources/Mocks/RoomPreviewProxyMock.swift
  ElementX/Sources/Screens/JoinRoomScreen/JoinRoomScreenModels.swift
  ElementX/Sources/Screens/JoinRoomScreen/JoinRoomScreenViewModel.swift
  ElementX/Sources/Screens/JoinRoomScreen/View/JoinRoomScreen.swift
  ElementX/Sources/Services/Client/ClientProxy.swift
  ElementX/Sources/Services/Client/ClientProxyProtocol.swift
  ElementX/Sources/Services/Room/RoomPreview/RoomPreviewProxy.swift
  ElementX/Sources/Services/Room/RoomPreview/RoomPreviewProxyProtocol.swift
  ElementX/Sources/Services/Room/RoomProxyProtocol.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_joinRoomScreen-iPad-en-GB.Banned.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_joinRoomScreen-iPad-en-GB.Forbidden.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_joinRoomScreen-iPad-en-GB.InvitedDM.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_joinRoomScreen-iPad-en-GB.Unknown.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_joinRoomScreen-iPad-pseudo.Banned.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_joinRoomScreen-iPad-pseudo.Forbidden.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_joinRoomScreen-iPad-pseudo.InvitedDM.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_joinRoomScreen-iPad-pseudo.Unknown.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_joinRoomScreen-iPhone-16-en-GB.Banned.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_joinRoomScreen-iPhone-16-en-GB.Forbidden.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_joinRoomScreen-iPhone-16-en-GB.InvitedDM.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_joinRoomScreen-iPhone-16-en-GB.Unknown.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_joinRoomScreen-iPhone-16-pseudo.Banned.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_joinRoomScreen-iPhone-16-pseudo.Forbidden.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_joinRoomScreen-iPhone-16-pseudo.InvitedDM.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_joinRoomScreen-iPhone-16-pseudo.Unknown.png
Labels: pr-wip

#3744 Added the banned room proxy
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Sources/Mocks/BannedRoomProxyMock.swift
  ElementX/Sources/Mocks/Generated/GeneratedMocks.swift
  ElementX/Sources/Screens/JoinRoomScreen/JoinRoomScreenModels.swift
  ElementX/Sources/Screens/JoinRoomScreen/JoinRoomScreenViewModel.swift
  ElementX/Sources/Screens/JoinRoomScreen/View/JoinRoomScreen.swift
  ElementX/Sources/Services/Client/ClientProxy.swift
  ElementX/Sources/Services/Room/BannedRoomProxy.swift
  ElementX/Sources/Services/Room/RoomPreview/RoomPreviewProxy.swift
  ElementX/Sources/Services/Room/RoomPreview/RoomPreviewProxyProtocol.swift
  ElementX/Sources/Services/Room/RoomProxyProtocol.swift
  project.yml
Labels: pr-wip

#3741 Fix some concurrency warnings, update missed licence headers.
  .githooks/pre-push
  ElementX/Sources/Application/AppCoordinatorProtocol.swift
  ElementX/Sources/Other/Extensions/Snapshotting.swift
  ElementX/Sources/Other/SwiftUI/ViewModel/BindableState.swift
  ElementX/Sources/Other/UserIndicator/UserIndicatorController.swift
  ElementX/Sources/Screens/Authentication/SoftLogoutScreen/SoftLogoutScreenViewModelProtocol.swift
  ElementX/Sources/Screens/Authentication/WebRegistrationScreen/View/WebRegistrationScreen.swift
  ElementX/Sources/Screens/CallScreen/View/CallScreen.swift
  ElementX/Sources/Screens/ReportContentScreen/ReportContentScreenViewModelProtocol.swift
  ElementX/Sources/Screens/ResolveVerifiedUserSendFailureScreen/ResolveVerifiedUserSendFailureScreenCoordinator.swift
  ElementX/Sources/Screens/ResolveVerifiedUserSendFailureScreen/ResolveVerifiedUserSendFailureScreenModels.swift
  ElementX/Sources/Screens/ResolveVerifiedUserSendFailureScreen/ResolveVerifiedUserSendFailureScreenViewModel.swift
  ElementX/Sources/Screens/ResolveVerifiedUserSendFailureScreen/ResolveVerifiedUserSendFailureScreenViewModelProtocol.swift
  ElementX/Sources/Screens/ResolveVerifiedUserSendFailureScreen/View/ResolveVerifiedUserSendFailureScreen.swift
  ElementX/Sources/Screens/RoomScreen/ComposerToolbar/ComposerToolbarViewModelProtocol.swift
  ElementX/Sources/Screens/RoomScreen/RoomScreenViewModelProtocol.swift
  ElementX/Sources/Services/Client/ClientProxy.swift
  ElementX/Sources/Services/ComposerDraft/ComposerDraftService.swift
  ElementX/Sources/Services/Timeline/TimelineController/TimelineController.swift
  ElementX/Sources/Services/Timeline/TimelineItems/RoomTimelineItemFactoryProtocol.swift
  UnitTests/Sources/ResolveVerifiedUserSendFailureScreenViewModelTests.swift
  UnitTests/Sources/ServerConfigurationScreenViewStateTests.swift
Labels: pr-misc

#3746 Fix a crash in the media browser by storing the active timeline context.
  ElementX/Sources/Screens/MediaEventsTimelineScreen/MediaEventsTimelineScreenModels.swift
  ElementX/Sources/Screens/MediaEventsTimelineScreen/MediaEventsTimelineScreenViewModel.swift
  ElementX/Sources/Screens/MediaEventsTimelineScreen/View/MediaEventsTimelineScreen.swift
Labels: pr-bugfix

#3748 Added a delayed loading when opening a room
  ElementX/Sources/FlowCoordinators/RoomFlowCoordinator.swift
Labels: pr-change

#3743 Updated Bottom Sheet message string
  ElementX/Resources/Localizations/en-US.lproj/Localizable.strings
  ElementX/Resources/Localizations/en.lproj/Localizable.strings
  ElementX/Sources/Generated/Strings.swift
  ElementX/Sources/Screens/StartChatScreen/View/SendInviteConfirmationView.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_sendInviteConfirmationView-iPad-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_sendInviteConfirmationView-iPhone-16-pseudo.1.png
Labels: pr-change

#3751 Updated File and Media timeline view
  ElementX/Sources/Other/Extensions/String.swift
  ElementX/Sources/Screens/Timeline/View/TimelineItemViews/FileRoomTimelineView.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_audioMediaEventsTimelineView-iPad-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_audioMediaEventsTimelineView-iPad-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_audioMediaEventsTimelineView-iPhone-16-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_audioMediaEventsTimelineView-iPhone-16-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_audioRoomTimelineView-iPad-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_audioRoomTimelineView-iPad-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_audioRoomTimelineView-iPhone-16-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_audioRoomTimelineView-iPhone-16-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_fileMediaEventsTimelineView-iPad-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_fileMediaEventsTimelineView-iPad-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_fileMediaEventsTimelineView-iPhone-16-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_fileMediaEventsTimelineView-iPhone-16-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_fileRoomTimelineView-iPad-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_fileRoomTimelineView-iPad-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_fileRoomTimelineView-iPhone-16-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_fileRoomTimelineView-iPhone-16-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_mediaEventsTimelineScreen-iPad-en-GB.Files.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_mediaEventsTimelineScreen-iPad-pseudo.Files.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_mediaEventsTimelineScreen-iPhone-16-en-GB.Files.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_mediaEventsTimelineScreen-iPhone-16-pseudo.Files.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemBubbledStylerView-iPad-en-GB.Pinned-messages.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemBubbledStylerView-iPad-en-GB.Thread-decorator.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemBubbledStylerView-iPad-pseudo.Pinned-messages.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemBubbledStylerView-iPad-pseudo.Thread-decorator.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemBubbledStylerView-iPhone-16-en-GB.Pinned-messages.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemBubbledStylerView-iPhone-16-en-GB.Thread-decorator.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemBubbledStylerView-iPhone-16-pseudo.Pinned-messages.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_timelineItemBubbledStylerView-iPhone-16-pseudo.Thread-decorator.png
Labels: pr-change

#3756 Add a test dependabot.yml file and see to see what it picks up.
  .github/dependabot.yml
Labels: pr-build

#3757 Delete dependabot.yml - it doesn't work for Xcode projects (or XcodeGen).
  .github/dependabot.yml
Labels: pr-build

#3750 Fix a bug where the preview controller breaks when swiping quickly.
  ElementX/Sources/Screens/FilePreviewScreen/View/TimelineMediaPreviewController.swift
Labels: pr-bugfix

#3776 Refactor how notifications are preprocessed and be explicit about which ones are supposed to be displayed or discarded
  NSE/Sources/NotificationServiceExtension.swift
Labels: pr-misc

#3779 Knock Polishing part 4
  ElementX/Resources/Localizations/en-US.lproj/Localizable.strings
  ElementX/Resources/Localizations/en.lproj/Localizable.strings
  ElementX/Sources/Generated/Strings.swift
  ElementX/Sources/Screens/JoinRoomScreen/JoinRoomScreenModels.swift
  ElementX/Sources/Screens/JoinRoomScreen/JoinRoomScreenViewModel.swift
  ElementX/Sources/Screens/JoinRoomScreen/View/JoinRoomScreen.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_joinRoomScreen-iPad-en-GB.Banned.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_joinRoomScreen-iPad-en-GB.Forbidden.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_joinRoomScreen-iPad-en-GB.InviteRequired.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_joinRoomScreen-iPad-en-GB.Invited.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_joinRoomScreen-iPad-en-GB.InvitedDM.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_joinRoomScreen-iPad-en-GB.Joinable.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_joinRoomScreen-iPad-en-GB.Knockable.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_joinRoomScreen-iPad-en-GB.Restricted.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_joinRoomScreen-iPad-en-GB.Unknown.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_joinRoomScreen-iPad-pseudo.Banned.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_joinRoomScreen-iPad-pseudo.Forbidden.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_joinRoomScreen-iPad-pseudo.InviteRequired.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_joinRoomScreen-iPad-pseudo.Invited.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_joinRoomScreen-iPad-pseudo.InvitedDM.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_joinRoomScreen-iPad-pseudo.Joinable.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_joinRoomScreen-iPad-pseudo.Knockable.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_joinRoomScreen-iPad-pseudo.Restricted.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_joinRoomScreen-iPad-pseudo.Unknown.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_joinRoomScreen-iPhone-16-en-GB.Banned.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_joinRoomScreen-iPhone-16-en-GB.Forbidden.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_joinRoomScreen-iPhone-16-en-GB.InviteRequired.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_joinRoomScreen-iPhone-16-en-GB.Invited.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_joinRoomScreen-iPhone-16-en-GB.InvitedDM.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_joinRoomScreen-iPhone-16-en-GB.Joinable.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_joinRoomScreen-iPhone-16-en-GB.Knockable.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_joinRoomScreen-iPhone-16-en-GB.Restricted.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_joinRoomScreen-iPhone-16-en-GB.Unknown.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_joinRoomScreen-iPhone-16-pseudo.Banned.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_joinRoomScreen-iPhone-16-pseudo.Forbidden.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_joinRoomScreen-iPhone-16-pseudo.InviteRequired.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_joinRoomScreen-iPhone-16-pseudo.Invited.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_joinRoomScreen-iPhone-16-pseudo.InvitedDM.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_joinRoomScreen-iPhone-16-pseudo.Joinable.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_joinRoomScreen-iPhone-16-pseudo.Knockable.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_joinRoomScreen-iPhone-16-pseudo.Restricted.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_joinRoomScreen-iPhone-16-pseudo.Unknown.png
  UnitTests/Sources/JoinRoomScreenViewModelTests.swift
Labels: pr-wip

#3782 Log whether a notification is expected to make a noise.
  ElementX/Sources/Mocks/Generated/GeneratedMocks.swift
  ElementX/Sources/Services/Notification/Manager/NotificationManager.swift
  ElementX/Sources/Services/Notification/Manager/UserNotificationCenterProtocol.swift
  NSE/Sources/NotificationContentBuilder.swift
  UnitTests/Sources/NotificationManager/NotificationManagerTests.swift
Labels: pr-misc

#3791 Update strings after resolving some duplicities.
  ElementX/Resources/Localizations/en-US.lproj/Localizable.strings
  ElementX/Resources/Localizations/en.lproj/Localizable.strings
  ElementX/Sources/Generated/Strings.swift
  ElementX/Sources/Screens/FilePreviewScreen/View/TimelineMediaPreviewRedactConfirmationView.swift
  Package.resolved
Labels: pr-misc

#3787 Updated dev options screen for ask to join
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/View/DeveloperOptionsScreen.swift
Labels: pr-wip

#3796 Stop the message composer from randomly changing the cursor position
  ElementX/Sources/Screens/RoomScreen/ComposerToolbar/View/MessageComposerTextField.swift
Labels: pr-bugfix

#3801 Remove support for the sliding sync proxy.
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Resources/Localizations/en-US.lproj/Localizable.strings
  ElementX/Resources/Localizations/en.lproj/Localizable.strings
  ElementX/Sources/Application/AppSettings.swift
  ElementX/Sources/FlowCoordinators/SettingsFlowCoordinator.swift
  ElementX/Sources/Generated/Strings.swift
  ElementX/Sources/Mocks/ClientProxyMock.swift
  ElementX/Sources/Mocks/Generated/GeneratedMocks.swift
  ElementX/Sources/Other/Extensions/ClientBuilder.swift
  ElementX/Sources/Screens/HomeScreen/HomeScreenModels.swift
  ElementX/Sources/Screens/HomeScreen/HomeScreenViewModel.swift
  ElementX/Sources/Screens/HomeScreen/View/HomeScreenContent.swift
  ElementX/Sources/Screens/HomeScreen/View/HomeScreenSlidingSyncMigrationBanner.swift
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/DeveloperOptionsScreenCoordinator.swift
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/DeveloperOptionsScreenModels.swift
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/DeveloperOptionsScreenViewModel.swift
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/View/DeveloperOptionsScreen.swift
  ElementX/Sources/Services/Authentication/AuthenticationClientBuilder.swift
  ElementX/Sources/Services/Client/ClientProxy.swift
  ElementX/Sources/Services/Client/ClientProxyProtocol.swift
  ElementX/Sources/Services/Keychain/KeychainController.swift
  ElementX/Sources/Services/UserSession/RestorationToken.swift
  ElementX/Sources/Services/UserSession/UserSessionStore.swift
  Package.resolved
  PreviewTests/Sources/GeneratedPreviewTests.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_homeScreenSlidingSyncMigrationBanner-iPad-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_homeScreenSlidingSyncMigrationBanner-iPad-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_homeScreenSlidingSyncMigrationBanner-iPhone-16-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_homeScreenSlidingSyncMigrationBanner-iPhone-16-pseudo.1.png
  UnitTests/Sources/KeychainControllerTests.swift
  UnitTests/Sources/RestorationTokenTests.swift
  project.yml
Labels: pr-api

#3800 Hide the unread dot after previewing an invite.
  ElementX/Sources/Application/AppSettings.swift
  ElementX/Sources/Mocks/InvitedRoomProxyMock.swift
  ElementX/Sources/Mocks/RoomSummaryProviderMock.swift
  ElementX/Sources/Screens/HomeScreen/HomeScreenModels.swift
  ElementX/Sources/Screens/HomeScreen/HomeScreenViewModel.swift
  ElementX/Sources/Screens/HomeScreen/View/HomeScreenInviteCell.swift
  ElementX/Sources/Screens/HomeScreen/View/HomeScreenKnockedCell.swift
  ElementX/Sources/Screens/JoinRoomScreen/JoinRoomScreenViewModel.swift
  ElementX/Sources/Services/Room/RoomSummary/RoomSummary.swift
  ElementX/Sources/Services/Room/RoomSummary/RoomSummaryProvider.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_homeScreenKnockedCell-iPad-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_homeScreenKnockedCell-iPad-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_homeScreenKnockedCell-iPhone-16-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_homeScreenKnockedCell-iPhone-16-pseudo.1.png
  UnitTests/Sources/HomeScreenRoomTests.swift
  UnitTests/Sources/HomeScreenViewModelTests.swift
  UnitTests/Sources/JoinRoomScreenViewModelTests.swift
  UnitTests/Sources/LoggingTests.swift
  UnitTests/Sources/RoomSummaryTests.swift
Labels: pr-change

#3804 Rename a couple of missed isEncryptedOneToOneRoom properties.
  ElementX/Sources/Screens/FilePreviewScreen/TimelineMediaPreviewViewModel.swift
  ElementX/Sources/Screens/PinnedEventsTimelineScreen/View/PinnedEventsTimelineScreen.swift
  ElementX/Sources/Screens/RoomScreen/View/RoomScreen.swift
  ElementX/Sources/Screens/Timeline/TimelineModels.swift
  ElementX/Sources/Screens/Timeline/TimelineViewModel.swift
  ElementX/Sources/Screens/Timeline/View/Style/TimelineItemBubbledStylerView.swift
Labels: pr-misc

#3808 Add a couple of extra logs around the state of call ringing notifications.
  NSE/Sources/NotificationServiceExtension.swift
Labels: pr-misc

#3813 Show error screens in group calls
  ElementX/Sources/Services/ElementCall/ElementCallWidgetDriver.swift
Labels: T-Defect, Trigger-PR-Build, X-Blocked, pr-feature

#3815 Update translations (manually).
  ElementX/Resources/Localizations/be.lproj/Localizable.strings
  ElementX/Resources/Localizations/bg.lproj/Localizable.strings
  ElementX/Resources/Localizations/cs.lproj/Localizable.strings
  ElementX/Resources/Localizations/de.lproj/Localizable.strings
  ElementX/Resources/Localizations/el.lproj/Localizable.strings
  ElementX/Resources/Localizations/en-US.lproj/Localizable.strings
  ElementX/Resources/Localizations/en.lproj/Localizable.strings
  ElementX/Resources/Localizations/es.lproj/Localizable.strings
  ElementX/Resources/Localizations/et.lproj/Localizable.strings
  ElementX/Resources/Localizations/fa.lproj/Localizable.strings
  ElementX/Resources/Localizations/fi.lproj/Localizable.strings
  ElementX/Resources/Localizations/fr.lproj/Localizable.strings
  ElementX/Resources/Localizations/hu.lproj/Localizable.strings
  ElementX/Resources/Localizations/id.lproj/Localizable.strings
  ElementX/Resources/Localizations/it.lproj/Localizable.strings
  ElementX/Resources/Localizations/ka.lproj/Localizable.strings
  ElementX/Resources/Localizations/nb.lproj/InfoPlist.strings
  ElementX/Resources/Localizations/nb.lproj/Localizable.strings
  ElementX/Resources/Localizations/nl.lproj/Localizable.strings
  ElementX/Resources/Localizations/pl.lproj/Localizable.strings
  ElementX/Resources/Localizations/pt-BR.lproj/Localizable.strings
  ElementX/Resources/Localizations/pt.lproj/Localizable.strings
  ElementX/Resources/Localizations/ro.lproj/Localizable.strings
  ElementX/Resources/Localizations/ru.lproj/Localizable.strings
  ElementX/Resources/Localizations/sk.lproj/Localizable.strings
  ElementX/Resources/Localizations/sv.lproj/Localizable.strings
  ElementX/Resources/Localizations/tr.lproj/Localizable.strings
  ElementX/Resources/Localizations/uk.lproj/Localizable.strings
  ElementX/Resources/Localizations/uz.lproj/Localizable.strings
  ElementX/Resources/Localizations/zh-Hans.lproj/Localizable.strings
  ElementX/Resources/Localizations/zh-Hant-TW.lproj/Localizable.strings
  ElementX/Sources/Generated/Strings.swift
Labels: pr-i18n

#3816 Fix various UI test snapshots following changes to the development assets
  UITests/Sources/__Snapshots__/Application/roomLayoutBottom-0-iPad-18-1-en-GB.UI.png
  UITests/Sources/__Snapshots__/Application/roomLayoutBottom-0-iPhone-18-1-en-GB.UI.png
  UITests/Sources/__Snapshots__/Application/roomLayoutBottom-1-iPad-18-1-en-GB.UI.png
  UITests/Sources/__Snapshots__/Application/roomLayoutBottom-1-iPhone-18-1-en-GB.UI.png
  UITests/Sources/__Snapshots__/Application/roomLayoutHighlight-0-iPad-18-1-en-GB.UI.png
  UITests/Sources/__Snapshots__/Application/roomLayoutHighlight-0-iPhone-18-1-en-GB.UI.png
  UITests/Sources/__Snapshots__/Application/roomLayoutTop-iPad-18-1-en-GB.UI.png
  UITests/Sources/__Snapshots__/Application/roomLayoutTop-iPhone-18-1-en-GB.UI.png
  UITests/Sources/__Snapshots__/Application/roomSmallTimeline-iPad-18-1-en-GB.UI.png
  UITests/Sources/__Snapshots__/Application/roomSmallTimeline-iPhone-18-1-en-GB.UI.png
  UITests/Sources/__Snapshots__/Application/roomSmallTimelineIncomingAndSmallPagination-iPad-18-1-en-GB.UI.png
  UITests/Sources/__Snapshots__/Application/roomSmallTimelineIncomingAndSmallPagination-iPhone-18-1-en-GB.UI.png
  UITests/Sources/__Snapshots__/Application/roomSmallTimelineLargePagination-iPad-18-1-en-GB.UI.png
  UITests/Sources/__Snapshots__/Application/roomSmallTimelineLargePagination-iPhone-18-1-en-GB.UI.png
  UITests/Sources/__Snapshots__/Application/roomSmallTimelineWithReadReceipts-iPad-18-1-en-GB.UI.png
  UITests/Sources/__Snapshots__/Application/roomSmallTimelineWithReadReceipts-iPhone-18-1-en-GB.UI.png
  UITests/Sources/__Snapshots__/Application/roomWithDisclosedPolls-iPad-18-1-en-GB.UI.png
  UITests/Sources/__Snapshots__/Application/roomWithDisclosedPolls-iPhone-18-1-en-GB.UI.png
  UITests/Sources/__Snapshots__/Application/roomWithOutgoingPolls-iPad-18-1-en-GB.UI.png
  UITests/Sources/__Snapshots__/Application/roomWithOutgoingPolls-iPhone-18-1-en-GB.UI.png
  UITests/Sources/__Snapshots__/Application/roomWithUndisclosedPolls-iPad-18-1-en-GB.UI.png
  UITests/Sources/__Snapshots__/Application/roomWithUndisclosedPolls-iPhone-18-1-en-GB.UI.png
  UITests/Sources/__Snapshots__/Application/userSessionScreen-1-iPad-18-1-en-GB.UI.png
  UITests/Sources/__Snapshots__/Application/userSessionScreen-1-iPhone-18-1-en-GB.UI.png
  UITests/Sources/__Snapshots__/Application/userSessionScreen-2-iPad-18-1-en-GB.UI.png
  UITests/Sources/__Snapshots__/Application/userSessionScreen-2-iPhone-18-1-en-GB.UI.png
  UITests/Sources/__Snapshots__/Application/userSessionScreen-3-iPad-18-1-en-GB.UI.png
  UITests/Sources/__Snapshots__/Application/userSessionScreen-3-iPhone-18-1-en-GB.UI.png
  UITests/Sources/__Snapshots__/Application/userSessionScreenReply-iPad-18-1-en-GB.UI.png
  UITests/Sources/__Snapshots__/Application/userSessionScreenReply-iPhone-18-1-en-GB.UI.png
Labels: pr-misc

#3817 Use alternative summary provider when listening to knocked membership change
  ElementX/Sources/Screens/JoinRoomScreen/JoinRoomScreenViewModel.swift
Labels: pr-bugfix

#3819 Revert "Show error screens in group calls"
  ElementX/Sources/Services/ElementCall/ElementCallWidgetDriver.swift
Labels: pr-misc

#3820 Configure diagnostics (and MapLibre) using Pkl.
  .githooks/post-checkout
  .github/workflows/unit_tests_enterprise.yml
  .gitignore
  .swiftformat
  ElementX.xcodeproj/project.pbxproj
  ElementX/Sources/Application/AppSettings.swift
  ElementX/Sources/Other/InfoPlistReader.swift
  ElementX/SupportingFiles/Info.plist
  ElementX/SupportingFiles/secrets.xcconfig
  ElementX/SupportingFiles/target.yml
  Secrets/Secrets.pkl
  Secrets/Secrets.swift
  ci_scripts/ci_common.sh
  docs/FORKING.md
  fastlane/Fastfile
  fastlane/README.md
  project.yml
  secrets.xcconfig
Labels: pr-build

#3821 Don't set the room topic when creating a room if it is blank.
  ElementX/Sources/Screens/CreateRoom/CreateRoomViewModel.swift
  ElementX/Sources/Screens/CreateRoom/View/CreateRoomScreen.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_createRoom-iPhone-16-en-GB.Create-Public-Room-existing-alias.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_createRoom-iPhone-16-en-GB.Create-Public-Room-invalid-alias.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_createRoom-iPhone-16-en-GB.Create-Public-Room.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_createRoom-iPhone-16-en-GB.Create-Room-without-users.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_createRoom-iPhone-16-en-GB.Create-Room.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_createRoom-iPhone-16-pseudo.Create-Public-Room-existing-alias.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_createRoom-iPhone-16-pseudo.Create-Public-Room-invalid-alias.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_createRoom-iPhone-16-pseudo.Create-Public-Room.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_createRoom-iPhone-16-pseudo.Create-Room-without-users.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_createRoom-iPhone-16-pseudo.Create-Room.png
  UnitTests/Sources/CreateRoomViewModelTests.swift
Labels: pr-bugfix

#3826 Cache account management URL
  ElementX/Sources/Services/Client/ClientProxy.swift
  ElementX/Sources/Services/Client/ClientProxyProtocol.swift
Labels: pr-bugfix

#3833 Fix editing messages not placing the cursor at the end of the text
  ElementX/Sources/Screens/RoomScreen/ComposerToolbar/View/MessageComposerTextField.swift
Labels: pr-bugfix

#3829 Fix a bug where you couldn't log in to matrix.org
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  project.yml
Labels: pr-bugfix

#3844 Increase the time before we show loading indicators when processing user session and flow coordinators routes
  ElementX/Sources/FlowCoordinators/RoomFlowCoordinator.swift
  ElementX/Sources/FlowCoordinators/UserSessionFlowCoordinator.swift
Labels: pr-misc

#3854 show "Room" for unresolved event permalinks
  ElementX/Sources/Other/Pills/PillTextAttachmentData.swift
  ElementX/Sources/Screens/Timeline/TimelineViewModel.swift
  UnitTests/Sources/PillContextTests.swift
Labels: pr-bugfix

#3853 Private rooms are now created with the `.invited` room history visibility
  ElementX/Sources/Services/Client/ClientProxy.swift
Labels: pr-bugfix

#3840 Join room by address
  ElementX.xcodeproj/project.pbxproj
  ElementX/Resources/Localizations/en-US.lproj/Localizable.strings
  ElementX/Resources/Localizations/en.lproj/Localizable.strings
  ElementX/Sources/FlowCoordinators/UserSessionFlowCoordinator.swift
  ElementX/Sources/Generated/Strings.swift
  ElementX/Sources/Other/SwiftUI/Styles/ElementTextFieldStyle.swift
  ElementX/Sources/Screens/Authentication/AuthenticationTextFieldStyle.swift
  ElementX/Sources/Screens/Authentication/LoginScreen/View/LoginScreen.swift
  ElementX/Sources/Screens/Authentication/ServerSelectionScreen/View/ServerSelectionScreen.swift
  ElementX/Sources/Screens/Authentication/SoftLogoutScreen/View/SoftLogoutScreen.swift
  ElementX/Sources/Screens/HomeScreen/HomeScreenCoordinator.swift
  ElementX/Sources/Screens/HomeScreen/HomeScreenModels.swift
  ElementX/Sources/Screens/HomeScreen/HomeScreenViewModel.swift
  ElementX/Sources/Screens/HomeScreen/View/HomeScreenRoomList.swift
  ElementX/Sources/Screens/HomeScreen/View/RoomDirectorySearchView.swift
  ElementX/Sources/Screens/StartChatScreen/StartChatScreenCoordinator.swift
  ElementX/Sources/Screens/StartChatScreen/StartChatScreenModels.swift
  ElementX/Sources/Screens/StartChatScreen/StartChatScreenViewModel.swift
  ElementX/Sources/Screens/StartChatScreen/View/JoinRoomByAddressView.swift
  ElementX/Sources/Screens/StartChatScreen/View/StartChatScreen.swift
  PreviewTests/Sources/GeneratedPreviewTests.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_elementTextFieldStyle-iPad-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_elementTextFieldStyle-iPad-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_elementTextFieldStyle-iPhone-16-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_elementTextFieldStyle-iPhone-16-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_joinRoomByAddressView-iPad-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_joinRoomByAddressView-iPad-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_joinRoomByAddressView-iPhone-16-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_joinRoomByAddressView-iPhone-16-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomDirectorySearchView-iPad-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomDirectorySearchView-iPad-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomDirectorySearchView-iPhone-16-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_roomDirectorySearchView-iPhone-16-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_serverSelection-iPad-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_serverSelection-iPad-en-GB.2.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_serverSelection-iPad-en-GB.3.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_serverSelection-iPad-en-GB.4.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_serverSelection-iPad-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_serverSelection-iPad-pseudo.2.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_serverSelection-iPad-pseudo.3.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_serverSelection-iPad-pseudo.4.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_serverSelection-iPhone-16-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_serverSelection-iPhone-16-en-GB.2.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_serverSelection-iPhone-16-en-GB.3.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_serverSelection-iPhone-16-en-GB.4.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_serverSelection-iPhone-16-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_serverSelection-iPhone-16-pseudo.2.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_serverSelection-iPhone-16-pseudo.3.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_serverSelection-iPhone-16-pseudo.4.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_startChatScreen-iPad-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_startChatScreen-iPad-pseudo.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_startChatScreen-iPhone-16-en-GB.1.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/test_startChatScreen-iPhone-16-pseudo.1.png
  UnitTests/Sources/StartChatViewModelTests.swift
Labels: pr-feature

#3855 Bump the RustSDK to v25.02.28
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Sources/Services/Timeline/TimelineProxy.swift
  project.yml
Labels: pr-misc
