Repository element-hq/element-x-ios, pull requests merged in 2025-08, with the labels that each got.

#4370 Delegate the sending of call notifications to Element Call
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Sources/FlowCoordinators/ChatsFlowCoordinator.swift
  ElementX/Sources/Mocks/Generated/GeneratedMocks.swift
  ElementX/Sources/Mocks/Generated/SDKGeneratedMocks.swift
  ElementX/Sources/Mocks/JoinedRoomProxyMock.swift
  ElementX/Sources/Screens/CallScreen/CallScreenViewModel.swift
  ElementX/Sources/Screens/CallScreen/View/CallScreen.swift
  ElementX/Sources/Services/ElementCall/ElementCallConfiguration.swift
  ElementX/Sources/Services/ElementCall/ElementCallWidgetDriver.swift
  ElementX/Sources/Services/Room/JoinedRoomProxy.swift
  ElementX/Sources/Services/Room/RoomProxyProtocol.swift
  project.yml
Labels: pr-bugfix

#4379 Handle `TimelineDiff` as an enum with associated values.
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Sources/Mocks/Generated/SDKGeneratedMocks.swift
  ElementX/Sources/Mocks/TimelineProviderMock.swift
  ElementX/Sources/Services/Timeline/TimelineItemProvider.swift
  ElementX/Sources/Services/UserSession/UserSessionStore.swift
  NSE/Sources/NSEUserSession.swift
  project.yml
Labels: pr-api

#4373 Implement tab bar badges, visibility and selection.
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Sources/Application/Navigation/NavigationTabCoordinator.swift
  ElementX/Sources/FlowCoordinators/UserSessionFlowCoordinator.swift
  UnitTests/Sources/NavigationTabCoordinatorTests.swift
  project.yml
Labels: pr-wip

#4405 Update the SDK.
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Sources/Mocks/Generated/SDKGeneratedMocks.swift
  ElementX/Sources/Other/Extensions/ClientBuilder.swift
  project.yml
Labels: pr-misc

#4413 Add a workaround to include some via parameters for room v12 tombstone links.
  ElementX/Sources/FlowCoordinators/RoomFlowCoordinator.swift
  ElementX/Sources/Screens/RoomScreen/RoomScreenCoordinator.swift
  ElementX/Sources/Screens/RoomScreen/RoomScreenModels.swift
  ElementX/Sources/Screens/RoomScreen/RoomScreenViewModel.swift
  ElementX/Sources/Screens/Timeline/TimelineModels.swift
  ElementX/Sources/Screens/Timeline/TimelineViewModel.swift
  ElementX/Sources/Services/Room/RoomProxyProtocol.swift
Labels: pr-bugfix

#4412 Add a SpaceScreen for listing rooms and subspaces within a space.
  AccessibilityTests/Sources/GeneratedAccessibilityTests.swift
  ElementX.xcodeproj/project.pbxproj
  ElementX/Resources/Localizations/en.lproj/Localizable.strings
  ElementX/Sources/Generated/Strings.swift
  ElementX/Sources/Mocks/SpaceRoomListProxyMock.swift
  ElementX/Sources/Mocks/SpaceRoomProxyMock.swift
  ElementX/Sources/Mocks/UserProfile+Mock.swift
  ElementX/Sources/Other/Avatars.swift
  ElementX/Sources/Other/TestablePreview/TestablePreviewsDictionary.swift
  ElementX/Sources/Screens/Spaces/Common/SpaceHeaderView.swift
  ElementX/Sources/Screens/Spaces/Common/SpaceRoomCell.swift
  ElementX/Sources/Screens/Spaces/SpaceListScreen/SpaceListScreenViewModel.swift
  ElementX/Sources/Screens/Spaces/SpaceListScreen/View/SpaceListScreen.swift
  ElementX/Sources/Screens/Spaces/SpaceScreen/SpaceScreenCoordinator.swift
  ElementX/Sources/Screens/Spaces/SpaceScreen/SpaceScreenModels.swift
  ElementX/Sources/Screens/Spaces/SpaceScreen/SpaceScreenViewModel.swift
  ElementX/Sources/Screens/Spaces/SpaceScreen/SpaceScreenViewModelProtocol.swift
  ElementX/Sources/Screens/Spaces/SpaceScreen/View/SpaceScreen.swift
  ElementX/Sources/Services/Spaces/SpaceRoomListProxyProtocol.swift
  PreviewTests/Sources/GeneratedPreviewTests.swift
  PreviewTests/Sources/__Snapshots__/PreviewTests/spaceHeaderView.iPad-en-GB-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/spaceHeaderView.iPad-pseudo-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/spaceHeaderView.iPhone-16-en-GB-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/spaceHeaderView.iPhone-16-pseudo-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/spaceRoomCell.iPad-en-GB-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/spaceRoomCell.iPad-pseudo-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/spaceRoomCell.iPhone-16-en-GB-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/spaceRoomCell.iPhone-16-pseudo-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/spaceScreen.iPad-en-GB-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/spaceScreen.iPad-pseudo-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/spaceScreen.iPhone-16-en-GB-0.png
  PreviewTests/Sources/__Snapshots__/PreviewTests/spaceScreen.iPhone-16-pseudo-0.png
  UnitTests/Sources/SpaceListScreenViewModelTests.swift
  UnitTests/Sources/SpaceScreenViewModelTests.swift
Labels: pr-wip

#4415 Fix some app route navigation bugs.
  ElementX/Sources/FlowCoordinators/UserSessionFlowCoordinator.swift
  ElementX/Sources/Screens/RoomScreen/RoomScreenViewModel.swift
  ElementX/Sources/Services/Room/RoomProxyProtocol.swift
  UnitTests/Sources/UserSessionFlowCoordinatorTests.swift
Labels: pr-bugfix

#4418 Update the SDK, handle API breaks.
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ElementX/Sources/Mocks/Generated/SDKGeneratedMocks.swift
  ElementX/Sources/Services/Timeline/TimelineProxy.swift
  project.yml
Labels: pr-misc

#4425 Add a couple of logs to debug badge counts.
  NSE/Sources/NotificationHandler.swift
Labels: pr-misc

#4424 Fix document picker tint colors, remove multi-selection feature flag
  ElementX/Sources/Application/Settings/AppSettings.swift
  ElementX/Sources/FlowCoordinators/RoomFlowCoordinator.swift
  ElementX/Sources/Screens/MediaPickerScreen/DocumentPicker.swift
  ElementX/Sources/Screens/MediaPickerScreen/MediaPickerScreenCoordinator.swift
  ElementX/Sources/Screens/MediaPickerScreen/PhotoLibraryPicker.swift
  ElementX/Sources/Screens/RoomDetailsEditScreen/RoomDetailsEditScreenCoordinator.swift
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/DeveloperOptionsScreenModels.swift
  ElementX/Sources/Screens/Settings/DeveloperOptionsScreen/View/DeveloperOptionsScreen.swift
  ElementX/Sources/Screens/Settings/UserDetailsEditScreen/UserDetailsEditScreenCoordinator.swift
  ElementX/Sources/Screens/StartChatScreen/StartChatScreenCoordinator.swift
Labels: pr-feature

#4434 Remove unnecessary awaits on RoomFlowCoordinator.init.
  ElementX/Sources/FlowCoordinators/ChatsFlowCoordinator.swift
  ElementX/Sources/FlowCoordinators/RoomFlowCoordinator.swift
  UnitTests/Sources/RoomFlowCoordinatorTests.swift
Labels: pr-misc

#4445 Update the SDK.
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  project.yml
Labels: pr-misc

#4446 Update Element Call to 0.15.0.
  ElementX.xcodeproj/project.pbxproj
  ElementX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  project.yml
Labels: pr-misc

#4448 Introduce flow parameters to simplify dependencies for child flows.
  ElementX/Sources/Application/AppCoordinator.swift
  ElementX/Sources/Application/FlowCoordinatorProtocol.swift
  ElementX/Sources/FlowCoordinators/ChatsFlowCoordinator.swift
  ElementX/Sources/FlowCoordinators/MediaEventsTimelineFlowCoordinator.swift
  ElementX/Sources/FlowCoordinators/OnboardingFlowCoordinator.swift
  ElementX/Sources/FlowCoordinators/PinnedEventsTimelineFlowCoordinator.swift
  ElementX/Sources/FlowCoordinators/RoomFlowCoordinator.swift
  ElementX/Sources/FlowCoordinators/SettingsFlowCoordinator.swift
  ElementX/Sources/FlowCoordinators/SpaceExplorerFlowCoordinator.swift
  ElementX/Sources/FlowCoordinators/SpaceFlowCoordinator.swift
  ElementX/Sources/FlowCoordinators/UserSessionFlowCoordinator.swift
  ElementX/Sources/Mocks/ClientProxyMock.swift
  ElementX/Sources/Screens/Settings/NotificationSettingsEditScreen/NotificationSettingsEditScreenCoordinator.swift
  ElementX/Sources/Screens/Settings/NotificationSettingsEditScreen/NotificationSettingsEditScreenViewModel.swift
  ElementX/Sources/Screens/Settings/NotificationSettingsEditScreen/View/NotificationSettingsEditScreen.swift
  ElementX/Sources/Screens/Settings/NotificationSettingsEditScreen/View/NotificationSettingsEditScreenRoomCell.swift
  ElementX/Sources/Screens/Settings/NotificationSettingsScreen/NotificationSettingsScreenCoordinator.swift
  ElementX/Sources/UITests/UITestsAppCoordinator.swift
  UnitTests/Sources/ChatsFlowCoordinatorTests.swift
  UnitTests/Sources/NotificationSettingsEditScreenViewModelTests.swift
  UnitTests/Sources/RoomFlowCoordinatorTests.swift
  UnitTests/Sources/UserSessionFlowCoordinatorTests.swift
Labels: pr-api
